### ISSUE TITLE
Accessing JSONP objects in Angular

### ISSUE THREAD

**Issue by M00staff** [ga-wdi-exercises/project4#10]
So apparently i have to use JSONP to access my API because of some cross domain issues. 

I was wondering why the following code works in JS/jQuery

```
$.ajax({
  type: "GET",
  url: "https://archive.org/advancedsearch.php?q=BrothersPast&fl%5B%5D=identifier,title&sort%5B%5D=&sort%5B%5D=&sort%5B%5D=&rows=50&page=1&output=json&callback=callback",
  dataType: 'jsonp',
  success: function(data) {
      var shows = data.response.docs;
        console.log(shows);                       // testing the return object
```

but this doesn't work in Angular

```
$http.jsonp('https://archive.org/advancedsearch.php?q=BrothersPast&fl%5B%5D=identifier,title&sort%5B%5D=&sort%5B%5D=&sort%5B%5D=&rows=50&page=1&output=json&callback=JSON_CALLBACK')
  .then(function(data) {

    var shows = data.response.docs;
    console.log(shows);
```

I get the error "TypeError: Cannot read property 'docs' of undefined

**Comment by M00staff** [comment]
if you go to the JSON links they are identical

**Comment by RobertAKARobin** [comment]
What happens when you do `console.dir(data)` in Angular? Do you get anything back?

**Comment by M00staff** [comment]
i get 'TypeError: Cannot read property 'docs' of undefined' when i put it in the controller where the console log was

**Comment by RobertAKARobin** [comment]
You were doing `console.dir(shows)`, which is a property of a property of the response. I don't want to see the properties; I want to see the raw response in its entirety.

**Comment by M00staff** [comment]
nm i get an object

**Comment by RobertAKARobin** [comment]
Is there any data in it?

**Comment by M00staff** [comment]
yep

**Comment by M00staff** [comment]
so in this object it looks like what im looking for is in data.response.docs - same as the other

**Comment by M00staff** [comment]
ill try to screen shot it

**Comment by M00staff** [comment]
![screen shot 2015-09-15 at 11 45 07 am](https://cloud.githubusercontent.com/assets/12723877/9881719/428efcb4-5b9f-11e5-8abd-249561a7a552.png)

**Comment by M00staff** [comment]
that array of 50

**Comment by RobertAKARobin** [comment]
`data` is _inside_ another object. So you'd need this:

```
.then(function(response){
  var shows = response.data.response.docs;
});
```

**Comment by M00staff** [comment]
that worked!! 
BLESS YOU KIND SIR! 

I'll go ahead and close the issue

**Comment by M00staff** [comment]
just wondering though , why it worked in the jQuery example above..?

**Comment by RobertAKARobin** [comment]
Because jQuery returns a slightly different response, where `data` is **not** inside another object. Angular has an extra layer of nesting.

**Comment by M00staff** [comment]
thank you so much!!!
