### ISSUE TITLE
WordPress header.php (i.e. <head>) content appearing in <body>

### ISSUE THREAD

**Issue by mpopv** [ga-wdi-exercises/project4#100]
Hey, I'm experiencing a weird problem and having trouble finding a solution.

In WordPress the `header.php` file represents the first couple tags and `<head>` section of each page, along with the opening `<body>` tag any elements common to all pages (i.e. navbar).

Mine looks like this:

``` php
<!DOCTYPE html>
<html>
  <head>
    <title><?php bloginfo('name'); ?></title>
    <meta charset="UTF-8 without BOM" />
    <?php wp_head(); ?>
  </head>
  <body>
    <?php if ( get_post_type() !== 'ngp-form-pages' ): ?>
      <?php wp_nav_menu(); ?>
    <?php endif; ?>
```

Now when I load a page, the styles and scripts all seem to have enqueued and been loaded correctly, based on the page looking and functioning as it should.

And yet, when I inspect the code, I see this:

![screen shot 2016-01-13 at 12 39 42 pm](https://cloud.githubusercontent.com/assets/15032398/12302503/8001f760-b9f3-11e5-98bc-a0cf2199c392.png)

As you can see, the code meant to go in `<head>` appears to have been appended to a div called `<header>` inside the `<body>`.

I have tried, as [other](https://wordpress.org/support/topic/head-scriptslinks-showing-up-inside-body-tag) people experiencing this problem have suggested, changing the meta charset to `UTF-8` and `UTF-8 without BOM` and neither seems to make a difference. I can't find any other solutions. Sort of stuck.

Could this just be a weird bug with how browser dev tools display it? I have checked and it seems to occur in both Chrome and Safari.

**Comment by RobertAKARobin** [comment]
Wow, that's weird. I think this must be a WP bug, so I'm going to defer to @jshawl .

**Comment by mpopv** [comment]
Okay. Not super urgent or anything since the code seems to be displaying correctly in-browser. But I've been trying to find a solution on and off for two days so I was wondering if I'm overlooking something. I'm concerned that it could cause some sort of issue down the line.

**Comment by jshawl** [comment]
I too am unsure about this issue. ?!!?

**Comment by RobertAKARobin** [comment]
Is it OK if I close this, Matt, just because it seems to be working?

**Comment by mpopv** [comment]
Yeah, sorry I missed this before.
