### ISSUE TITLE
problem with routes

### ISSUE THREAD

**Issue by rebeccaestes** [ga-wdi-exercises/project4#101]
I am trying to make my routes do what I want them to do, and every time I fix one thing a different thing breaks.

I'm making a yoga app, and there are two sets of asanas(poses) available:
1. ones available to all users (seeded data). This should display at /asanas
2. user-created asanas that are only available to the user that created them. This should display at /your_asanas

Currently the first route works fine; /asanas brings up the view I named index.html.erb. 

/your_asanas should display the view at your_asanas.html.erb. I looked at my custom routes from project 2 and tried to put in my routes.rb file `get '/your_asanas', to: 'asanas#your_asanas', as :your_asanas` but when I do that my entire app breaks due to a syntax error. 

If I delete the `as :your_asanas` from that line, things start working again, but on /your_asanas, I get an "ArgumentError in Asanas#your_asanas" error, that says there's a syntax error in my form's first line, `<%= form_for @asana do |f| %>`, because the first argument is empty. The form is not even referenced anywhere on your_asanas so I don't know why it's upset about that. That said, I'm (trying to ...) use React, so I have to make the routes for editing be /asanas/5 instead of /asanas/5/edit. I don't know why that would be affecting /your_asanas though ... I can edit and create asanas like normal with the form.

I also tried to make the your_asanas page display at asanas/your_asanas, but all I get is a "Couldn't find Asana with 'id'=your_asanas", even though your_asanas is defined in my controller before show is.

My repo is here: https://github.com/rebeccaestes/readysetom

**Comment by RobertAKARobin** [comment]
Can you screenshot the syntax error?

**Comment by rebeccaestes** [comment]
<img width="896" alt="screen shot 2016-01-13 at 1 02 59 pm" src="https://cloud.githubusercontent.com/assets/3891862/12302929/cd113e7e-b9f5-11e5-80ae-bcae2b065fb4.png">

**Comment by RobertAKARobin** [comment]
I think that's because you're routing to the `your_asanas` method, and it doesn't define `@asanas` anywhere.

You have this:

``` rb
def your_asanas
        @current_user = current_user
        @your_asanas = Asana.where(user: @current_user)

        respond_to do |format|
        format.html { render :show }
      format.json { render json: @your_asanas.to_json }
    end
end
```

How about this:

``` rb
def your_asanas
  @current_user = current_user
  @asanas = Asana.where(user: @current_user)

  respond_to do |format|
    format.html { render :show }
    format.json { render json: @asanas.to_json }
  end
end
```

**Comment by rebeccaestes** [comment]
That didn't work; I'm getting the same error. 

Do you know why `Trace of template inclusion: app/views/asanas/show.html.erb` is showing up at the bottom? I sort of forced my show view into being my edit view. I don't know why your_asana would try to display it though. I don't want your_asana to display a form in the first place.

**Comment by RobertAKARobin** [comment]
Oops, sorry, I'm a moron -- it's looking for `@asana`, not `@asanas`. So you'll need `@asana` defined somewhere in the controller.

**Comment by rebeccaestes** [comment]
That's not the problem though. All these errors are because the app keeps trying to load the form I created whenever I go to /your_asanas. I don't want that form to display on /your_asanas, and I don't know why it is. This is the entirety of my your_asanas file:

```
<p>Click an asana to edit it.</p>

<%= react_component('YourAsanasList',
                    { initialAsanas: @asanas },
                    { prerender: true }) %>
```

The form the app is trying to display IS included in show.html.erb, which is why I asked about the `Trace of template inclusion: app/views/asanas/show.html.erb` line.

**Comment by RobertAKARobin** [comment]
Oh, I'm sorry. I'm taking another look right now.

**Comment by RobertAKARobin** [comment]
I see that your repo has both a Gemfile and a package.json in it. Is this a Rails or a Node app?

**Comment by RobertAKARobin** [comment]
Your `your_asanas` method renders the `show` view:

```
format.html { render :show }
```

The `show` view in turn renders the form:

```
<div id="new_form"><%= render partial: "form" %></div>
```

**Comment by rebeccaestes** [comment]
It's Rails, but the Rails with React tutorial I was following had us
install some NPM packages too. I'm pretty sure I'm not using any of them.

**Comment by RobertAKARobin** [comment]
Gotcha -- thanks. See my other comment!

**Comment by rebeccaestes** [comment]
Ugh I can't believe that was it. Thanks!!
