### ISSUE TITLE
issue with javascript

### ISSUE THREAD

**Issue by tkentor** [ga-wdi-exercises/project4#102]
Link to my repo here: https://github.com/tkentor/end-of-days

Sort of hard to explain this... but when you're on the "blog" section of my page, and you click on a post, the post expands revealing more text. This works fine. However, if you get to this page by clicking the "blog" link on the homepage of my site, the javascript doesn't work (the posts don't expand). But when you just refresh the page, it works fine again. It only doesn't work if you've gotten to that page by clicking the link...until you refresh.

JavaScript here:

``` js
$(document).ready(function(){

  $(".article").click(function(){
    console.log(this)
      $(this).find(".expand").toggle();
      $(this).find(".click").toggle();
    })

});
```

**Comment by RobertAKARobin** [comment]
Looking now. Next time, remember to use backtics to format your code in these issues!

**Comment by RobertAKARobin** [comment]
Do you get an error?

**Comment by tkentor** [comment]
Sorry! Thanks

**Comment by RobertAKARobin** [comment]
Also, I noticed that your app's using SQLite instead of Postgres. Take a look at this:

https://github.com/ga-dc/curriculum/tree/master/05-mvc-with-rails/rails-deployment#make-sure-you-create-your-app-with-rails-new-my-app-name--d-postgresql

**Comment by tkentor** [comment]
Ah...thanks...yeah forgot about that.

No errors...just doesn't work.

**Comment by RobertAKARobin** [comment]
Part of the problem may be how you've written `welcome/index.html.erb`: you've given it a `DOCTYPE`, a `head`, a `body`, and the whole shebang. Remember that everything in a Rails app gets inserted into your `layouts/application.html.erb`... which also has a `DOCTYPE`, `head`, `body`, etc. So you basically have a whole webpage embedded inside a webpage. A webpage should only ever have one `DOCTYPE`, `head`, and `body`.

**Comment by RobertAKARobin** [comment]
With respect to your Javascript, remember that jQuery uses CSS selectors. Here you've written `$(".article")...` which means "Select everything with the class of 'article'." I don't see anything in your HTML with the class of 'article', so this event is never being fired.

**Comment by tkentor** [comment]
Hm I don't really understand that first email, but the .article div can be
found on line 2 of views/articles/index.html.erb and line 1 of
views/stories/index.html.erb.

Also, the JavaScript runs fine if you refresh the page, so it definitely
works to some extent...just not if you get there through the link until you
refresh.

**Comment by RobertAKARobin** [comment]
Oh, gotcha. Try commenting out the `gem "turbolinks"` line in your Gemfile, running `bundle install`, and then deleting the `//= require turbolinks` line in `app/assets/javascripts/application.js`. Then `rails s` again.

**Comment by tkentor** [comment]
Cool, that worked! I also switched to postgres and deleted the extra
doctype...hopefully it all worked... Thank you!
