### ISSUE TITLE
Backbone/Express: .save on existing model will not go to the right API route

### ISSUE THREAD

**Issue by neka-io** [ga-wdi-exercises/project4#103]
I'm updating a Backbone model by calling .save on it with new data. In Backbone the model is updated but the update doesn't persist in the database. Reading Backbone documentation I learned that when you call .save, it will check if the model already exists. If it doesn't it creates and if it does it updates. But when I save, it's routed to "create" and stops there without creating a duplicate or going to "update" route. 

This is the method I have on my model in Backbone: 

```
  update: function(newCountry){
    var countryArray = this.get('countries')
    countryArray.push(newCountry.attributes._id)
    var data = {
      countries: countryArray
    }
    this.save(data)
  }
```

At this point, if I `console.log(this)` it will be updated but not changed in the backend. After a while I get a ERR_CONNECTION_REFUSED from the 'create' route in my browser console. This is my controller in express: 

```
  create: function(req, res){
    console.log('creating game')
    Game.create(req.body).then(function(game){
      res.json(game)
    })
  },

  update: function(req, res){
    console.log('update')
    // Game.findById(req.game_id).update(req.data).then(function(game){
    //   res.json(game)
    // })
  }
```

**Comment by RobertAKARobin** [comment]
How can you tell it's being routed to the `create` route? Because `creating game` is console logged?

**Comment by neka-io** [comment]
Yes

**Comment by RobertAKARobin** [comment]
You'll need to define the `update` method yourself:

https://github.com/ga-dc/grumblr_angular/blob/solution/js/grumbles/grumble.factory.js#L12

**Comment by neka-io** [comment]
In Backbone as well? I'm looking at this example in grumblr_backbone:
https://github.com/ga-dc/grumblr_backbone/blob/routing_solution/js/backbone/views/grumble.js#L45

**Comment by RobertAKARobin** [comment]
Argh, I'm sorry. I've been on Angular mode all day. Want to come over to the Genius Bar?

**Comment by neka-io** [comment]
Yes, thank you. I'll be there in a few minutes

**Comment by RobertAKARobin** [comment]
We needed to specify `idAttribute`.

http://stackoverflow.com/questions/12390553/how-to-make-backbones-and-mongodbs-ids-work-seamlessly
