### ISSUE TITLE
Getting info from rails api to render in angular

### ISSUE THREAD

**Issue by dan-ator** [ga-wdi-exercises/project4#105]
I have one of the models in my app, items, rendering from the backend API.  Following the same convention and syntax I expected one of my other models, outfits, to render as well.  I checked with the localhost:3000 where my backend is at and when i hit `http://localhost:3000/outfits` i receive the seeded json data I expect.  But it isn't showing up in my app.

My index controller for outfits is: 

``` js
"use strict";

(function(){
  angular
  .module("outfits")
  .controller("OutfitIndexController", [
    "OutfitFactory",
    OutfitIndexControllerFunction
  ]);

  function OutfitIndexControllerFunction(OutfitFactory){
    this.items = OutfitFactory.query();
  }
}());
```

My  outfit factory is:

``` js
(function(){
  angular
  .module("outfits")
  .factory("OutfitFactory", [
    "$resource",
    FactoryFunction
  ]);

  function FactoryFunction($resource){
    return $resource("http://localhost:3000/outfits/:id", {}, {
      update: {method: "PUT"}
    });
  }
}());
```

and my outfit.js module is:

``` js
"use strict";

(function(){
  angular
  .module("outfits", [
    "ngResource"
  ]);
}());
```

and my index.html is:

``` html
<h2>Outfits</h2>
<div data-ng-repeat="outfit in OutfitIndexViewModel.outfits">
  <p><a data-ui-sref="outfitShow({id: outfit.id})">{{outfit.name}}</a></p>
</div>
```

I basically followed the exact same syntax as my items and they are all rendered perfectly fine so I can't figure out what is going on here.  There also aren't any errors, so that is no help.

**Comment by RobertAKARobin** [comment]
I'd like to check whether anything's actually being returned by the database. Try this:

``` js
  function OutfitIndexControllerFunction(OutfitFactory){
    this.items = OutfitFactory.query(function(response){
      console.dir(response);
    });
  }
```

**Comment by dan-ator** [comment]
Indeed the three seeded outfits are showing up in the console as an array.

**Comment by RobertAKARobin** [comment]
That's good!

Oh. The problem is you're calling `outfit in OutfitIndexViewModel.outfits`, but you're saving all the outfits to `this.items`.

**Comment by dan-ator** [comment]
I knew it was going to be some typo, no matter how may times I read it over. Thanks Robin.
