### ISSUE TITLE
angular - create, delete nested items

### ISSUE THREAD

**Issue by ghost** [ga-wdi-exercises/project4#107]
still trying to solve my issue of adding create and delete functionality to comments, which are nested under posts.

i'm working in posts/show.html and trying 

```
<p><a data-ui-sref="commentNew">Add an Answer</a></p>
```

with commentNew defined in app.js as

```
.state("commentNew", {
      url: "/posts/:id", //?
      templateUrl: "app/comments/new.html", //?
      controller: "CommentNewController",
      controllerAs: "CommentNewViewModel"
```

my back end is https://github.com/thomhouseholder/runners-app

and my front is https://github.com/thomhouseholder/runners-angular.

**Comment by RobertAKARobin** [comment]
The three backtics have to be on a line by themselves.

**Comment by RobertAKARobin** [comment]
What error or unexpected behavior are you getting?
