### ISSUE TITLE
issue with ____

### ISSUE THREAD

**Issue by jacohen10** [ga-wdi-exercises/project4#108]
I tried to implement backbone. I expected to see my models to show up. Instead I see a lot of errors referencing bower and 3 of these: ReferenceError: Backbone is not defined.
My repo link is https://github.com/jacohen10/Project4/tree/backbone.

**Comment by jacohen10** [comment]
index.hbs looks like this  

``` js
<script src="bower_components/jquery/dist/jquery.min.js"></script>
 <script src="bower_components/underscore/underscore-min.js"></script>
 <script src="bower_components/handlebars/handlebars.min.js"></script>
 <script src="bower_components/backbone/backbone-min.js"></script>
 <script src="js/script.js"></script>
 <script src="js/models/rak.js"></script>
 <script src="js/collections/raks.js"></script>
 <script src="js/views/rakView.js"></script>
 <script src="js/views/rak.js"></script>
```

and I also have a bower components folder with backbone, hbs, jquery, and underscore in there

**Comment by RobertAKARobin** [comment]
Sorry, Josh, looking now.

**Comment by RobertAKARobin** [comment]
Could you take a screenshot of the error?

**Comment by RobertAKARobin** [comment]
Needed to tell Express where to find Bower.
