### ISSUE TITLE
CORS configuration: Backbone + Rails Backend

### ISSUE THREAD

**Issue by elisekain** [ga-wdi-exercises/project4#109]
I am working through configuring CORS on my front and back end. I previously had everything working by bypassing the authentication with: `skip_before_filter :verify_authenticity_token` in my Rails controllers. But, I want to do things the right way. 

I set up `gem "rack-cors", :require => "rack/cors"` in my Rails app. 
I am also looking at a few Backbone tutorials to add the authenticity token. I thought this got me the furthest:
- http://ngauthier.com/2011/02/backbone-and-rails-forgery-protection.html

I tried reading tutorials...but I'm lost as to what specific things I'm configuring. 
I expected to be able to set up CORS.
Still getting `unprocessable entity` errors instead.
My repo link is: https://github.com/elisekain/bind and https://github.com/elisekain/bind_api and I'm not even 100% sure which files each of these things should be going.

**Comment by andrewsunglaekim** [comment]
Check out this link https://github.com/ga-dc/wdi_radio_api/blob/master/app/controllers/application_controller.rb

**Comment by elisekain** [comment]
@andrewsunglaekim what is this magic?!? Welp that works.
