### ISSUE TITLE
Accessing API endpoint $resource in Angular

### ISSUE THREAD

**Issue by edwardpark** [ga-wdi-exercises/project4#11]
I am trying to display and access the data from a api endpoint at http://localhost/movies and currently getting a error saying a factory value is undefined? I have tested the rails API endpoint and it works just fine itself. 

![screen shot 2015-09-15 at 11 44 51 am](https://cloud.githubusercontent.com/assets/7883907/9881738/518341e4-5b9f-11e5-9641-d0c9cba22ded.png)

Here is my Js Code 

``` js
(function() {
  angular.module('dinedash', ['ngResource','movieServices']);
})();

---------------

(function() {
  var movieServices = angular.module('movieServices', ['ngResource']);

  movieServices.factory('AllMovies', ['$resource', function($resource) {
    return $resource('http://localhost:3000/movies');
  }]);
})();

-------------
angular.module("dinedash").controller("MovieIndex",function($scope){
  $scope.someValue="Hello";
  $scope.listIsVisible =false;
  $scope.showList=function(){
    $scope.listIsVisible = true;
    //console.log("fired")

    $scope.movieIndex();
  }
  $scope.movieIndex = $scope.AllMovies.query();

})

```

**Comment by edwardpark** [comment]
Clarify that I am using Rails as the API backend and have downloaded and included the angular_resource.js file itself directly in my assets/javascript folder assuming rails will just load them all together anyways since it's using the require_tree

**Comment by RobertAKARobin** [comment]
Sorry, Eddie, will get to this in a sec

**Comment by edwardpark** [comment]
its cool!

**Comment by RobertAKARobin** [comment]
I'm confused as to why you have both `$scope.movieIndex();` and `$scope.movieIndex`. Is it a property or a method?

**Comment by edwardpark** [comment]
honestly  it was a trial and error piece I took from a angular tutorial .

took out the $scope just like the class tutorial and now error states that AllMovies is undefined
![screen shot 2015-09-15 at 12 45 14 pm](https://cloud.githubusercontent.com/assets/7883907/9883369/bd820abc-5ba7-11e5-9b19-7b0c0935f1bf.png)

**Comment by edwardpark** [comment]
I am trying to use it as a method so when the user hits the ng-click which executes the .showList  it cues the $resource call

**Comment by RobertAKARobin** [comment]
Can you push your code to GH?

**Comment by edwardpark** [comment]
https://github.com/edwardpark/dine_and_dash 

it's on the movieApi branch

**Comment by mattscilipoti** [comment]
I don't see any javascript files in movieApi branch.
