### ISSUE TITLE
q: deleting a comment

### ISSUE THREAD

**Issue by ghost** [ga-wdi-exercises/project4#113]
working on adding delete fn to comments.

i've tried to delete a comment with

```
<div data-ng-repeat="comment in PostShowViewModel.comments">
  <blockquote>{{comment.commentBody}} <a data-ng-click="CommentEditViewModel.destroy()">Delete</a></blockquote>
</div>
```

as well as deleting a post with 

```
<div data-ng-repeat="post in PostIndexViewModel.posts">
  <p><a data-ui-sref="postShow({id: post.id})">{{post.questionTitle}}</a> | <a data-ui-sref="postEdit({id: post.id})">Edit or Delete</a> | <a data-ng-click="postDelete({id: post.id})">Delete</a></p>

   <!-- ^^ create function in controller to use above with ngClick -->
</div>
```

in both cases, i'm not able to create an active link as i am using 

```
  <button data-ng-click="PostEditViewModel.destroy()">Delete</button>
```

my repos:
back end:  https://github.com/thomhouseholder/runners-app
front:  https://github.com/thomhouseholder/runners-angular

**Comment by RobertAKARobin** [comment]
What do you mean by "create an active link"?

**Comment by ghost** [comment]
creating an href link vs. a click event.  i'm going to do that in css.

**Comment by RobertAKARobin** [comment]
You don't want to make a link to a "delete" page. Think about it: if someone can just type in a URL into their browser to delete something from your database, they can very cleanly delete everything from your database. Having a button that deletes is plenty.

**Comment by ghost** [comment]
ah makes tons of sense.  thanks!

**Comment by ghost** [comment]
Still struggling with this issue.

with some help, i set up ng-click to work fine with posts:
- on index.html:

```
<a data-ng-click="PostIndexViewModel.delete(post)">Delete</a>
```
- and on index.controller.js in PostIndexControllerFunction:

```
  this.delete = function(post){
        post.$delete({id: post.id});
        $state.go("postIndex")
      }
```

I'm trying this to delete a comment:
- on posts/show.html:

```
<a data-ng-click="CommentEditViewModel.delete(comment)">Delete</a>
```
- and on comments/edit.controller.js in CommentEditControllerFunction:

```
this.delete = function(comment){
      comment.$delete({id: comment.id});
      console.log('clicked comment delete');
    }
```

I'm not seeing the text logged in the console as a starter, but unsure why.

my repos:
back end: https://github.com/thomhouseholder/runners-app
front: https://github.com/thomhouseholder/runners-angular

**Comment by RobertAKARobin** [comment]
It looks like the Comment Controller hasn't been instantiated on the Post show page. I can tell because I just put a `console.log("hello")` inside the `CommentEditControllerFunction` and it didn't run.

Generally, you want to stick to one controller per page, and you don't want a controller inside a controller.

So I'd recommend attaching a `deleteComment` method to your `PostShowControllerFunction`.

**Comment by ghost** [comment]
that is working, thanks!
