### ISSUE TITLE
Scope and Automating Migrations in Rails

### ISSUE THREAD

**Issue by ajohnson052** [ga-wdi-exercises/project4#114]
I am doing a lot of work in seeds.db, and I am having some trouble with scaling up. One problem is that I would like to create an array and access it throughout the seed file. Thus far I have been passing in the array as an argument to various methods, but I am sure that there is a smarter way to approach this.

Also, I would like some advice on creating several models/ migrations/ controllers/ routes at once according to the same format. I have been able to create the files, but not able to fill them out correctly.

**Comment by RobertAKARobin** [comment]
Can you show me some of the code that's bugging you?
