### ISSUE TITLE
Angular user auth w/ Passport

### ISSUE THREAD

**Issue by starrchen** [ga-wdi-exercises/project4#115]
I'm (still) trying to figure out how best to integrate all we've learned about Passport authentication and Angular to get some user auth going on. I'm trying to figure out the best way to use Angular to implement the user models I have set up through Express, but I am starting to get confused about what the best way to have the app go to "/login" might be and how to get Angular working on that page.

I'm working on [this repo](https://github.com/starrchen/dc-bucket-list/tree/user-auth-2) and not able to get `{{5+5}}` to show up as `10` on `/login` yet and also not sure if my user model is set up correctly. =/

I think I'm still very overwhelmed by the different methods I looked into trying to find the best, most straight-forward way to do this and given the many different ways we've done user auth in class so far.

**Comment by RobertAKARobin** [comment]
Does your app _have_ to have secure user auth?

**Comment by starrchen** [comment]
Ummm please define "_have_ to"?

Essentially, the two main features of my app are:
- Ability to filter through the data (which I think I have)
- Ability to check data items off (think adding favorites on Tunr?)

So I really would like to have it? But I can modify my scope?

**Comment by RobertAKARobin** [comment]
There's a difference between having users and having user auth. You can have users by creating a "Users" table that has one column: "username". To log in, just type your username. No passwords, no nothing. Of course it's completely insecure, but unless you have people using your app and/or you're storing sensitive data, that doesn't matter. Don't let Passport get in the way of actually making an app! User auth without an app is nothing; an app without user auth is still an app!
