### ISSUE TITLE
Issue with click events registering multiple times per click

### ISSUE THREAD

**Issue by jordanbrauner** [ga-wdi-exercises/project4#117]
I tried to use booleans to keep the click events from firing more than once but it continues to happen.

My repo link is https://github.com/jordanbrauner/Project-4
Code is in game.js in the drawEventCard method. The first click event for the event card actions starts at line 106.

Basic flow to the game:
Click a tile on the map to draw that particular event card. Choose one of three actions to resolve and discard the card. Effect for each action are to the right of the name of the action. (itemU1, for example, means to draw one card).

**Comment by RobertAKARobin** [comment]
Dang. You have some complicated code. Is there any chance you could refactor this and split things up into discrete objects? It would make it much easier to solve the problem! Hint: If a bunch of functions all have the same word in their names (e.g. "card") you can probably make that word into an object wth all those functions as methods.

I'm not sure how to reproduce the error. Which click events are firing more than once? How can I tell?

One thing to keep in mind is that every time Javascript evaluates `$(something).on("click"` it adds a new event listener to that `something` -- it doesn't overwrite existing event listeners. So if it evaluates `$(something).on("click"` three times, and then you click on the `something`, the event listener will fire three times all at once.

**Comment by RobertAKARobin** [comment]
This looks really cool!

**Comment by jordanbrauner** [comment]
Thanks Robin. If you check the console you'll see what the code is doing as you play but what you said here is exactly what's happening:

"One thing to keep in mind is that every time Javascript evaluates $(something).on("click" it adds a new event listener to that something -- it doesn't overwrite existing event listeners. So if it evaluates $(something).on("click" three times, and then you click on the something, the event listener will fire three times all at once."

So is the best way to fix this just to use .off() after the click and then start new .on() listeners at the beginning of each next turn?

And yeah, the code has gotten a little messy. I've learned a lot in the last few days while working on this and I have some ideas of how I can improve on it. I'm going to refactor as soon as I get the core mechanics of the game in but chances are it won't be until after Friday as there's a bit more to do to get to my MVP and have a playable game (finish designing the rest of the cards, game balance, and a couple more mechanics).

**Comment by jordanbrauner** [comment]
Yep, using .off() works like a charm. Thanks for catching that! :+1: :+1:
