### ISSUE TITLE
issue with hbs

### ISSUE THREAD

**Issue by jacohen10** [ga-wdi-exercises/project4#119]
I tried to use handlebars in my handlebars template. I expected {{body}} to return the body from my model. However nothing gets returned instead. If I use 

``` js
this.$el.html("<h2>"+ this.model.toJSON().body + "</h2>")
```

Then it works, but for some reason the following doesn't

``` js
this.$el.html(this.template(this.model.toJSON()));
```

I'm happy to use the first option, but I'd also like to learn why it isn't working.

My repo link is https://github.com/jacohen10/project4/blob/backbone/public/js/backbone/views/rak.js and my question is about lines 22-23.

If I change {{body}} to {{this}} I get [object Object], so I wonder if this is related to parsing the json data correctly?

**Comment by andrewsunglaekim** [comment]
I think the issue is that your handebars template.. is in a handlebars file.. lol... Could you try making `index.hbs` to `index.html` instead. otherwise everything else is the same.

**Comment by andrewsunglaekim** [comment]
just to check and see if it works. If it does work, than you know the issue is `.hbs` and have to find some configuration for it.

**Comment by jacohen10** [comment]
that fixed it. That causes a new issue though because I was using hbs to hide and show login/logout :disappointed:

**Comment by RobertAKARobin** [comment]
Could you open a new issue if that's still giving you trouble?
