### ISSUE TITLE
Wiring up MongoDB and Express

### ISSUE THREAD

**Issue by petergcutler** [ga-wdi-exercises/project4#12]
Running into issues trying to connect Mongo and Express

In order to do the wiring, I've been attempting to use mongojs, mongodb, and monk in different approaches, and none of them are coming through. Right now, I'm just using a simple connection in my app.js:

```
var dbUrl = "d3bq";
var collections = ["barbecues"];

console.log(db.barbecues.find().pretty())
var db = require("mongojs").connect(dbUrl, collections);
```

but the second I reference the db.barbecues.find() expression, I'm receiving errors.

I have my app running via nodemon, my mongo database running via mongod, and my mongo server running. I have an object stored within my collection, "barbecues" , within my mongo database, "d3bq"

Thanks for any tips.

**Comment by jshawl** [comment]
what errors do you get?

**Comment by RobertAKARobin** [comment]
That's because you're running `db.barbecues` before you define what `db` is with `var db`. `db` doesn't exist when you're trying to log it.

**Comment by petergcutler** [comment]
Sorry, that was just me placing the console log in the wrong place. -- even with that following the db instantiation, still throws errors. Error thrown is:

/deep/ combinator is deprecated. See https://www.chromestatus.com/features/6750456638341120 for more details.

**Comment by petergcutler** [comment]
Current state of app.js:

```
// basics
var express = require('express');
var path = require('path');
var favicon = require('serve-favicon');
var logger = require('morgan');
var cookieParser = require('cookie-parser');
var bodyParser = require('body-parser');

// mongo db
var dbUrl = "d3bq";
var collections = ["barbecues"];


var db = require("mongojs").connect(dbUrl, collections);
console.log(db.barbecues.find().pretty())


app.get("/barbecues", function(req,res){
  db.barbecues.find({}, function(err, barbecues){
    if(err) return
    var response = {
      barbecues: barbecues
    }
    res.json(response)
  })
})

// routes
var routes = require('./routes/index');
var users = require('./routes/users');

// application instantiation
var app = express();

// view engine setup
app.set('views', path.join(__dirname, 'views'));
app.set('view engine', 'hbs');

// load dependencies and public directory
app.use(favicon(path.join(__dirname, 'public', 'images', 'd3bq_fav.png')));
app.use(logger('dev'));
app.use(bodyParser.json());
app.use(bodyParser.urlencoded({ extended: false }));
app.use(cookieParser());
app.use(express.static(path.join(__dirname, 'public')));

// load routes
app.use('/', routes);
app.use('/users', users);




// error handlers

// catch 404 and forward to error handler
app.use(function(req, res, next) {
  var err = new Error('Not Found');
  err.status = 404;
  next(err);
});

// development error handler
// will print stacktrace
if (app.get('env') === 'development') {
  app.use(function(err, req, res, next) {
    res.status(err.status || 500);
    res.render('error', {
      message: err.message,
      error: err
    });
  });
}

// production error handler
// no stacktraces leaked to user
app.use(function(err, req, res, next) {
  res.status(err.status || 500);
  res.render('error', {
    message: err.message,
    error: {}
  });
});


module.exports = app;
```

**Comment by jshawl** [comment]
can you paste the error or a screenshot of error

**Comment by petergcutler** [comment]
Yeah, it's above, I'll grab a screenshot

**Comment by petergcutler** [comment]
![screen shot 2015-09-15 at 1 04 32 pm](https://cloud.githubusercontent.com/assets/11398019/9883820/594140d8-5baa-11e5-967a-ea301f162453.png)

**Comment by jshawl** [comment]
what url are you visiting (it's missing from the image)

**Comment by petergcutler** [comment]
http://localhost:3000/ and http://localhost:3000/barbecues

**Comment by petergcutler** [comment]
I've visited http://localhost:27017/, and I get the generic "looks like you're trying to visit a mongodb page over http" text, and my /users is working properly too

**Comment by jshawl** [comment]
is your node server running (express)? This is an express issue if you are trying to visit in the browser and the connection is refused

**Comment by petergcutler** [comment]
yeah, nodemon is running when the error occurs. If I comment out the mongo connection language, I regain access to my index. If I comment it back in, error thrown

**Comment by jshawl** [comment]
put the mongo connection language in there. try visiting the browser - are there any errors in the tab that was running nodemon?

**Comment by petergcutler** [comment]
Yeah-- 
![screen shot 2015-09-15 at 1 13 12 pm](https://cloud.githubusercontent.com/assets/11398019/9884024/95b3ddfe-5bab-11e5-9d9a-9f757f11a938.png)

![screen shot 2015-09-15 at 1 13 26 pm](https://cloud.githubusercontent.com/assets/11398019/9884033/97aef7ba-5bab-11e5-9a8c-438ec65aa412.png)

**Comment by jshawl** [comment]
boom! `undefined is not a function`

check out the documentation for connecting - https://github.com/mafintosh/mongojs

it suggests a slightly different syntax:

``` js
// simple usage for a local db
var db = mongojs('mydb', ['mycollection'])

```

**Comment by petergcutler** [comment]
Nice, was hoping that would work, but it looks like it points to the same place, same error:

![screen shot 2015-09-15 at 1 18 03 pm](https://cloud.githubusercontent.com/assets/11398019/9884147/3ce63518-5bac-11e5-8493-263b77865626.png)

![screen shot 2015-09-15 at 1 18 13 pm](https://cloud.githubusercontent.com/assets/11398019/9884152/3f2e57ec-5bac-11e5-9276-b560f875cc52.png)

**Comment by jshawl** [comment]
did you require it?

``` js
var mongojs = require("mongojs")
var db = mongojs(""...)
```

**Comment by petergcutler** [comment]
Ah good call. I just did, and now it points to the same error that mongoose pointed to before I switched it out, the first get call in line 15 above.

**Comment by jshawl** [comment]
can you paste the error please

**Comment by petergcutler** [comment]
![screen shot 2015-09-15 at 1 26 26 pm](https://cloud.githubusercontent.com/assets/11398019/9884380/61cbaa42-5bad-11e5-8438-83dd93e1513f.png)

**Comment by jshawl** [comment]
move `var app = express()` before `app.get()`

**Comment by petergcutler** [comment]
Yeah, haha, I finally saw that

**Comment by petergcutler** [comment]
Thanks for reviewing.

**Comment by jshawl** [comment]
is it working?!

**Comment by petergcutler** [comment]
Yeah, thanks again
