### ISSUE TITLE
issue with this tiny phantom box that won't go away

### ISSUE THREAD

**Issue by tkentor** [ga-wdi-exercises/project4#121]
screenshot:
<img width="574" alt="screen shot 2016-01-14 at 9 56 35 am" src="https://cloud.githubusercontent.com/assets/14913251/12327620/99c7f386-baa5-11e5-9a27-c8b2ef8fea07.png">

There's this tiny box that won't go away, as if an empty image or an image that won't load is there. It appears on every post. I have a form with select options for the little images, but no matter what combination of images is selected, the box still appears. Each image is able to load on it's own, and even when all images are selected, the box still appears.

form:

`````` <p>
    <%= f.label :picture_list, "pictures" %>
    <%= f.select :picture_list, [['mindfulness','http://i.imgur.com/k4MwmCr.gif'],['languages','http://i.imgur.com/u2K1SPg.gif'],['books','http://i.imgur.com/s08ysrL.gif'],['travel','http://i.imgur.com/hGPFD48.gif']],{ :prompt => "Please select"},{ :multiple => true } %>
  </p>```

html:
```    <div class="tag-picture"><% article.pictures.each do |picture| %><%= image_tag "#{picture.link}" %><% end %></div> ```
``````

**Comment by tkentor** [comment]
oops, sorry about the formatting... The first block shows the text on my _form.html.erb and the "html:" is coming from my index.html.erb. Link to my repo: https://github.com/tkentor/end-of-days

**Comment by RobertAKARobin** [comment]
Try `inspect element` on it. What's the HTML of the box?

**Comment by tkentor** [comment]
Forgot to mention that... I don't think you can inspect it. It doesn't
highlight.

Thanks!

**Comment by RobertAKARobin** [comment]
If you see it on your webpage, you can inspect it! You may just have to hunt-and-peck by hovering over different parts of the source code. See this GIF:

![project_url](https://cloud.githubusercontent.com/assets/6268177/12330288/567c5fba-bab2-11e5-9eb8-921ee5f70129.gif)

**Comment by tkentor** [comment]
Ah! Ok, thanks. It's an empty <img src> tag, so that makes sense why it
appears, although I have no idea why it's there.

**Comment by RobertAKARobin** [comment]
There must be an empty item in `article.pictures`. For example:

``` rb
["Picture 1", "Picture2", nil, "Picture 3"]
```

...or, maybe more likely, a picture that doesn't have a `link`.

**Comment by tkentor** [comment]
Hm...this is the exact code:

``` rb
    <%= f.select :picture_list, [['mindfulness','
http://i.imgur.com/k4MwmCr.gif'],['languages','
http://i.imgur.com/u2K1SPg.gif'],['books','http://i.imgur.com/s08ysrL.gif'
],['travel','http://i.imgur.com/hGPFD48.gif']],{:prompt => "Please
select"},{ :multiple => true } %>
```

There's no empty spaces. Is it the {prompt} that's doing it? If I take it
away, it makes it so that I can no longer select multiple options like I
want (switches to a drop down menu instead where only one item can be
selected).

**Comment by RobertAKARobin** [comment]
``` erb
<%= f.select :picture_list, [['mindfulness','
http://i.imgur.com/k4MwmCr.gif'],['languages','
http://i.imgur.com/u2K1SPg.gif'],['books','http://i.imgur.com/s08ysrL.gif'
],['travel','http://i.imgur.com/hGPFD48.gif']],{:prompt => "Please
select"},{ :multiple => true } %>
```

**Comment by RobertAKARobin** [comment]
Huh. Weird. I have no idea, honestly. Maybe ignore it for now and we'll deal with it later?

**Comment by RobertAKARobin** [comment]
Where are your articles coming from? Your seed file is blank.

**Comment by tkentor** [comment]
I don't have any actual articles on it yet...content coming soon (this
weekend). I've just been making dummy articles for now, but I think I
dropped the database pretty recently.

**Comment by RobertAKARobin** [comment]
Holy crap, this makes zero sense. So basically, the prompt you have is causing a new blank value to be added. For the life of me I can't figure out how to make it stop without doing something totally hacky.

**Comment by tkentor** [comment]
Haha it's currently the bane of my existence!

Is there a different way to handle the form field that would accomplish the same goal? If not, hacky is better than nothing... I'm on my way to GA now.

**Comment by RobertAKARobin** [comment]
Sure, just write the `select` in HTML:

``` erb
<select multiple="true">
<%= pictures.each do |picture| %>
  <option value="<%= picture.link %>"> <%= picture.title %></option>
<% end %>
</select>
```

**Comment by tkentor** [comment]
Could you help me for a sec with it?

**Comment by RobertAKARobin** [comment]
How's that working out for you?

**Comment by tkentor** [comment]
I couldn't get the html to work, but I fixed it by just throwing in some
javascript to remove the empty tags.

  $("img[src='']").remove();

Definitely super hacky...but it's simple and works?

**Comment by RobertAKARobin** [comment]
If it works, awesome! Move on!
