### ISSUE TITLE
importing some static data into my front end with a script tag

### ISSUE THREAD

**Issue by solowt** [ga-wdi-exercises/project4#122]
At some point I realized that some of the data my backend was serving was static.  So rather than get updates on data that never changes, I put it in a .js file inside public/assets and linked it into my index.html in a script tag.  

This works fine, but the issue is that the data from that js file appears in the window scope and I don't really want it to be in the global scope.  

I figured I could put it inside a function, like angular directives/controllers, and set the data inside that function like this:

``` js
(function(){
    var serveData=function(){
         this.data = {...};
    }
})()
```

But after doing this, I can't seem to find how to access that function "serveData" and its scope.

**Comment by RobertAKARobin** [comment]
I actually just responded to a question about this on StackOverflow! It's in response to an Angular question, but the idea's exactly the same:

http://stackoverflow.com/questions/34778484/angularjs-using-javascript-functions-in-whole-app/34778536#34778536

**Comment by solowt** [comment]
Worked perfectly, thanks.
