### ISSUE TITLE
scope.$watch on multiple options

### ISSUE THREAD

**Issue by joe-gz** [ga-wdi-exercises/project4#123]
Hi, I am using scope.$watch to watch for changes in a filter on a directive. I have it working for one filter, but I now have 2 separate filters that I'm trying to run through the same watch function. is that possible?
My code currently looks like:

``` js
scope.masterData = scope.data;

        scope.$watch('filter', function(newValue, oldValue) {

          $('.chart').remove();
          $('.bubble').remove();
          scope.data = [];

          if (newValue.round === 'Show All') {
            console.log('Make everything show!');
            scope.data = scope.masterData
          } else {
            for (var i = 0; i < scope.masterData.length; i++){
              if (Number(scope.masterData[i].round) === newValue.round) {
                console.log('SHOW JUST '+ scope.masterData[i].round);
                scope.data.push(scope.masterData[i])
              }
            }
          }

          scope.loadChart();
          console.log('NEW VALUE: ' + newValue.round);
        }, true);
```

Where 'filter' is one of my filters, and I'd like to add in a second.  I've researched using scope.$watchCollection or $watchGroup, but the newValues don't understand how to read different options.  Let me know if I can provide additional information.  Thanks!

**Comment by RobertAKARobin** [comment]
Sure, you can do that! Just move the function somewhere else and call it by reference.

``` js
    scope.$watch('filter', myfunction, true);

    function myFunction(newValue, oldValue) {

      $('.chart').remove();
      $('.bubble').remove();
      scope.data = [];

      if (newValue.round === 'Show All') {
        console.log('Make everything show!');
        scope.data = scope.masterData
      } else {
        for (var i = 0; i < scope.masterData.length; i++){
          if (Number(scope.masterData[i].round) === newValue.round) {
            console.log('SHOW JUST '+ scope.masterData[i].round);
            scope.data.push(scope.masterData[i])
          }
        }
      }

      scope.loadChart();
      console.log('NEW VALUE: ' + newValue.round);
    }
```

**Comment by joe-gz** [comment]
I think that could work, but I'm not quite sure how to implement it. I might not have explained my issue very well. 
Basically I am hoping for the .$watch to end up looking something like:

```
scope.$watchCollection(['filter','filterPosition'], function(newValue, oldValue) {...CODE}
```

the issue I'm having is that 'filter' would return something like `newValue.round` while 'filterPosition' would return `newValue.position`. So the function that you are showing above still wouldn't quite work, because it only recognizes `newValue.round`. Is that helpful?

**Comment by RobertAKARobin** [comment]
Gotcha. What is `this` inside the function? My guess is that changes based on the "watched" thing that's activating the function.

**Comment by joe-gz** [comment]
Sorry, I'm not seeing the `this` haha, are you saying i should use that?

**Comment by RobertAKARobin** [comment]
I'm saying try adding a `console.log(this)`.

**Comment by joe-gz** [comment]
ohh, gotcha sorry, let me give that a try

**Comment by joe-gz** [comment]
If i run it with the `scope.$watchCollection` and pass in both filters, `this` returns undefined. if i do it with just one filter in there at a time i see:

```
Object {last: Object, exp: "filter", eq: true}
```

**Comment by RobertAKARobin** [comment]
Wat.

Could you push your code to GH and I'll clone it down and give it a whirl?

**Comment by joe-gz** [comment]
sure thing! https://github.com/joe-gz/fsVisuals
the specific file is in js/league/chart.directive.js, lines 27-52

**Comment by joe-gz** [comment]
and thanks!

**Comment by RobertAKARobin** [comment]
You're not getting this error?
![screen shot 2016-01-14 at 11 52 50 am](https://cloud.githubusercontent.com/assets/6268177/12330911/5d37ca76-bab5-11e5-81f3-1d458584ea63.png)

**Comment by joe-gz** [comment]
Sorry, my readme isn't updated i realize.. Did that pop up just on a league search? right now there is only 1 available, so from the root page you'd have to search for 82326

**Comment by RobertAKARobin** [comment]
Yeah, doesn't seem to be working. How about just using two `scope.$watch`?

``` js
        scope.$watch('filter', filterWatch, true);
        scope.$watch('filterPosition', filterWatch, true);
```

**Comment by RobertAKARobin** [comment]
``` js
        function filterWatch(newValue, oldValue) {
          console.log("The filter is named '" + this.exp + "'");
          console.dir(this)
```

![screen shot 2016-01-14 at 12 06 29 pm](https://cloud.githubusercontent.com/assets/6268177/12331384/4542658c-bab7-11e5-910c-a4e3642344c9.png)

**Comment by joe-gz** [comment]
Thanks Robin! I will play around with this a little and let you know. The issue i've with separating it into two watch functions previously is that I am hoping that these two work concurrently.  So in other words, if i change something in the first filter, the data are updated. Then, if I change the second, the data are updated again, but still maintains whatever i set in the first filter as well

**Comment by RobertAKARobin** [comment]
I'll close this for now, then. Feel free to re-open it if necessary.
