### ISSUE TITLE
Accessing model methods in the front end

### ISSUE THREAD

**Issue by murgia** [ga-wdi-exercises/project4#124]
I currently have a couple methods defined in the front end, total_energy and total cost.  I am currently trying to access those methods in the front end to create a div that includes all of the properties of the Electcalc class and then the total_energy and total cost results that are defined in the Electcalc class.  I tried using the same bracket notation that got the properties to show like this

``` hbs
<ul>
    <li>{{electcalc.state}}</li>
    <li>{{electcalc.avg_cost}}</li>
    <li>{{electcalc.total_energy}}</li>
    <li>{{electcalc.total_cost}}</li>
  </ul>
```

The first two work because they are direct properties.  The second two do not and I am not sure how to get them to work.  I have tried a couple things I saw online like including self. in the methods.  I am able to access the methods using my rails console but I am having trouble connecting that to the front end.  

Here is a link to my repo for the front end and back end
https://github.com/murgia/kilowatt_calc_api
https://github.com/murgia/kilowatt-calc

I believe the issue is in js/electcalcs/index.html

Thank you!

**Comment by RobertAKARobin** [comment]
This is Angular? If so, then you should be able to just call the method with `()` as usual.

``` js
        scope.hello = function(){
          return "hi there";
        }
```

``` html
<h3>{{hello()}}</h3>
```

**Comment by murgia** [comment]
The methods are written in the model in rails.

**Comment by RobertAKARobin** [comment]
You call stuff in Rails with clownhats, not handlebars...?

**Comment by murgia** [comment]
so my front end is in angular but the back end is in rails

**Comment by murgia** [comment]
```
def total_energy
    estimates = self.estimates
    cumulative_energy = 0

    estimates.each do |estimate|
      power = estimate.appliance.power
      quantity = estimate.quantity
      yearly_power = power*quantity*12
      cumulative_energy += yearly_power
    end
    cumulative_energy
  end
```

that is what the method looks like in my api

**Comment by RobertAKARobin** [comment]
So you're trying to use Javascript to call a method of a Ruby object? I'm afraid that's not possible.

**Comment by murgia** [comment]
hmmm i was afraid of that

**Comment by RobertAKARobin** [comment]
If all it's doing is calculating stuff, do it in Javascript instead of Ruby!

**Comment by murgia** [comment]
so even though if i pull up my rails console and do Electcalc.last.total_energy to get the total energy, there is no way i can somehow get that information with an ajax call or something?

**Comment by RobertAKARobin** [comment]
You'd have to create a whole Rails route for it. Programming languages can't just talk to each other like that. It's like expecting Chinese and Arabic to flow nicely together.

**Comment by murgia** [comment]
hmmm okay.  I am worried about the logic in the javascript because information i need exists across 3 separate models and i need information from all of them to be able to compile the information.

**Comment by RobertAKARobin** [comment]
How about you add something to your Rails controller so that whenever AJAX asks it to serve that Electcalc information, Rails calculates the total energy and adds the result to the JSON that's sent back?

``` rb
def show
  @el = Electricalc.find(42)
  @el.t_energy = @el.total_energy
  res json: @el
end
```
