### ISSUE TITLE
Adding value to join table, and duplicating entries

### ISSUE THREAD

**Issue by rebeccaestes** [ga-wdi-exercises/project4#127]
I have three tables in my app: asanas for yoga poses, sequences for lists of those poses, and a join table. I need help figuring out a way to have the "order" column in the join table automatically populate with the next number available in a specific sequence when a new asana is added to it, and ideally, a way for the user to reassign those numbers. This was mentioned briefly in a <a href="https://github.com/ga-dc/curriculum/blob/ce54ddb6c20814769420c76f5e6aef82b260e15c/06-project-2/rails-many-to-many-relationships/readme.md">tunr playlist exercise</a>, but the solution doesn't appear to actually implement it. I did some googling but nothing really helped me.

I suspect the solution is including the sequence as { data: # } somewhere in the `add_asana_sequence_path` link in views/sequences/show (lines 21 & 31) but I don't know where exactly, or how to tell it to grab the next available value (or at least how to make the user specify an order - although in that case the following asanas would have to know to reorder themselves).

Also, I am able to add multiple asanas to a sequence, but if I decide to delete one of those instances they all disappear. I know this is coming from line 14 of that views/sequences/show file, because it's looking for all the asana.ids that match, but I can't figure out how to change it to the actual ID. `id: id` and all the variations of that I tried don't work.

**Comment by RobertAKARobin** [comment]
Could you give me an example of what this might look like in your database? If you could make a few rows and columns in a Google Sheet or Excel or something and screenshot it that would be awesome.

**Comment by rebeccaestes** [comment]
I'm actually using a database GUI, so here's a screenshot of the join table (that first column that's a little bit cut off is the ID)

<img width="504" alt="screen shot 2016-01-14 at 2 00 42 pm" src="https://cloud.githubusercontent.com/assets/3891862/12334266/2477e7d6-bac7-11e5-9eb3-67da0253591d.png">

So the first two lines, which are part of sequence 1, should have 1 and 2 (or 2 and 1, depending on the order) in the column Order, instead of null. Then each of the next 10 lines should have a number between 1 and 10 that no other asana in sequence 2 has.

**Comment by RobertAKARobin** [comment]
Oh, wow!

**Comment by rebeccaestes** [comment]
Hmm I think I may have actually just solved this with a useful drop-down menu ... let me check

<img width="925" alt="screen shot 2016-01-14 at 2 06 19 pm" src="https://cloud.githubusercontent.com/assets/3891862/12334390/cc0bd782-bac7-11e5-8277-ed9fc4bd7a13.png">

**Comment by RobertAKARobin** [comment]
Honestly, there isn't really a good way to do this as far as I know. You could do a `after_save` or something that updates other records automatically, but it's easy to get into infinite loops that way and I think it'd be more trouble than it's worth.

Instead, I'd recommend creating a new field called `order` on the `sequence` table and inside it just writing a CSV of the asanas in order: `32,41,8,29,6`

**Comment by RobertAKARobin** [comment]
You can't rely on the order in which things visually appear in the database. Postgres may shuffle them around. That's why an ID column is necessary.

**Comment by rebeccaestes** [comment]
OK - so if I had an order field in the sequence, would I need a join table at all? Since I could just split the sequence.order value at the commas and then find the asana with that ID ...

**Comment by RobertAKARobin** [comment]
Depends on whether you want to be able to do snappy ActiveRecord stuff like `Sequence.asanas.create` and so on. If so, then you still need the join table.
