### ISSUE TITLE
404 Error loading fonts with @font-face

### ISSUE THREAD

**Issue by mpopv** [ga-wdi-exercises/project4#128]
Here is my CSS:

``` php
<?php $root = get_template_directory(); ?>
<style>
  @font-face {
    font-family: NowBold;
    src: url(<?php echo $root ?>/fonts/now/now-bold-webfont.eot),
      url(<?php echo $root ?>/fonts/now/now-bold-webfont.eot?iefix) format('eot'),
      url(<?php echo $root ?>/fonts/now/now-bold-webfont.woff2) format('woff2'),
      url(<?php echo $root ?>/fonts/now/now-bold-webfont.woff) format('woff'),
      url(<?php echo $root ?>/fonts/now/now-bold-webfont.ttf) format('truetype'),
      url(<?php echo $root ?>/fonts/now/now-bold-webfont.svg#webfont) format('svg');
  }
  .now-bold {
    font-family: NowBold, Helvetica, Arial, sans-serif !important;
  }
</style>
```

Here is the error I am seeing:

![screen shot 2016-01-14 at 1 20 38 pm](https://cloud.githubusercontent.com/assets/15032398/12333353/b82d7cc6-bac1-11e5-94b6-02f90fdbf912.png)

Here is my file structure:

![screen shot 2016-01-14 at 1 22 15 pm](https://cloud.githubusercontent.com/assets/15032398/12333376/dab4f8aa-bac1-11e5-9b14-57f4bd3acf03.png)

Although only some of the fonts are returning a 404 error, none of the fonts are loading.

**Comment by mpopv** [comment]
Ignore the ugly !importants and hacky php > html > css nesting, those were both a result of trying to debug.

**Comment by mpopv** [comment]
Anyway I found a CDN for this font, but I'm still very curious as to why I'm getting this error, so if you see something obvious I've overlooked let me know--otherwise don't worry about it and feel free to close.

**Comment by RobertAKARobin** [comment]
Sorry for the delay. Check out those URLs that `$root` is giving you: `localhost/Applications/XAMPP/htdocs`...

When you're using XAMPP, `localhost` _is_ the `htdocs` folder. So you're telling the server "Look inside the `htdocs` folder for an Applications folder, for a XAMPP folder, for an `htdocs` folder."

**Comment by mpopv** [comment]
Ahhhh okay, got it. Thanks Robin!
