### ISSUE TITLE
Deploying Rails/Backbone App on Heroku

### ISSUE THREAD

**Issue by ajohnson052** [ga-wdi-exercises/project4#132]
I am trying to deploy to Heroku, and I keep getting the following error: 

```
remote: -----> Preparing app for Rails asset pipeline
remote:        Running: rake assets:precompile
remote:        rake aborted!
remote:        ExecJS::ProgramError: Unexpected token: punc (.) (line: 15308, col: 23, pos: 459589)
remote:        Error
```

Initially I had created my own backbone file structure within assets, but I added in the gem rails-backbone hoping that it would help remedy the problem. Unfortunately I am still getting the same error. I'm finding it very difficult to research/troubleshoot, but I'm guessing that something within my javascripts/application.js might be the problem. Here are the requirements I currently have.

```
//= require 'backbone/app.js'
//= require 'backbone/models/hood.js'
//
//= require jquery
//= require jquery_ujs
//= require turbolinks
//= require underscore
//= require backbone
//= require backbone_rails_sync
//= require backbone_datalink
//= require_tree .
```

I made sure to include "gem 'rails_12factor', group: :production". 

When I try to precompile assets locally, as per the heroku devcenter, I get the same error.

It would be awesome if someone else could take a look!

**Comment by RobertAKARobin** [comment]
For now, I'd say just disable the precompiling.

http://stackoverflow.com/a/18936392/2053389

Once it's deployed, then you can worry about tracking down the rogue period, if you really want to.
