### ISSUE TITLE
Adding Functionality to Outfit_Items

### ISSUE THREAD

**Issue by dan-ator** [ga-wdi-exercises/project4#134]
I have items working. I have outfits working.  Now I need a way to add the items to the outfits.  In my active record/models I have outfit_items for this and it is a model that belongs to both outfits and items.  Items has many outfits through outfit_items and outfits have many items through outfit_items.  I know this has something to do with on my backend adding routes and so I have this on items controller:

``` rb
def add_outfit_item
  @item = Item.find(params[:id])
  @item.outfit_items.new(item_params)
  if @item.outfit_items.save
    render json: @item.outfit_items.to_json, status: :created
  else
    render json: @item.outfit_items.errors, status: :unprocessable_entity
  end
end

def remove_outfit_item
  @item = Item.find(params[:id])
  @item.outfit_items.destroy_all
  render json: {message: "success"}, status: :ok
end
```

and in routes.rb I have:

``` rb
resources :items , except: [:new, :edit] do
    member do
      post 'add_outfit_item'
      delete 'remove_outfit_item'
    end
  end
```

I know there are other things I need to do but on a conceptual understanding level I don't really understand what is going on so I am submitting this issue so I can speak to someone at genius bar hopefully.

**Comment by RobertAKARobin** [comment]
`@item.outfit_items` is an array. You can't call `.save` on an array. You can only call it on one item in the array.

How about `@item.outfit_items.create(item_params)`?

**Comment by dan-ator** [comment]
I am trying to write a drop down menu on the show page for an item that lists all of the outfits.  I have 

``` html
<select>
  <div data-ng-repeat="outfit in ItemShowViewModel.outfits">
    <option value = "{{ItemShowViewModel.outfit.name}}" >Boo</option>
  </div>
</select>
```

and to do this I thought I could just add the OutfitFactory to the Show controller and then add `this.outfits = OutfitFactory.query();` to the show controller function and so I also added OutfitFactory to the .controller but that didn't work so I tried adding "outfits" to  the .module.  It looked like this:

``` js
"use strict";

(function(){
  angular
  .module("items", "outfits")
  .controller("ItemShowController", [
    "ItemFactory",
    "OutfitFactory",
    "$stateParams",
    ItemShowControllerFunction
  ]);

  function ItemShowControllerFunction(ItemFactory, $stateParams, OutfitFactory){
    this.item = ItemFactory.get({id: $stateParams.id});
    this.outfits = OutfitFactory.query();
  }
}());
```

That gave me an error:

```
Error: $injector:modulerr
Module Error
```

So I don't know if that means that this whole path I am trying to take is just not going to work or if I need to add something else.
