### ISSUE TITLE
big picture - angular authentication

### ISSUE THREAD

**Issue by ghost** [ga-wdi-exercises/project4#135]
i'm wading into authentication setup and want to clarify i few things before i lose sight of the shore.

namely:
- the fields in my back-end table need to mirror what i'll request in the front end?  email, zip code, name.
- giving anyone the ability to view the posts without logging in, and requiring login to create/edit/delete posts and to view/delete comments.

i've looked through the angular auth lesson plan and online, but don't feel like i've answered my questions.

my backend repo: https://github.com/thomhouseholder/runners-app

front end:  https://github.com/thomhouseholder/runners-angular

**Comment by RobertAKARobin** [comment]
Don't do authentication unless the rest of your app is working great. If your app needs to have users, create a "User" table that just has one "username" or "email" column. No passwords -- no actual security. That's perfectly adequate for development.

**Comment by ghost** [comment]
Leaving until the very end makes sense.  Hello back-to-master-branch!

I'm a little unclear on the merits of creating the simple user table you describe.  The reason I want users/authentication is to segment functionality for logged in/out users.  Doesn't seem like the simple user table would allow me to play in that area, so I should skip users altogether for now, right?

**Comment by RobertAKARobin** [comment]
Sure, you can still log in and log out! The way you do it is you type in the username (or the e-mail, if that's the column you use). Of course it's completely insecure -- if I know John Smith's username I can log in as him -- but that doesn't make one lick of difference until you have people actually using your app.

And you can certainly have other columns -- name, profile picture, favorite food, etc -- you just don't need to have passwords and all that gnarly security stuff which you'll spend all night banging your head against.

**Comment by ghost** [comment]
I like this idea. Is the angular lesson plan still the best walkthrough of doing this simplified setup?  I feel like it might be but some steps need to be skipped.
- still install devise gem and set up back end?
- follow lesson plan to set up front end but with no pw, only email address?
- is that too simplified?

**Comment by RobertAKARobin** [comment]
- Don't install Devise, nor Passport, nor anything. You only need that stuff if you're doing fancy user auth with security and everything.
- Yep.
- Nope.

**Comment by ghost** [comment]
hmm okay i'll give that a whirl!
