### ISSUE TITLE
Angular class toggle?

### ISSUE THREAD

**Issue by starrchen** [ga-wdi-exercises/project4#137]
I think I'm just at a point where I have, once again, looked at too many different tutorials and StackOverflow answers so I'm not sure what the best way to do this is?

Still trying to just toggle class names by click so that I can filter by them later. I was having trouble even adding checkmarks to my bucket list items at all, so I can't even toggle colors/class by checkboxes because I can't get checkboxes to show up or to check if they do show up.

Am I overlooking some tenet of Angular that is like "Don't do these things you would otherwise do with your apps because the Angular magic will interfere"? This has been a very frustrating styling afternoong for me. :disappointed:

**Comment by starrchen** [comment]
Got some of the checkmark stuff working but I'm still not sure what the best way to toggle classes might be? Or... should I just drop that and try to use an Angular filter by if it's checked/unchecked?

(Is it even possible to filter by class name or by checked/unchecked inputs?)

**Comment by RobertAKARobin** [comment]
Want to push up your code so I can look?

**Comment by starrchen** [comment]
Sure! Working mainly off this file: https://github.com/starrchen/dc-bucket-list/blob/master/public/js/items/index.html

I've also re-deployed it if you just want to see what I am looking at while banging my head: https://dc-bucket-list.herokuapp.com/

**Comment by RobertAKARobin** [comment]
Give this a whirlypoo:

``` html
<!DOCTYPE html>
<html>
  <head>
    <title>Angular</title>
    <script src="https://ajax.googleapis.com/ajax/libs/angularjs/1.3.15/angular.min.js"></script>
    <style>
.rouge{
  background-color:red;
}
.bleu{
  background-color:blue;
}
    </style>
    <script>
    angular.module("myApp", [])
    .controller("myCtrl", [function(){
      this.clazz = "";
    }]);
    </script>
  </head>
  <body ng-app="myApp" ng-controller="myCtrl as VM" ng-class="VM.clazz">
    <input ng-model="VM.clazz" />
    <p>Type 'rouge' or 'bleu'.</p>
  </body>
</html>
```
