### ISSUE TITLE
Couple of concept issues

### ISSUE THREAD

**Issue by onesick** [ga-wdi-exercises/project4#138]
Hey guys, there are couple of concepts and terminologies I cannot understand, which I believe these are general programming concept that are not limited to Angular.
1. injection dependencies
2. property binding. I understood that you are binding a property by notating it someway, but usage is a bit itchy for me.

Reading docs were not enough for me to clear them. Can you please help me?

**Comment by RobertAKARobin** [comment]
1. That's the process of including a library (like a gem) in an Angular app. As in, "My Rails app is dependent on ActiveRecord. My Angular app is dependent on UI Router. My website is dependent on jQuery."
2. Can you give a specific example?
