### ISSUE TITLE
Issue with Plugin in Angular

### ISSUE THREAD

**Issue by Ly900** [ga-wdi-exercises/project4#139]
I am trying to use a JQuery plugin called "Featherlight" in Angular. I think I am mixing the different ways I can configure the plugin. 

What I would like to happen is when I click on the card, the whole card along with its HTML opens in the Featherlight box. 

I've tried using the data-featherlight attribute as an html attribute and got the whole page to show up in the lightbox. However, ideally, I would like to bind the Featherlight event to the card divs in my special directive that I made for it. 

Documentation for Featherlight: 
https://github.com/noelboss/featherlight/#usage

// index.html (this is the div I want to show up in the lightbox, specifically, the card clicked on)
![image](https://cloud.githubusercontent.com/assets/12722650/12337710/8e285550-bad9-11e5-8acc-8720248ee299.png)

// featherlight.directive.js
![image](https://cloud.githubusercontent.com/assets/12722650/12337727/a968444c-bad9-11e5-8fa5-18c10be1a7f5.png)

**Comment by Ly900** [comment]
Update: 

// directive
![image](https://cloud.githubusercontent.com/assets/12722650/12337823/5ee52d76-bada-11e5-9bd2-df3c378bdcd4.png)

// index.html
![image](https://cloud.githubusercontent.com/assets/12722650/12337834/6c2f9f98-bada-11e5-98c8-40fa10d7bbe1.png)

Result (Empty lightbox):
![image](https://cloud.githubusercontent.com/assets/12722650/12337844/75c9f486-bada-11e5-950f-48d6d63a0fcf.png)

**Comment by RobertAKARobin** [comment]
I'm afraid I don't know a thing about Featherlight, Ly. I'd encourage you to make a StackOverflow question about it.

**Comment by Ly900** [comment]
I'm really close. I can get a card to show up now. Are you not able to look at it for 5 mins?

**Comment by Ly900** [comment]
I can get the lightbox to work now but not show the correct card. I think it may be an Angular problem?
