### ISSUE TITLE
issue with Heroku deployment

### ISSUE THREAD

**Issue by jordanbrauner** [ga-wdi-exercises/project4#140]
I tried to deploy my app to Heroku. I followed the getting started guide and specified the npm and node versions in my package.json file. I also added a Procfile containing "web: node app.js". I also temporarily deactivated mongoose to make sure that's not an issue (I know I'll have to change the url it connects to).

Here's the two errors in my heroku logs:
2016-01-14T23:19:08.876942+00:00 heroku[router]: at=error code=H10 desc="App crashed" method=GET path="/favicon.ico" host=moonlight-mansion.herokuapp.com request_id=4d1953f0-22d9-4b47-8d63-3f2273e114de fwd="173.69.171.55" dyno= connect= service= status=503 bytes=

2016-01-14T23:19:08.786624+00:00 heroku[router]: at=error code=H10 desc="App crashed" method=GET path="/" host=moonlight-mansion.herokuapp.com request_id=017ded87-6151-4db4-b71d-67bd077ce4e1 fwd="173.69.171.55" dyno= connect= service= status=503 bytes=

https://github.com/jordanbrauner/moonlight-mansion/tree/herokuDeployed

heroku url:
https://moonlight-mansion.herokuapp.com/

**Comment by solowt** [comment]
what does `heroku ps` return?

edit- tested on my deploy, returns a different error if scaling is set to 0

**Comment by jordanbrauner** [comment]
=== web (Free): npm start
web.1: crashed 2016/01/14 20:43:00 (~ 55m ago)

**Comment by RobertAKARobin** [comment]
What does `heroku logs --tail` tell you?

**Comment by RobertAKARobin** [comment]
Here's a problematic line:

https://github.com/jordanbrauner/moonlight-mansion/blob/herokuDeployed/app.js#L26

**Comment by jordanbrauner** [comment]
Thanks Robin. It seems there a few other problematic lines as well. I've tried setting up MongoLab but keep finding new errors. I think I'm going to just demo it locally as I've run out of time. Thanks for checking!

**Comment by RobertAKARobin** [comment]
Did you try deploying the little_node_app I sent out?

**Comment by jordanbrauner** [comment]
Thank you, I saw that and will definitely go through it when I have the chance to do so. But I'm out of time as I present at 1 and I've been working at home this morning and I'm just leaving my house now (long commute).
