### ISSUE TITLE
not a project issue, just a question about the design resources

### ISSUE THREAD

**Issue by rebeccaestes** [ga-wdi-exercises/project4#141]
Are we supposed to have free access to the two GA design links? All I see is a button to start a free trial.

**Comment by RobertAKARobin** [comment]
I'm not sure which design resources these are... Can you be more specific?

**Comment by rebeccaestes** [comment]
These two:
Visual Design Hacking (a great tips-and-tricks focused video from Front Row)
Web Design For Non-designers (another great design-related course for all the nerds out there)

**Comment by RobertAKARobin** [comment]
I understand Brian responded to you, so I'ma close this.
