### ISSUE TITLE
Angular Create Button Many to Many Relationship

### ISSUE THREAD

**Issue by dan-ator** [ga-wdi-exercises/project4#142]
I am trying to get the create button to work that would add an item to an outfit (I think it would be creating an outfit_item in the process, that is the join model).  My button looks like this:

``` html
<button type="button" class="btn btn-success" data-ng-click="ItemShowViewModel.create()">Add to Outfit</button>
```

and I have tried several things in the show controller but none of them work.  The current try is something like this:

``` js
    this.outfit = OutfitFactory.get({id: $stateParams.id });
    this.outfit.create(function(){
      this.outfit.$save(this.outfit, function(item){
        $state.go('itemIndex', item);
      })
    })
```

and that gets `TypeError: this.outfit.create is not a function`.  So I guess the issue is properly referencing the outfit (I think).  I would think that it really should be `this.outfit_item.create` and that would be a function of `this.outfit.$save` but I don't know how I would be able to reference outfit_items here.

**Comment by RobertAKARobin** [comment]
`this.outfit` is an instance of `OutfitFactory`. Instances of `OutfitFactory` do not have a `create` method.

When you say `ItemShowViewModel.create()`, you're trying to call a `create` method on an **instance of your controller** -- _not_ `OutfitFactory`.

What word do you need to delete from `this.outfit.create(function(){` to make `create` an instance method of the controller, rather than an instance method of `OutfitFactory`?

**Comment by dan-ator** [comment]
I tried using just `this.create(function(){...` but that returns the same error (`type error` ).

**Comment by RobertAKARobin** [comment]
`this.create(function(){` _calls_ a function. You need to _define_ a function. `this.create = function(){`.

**Comment by dan-ator** [comment]
Now I have 

```
this.outfit = OutfitFactory.get({id: $stateParams.id });
    this.create = function(){
      this.outfit.$save(this.outfit, function(item){
        $state.go('itemIndex', item);
      })
    }
```

and the error I get is

```
POST http://localhost:3000/outfits?$promise=%7B%7D&$resolved=true 400 (Bad Request)
```

What I am trying to do is save the item to the outfit that is selected but clearly it is not doing that.

**Comment by RobertAKARobin** [comment]
Check your Rails server logs in Terminal.
