### ISSUE TITLE
AWS Rails Carrierwave Issue

### ISSUE THREAD

**Issue by dan-ator** [ga-wdi-exercises/project4#143]
I thought I had set up carrierwave to upload pictures to the bucket on AWS that I set up using the lesson plan from the mini lesson.  But the pictures that are uploaded through Angular with "angularFileUpload" are actually being stored locally in the public folder on the rails backend.  I don't know if this is something to do with the Angular module I am using or with how it is set up in Rails.  I am not really sure how to start on this one.

**Comment by RobertAKARobin** [comment]
As long as your pictures are getting stored somewhere, that's good enough for presenting today.

My guess is you're uploading the files to the wrong URL. Can you push to Github?

**Comment by dan-ator** [comment]
This is the backend: https://github.com/dan-ator/project_four_rails
This is the frontend: https://github.com/dan-ator/project_four_angular

**Comment by RobertAKARobin** [comment]
Should this be an AWS URL?

https://github.com/dan-ator/project_four_angular/blob/master/app/items/new.controller.js#L16

**Comment by dan-ator** [comment]
I suppose so.  Where in my application would that URL be located so I know what it is? I know the name of the bucket but can't find a proper name for the URL.  I tried:

```
project-4-closet-photos.s3-website-us-east-1.amazonaws.com
```

But this gave me an error when I tried to upload, saying `POST http://localhost:8080/project-4-closet-photos.s3-website-us-east-1.amazonaws.com 405 (Method Not Allowed)`

**Comment by RobertAKARobin** [comment]
I'm afraid that's on you to figure out. You'll need to read the AWS documentation.
