### ISSUE TITLE
website forwarding

### ISSUE THREAD

**Issue by jacohen10** [ga-wdi-exercises/project4#144]
I’ve made app.elevatemealplan.com a subdomain of my website elevatemealplan.com. It forwards to my heroku site, but it appears as the heroku site and not the subdomain. In order to make it appear as app.elevatemealplan.com am I supposed to doing something additional on heroku?

**Comment by RobertAKARobin** [comment]
Hmm. So you're saying that the site _redirects_ to Heroku, and you want it to just _display_ Heroku without changing the URL?

**Comment by jacohen10** [comment]
correct

**Comment by RobertAKARobin** [comment]
There's not really a way to do that without configuring the DNS settings on your Heroku app. I'm not sure how to do that.

**Comment by jacohen10** [comment]
So I went to my host and entered in the subdomain and my heroku site as the alias. That seems to have solved it!
