### ISSUE TITLE
Simple Angular Login Not Working

### ISSUE THREAD

**Issue by ghost** [ga-wdi-exercises/project4#145]
On good advise, I'm trying to create a simple login on the front end of my project.  No pw, just email.

I've used the angular authentication lesson plan to set up a user signin, but now the 'runner' module won't load:

angular.js:4109Uncaught Error: [$injector:modulerr] http://errors.angularjs.org/1.3.15/$injector/modulerr?p0=runner&p1=Error%3A…gleapis.com%2Fajax%2Flibs%2Fangularjs%2F1.3.15%2Fangular.min.js%3A18%3A179)

That's the error even though I set up my sessions.controller with 

```
"use strict";

(function(){
  angular
  .module("posts")
  .controller("SessionsController", function($auth){
    this.signinForm = {};
    this.signin = function() {
      $auth.submitLogin(this.signinForm)
      .then(function(resp) {
        console.log("Signin success:", resp);
      })
      .catch(function(resp) {
        console.log("Signin failure:", resp);
      });
    };
  });
}());
```

my back end is https://github.com/thomhouseholder/runners-app
and my front end is https://github.com/thomhouseholder/runners-angular/tree/simple-user

**Comment by nolds9** [comment]
@thomhouseholder looks like you have `.module("posts")` in your sessions controller, have you injected `$auth` anywhere? Maybe into that module?

**Comment by ghost** [comment]
have not.

that's adding $auth to that .controller array?

**Comment by nolds9** [comment]
exactly

**Comment by ghost** [comment]
thanks!  please add this to my tab.
