### ISSUE TITLE
Deployment

### ISSUE THREAD

**Issue by kaustly** [ga-wdi-exercises/project4#147]
I'm trying to deploy to heroku, but getting this error:
<img width="1440" alt="screen shot 2016-01-15 at 10 22 30 am" src="https://cloud.githubusercontent.com/assets/13460389/12356703/f944b214-bb71-11e5-979b-cceab172557e.png">
Just not quite sure what to do next. I tried reseting the database and running migrations again, but no luck

**Comment by nolds9** [comment]
Looks like a migrations issue. What happens when you run `heroku run rake db:migrate`?

**Comment by kaustly** [comment]
🙁
<img width="1325" alt="screen shot 2016-01-15 at 10 35 15 am" src="https://cloud.githubusercontent.com/assets/13460389/12357015/b4e4e1dc-bb73-11e5-9275-82c59da4bc9f.png">

**Comment by RobertAKARobin** [comment]
~~What are the first lines in that stack trace?~~

I understand Nick's working with you.
