### ISSUE TITLE
Angular div not appearing when data is pushed

### ISSUE THREAD

**Issue by Briik** [ga-wdi-exercises/project4#148]
I want this div to appear when the array it draws data from is populated, it is not.

HTML:

``` html
<ul data-ng-if="Contract.IndexViewModel.selectedElements[0]">
    <li data-ng-repeat="selectedElement in ContractIndexViewModel.selectedElements"><a data-ui-sref="contractShow({title: selectedElement.label})">{{selectedElement.label}} - ${{selectedElement.value}}</a></li>
</ul>
</div>
```

JS:

``` javascript
self.selectedElements = [];
// skipping down to related code...
document.getElementById('myChart').onclick = function(evt) {
                    var activePoints = contractsOverTime.getPointsAtEvent(evt);
                    console.log(activePoints);
                    self.selectedElements.splice(0,self.selectedElements.length);
                    activePoints.forEach(function(contract) {
                        self.selectedElements.push(contract)
                    });
                    console.log("selectedElements: " + self.selectedElements);
                    // => activePoints is an array of points on the canvas that are at the same position as the click event.
                };
```

**Comment by Briik** [comment]
I corrected the html typos and it's still not working

``` html
<ul data-ng-if="ContractIndexViewModel.selectedElements[0]">
    <li data-ng-repeat="selectedElement in ContractIndexViewModel.selectedElements"><a data-ui-sref="contractShow({title: selectedElement.label})">{{selectedElement.label}} - ${{selectedElement.value}}</a></li>
</ul>
```

**Comment by nolds9** [comment]
I think you're trying to do a little too much DOM manipulation in the controller, I would recommend instead attaching a method to `self` like `self.myFunction( )` that you could then call in the view with `ng-click = ContractIndexViewModel.myFunction( )`

**Comment by Briik** [comment]
I tried moving things around in the controller but it gets too messy. So I moved it all to a scripts.js file, but can't get it to load (because it either errors out if it's in the page's html head or doesn't get loaded at all if it's in the Angular View)

**Comment by Briik** [comment]
Can I link to the scripts.js file with ng-click?  I'm not sure how.

**Comment by nolds9** [comment]
can you push your code?
It all depends on how you set up angular

**Comment by Briik** [comment]
pushed

**Comment by nolds9** [comment]
and link it

**Comment by nolds9** [comment]
and link it

**Comment by Briik** [comment]
https://github.com/Briik/milContracts/tree/master/milC_AngularFE/js

**Comment by RobertAKARobin** [comment]
Don't worry about mess. That kind of logic belongs in the controller. You can't really mix Vanilla JS click events with Angular click events. Just go with Angular.

**Comment by Briik** [comment]
ok

**Comment by nolds9** [comment]
As a rough outline, I would move the method you have in `script.js` to `index.controller.js` like so:

```
// in ContractIndexControllerFunction

self.showDiv = function( evt ){
      var activePoints = contractsOverTime.getPointsAtEvent(evt);
      console.log(activePoints);
      self.selectedElements.splice(0,self.selectedElements.length);
       activePoints.forEach(function(contract) {
          self.selectedElements.push(contract)
       });
      console.log("selectedElements: " + self.selectedElements);
}
```

and then in the `html`:

```
<ul data-ng-if="ContractIndexViewModel.selectedElements[0]">
    <li data-ng-click="ContractIndexViewModel.showDiv( )" data-ng-repeat="selectedElement in ContractIndexViewModel.selectedElements"><a data-ui-sref="contractShow({title: selectedElement.label})">{{selectedElement.label}} - ${{selectedElement.value}}</a></li>
</ul>
```

**Comment by Briik** [comment]
So one issue there is that contractsOverTime refers to a DOM element that does not exist for the first 1second after page load (getting the data together to build the chart takes somewhere between 500 and 1000ms on my machine).

The other issue is that the click event needs to be on that DOM element (contractsOverTime) and pass in the click event data (as is normally passed by whatever.onclick = function(evt){...}

I will try to get that working.
Question: Can i pass that evt data using ng-click?  I tried something like data-ng-click="ContractIndexModel.showDiv(evt)" and i don't think it worked.

**Comment by RobertAKARobin** [comment]
https://docs.angularjs.org/guide/expression#-event-

**Comment by Briik** [comment]
Fixed! Thank you.
https://github.com/Briik/milContracts/tree/master/milC_AngularFE/js/contracts
