### ISSUE TITLE
Delete/Destroy function in Rails App

### ISSUE THREAD

**Issue by dttruong** [ga-wdi-exercises/project4#149]
I defined destroy in my controller but when I click delete on the app, it redirects me to the previous page. I looked on rake routes to see where to send the path, but it continues to not work. 

```
    def destroy
        @comment = pho.comment.find(params[:pho_id])
        authorize! :destroy, @pho.comment
        @pho.comment.destroy
        redirect_to phos_path
    end
```

**Comment by nolds9** [comment]
I think this is a problem with how we are selecting our comment to destroy- I'd check the output of `rake routes` to see what the path should be

**Comment by nolds9** [comment]
Also, would recommend looking at how we are currently selecting our comment to destroy. i.e.  if we were to log the value of `@comment` I don't think its what we would expect...

**Comment by dttruong** [comment]
Thanks! I see that I had defined the comments the wrong way

```
    def destroy
        @comment = Comment.find(params[:id])
        @pho = Pho.find(params[:pho_id])
        @comment.destroy
        redirect_to @pho
    end
```
