### ISSUE TITLE
Ruby enumerables -- find in an array of hashes

### ISSUE THREAD

**Issue by mattficke** [ga-wdi-exercises/project4#15]
I'm trying to find a particular hash in an array of hashes by the `:id` key:value pair, and can't quite get it to work. I've tried a bunch of ruby enumerable variations, I was expecting something like this to work:

``` ruby
def self.fetch(id)
    data = self.status() #data is the array of hashes, each representing a station
    data.find{|station| station[:id].to_i == id}
  end
```

I also tried `data.index`, and a few others without success. Depending on how I word it, I'll either get back the whole array, or null.

I checked if the data is being passed through by doing `puts station[:id]` and `puts id`, and it comes through ok.

Any thoughts?

**Comment by jshawl** [comment]
what about `puts station[:id] == id`?

also recommend using `binding.pry` inside of `find` method

**Comment by mattficke** [comment]
Ah! Helpful. Got it working. Thanks.
