### ISSUE TITLE
issue with connecting to mongolab

### ISSUE THREAD

**Issue by Ly900** [ga-wdi-exercises/project4#151]
Not sure which one would be correct or how to change it to make it work. The documentation has it the first way and your little node app has it the second way:

![image](https://cloud.githubusercontent.com/assets/12722650/12358573/e5641ad2-bb7b-11e5-939f-b0670f41ac4c.png)

**Comment by RobertAKARobin** [comment]
Looking at the `mongojs` documentation, you don't need to put `mongodb://` before the URL.

**Comment by Ly900** [comment]
![image](https://cloud.githubusercontent.com/assets/12722650/12358652/5dfaedd6-bb7c-11e5-97d5-8ce6c1a80fb3.png)

**Comment by RobertAKARobin** [comment]
``` js
var db = mongojs('ly900:f00@ds045785.mongolab.com:45785/techwizme', ['techwizme'])
```

**Comment by Ly900** [comment]
OK that is what I am using... looks like there are other issues in the log

**Comment by RobertAKARobin** [comment]
Is that _exactly_ what you're using? You wrote something different above. It began with `mongodb://`.

**Comment by Ly900** [comment]
This is what I have now:
![image](https://cloud.githubusercontent.com/assets/12722650/12358880/66bd066a-bb7d-11e5-8aa2-4a643407f2ce.png)

**Comment by RobertAKARobin** [comment]
Can you push your code to GH?

**Comment by Ly900** [comment]
https://github.com/Ly900/techwizme

**Comment by RobertAKARobin** [comment]
Just to make sure: your password is `f00`, and not `foo`?

**Comment by Ly900** [comment]
IM DEPLOYEED!!!!!!!!!!!!!
