### ISSUE TITLE
issue with checkbox in deployed version

### ISSUE THREAD

**Issue by jacohen10** [ga-wdi-exercises/project4#153]
I have a checkbox that works locally. I expected it to work the same way in the deployed version, but it doesn't.
My repo link is https://github.com/jacohen10/Project2/blob/master/app/views/restaurants/_form.html.erb and my question is about lines 22.

**Comment by RobertAKARobin** [comment]
Can you be more specific about how it's not working?

**Comment by jacohen10** [comment]
when you submit it when it's checked the value doesn't change to true

**Comment by RobertAKARobin** [comment]
How do I create a restaurant?

**Comment by jacohen10** [comment]
line 3 has a 2nd form for some reason. deleted it and about to test it in deployment

**Comment by jacohen10** [comment]
that fixed it
