### ISSUE TITLE
document.getElementById("calendar-container") not working as expected

### ISSUE THREAD

**Issue by khenry10** [ga-wdi-exercises/project4#155]
Hello,

I'm building a calendar with the MEAN stack, but currently stuck on the plain js part.  I'm building the calendar with vanilla js and trying to render in the html which isn't working, but I can see it in the console.

I'm building the calendar with an html table and storing in a variable called "calendar", and then using 
`document.getElementById("calendar-container").appendChild(calendar);`.  However, I'm getting the following error: "app.js:33 Uncaught TypeError: Cannot read property 'appendChild' of null".  It works correctly if I execute document.getElementById("calendar-container") in the console, but it returns null when I console.log it.

Repo link: https://github.com/khenry10/docket/tree/calendar

Thanks!
Keith

**Comment by RobertAKARobin** [comment]
Do you have `$(document).ready` or similar anywhere? It sounds like it's trying to `appendChild` before `#calendar-container` exists.

**Comment by khenry10** [comment]
thanks Robin - closing this out!
