### ISSUE TITLE
Having trouble getting create, update, delete to show up in views.

### ISSUE THREAD

**Issue by christine-sm** [ga-wdi-exercises/project4#156]
Link to my repo: https://github.com/cmmovius/knopliments

I am having difficulty with the CUD of my app. I am trying to use a form directive, which shows up fine. When I add a new compliment, it redirects me to a show page stating "That compliment cannot be found" and then the compliment does not show up on the index page. _However_ I know the compliment is being added because the length of the array says "7 compliments" although only my original 5 are showing up (I tried to add a compliment twice). See the image below:

<img width="739" alt="screen shot 2016-04-23 at 1 05 26 pm" src="https://cloud.githubusercontent.com/assets/15206696/14762925/b01cf502-0954-11e6-9ef9-d6cd6c1db619.png">

Any suggestions on where to look to debug this code? Would it be in my `app.js` where my angular view logic lies?

**Comment by RobertAKARobin** [comment]
I'd put a `console.log` after `Compliment.all.push(compliment);` in your `scope.create` method to double-check what you're actually getting back from the server.

Also, this is going to be a headache:

`$state.go("show", {compliment: compliment.compliment});`

See if there's a way to be clearer about what's what without re-using the word `compliment` so much.

**Comment by christine-sm** [comment]
Ah yes I see that it's not actually taking in the values of the form:
<img width="738" alt="screen shot 2016-04-23 at 1 24 14 pm" src="https://cloud.githubusercontent.com/assets/15206696/14762998/c96870c0-0956-11e6-81eb-6f5d43c87e4a.png">

Could one of the reasons why it's not working be because an attribute has the same name as a model `compliment.compliment`? I've been basing my code off of the `delpoy-starter` branch of `whenpresident` and my code looks pretty much the same otherwise: https://github.com/ga-wdi-exercises/whenpresident/blob/deploy_starter/public/js/app.js.

**Comment by christine-sm** [comment]
I think I am trying to run before I can walk. I am going to try it without the custom directive to get the functionality working.

**Comment by RobertAKARobin** [comment]
👍 👍 👍 👍 👍
