### ISSUE TITLE
Unsure about creating routes

### ISSUE THREAD

**Issue by iamanissa** [ga-wdi-exercises/project4#157]
Trying to figure out how to get a users weapon.  I think I found what I need here: http://stackoverflow.com/questions/7013658/rails-3-resource-routing-for-join-models 
but can't figure out how to do that. 
repo: https://github.com/SuperJones/project2/tree/relationships

I'm getting an issue from work I previously did on project2 but the information I had shouldn't work but I'm having a hard time fixing it.

**Comment by RobertAKARobin** [comment]
Can you clarify what you mean by "get"? Like, you just want to be able to do `@user.weapon` or something?

**Comment by iamanissa** [comment]
Yes. Like the way I have my tables set up, weapon_id isn't in the users table, its in the inventory table. I can't figure out how to show the users weapon. I did figure out an error I had before which was this: http://stackoverflow.com/questions/31574538/pgundefinedcolumn-error-column-comments-post-id-does-not-exist  but now its a new error. undefined method `weapons' for #User:0x000000059b98d0 at line 44. So I can't do @user.weapons because it doesn't exist anymore or never did...

**Comment by RobertAKARobin** [comment]
It `has_one` weapon, so use proper English! Try `@user.weapon` instead of `@user.weapons`.

**Comment by iamanissa** [comment]
thank you i had to remove the each too. 
Gotten more done in this past hour than I got done all weekend. :-(
