### ISSUE TITLE
Rails + Angular Cannot find View

### ISSUE THREAD

**Issue by malissaromero** [ga-wdi-exercises/project4#16]
I am getting an error message that says it cannot find the template: 
![screen shot 2015-09-15 at 2 30 22 pm](https://cloud.githubusercontent.com/assets/11203264/9886211/144c1b1c-5bb7-11e5-9068-42b3bf250515.png)

I previously got this error: 
![screen shot 2015-09-15 at 2 31 31 pm](https://cloud.githubusercontent.com/assets/11203264/9886213/175f62c8-5bb7-11e5-91a6-b5f4597271a3.png)

I looked online and most people solved it by adding the full path so I put public/views/index.html back into my routes.js next to templateUrl. However I can not seem to figure out the template one because I don't understand how it knows to connect to the public path.

Here is my source code: https://github.com/malissaromero/match_me

**Comment by RobertAKARobin** [comment]
Rails is grumpy because it's looking for `something.html.erb` to put inside your `application.html.erb` where the `<%= yield %>` is. Try just getting rid of that `yield` bit.

**Comment by RobertAKARobin** [comment]
Can you please not edit your previous message? I'm all confused now!

**Comment by jshawl** [comment]
there are two errors here. The cannot find view error can be fixed by removing the word "public" from https://github.com/malissaromero/match_me/blob/df783198b1fd83e4a50e7493f3f6ec1a4b81a686/app/assets/javascripts/users/directives/user.js#L5

**Comment by malissaromero** [comment]
When I remove the public from my routes.js, I get both errors. I thought it was fixing the second error.

**Comment by malissaromero** [comment]
So I put yield back in. I accidentally gave outdated error screenshots.

**Comment by RobertAKARobin** [comment]
OK. Did that change the errors you're getting?

**Comment by malissaromero** [comment]
No. I am still getting both errors after I take the public out from my routes.rb.

**Comment by RobertAKARobin** [comment]
Which error comes first?

**Comment by malissaromero** [comment]
The loading template one is first.

**Comment by RobertAKARobin** [comment]
I'll come over in a second!

**Comment by malissaromero** [comment]
I am in Andy's lesson right now but I would really appreciate someone in person. Can I find you afterwards?

**Comment by RobertAKARobin** [comment]
I may be in a student interview, so if that's the case just Slack your squad instructor, or any other instructor. Remember you can use `@instructors` in Slack.
