### ISSUE TITLE
Issue with getting a users weapon through inventories. 

### ISSUE THREAD

**Issue by iamanissa** [ga-wdi-exercises/project4#160]
repo: https://github.com/SuperJones/project2/tree/relationships

Similar issue but different than last time. 
When A user clicks on the weapon they want it should go to the users profile page and show that weapon in the inventory, but it shows an empty inventory. I'm not getting an error anymore, but the information isn't showing up.
Maybe I need to create a weapons view/a partial because there is no such thing as @user.weapon_id ...

**Comment by RobertAKARobin** [comment]
@SuperJones It's working just fine for me. Have you DCMS recently?

**Comment by iamanissa** [comment]
yes, and it is not working for me.

**Comment by RobertAKARobin** [comment]
The DCMS isn't working or the weapons aren't working?
