### ISSUE TITLE
Quick Question About Using Separate Collections in MongoDB

### ISSUE THREAD

**Issue by christine-sm** [ga-wdi-exercises/project4#161]
My app involves theaters and their shows. I currently am using embedded documents, wherein shows are embedded within their theaters. However, I would like to shift to separate collections so users can query shows more easily. I am looking at the MongoDB doc's and they have the following example:

```
{
   _id: "oreilly",
   name: "O'Reilly Media",
   founded: 1980,
   location: "CA"
}

{
   _id: 123456789,
   title: "MongoDB: The Definitive Guide",
   author: [ "Kristina Chodorow", "Mike Dirolf" ],
   published_date: ISODate("2010-09-24"),
   pages: 216,
   language: "English",
   publisher_id: "oreilly"
}

{
   _id: 234567890,
   title: "50 Tips and Tricks for MongoDB Developer",
   author: "Kristina Chodorow",
   published_date: ISODate("2011-05-06"),
   pages: 68,
   language: "English",
   publisher_id: "oreilly"
}
```

Does the `_id: oreilly` replace the alphanumerical id that is usually assigned to that first object? Or does the first object have two `_id`s?

**Comment by RobertAKARobin** [comment]
Hm. That's a weird way of doing it. Yes, `publisher_id` should be numerical, e.g. "8675309".

http://stackoverflow.com/a/20931452/2053389

**Comment by christine-sm** [comment]
Thanks. So when using something like this:

```
var ScoreSchema = new mongoose.Schema({
    user : { type: Schema.Types.ObjectId, ref: 'User' },
    game : { type: Schema.Types.ObjectId, ref: 'Game' },
    score: Number
});
```

How do you make sure the scores are linked to the proper users and vice versa? In the `Score .json file` would you do something like `ref: User.findOne({name: "namegoeshere"})`? I am struggling to figure out how to connect the two collections properly.

**Comment by christine-sm** [comment]
That wasn't clear. What I meant to say is that I'm struggling with is if the _id changes each time you seed the database, how do you link the proper shows to their theaters in their `.json` files based on their id?

**Comment by RobertAKARobin** [comment]
Gotcha. You're talking about basically using Mongo as a relational database, which is do-able but complicated because it's not intended to be a relational database.

To seed relational data, I'd do something like:

``` js
var theatersJSON = [
  {
    name: "Theater1",
    shows: [
      {
        name: "Show1"
      },
      {
        name: "Show2"
      }
    ]
  },
  {
    name: "Theater2",
    shows: [
      {
        name: "Show2"
      },
      {
        name: "Show3"
      }
    ]
  }
]

var theaters = {};
var shows = {};
theatersJSON.forEach(function(theaterJSON){
  var theater = new Theater(theaterJSON);
  theaterJSON.shows.forEach(function(showJSON){
    var show = null;
    // If the show isn't already in that `shows` object, add it
    if(!shows[showJSON.name]){
      show = new Show(showJSON);
      shows[showJSON.name] = show;
    }else{
      show = shows[showJSON.name];
    }
    theater.shows.push(show);
  });
  // This happens asynchronously, but I think that's OK
  theater.save();
});

// Only save the shows to the database once all the theaters have been looped through
for(showName in shows){
  // This happens asynchronously, but I think that's OK
  shows[showName].save();
}
```

**Comment by christine-sm** [comment]
Ahh okay. So I probably shouldn't do that. I think I am going to stick with embedded documents then. I figured out how to query shows on the theaters index page so that is a step in a right direction!

**Comment by RobertAKARobin** [comment]
👍 👍 👍 👍 👍 👍 👍  for embedded documents, at least for now
