### ISSUE TITLE
Lyndsey json file data not showing

### ISSUE THREAD

**Issue by LNewsome** [ga-wdi-exercises/project4#163]
I'm having a problem where the data on their json file doesn’t show up on the page? Everything looks connected but nothing is showing.

**Comment by RobertAKARobin** [comment]
Can you push your code up to Github and link to it here?

**Comment by LNewsome** [comment]
Sorry for the late response. Yun helped me figure it out. My Db was not connected.

**Comment by RobertAKARobin** [comment]
I'm glad you got it!
