### ISSUE TITLE
API

### ISSUE THREAD

**Issue by iamanissa** [ga-wdi-exercises/project4#164]
Sooooo....
I would wait til tomorrows one-on-one with Adrian but not sure were to go if not to figure out this API thing. 
I am reading Andrews blog on api calls in rails: http://andrewsunglaekim.github.io/Server-side-api-calls-wrapped-in-ruby-classes/
But I know that fitbit (if I understand right) will only let me get a users information not all info for every user. And I need a OAuth 2.0 library. I'm guessing this is like how we did with Twitter OAuth but in Rails. 

I signed up my app for Fitbit API and  I have this info:
 OAuth 2.0 Client ID, Client Secret, OAuth 2.0: Authorization URI, and OAuth 2.0: Access/Refresh Token Request URI from Fitbit. 

I also found a OAUTH gem I think: https://github.com/oauth-xx/oauth-ruby  

I really just need help with setting things up because I have lots of pieces but not like a whole understanding of doing this.

**Comment by RobertAKARobin** [comment]
Honestly, I think you're going too big for this project -- or at least too big for your bronze level. What you have going on with the weapons stuff is really cool! I'd recommend making that your bronze level for this project: users can log in and "battle" with other users. Sure, their HP and stuff isn't really connected to anything, but it's fun and gives you a lot to work on from a UX perspective. I'd try to get that tamped down, and then once the battling works fine, then worry about where the HP is coming from.

**Comment by iamanissa** [comment]
sigh, okay.
Ill add Devise...

**Comment by RobertAKARobin** [comment]
APIs can be really tricky. Sometimes they're not, but often they are -- each one stores data in different ways and while OAuth is similar everywhere there are enough minor differences to make things complicated. You can certainly do it — I'd say just take care of the other stuff first!
