### ISSUE TITLE
GET path="/" Error When Trying to Deploy App

### ISSUE THREAD

**Issue by christine-sm** [ga-wdi-exercises/project4#168]
My Repo: https://github.com/cmmovius/playbill-dc

<img width="567" alt="screen shot 2016-04-26 at 9 08 40 am" src="https://cloud.githubusercontent.com/assets/15206696/14819210/fda871a2-0b8e-11e6-86f3-325a220b25b3.png">

I have added a Procfile and configured my ports properly, but now I am getting this error upon trying to load my deployed application... Thoughts?

**Comment by jshawl** [comment]
are there any more logs?

**Comment by jshawl** [comment]
i.e. can you paste more output

**Comment by christine-sm** [comment]
Sure will do now

**Comment by christine-sm** [comment]
Hm when I refresh my page those are the only two errors that are "new". But I will send you the full log of errors that goes back to before I had a Procfile:
<img width="840" alt="screen shot 2016-04-26 at 9 18 25 am" src="https://cloud.githubusercontent.com/assets/15206696/14819384/ea6ba554-0b8f-11e6-91c7-18a2d2f63936.png">

```
2016-04-26T13:18:56.472223+00:00 app[web.1]: /app/node_modules/mongodb/lib/server.js:242
2016-04-26T13:18:56.472224+00:00 app[web.1]:         process.nextTick(function() { throw err; })
```

Could this be the issue?

**Comment by jshawl** [comment]
I think it's this ![](https://dl.dropbox.com/s/81ol5msuoqghy4g/Screenshot%202016-04-26%2009.21.47.png?dl=0)

**Comment by jshawl** [comment]
what's your `mongo.connect` look like?

**Comment by christine-sm** [comment]
```
if(process.env.NODE_ENV == "production"){
  mongoose.connect(process.env.MONGODB_URL);
}else{
  mongoose.connect("mongodb://localhost/playbill-dc");
}
```

Ah, I just took a look at that same section in WhenPresident's master branch and they have `MONGOLAB` instead of `MONGODB`:

```
mongoose.model("Candidate", CandidateSchema);
if(process.env.NODE_ENV == "production"){
  mongoose.connect(process.env.MONGOLAB_URL);
}else{
  mongoose.connect("mongodb://localhost/whenpresident");
}
```

But I haven't added MongoLab yet to my app. When I connect MongoLab would it fix this?

**Comment by jshawl** [comment]
what is the output of `$ herouk config` do you see MONGODB_URL in there?

**Comment by christine-sm** [comment]
Nope I only get this 

```
$ heroku config
=== playbill-dc Config Vars
```

**Comment by joe-gz** [comment]
Did you set up mongolab?

**Comment by christine-sm** [comment]
No I haven't set it up yet, so I feel like once I do that would fix that problem. Since it was a `GET` issue I didn't think it was related to MongoLab!

**Comment by joe-gz** [comment]
Yea, that last error message happens any time the app crashes. the ENOTFOUND error that jesse mentioned above is the culprit

**Comment by christine-sm** [comment]
So I removed the mongolab connection (knowing that my data wouldn't show up just to see if the app itself would show up) and it still doesn't work. I get the following:
<img width="842" alt="screen shot 2016-04-26 at 9 32 21 am" src="https://cloud.githubusercontent.com/assets/15206696/14819853/0659a9f8-0b92-11e6-9481-093ed4f58bd3.png">

**Comment by jshawl** [comment]
conneciton refused to localhost -- you have to use a mongolab url

**Comment by christine-sm** [comment]
Ok I will fully add MongoLab and see if that works. In our deployment class (@joe-gz) , we were able to reach an intermediate state where our app displayed on the page but didn't have any data yet, so I was hoping to see that before doing all of the MongoLab setup. Do you think there is some additional error I should look out for that is preventing this intermediate state for myself?

**Comment by RobertAKARobin** [comment]
If you require your `connection.js` file in any way, it's going to try to connect to Mongo, and so will throw an error. Maybe you could comment out that requirement or something?

**Comment by christine-sm** [comment]
@RobertAKARobin Good point. When I comment out that requirement it leads to a rabbit hole of other errors, so I will try to add MongoLab and see if that works!

**Comment by RobertAKARobin** [comment]
Other errors === better!

**Comment by christine-sm** [comment]
I added MongoLab and I'm still getting the same error:
<img width="842" alt="screen shot 2016-04-26 at 10 01 08 am" src="https://cloud.githubusercontent.com/assets/15206696/14820741/e3a1f4ac-0b95-11e6-831d-36d3428e5014.png">
I am getting the same `Error: getaddrinfo ENOTFOUND undefined undefined:27017` as before.

My `mongoose.connect` looks like this:

```
if(process.env.NODE_ENV == "production"){
  mongoose.connect(process.env.MONGOLAB_URL);
}else{
  mongoose.connect("mongodb://localhost/playbill-dc");
}
```

**Comment by joe-gz** [comment]
what's the output of `$ heroku config` ?

**Comment by RobertAKARobin** [comment]
^^ Gotta make sure you did the whole `heroku config:set MONGOLAB_URL=whatever` thing

**Comment by christine-sm** [comment]
```
$ heroku config
=== playbill-dc Config Vars
MONGODB_URI: mongodb://heroku_68ftcx6k:ckm1no5kr0k9rdr69ovpib8lv0@ds021711.mlab.com:21711/heroku_68ftcx6k

```

@RobertAKARobin ? So do I use `MONGODB_URI` or `MONGOLAB_URL=whatever`?

**Comment by RobertAKARobin** [comment]
You can use either. You can use `WOMBAT_HOOLIGAN` if you want -- the name doesn't matter. It just has to match what's in your code. You set `MONGODB_URI`, but your code references `process.env.MONGOLAB_URL`.

**Comment by joe-gz** [comment]
change mongoose.connect(process.env.MONGOLAB_URL); to mongoose.connect(process.env.MONGODB_URL);

**Comment by christine-sm** [comment]
So I did that but I'm still getting the same error as before:
<img width="842" alt="screen shot 2016-04-26 at 10 01 08 am" src="https://cloud.githubusercontent.com/assets/15206696/14820741/e3a1f4ac-0b95-11e6-831d-36d3428e5014.png">
I am getting the same `Error: getaddrinfo ENOTFOUND undefined undefined:27017` as before.
Is this error related to something else besides connecting to MongoLab? I have been getting this error the whole time.

**Comment by christine-sm** [comment]
Fixed IRL with Robin! For anyone else who reads this and is encountering the same issue:
- Rather than using the MongoLab add-on. Create a new db on MongoLaB yourself and add a user and password.
- On you db page, you will see something like the following:

```
To connect using a driver via the standard MongoDB URI (what's this?):
  mongodb://<dbuser>:<dbpassword>@ds021731.mlab.com:21731/playbill-dc
```

`playbill-dc` will replaced by whatever the name of your db is.
- In your command line, type the following: `heroku config:set MONGODB_URL=mongodb://<dbuser>:<dbpassword>@ds021731.mlab.com:21731/playbill-dc` putting in your `dbuser` and `dbpassword` that you created. Do NOT use the opening/closing tags around your username and pw. 
- Your connection.js will have something like this:

```
if(process.env.NODE_ENV == "production"){
  mongoose.connect(process.env.MONGODB_URL);
}else{
  mongoose.connect("mongodb://localhost/playbill-dc");
}
```
- Finally, in you command line enter `heroku run node db/seed.js` to seed your data.
- Refresh you heroku app and everything should show up!
