### ISSUE TITLE
Drop down not saving to database

### ISSUE THREAD

**Issue by iamanissa** [ga-wdi-exercises/project4#169]
So by the grace of God and many SO searches I finally was able to add a drop down box for weapons in the sign up view.
But now it will not save that weapon to my inventory/user. So the rest of my code in my view will not work because weapon is nil. 
```Showing /home/infinity/wdi/projects/project2/app/views/users/show.html.erb where line #36 raised:

undefined method `weapon_type' for nil:NilClass```

How do I go about saving the weapon to the inventory along side the user?

**Comment by amaseda** [comment]
Can you link to your repo plz and list the relevant files for this issue plz? Thx

**Comment by iamanissa** [comment]
oh yea
repo: https://github.com/SuperJones/project2/tree/dual

**Comment by iamanissa** [comment]
my drop down is under users/registration/new.html.erb (because of devise views)

**Comment by amaseda** [comment]
Gotcha. Taking a look now!

**Comment by iamanissa** [comment]
Somehow my form does not know to save the weapon to inventory with the new user id: I think it might be that it needs to be required in application_controller.rb (I think this is kind of like user_params) which I tried to do, but maybe I am permitting the wrong thing...?

**Comment by amaseda** [comment]
Solved IRL! Closing for now, but let me know if you have any other questions.
