### ISSUE TITLE
Angular_app

### ISSUE THREAD

**Issue by Thesheik** [ga-wdi-exercises/project4#17]
Hey guys, I am trying to set up an angular app from scratch by following angular lessons plan. Did all the installments but I am having trouble installing nodemon. This is the error I am getting when trying to run the server: 

```
Error: Cannot find module '/Users/Cheikhndiongue/wdi/projects/faverest/js'
    at Function.Module._resolveFilename (module.js:336:15)
    at Function.Module._load (module.js:278:25)
    at Function.Module.runMain (module.js:501:10)
    at startup (node.js:129:16)
    at node.js:814:3
15 Sep 14:57:54 - [nodemon] app crashed - waiting for file changes before starting...
```

**Comment by RobertAKARobin** [comment]
What's the command you're entering to start Nodemon?

**Comment by RobertAKARobin** [comment]
Because it looks like you're trying to run a file called `js`, rather than `something.js`

**Comment by Thesheik** [comment]
I do have a folder called js. I ran the command nodemon but server crashes everytime

**Comment by RobertAKARobin** [comment]
You're making Nodemon look for a **folder** called `js`. Nodemon only works with a **file**.

**Comment by Thesheik** [comment]
I was just trying to follow the lesson plan on angular. 
I started
touch index.html
mkdir js
mkdir js/controllers
touch js/app.js
and ran npm install -g bower 
npm install --save jquery
npm install --save angular

**Comment by RobertAKARobin** [comment]
That all looks fine. You need to do `nodemon js/app.js`

**Comment by Thesheik** [comment]
I did that as well but still crashes

**Comment by RobertAKARobin** [comment]
Is it the same error?

**Comment by Thesheik** [comment]
```
ReferenceError: angular is not defined
    at /Users/Cheikhndiongue/wdi/projects/faverest/js/app.js:2:3
    at Object.<anonymous> (/Users/Cheikhndiongue/wdi/projects/faverest/js/app.js:3:3)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Function.Module.runMain (module.js:501:10)
    at startup (node.js:129:16)
    at node.js:814:3
15 Sep 15:07:03 - [nodemon] app crashed - waiting for file changes before starting...
```

**Comment by RobertAKARobin** [comment]
That's a different error. Nodemon is working now. Look at the first line: it says you have an error on line 2 of `app.js`

**Comment by Thesheik** [comment]
I see but this is what my app.js looks like

```
(function() {
  angular.module('todo', []);
})();
```

**Comment by RobertAKARobin** [comment]
Nodemon can only run back-end Javascript. Angular is front-end Javascript.

I would recommend not doing anything with Angular yet. Instead, just get your back-end up and running. To do that, follow an example for setting up Express/Node applications.

**Comment by Thesheik** [comment]
All right. Well thank you I actually want to go into the Angular.js/FireBase route for my app

**Comment by Thesheik** [comment]
I will take a minute and think about it thought. I was having some issues with my rails backend up until this morning so I decided maybe it wouldn't be a bad idea going with Firebase

**Comment by RobertAKARobin** [comment]
There are definitely fewer moving parts with Firebase!
