### ISSUE TITLE
Express validator issue 

### ISSUE THREAD

**Issue by maureenv** [ga-wdi-exercises/project4#171]
Github repo: https://github.com/maureenv/cheatss/tree/validation 

Hi, I'm trying to add form validation using express validator but I'm having some issues. Here is the code that I've added into my index.js file for form validation: 

``` js
// Create post
app.post("/tutorials-show", function(req, res){
  //res.json(req.body); //The server will respond with JSON that contains the user input, which is stored in req.body. res.json(req.body) is the initial test to see if json data is rendered.

  //////// code for form validator
  req.checkBody("tutorial[title]", "A title must be entered").notEmpty();
  req.checkBody("tutorial[comment]", "A description must be entered").notEmpty();

  var errors = req.validationErrors();
  if (errors) {
   res.render('tutorials-show', {errors: errors});
   return;
   /////// end code for form validator
   } else {
    req.body.tutorial.title = req.body.tutorial.title.trim();
    Tutorial.create(req.body.tutorial).then(function(tutorial){
      res.redirect("/" + tutorial.title);

    });
  }
});
```

And in my seeds.json file I included the following information because the tutorial I looked at said that the "msg" portion of the JSON file renders an error message if the field isn't filled in. 

```
[
  {"param": "title", "msg": "A title must be entered", "value": ""},
  {"param": "comment", "msg": "A description must be entered", "value": ""}
]
```

And finally, in my form.hbs file I added the following  {{#if errors}} message in case there are errors. However, this portion of my code always gives me an error message which I've attached this issue.
Thanks a lot for all of your help! 
![screen shot 2016-04-26 at 10 32 47 am](https://cloud.githubusercontent.com/assets/16403532/14822282/09a198be-0b9c-11e6-93c0-bece5268fb75.png)

``` html
  <form action = "/tutorials-show" method = "post">
        <p class="label"> Tutorial Title </p>
        {{ #if errors }}
          <ul>
            {{ #each errors }}
              <li>{{ this.msg }}</li>
            {{ /each }}
          </ul>
        {{ /if }}
        <input type="text" name="tutorial[title]" placeholder = "Insert title">
```

**Comment by RobertAKARobin** [comment]
It's because you have a space between the `{{` and `#`. It's `{{#if errors}}`.

**Comment by maureenv** [comment]
Thanks Robin! That resolved my problem :)
