### ISSUE TITLE
Embedding Youtube Video

### ISSUE THREAD

**Issue by hh747hh** [ga-wdi-exercises/project4#172]
Still struggling with it...

I followed this step from the repository I found in github.

```
Embed a YouTube player with a simple directive.
$ npm install --save angular-youtube-embed

<!-- Include YT library and this directive -->
<script src="https://www.youtube.com/iframe_api"></script>
<script src="angular-youtube-embed.js"></script>
// Create your app with 'youtube-embed' dependency
var myApp = angular.module('myApp', ['youtube-embed']);
// Inside your controller...
myApp.controller('MyCtrl', function ($scope) {
  // have a video id
  $scope.theBestVideo = 'sMKoNBRZM1M';
});
<!-- Use 'youtube-video' as an element or attribute. -->
<youtube-video video-id="theBestVideo"></youtube-video>
```

Now It is throwing this error

Error: $injector:nomod
Module Unavailable
Module 'youtube-embed' is not available! You either misspelled the module name or forgot to load it. If registering a module ensure that you specify the dependencies as the second argument.

**Comment by RobertAKARobin** [comment]
Can you push your code to Github and link to it here?

**Comment by hh747hh** [comment]
https://github.com/hh747hh/Inspired

Thank you Robin!

**Comment by RobertAKARobin** [comment]
You have `<script src="angular-youtube-embed.js"></script>`, but that file doesn't exist...?

**Comment by hh747hh** [comment]
It is under node_modules folder. It got ".gitignore"ed...

**Comment by hh747hh** [comment]
![screen shot 2016-04-26 at 12 10 45 pm](https://cloud.githubusercontent.com/assets/16959988/14825425/f83b636e-0ba7-11e6-9ae1-89bfc73da060.png)

**Comment by RobertAKARobin** [comment]
You can't use `<script>` on a Node module...

**Comment by RobertAKARobin** [comment]
Can you provide the link for the tutorial you used for this?

**Comment by RobertAKARobin** [comment]
Node modules are like Ruby gems: they're for the back-end.

**Comment by hh747hh** [comment]
https://github.com/brandly/angular-youtube-embed

**Comment by RobertAKARobin** [comment]
Ohhhh. Take this file and put it in your `public/js` folder:

https://github.com/brandly/angular-youtube-embed/blob/master/src/angular-youtube-embed.js

**Comment by hh747hh** [comment]
Great. It is not throwing the the error but still not showing the video on index page...

teachers-index.html page

<youtube-video video-id="theBestVideo"></youtube-video>

**Comment by RobertAKARobin** [comment]
You're following the instructions too literally:

https://github.com/hh747hh/Inspired/blob/master/public/js/app.js#L17

This should go inside the controller of whatever view you're looking at. If it's the teachers index view, it should go in the teacher's index controller. That `MyCtrl` thing is just an example they put in the documentation.

Also, don't use `$scope`. Instead of doing `$scope.whateverTheVideoIs`, do `vm.whateverTheVideoIs`.
