### ISSUE TITLE
CRUD confusion

### ISSUE THREAD

**Issue by LNewsome** [ga-wdi-exercises/project4#173]
I've trying to create CRUD for my page. My goal is to have the data submitted on my form to redirect to another page. I tried to create a code to perform this task but nothing. I know I'm doing something wrong and I seriously need help.
Here is my code: https://github.com/LNewsome/quiet-loud

**Comment by RobertAKARobin** [comment]
Are you getting an error?

**Comment by RobertAKARobin** [comment]
I'm seeing 2 problems in your code:
1) You need to do `npm install --save express` to make sure Express is in your `package.json`
2) This line:

``` js
var Forum = mongoose.model("Forum-show");
```

...references a model you haven't defined yet. For this to work, you'd need to have done `mongoose.model("Forum-show"` like you did with "Personalities" in your `connection.js`. Just delete or comment out this line for now, until you need it.

**Comment by LNewsome** [comment]
I've installed npm save express and commented out the var Forum, and I'm still having the same problem.

**Comment by RobertAKARobin** [comment]
This is showing up for me:

![screen shot 2016-04-26 at 12 05 29 pm](https://cloud.githubusercontent.com/assets/6268177/14825278/326fb2f2-0ba7-11e6-9bdb-e21a2216c22d.jpg)

What should I be seeing that I'm not?

**Comment by LNewsome** [comment]
That's most of what's suppose to show up. I had a form that I created if you click on introvert or extrovert. I wanted to put whatever was typed in the form to show in another show page but nothing happens. It reloads but doesn't redirect to another page.

**Comment by RobertAKARobin** [comment]
Ahh, so we're looking at this page:

https://github.com/LNewsome/quiet-loud/blob/master/views/personalities-show.hbs

**Comment by RobertAKARobin** [comment]
In that case, the problem is just that your "Ask!" button needs to be inside the `<form>` element. It's outside it at the moment.

**Comment by LNewsome** [comment]
I forgot to push up the changes I've made. It's not the button. It's a file I created called forum-show.hbs where I want to display all the questions. Nothing is showing, not even the page.

**Comment by LNewsome** [comment]
I'm probably not connecting the files the correct way.

**Comment by RobertAKARobin** [comment]
You have several syntax errors/typos. Check your Terminal output.
