### ISSUE TITLE
mongo won't open in express nor will it create the db

### ISSUE THREAD

**Issue by Crunchwrap78** [ga-wdi-exercises/project4#174]
no messages output to the console to check whether or not the db is running
I have mongod running and when I check mongo and do show dbs, it shows my db hasn't been created 

here's a link to repo
https://github.com/Crunchwrap78/TeslaTravels

**Comment by RobertAKARobin** [comment]
Does running your seed file do anything?

**Comment by Crunchwrap78** [comment]
nope

**Comment by jshawl** [comment]
where are you requiring mongo / mongo.connect? https://github.com/Crunchwrap78/TeslaTravels/blob/master/index.js

**Comment by Crunchwrap78** [comment]
connection.js file

**Comment by Crunchwrap78** [comment]
if it helps it says in mongod  Failed to obtain name info for: [ (172.20.9.23, "nodename nor servname provided not known")

**Comment by RobertAKARobin** [comment]
You need to `require` your `connection.js` file too! Your `index.js` doesn't automatically know about `connection.js` unless it's `require`d somewhere.

**Comment by Crunchwrap78** [comment]
put it in the index.js and it's still not working

**Comment by jshawl** [comment]
Any errors in the console?

**Comment by RobertAKARobin** [comment]
Fixed in person. Just a few syntactical things.
