### ISSUE TITLE
Broke my posting ability when Angularizing

### ISSUE THREAD

**Issue by jeffreyeaton76** [ga-wdi-exercises/project4#175]
Yesterday I was able to post to my DB but it was all happening on the Express side (I had a MEN app with a few angular bits hanging around). Now I'm trying to make it a real MEAN app. I moved the create/post function over to the Angular side but I can't actually post and there are no errors; my submit button is just inert. 

Here is the form on the new.html file (aka http://localhost:3000/#/new):

```
<div data-ng-controller="newController as newVM">
<form data-ng-submit="create()">
  <input type="text" data-ng-model="newVm.new_sit.durationset" placeholder="Minutes"/>
  <button type="submit">Start Session</button>
</form>
</div>
```

The Angular create function:

```
  function sitFactoryFunc($resource){
    var Sit = $resource("/api/sits/:id");
    return Sit;
  }
  function newControllerFunc(sitFactory, $resource, $state){
    var newVM = this;
    newVM.new_sit = new sitFactory();
    newVM.create = function(){
      newVM.new_sit.$save().then(function(){
        $state.go("index");
      });
    };
  }
```

and the kind of do-nothing Express bit. This is a known unknown - I used to have a working `Sit.create(req.body.sit)` in here but now that that's over in Angular I'm not sure what ought to go on over here. 

```
app.post("/new", function(req, res){
    res.end();
});
```

**Comment by RobertAKARobin** [comment]
First things first. Put a `console.log` inside that `newVM.create`. Are you sure it's firing when you click the button?

**Comment by jeffreyeaton76** [comment]
not firing

**Comment by RobertAKARobin** [comment]
So let's not use `ng-submit`. How else can you tell it to do something when you click on the button?

**Comment by RobertAKARobin** [comment]
Also, don't use `type="submit"` in Angular. That actually submits the form when you click the "submit" button. You don't _want_ to submit the form -- you want to fire an AJAX request with Angular.

**Comment by jeffreyeaton76** [comment]
`<button data-ng-click="create()">Start Session</button>`? That doesn't fire the function either.

**Comment by RobertAKARobin** [comment]
Functions have to be attached to `vm` just like everything else.

**Comment by jeffreyeaton76** [comment]
I've been nailed by that one a few times. But I'm not out of the woods. I now have a `POST http://localhost:3000/api/sits 404 (Not Found)`. That url does render my json. I've been worried I would run into an error regarding the `/:id` in my factory function above; is that what's happening?

**Comment by RobertAKARobin** [comment]
Do you have `app.post("/api/:id"` somewhere?

**Comment by jeffreyeaton76** [comment]
ah, I added 

```
app.post("/api/:id", function(req, res){
    res.end();
});
```

and it can't read property `go` of undefined. Definitely progress. Didn't post to DB while it was pondering my undefined state.

**Comment by RobertAKARobin** [comment]
What does `res.end()` do? Haven't seen that before.

**Comment by jeffreyeaton76** [comment]
Res.end "[Finishes sending the request](https://nodejs.org/api/http.html#http_request_end_data_encoding_callback)." That's part of my large-scale confusion. I don't want it to render json and if I redirect then it (last night anyway) would only redirect to non-Angular pages. So `/session` and not `/#/session`. I thought a simple "just stop" would give it something to do.

**Comment by RobertAKARobin** [comment]
I don't think you'll ever really need to use that. With respect to redirecting to non-Angular pages, take a look at this commit:

https://github.com/ga-wdi-exercises/whenpresident/commit/fee8317c3bdb10dfcb1110d73a1361854ce0e0e1

**Comment by jeffreyeaton76** [comment]
so I still have two problems. One, clicking the button console logs 'hello' but then it can't read property `go` of undefined. The other issue is I suspect it won't write to the DB once the state is sorted out. 

This is the function:

```
  function newControllerFunc(sitFactory, $resource, $state){
    var newVM = this;
    newVM.new_sit = new sitFactory();
    newVM.create = function(){
      console.log("hello");
      newVM.new_sit.$save().then(function(){
        $state.go("index");
      });
    };
  }
```

and this is the target state for now

```
function routerFunction($stateProvider, $locationProvider){
    $locationProvider.html5Mode(true);
    $stateProvider
    .state("index", {
      url:"/",
      templateUrl:"/assets/html/index.html",
      controller:"indexController",
      controllerAs:"indexVM"
    })
```

**Comment by RobertAKARobin** [comment]
Did you inject `$state`?

**Comment by jeffreyeaton76** [comment]
also relevant:
`.controller("newController", ["sitFactory", "$state", newControllerFunc])`

**Comment by RobertAKARobin** [comment]
The order matters. They have to be in the same order in the array and in the `function`.

**Comment by jeffreyeaton76** [comment]
whooooaaa

**Comment by jeffreyeaton76** [comment]
ok, as I thought, the redirect is now cool but nothing is going into the db

**Comment by RobertAKARobin** [comment]
...for the same reason this doesn't print out "Hello there, Steve!"

``` js
function sayHello(name, greeting){
  console.log(greeting + " there , " + name + "!");
}
sayHello("Hello", "Steve");
// "Steve there, Hello!"
```

**Comment by RobertAKARobin** [comment]
So put in more console logs. Get out of "flight" mode and go one baby step at a time.

``` js
newVM.new_sit.$save().then(function(response){
  console.log(response);
});
```

**Comment by jeffreyeaton76** [comment]
it does console log an object with deep subsections. I opened a bunch and can't find my data in it. starts with `{$resolved: true}`

**Comment by RobertAKARobin** [comment]
Keep working backwards. It looks like Angular's working fine. So the problem must be in Express. Try putting a console log in the appropriate Express route to check that `req.body` -- that is, the data Angular is sending -- is what you expect.

**Comment by jeffreyeaton76** [comment]
The error is prior to Express getting anything from req.body. Clicking the button results in a `POST http://localhost:3000/api 404 (Not Found)` error. I find that weird because a GET version (i.e., going to that URL) shows my data. I would think the code below would give it what it's looking for. 

```
app.get("/api", function(req, res){
  Sit.find().then(function(sits){
    res.json(sits);
  });
});

app.post("/api/:id", function(req, res){
  console.log(req.body);
  res.json({success: true});
});
```

**Comment by RobertAKARobin** [comment]
You don't have a route set up for POSTs to `:3000/api`. You have one set up for POSTs to `:3000/api/:id`, and one for GETs to `:3000/api`.

**Comment by jeffreyeaton76** [comment]
After correcting the route `req.body` was/is an empty object. That has led me to believe the issue is with my form but I can't spot the error. I have 
`var parser = require("body-parser");`
`app.use(parser.urlencoded({extended: true}));`
and my form looks like this:

```
<div data-ng-controller="newController as newVM">
<form>
  <input type="text" data-ng-model="newVm.new_sit.durationset" placeholder="Minutes"/>
  <button type="button" data-ng-click="newVM.create()">Start Session</button>
</form>
</div>
```

**Comment by RobertAKARobin** [comment]
Your form isn't actually doing anything because you're submitting your data with Angular. Angular uses AJAX. Forms and AJAX are basically mutually exclusive. So forms and Angular are basically mutually exclusive (at least the way we've done things). You can still have `<form>` tags, they just don't do anything different than `<div>` tags.

**Comment by RobertAKARobin** [comment]
Can you push your code to Github and link to it here?

**Comment by jeffreyeaton76** [comment]
`angular-form` is the branch
https://github.com/jeffreyeaton76/timer/tree/angluar-form

**Comment by RobertAKARobin** [comment]
You're really going to like this.

`newVM` has a lowercase `m` in this line:

https://github.com/jeffreyeaton76/timer/blob/angluar-form/public/html/new.html#L3

**Comment by jeffreyeaton76** [comment]
that's true but fixing it doesn't solve the problem

**Comment by jeffreyeaton76** [comment]
req.res is still an empty object

**Comment by RobertAKARobin** [comment]
`app.use(parser.urlencoded({extended: true}));` is only for when you're using forms. Angular uses AJAX, which submit JSON, so this should be `app.use(parser.json({extended: true}));`

**Comment by jeffreyeaton76** [comment]
wow. that is really something. req.res is no longer an empty object. in the meantime I've decided to carve seashells in Antigua for the rest of my life. but before I go, you didn't happen to spot why it doesn't actually put req.res into the database did you?

**Comment by jeffreyeaton76** [comment]
Since nothing is going in the db I'm confused as to where that ought to go down. `create` is called in Angular but not in Express . . . so I added a `create` method in `app.post` to see what I'd learn and it now console logs `req.res` correctly but puts empty objects in the db (better than not putting anything?).  So Express looks like this:

```
app.post("/api", function(req, res){
  console.log(req.body);
  Sit.create(req.body.sit).then(function(){
    res.json({success: true});
  });
});
```

and Angular looks like this:

```
  function newControllerFunc(sitFactory, $state){
    var newVM = this;
    newVM.new_sit = new sitFactory();
    newVM.create = function(){
      newVM.new_sit.$save().then(function(response){
        $state.go("index");
      });
    };
  }
```

**Comment by RobertAKARobin** [comment]
`Sit.create` should look something like this:

``` js
Site.create({name: "foo", age: "bar"})
```

If you're getting empty entries in the database, that means the object you're passing in doesn't match.

**Comment by RobertAKARobin** [comment]
So maybe it should be `Sit.create(req.body)`, or `Sit.create({name: req.body.name})` or `Sit.create({name: req.body.sit.name})` or something.

**Comment by jeffreyeaton76** [comment]
Oh yes. It works. 
Jesus that was a rough one.
Many thanks.
