### ISSUE TITLE
Passing data from backend to frontend

### ISSUE THREAD

**Issue by MattLeeStevens** [ga-wdi-exercises/project4#176]
I create an array of objects, `var scores` in `/db/scores.js` that I want to pass to the front end and display in a handlebars view.

When I run `node /db/scores.js` in the terminal, the `console.log(scores)` shows that the array has been created correctly.  

At the end of `/db/scores.js` I have

```
    module.exports = {
      games: scores
    };
```

and then in `/routes.js`:

`var db = require("./db/scores");`

```
app.get('/*', function(req, res) {
    res.render('index', {
      games : db.games
    });
  });
```

and then in `index.hbs` I have `{{games}}`

I think the problem is with `/db/scores.js` not exporting the array correctly.

Here is my repo: https://github.com/MattLeeStevens/nbaProject

**Comment by RobertAKARobin** [comment]
Can you clarify what it's not doing that it should be?

**Comment by MattLeeStevens** [comment]
I can't access the data in the view.

**Comment by RobertAKARobin** [comment]
Do you get an error?

**Comment by MattLeeStevens** [comment]
No. I don't think the function in `/db/scores.js` is properly returning the array of objects that it creates.

**Comment by RobertAKARobin** [comment]
You getting all these errors too?

![screen shot 2016-04-26 at 2 39 48 pm](https://cloud.githubusercontent.com/assets/6268177/14830067/bfe4a6b4-0bbc-11e6-916d-9986fbfef02d.jpg)

**Comment by MattLeeStevens** [comment]
No, but it looks like it has something to do with bower.

**Comment by RobertAKARobin** [comment]
Oh, yeah, there's no `bower.json` in here. You need `$ bower init` to create it, like `$ npm init` and `package.json`.

**Comment by RobertAKARobin** [comment]
Can you add that, please?

**Comment by MattLeeStevens** [comment]
I'm pretty sure I already have one there.

**Comment by RobertAKARobin** [comment]
Doh!

**Comment by RobertAKARobin** [comment]
Which data can't you access? I'm getting this:

![screen shot 2016-04-26 at 2 44 58 pm](https://cloud.githubusercontent.com/assets/6268177/14830228/98133d98-0bbd-11e6-826d-dfd6a027c894.jpg)

**Comment by MattLeeStevens** [comment]
In `/views/index.hbs` I'm trying to access the array returned by the function in `db/scores.js`

**Comment by MattLeeStevens** [comment]
Nothing to do with the angular app.  Just express and handlebars.

**Comment by RobertAKARobin** [comment]
Gotcha. You can't asynchronously do a `module.exports` in the same way that you can't put a `return` inside a callback. The best you can do is `module.exports` a callback that fires when the data query has ended.

This goes into more detail:

http://stackoverflow.com/a/20239667/2053389

Not a great answer, but there are plenty of others. I Googled "async module exports".

**Comment by MattLeeStevens** [comment]
OK, I'll check it out.  Thanks for taking a look.
