### ISSUE TITLE
Cannot connect with my db/api in MEAN

### ISSUE THREAD

**Issue by kairajohnson** [ga-wdi-exercises/project4#177]
I have followed the instructions within the lesson plan but am not sure that I set it up in a way that works with my app. The html is showing from angular but not the actual params from my db. 

here is my repo
https://github.com/kairajohnson/gentrification.git

**Comment by RobertAKARobin** [comment]
The problem is this line:

```
function contributorController(contributor){
```

It should be `(Contributor)` with a capital C.

**Comment by kairajohnson** [comment]
thanks. I changed that but it doesn't reflect the data in my seeds which showed fine before incorporating angular so i'm assuming the way i wrote the functions in my index.js is wrong

**Comment by RobertAKARobin** [comment]
Something's missing here:

``` js
app.get("/api/contributors", function(req, res){
  Contributor.find({}).then(function(contributors){
    res.json
  });
});
```

**Comment by kairajohnson** [comment]
I didn't get to your last suggestion until now. I have updated my repository and am having the same issue. for my length, it has 0. I tried reseeding my data, console logging, and going back on our material but don't really understand what I'm doing at this point to pinpoint the issue. 

https://github.com/kairajohnson/gentrification.git
