### ISSUE TITLE
Defining an href to hit a route on the backend for user authorization thru facebook

### ISSUE THREAD

**Issue by Ceisen9** [ga-wdi-exercises/project4#178]
I am trying to link a facebook authorization route on my welcome page. I have not created a route on the angular front end for the authorization through facebook because I want the user to be redirected. So right now when I click on the link to go to localhost:3001/auth/facebook from my welcome page (localhost3001/) the url quickly changes and then changes back with nothing happening.  Also, when I console log something in the route defined on my server, it does not appear, indicating that it never reaches this route. I tried changing the hyperlink to http://localhost3001/auth/facebook and that gives me an error that the site cant be reached.  Here’s the code for my route defined on the server:

`app.get('/auth/facebook', function(){
  console.log(passport.authenticate);
  passport.authenticate('facebook', { scope : 'email' });
});`

My code can be found on my repo on the fb-authentication branch:
https://github.com/Ceisen9/show-stopper

**Comment by jshawl** [comment]
Are you already logged in? Try an incognito window

**Comment by Ceisen9** [comment]
same thing.

**Comment by jshawl** [comment]
wondering if this is conflicting - https://github.com/Ceisen9/show-stopper/blob/91c8ed1099fd8976f4ccd3ae3f12b11f71de8131/index.js#L56-L58 can you try commenting that out and then try logging in again?

**Comment by Ceisen9** [comment]
Now no page is showing up, but its saying "cannot GET /"

**Comment by Ceisen9** [comment]
Ok, I think I figured it out. If you disable html5 mode the link will work... Do you know of a way to do this with HTML5 mode still intact?

**Comment by RobertAKARobin** [comment]
I just pulled down your repo and don't see anything having to do with Passport... But one thing I do see is that [this line](https://github.com/Ceisen9/show-stopper/blob/fb-authentication/public/js/app.js#L39) is referring to a template that doesn't exist. You have `welcome.html` but not `shows-welcome.html`.

**Comment by Ceisen9** [comment]
Thanks, but Idk if that was the route of the problem. I have it up and running, just without using HTML5 mode.
