### ISSUE TITLE
need help deciphering json

### ISSUE THREAD

**Issue by adrianshep** [ga-wdi-exercises/project4#18]
I've got some example code I'm trying to work with and I can't make it display. I feel like it's something obvious, but can't get at it...

**Comment by RobertAKARobin** [comment]
Can you be more specific?

**Comment by adrianshep** [comment]
I'm trying to nail down whether this stretch of code is trying to pull its data from a 'people.json' file in the directory or whether there's a crucial missing piece:

`````` <script>
    $(function() {
   var people = [];

   $.getJSON('people.json', function(data) {
       $.each(data.person, function(i, f) {
          var tblRow = "<tr>" + "<td>" + f.firstName + "</td>" +
           "<td>" + f.lastName + "</td>" + "<td>" + f.job + "</td>" + "<td>" + f.roll + "</td>" + "</tr>"
           $(tblRow).appendTo("#userdata tbody");
     });
   });
});
</script>```
``````

**Comment by RobertAKARobin** [comment]
Yep, it's trying to get a `people.json` in the current directory. Have you tried just doing `console.log(data)` without all of the `.each` stuff? Need to make sure the file's actually being read first.

**Comment by adrianshep** [comment]
when i tried console.log, I got this error message:

XMLHttpRequest cannot load file:///Users/adrianshepelavey/wdi/projects/ad-gauge/people.json. Cross origin requests are only supported for protocol schemes: http, data, chrome, chrome-extension, https, chrome-extension-resource.

**Comment by RobertAKARobin** [comment]
Try accessing your app through a server. For example:

```
python -m SimpleHTTPServer
```

Then go to `localhost:8000/index.html` or whatever.

**Comment by adrianshep** [comment]
Just did that and I'm getting what I've gotten without it, which is the column header row and no data.

Is it the formatting of the data perhaps? Here's my people.json content:

```
{
   "person": [
       {
           "firstName": "Clark",
           "lastName": "Kent",
           "job": "Reporter",
           "roll": 20
       },
       {
           "firstName": "Bruce",
           "lastName": "Wayne",
           "job": "Playboy",
           "roll": 30
       },
       {
           "firstName": "Peter",
           "lastName": "Parker",
           "job": "Photographer",
           "roll": 40
       }
   ]
}
```

**Comment by adrianshep** [comment]
I uncommented the each code and now it shows up in my localhost 8000. Thanks!

**Comment by RobertAKARobin** [comment]
Woooo
