### ISSUE TITLE
Ng-binding 

### ISSUE THREAD

**Issue by nyron** [ga-wdi-exercises/project4#180]
trying to get angular show data to display index works fine.

**Comment by RobertAKARobin** [comment]
Can you include any errors or screenshots?

**Comment by jshawl** [comment]
@nyron ^^ - also any console.logs of the angular data?

**Comment by nyron** [comment]
ah thanks guys I figured it out. by dropping the database it changed my id numbers and I was manually putting in id numbers like 1, 2, 3, 4 and it started around 33.

**Comment by nyron** [comment]
for my show page so that fixed the problem.
