### ISSUE TITLE
query error

### ISSUE THREAD

**Issue by Crunchwrap78** [ga-wdi-exercises/project4#183]
The data isn't being queried by factory and it thinks I'm trying to pass an array when I'm try to pass an object.I ran a
I ran a console.log on the data it has the same error in the value
<img width="1361" alt="screen shot 2016-04-27 at 9 27 58 am" src="https://cloud.githubusercontent.com/assets/14954458/14853821/0b269cc4-0c5b-11e6-8df9-8bebf1033a24.png">

**Comment by amaseda** [comment]
Can you include code snippets / link to the code in your repo that might be causing this error? Might as well include the entire error message here too.

**Comment by Crunchwrap78** [comment]
sorry I accidentally posted this before completing it
