### ISSUE TITLE
query error

### ISSUE THREAD

**Issue by Crunchwrap78** [ga-wdi-exercises/project4#184]
I'm trying to query my data, but I'm getting an error saying It's to pass in an array when I'm not. I'm trying to pass in an object, which is what I want. I'm sure I'm using the correct routes because they do work. 

Why would it be doing that. 

Stackoverflow suggested I should us isArray: true, but that didn't do anything

<img width="1361" alt="screen shot 2016-04-27 at 9 27 58 am" src="https://cloud.githubusercontent.com/assets/14954458/14854190/b3a8fa1c-0c5c-11e6-9045-1069205a1b73.png">

**Comment by Crunchwrap78** [comment]
Heres my repo. https://github.com/Crunchwrap78/TeslaTravels/pull/1

the code is in public/js/app.js

**Comment by RobertAKARobin** [comment]
You're telling Angular to get the car data from `"api/cars"`, but you haven't defined a route for `"api/cars"` in your `index.js`.

**Comment by Crunchwrap78** [comment]
I'm using the express router, so the route is in cars.js

**Comment by amaseda** [comment]
If I try to visit `http://localhost:3001/api/cars` or `http://localhost:3001/api/cars.json` in the browser I get your welcome page. Should that be happening?

It might have to do with your wild card (`/*`) route.

**Comment by RobertAKARobin** [comment]
Found it. It's because of this:

``` js
app.use("/cars", require("./controllers/cars"));
```

That means `/cars` must come _before_ all the routes in your cars controller. So in your controller where you have this:

``` js
router.get("api/cars"
```

...the URL would actually be `/cars/api/cars`.

Additionally, you need a slash at the beginning of each of those `/api` routes:

``` js
router.get("/api/cars"
```

**Comment by Crunchwrap78** [comment]
ok that fixed the issue. Thanks!
