### ISSUE TITLE
Having trouble using Passport for users 

### ISSUE THREAD

**Issue by maureenv** [ga-wdi-exercises/project4#185]
I've gone through the following tutorial to create users for my site: 
https://scotch.io/tutorials/easy-node-authentication-setup-and-local 
and  tested out the signup form but nothing happened. I was wondering how I'm supposed to know if a user is actually created in the database. I tried searching db.users.find() and db.user.find() but nothing shows up. I might be searching for the wrong keyword in the database, or the code just isn't working. 

My github repo is https://github.com/maureenv/cheatss/tree/users, most of my user information is in the "user" folder. 

Thank you

**Comment by RobertAKARobin** [comment]
It's not being created. Note these lines:

``` js
     successRedirect : '/', // redirect to the secure profile section
     failureRedirect : '/signup', // redirect back to the signup page if there is an error
```

Every time you try to sign up, it takes you back to the `signup` page, correct? So it must not be signing up successfully.

**Comment by maureenv** [comment]
Yes, but I still don't know how to check for the information in the database. I'm afraid my database doesn't have access to the user information and I'm not sure how to check for that. 

in my db/connection.js file there's this information which I believe hooks up my schema information to the database:

```
if(process.env.NODE_ENV == "production"){
  mongoose.connect(process.env.MONGODB_URI); // make sure this says MONGODB
}else{
  mongoose.connect("mongodb://localhost/cheatss");
} //heroku attempt
```

but my schema information for users is located in the users/user.js file where it doesn't say 

```
if(process.env.NODE_ENV == "production"){
  mongoose.connect(process.env.MONGODB_URI); // make sure this says MONGODB
}else{
  mongoose.connect("mongodb://localhost/cheatss");
} //heroku attempt
```

So I don't know if this will cause an issue

**Comment by RobertAKARobin** [comment]
`db.user.find()` would work correctly. That all looks fine.

You only need `mongoose.connect` in one file; as long as something `require`s both your `users/user.js` file and your `connection.js` file, everything will work correctly.

**Comment by RobertAKARobin** [comment]
I'm not sure which tutorial you used, but honestly it looks really complicated to me. If you're determined to go the Passport route instead of doing it yourself, I would suggest modeling things after [this example](https://github.com/passport/express-4.x-twitter-example/blob/master/server.js).

**Comment by maureenv** [comment]
Okay, I also think I should start over with an easier tutorial.

**Comment by maureenv** [comment]
Also, what do you mean by the passport route vs doing it myself? Do you mean that I can try creating users without passport?

**Comment by RobertAKARobin** [comment]
https://github.com/ga-wdi-lessons/express-oauth-handrolled
