### ISSUE TITLE
running a server side function from the client

### ISSUE THREAD

**Issue by MattLeeStevens** [ga-wdi-exercises/project4#186]
In express, `db/get_games.js` exports a `getGames` function that parses information from a request url.  

I can run `getGames()` on the server in `routes.js` and render the results in my view so I know it works.  

I would like to be able to initiate the function from the client and pass in different dates to the request url.  

I have no idea how to access that function from the client.  I was hoping I could get a nudge in the right direction.  

Repo: https://github.com/MattLeeStevens/nbaProject

**Comment by RobertAKARobin** [comment]
The short answer is to take your `.js` file and put it with all your static assets. Then your front-end can access it, and your back-end can access it with `require("public/whatever.js")`.

However, things that work on the back-end don't work on the front, and vice-versa. For instance, you're using `request` which is back-end only. I'm unsure about `cheerio` but it may be as well. So even if you could access it on the front, it wouldn't do much good.

**Comment by MattLeeStevens** [comment]
Yeah, those won't work on the front.  Any ideas for triggering that function from the client to get back info for different dates?  Or where I would even be putting that logic?  Would it be when render I the view?

**Comment by RobertAKARobin** [comment]
I'd say create an API route that calls it, and then ping that route with Angular. Take a look at Angular's `$http` module -- `$resource` is built on top of it.

**Comment by MattLeeStevens** [comment]
Ahh, that's a good idea. Thank you.  I actually have this stuff separate from the angular app at the moment.  Is there a good way to access the api route without angular or is that the easiest way to do it.

**Comment by RobertAKARobin** [comment]
Either that, or `$.ajax` with jQuery.
