### ISSUE TITLE
making a list within a list

### ISSUE THREAD

**Issue by Dibbledl01** [ga-wdi-exercises/project4#187]
Link to repo: https://github.com/Dibbledl01/AppOfHonor

Hi again!

Would anyone be able to direct me towards the right direction in terms of making lists within my lists? I fixed my previous syntax error (thanks Matt!).

Robin had previously tried to help me by offering me some code, but him being brilliant....I butchered his idea xD

**Comment by RobertAKARobin** [comment]
Can you clarify what you mean by lists within lists? Like in your schema or something?

**Comment by Dibbledl01** [comment]
Sure! Sorry about that!

So, right now in my seeds.json file, I have 9 "lists" that are actually called "months" throughout the rest of my code. These are broken down into periods of time from 12 months before a wedding down to the day of. Ideally, what I would love to do, is direct a user to the homepage that says, "hey girl! you have 9 lists to review!" that's broken down into those time increments (i.e. 10-12 Months Out, 6-9 Months Out, etc.). Those are working right now (yay!) The user would then click on a list (let's say, she clicks on "Day Of"). Another list will then appear with "tasks" that she should complete the day of the wedding (i.e. "have cash ready for beauty vendors," "keep bride calm," "have emergency sewing kit on hand.")

I'm confusing myself as to where those "tasks" should live....since they will be "living" within the individual {name: "....."} in my seeds.json file.

Did that help at all? :/

**Comment by RobertAKARobin** [comment]
How about this: If your database was JSON, what would it look like? For example:

``` js
var users = [
  {
    name: "Alice",
    lists: [
      {
        title: "Shopping",
        tasks: [
          {
            description: "milk",
            completed: false
          },
          {
            description: "eggs",
            completed: true
          }
        ]
      },
      {
        title: "Bills to pay",
        tasks: [
          {
            description: "cable company",
            completed: true
          }
        ]
      }
    ]
  },
  {
    name: "Bob"
  }
]
```
