### ISSUE TITLE
Trouble reaching the twitter api

### ISSUE THREAD

**Issue by pkmoran** [ga-wdi-exercises/project4#188]
I've used passport-twitter auth successfully (users can log in with twitter credentials) but I can't seem to access the twitter api using the tokens given to me by my twitter app.

I keep getting an error in req.body: `{"errors":[{"code":89,"message":"Invalid or expired token."}]}`

I'm using the `request` module to make the request with hard coded query params for now.

[Github Repo](https://github.com/pkmoran/wdi-project-4)

request happening around:
- index.js, line 103

Thanks!

EDIT: repo wasn't updated, but is updated now

**Comment by pkmoran** [comment]
Oh goodness... I forgot to define `process.env.t_token` and `process.env.t_token_secret` after I added them to my `env.json` file... It seems to be working fine now

**Comment by RobertAKARobin** [comment]
Woo! Glad you got it!
