### ISSUE TITLE
Unable to create a new list

### ISSUE THREAD

**Issue by winishahines** [ga-wdi-exercises/project4#189]
I'm trying to create a new list in my app but I'm getting the following error:

![snip20160427_2](https://cloud.githubusercontent.com/assets/16657107/14861470/645f3308-0c7b-11e6-8e68-98fb966d02ca.png)

Here is my task list controller and routes.rb pages:

![snip20160427_3](https://cloud.githubusercontent.com/assets/16657107/14861498/7980846c-0c7b-11e6-90a7-f15f2ab8cb78.png)
![snip20160427_4](https://cloud.githubusercontent.com/assets/16657107/14861500/7c6823ec-0c7b-11e6-902b-cf6b227b35cd.png)

**Comment by RobertAKARobin** [comment]
Look at your URL. It ends in `new.3`. That `.3` looks pretty weird. This indicates you passed parameters to a `link_to` that don't belong.

**Comment by RobertAKARobin** [comment]
Your `routes.rb` and controller look fine. It's whatever you clicked on to get to that URL in the first place.

**Comment by winishahines** [comment]
The link to "create new task" was set to new_task_list_path(current_user) in my application.html file. I removed it but now I get this error:

![snip20160427_7](https://cloud.githubusercontent.com/assets/16657107/14862067/dbb4227c-0c7d-11e6-8d33-513e0d045b90.png)

Each tasklist should be long to a user so I'm not sure what I'm doing wrong...I still get the ".3" thing in the url.

**Comment by winishahines** [comment]
New changes to the application.html:

Snip20160427_5

**Comment by RobertAKARobin** [comment]
Are `@user` and `@task_list` both defined in your controller?

I'm asking because it's talking about `nil:Nilclass` which means something hasn't been defined.

**Comment by winishahines** [comment]
Yes, here's my controller:

![snip20160427_4](https://cloud.githubusercontent.com/assets/16657107/14862423/54b2a418-0c7f-11e6-85c6-1c586bd9296c.png)

**Comment by RobertAKARobin** [comment]
The problem isn't on the `new` page -- it's how you're getting to that `new` page to begin with. Rails can only get `params[:user_id]` if it's `new/32` or something else with a `/`. With a period, like `new.32`, it won't work.

**Comment by winishahines** [comment]
I was able to fix the path so that it no longer routes to "new.3" but I'm still struggling with how to recognize that the user is creating a new task list. My route for creating a new list is "/task_lists/new" and I'm getting a model name nil error. I spoke with some of the other students but none of us can seem to figure out the issue. Here's some updated screenshots:

![snip20160427_10](https://cloud.githubusercontent.com/assets/16657107/14864984/80eb9976-0c8a-11e6-9a86-b85a3db0c22d.png)

![snip20160427_11](https://cloud.githubusercontent.com/assets/16657107/14865000/8d03e2cc-0c8a-11e6-979c-85443412f8e3.png)

**Comment by RobertAKARobin** [comment]
It looks like you're missing a `def new` for task lists.

**Comment by winishahines** [comment]
I added def new and got the following:

![snip20160427_12](https://cloud.githubusercontent.com/assets/16657107/14865762/39ce59bc-0c8e-11e6-8748-57bb2420c855.png)

![snip20160427_13](https://cloud.githubusercontent.com/assets/16657107/14865776/41457964-0c8e-11e6-80b3-40e5a82ece2d.png)
