### ISSUE TITLE
Passport attempt 2 not working. 

### ISSUE THREAD

**Issue by maureenv** [ga-wdi-exercises/project4#190]
So I really want users to be able to sign in locally instead of through Twitter and Facebook so I'm using a different tutorial this time to do it. 

I'm only in the beginning of the following tutorial http://mherman.org/blog/2015/01/31/local-authentication-with-passport-and-express-4/#.VyD1o2Z7JSY and I'm getting an error already. 

The lines below in index.js are what are causing the error: 

``` js
var Account = require('./db/connection');
passport.use(new LocalStrategy(Account.authenticate()));
```

and the error says 
![screen shot 2016-04-27 at 1 34 55 pm](https://cloud.githubusercontent.com/assets/16403532/14861956/6d369f64-0c7d-11e6-9f73-28f36c9dd4cf.png)

Do you know why this could be throwing an error?

My github repo is https://github.com/maureenv/cheatss/tree/users

Thank you

**Comment by RobertAKARobin** [comment]
``` js
var Account = require('./db/connection');
```

...so let's see what's `module.exports`ed from `db/connection.js`:

``` js
module.exports = mongoose;
```

...so we know:

``` js
Account === require("./db/connection") === module.exports === mongoose
```

That means you're trying to do `mongoose.Authenticate`. I don't think Mongoose has an `Authenticate` method.

**Comment by maureenv** [comment]
Hey Robin, Matt helped me solve the problem. 
I had to type in 

``` js
var mongoose = require('./db/connection');
Account = mongoose.model("Account");
```

instead of 

``` js
var Account = require('./db/connection');
```

Thank you for your help :)
