### ISSUE TITLE
app not working with rails

### ISSUE THREAD

**Issue by ghost** [ga-wdi-exercises/project4#192]
when running on angular server it works but on rails it does not load. https://github.com/Bneupane/newsfeed

**Comment by RobertAKARobin** [comment]
Can you be more specific?

**Comment by ghost** [comment]
yeah, when i run the app on angular server it works. and then i integrated it with rails and only title shows up on the browser and browser shows blank while on the rails server. i've integrated it with rails the way it should and been trying to figure out why its not working...

**Comment by ghost** [comment]
application_controller.rb file

``` rb
class ApplicationController < ActionController::Base

  def index

  end
end

and my routs.rb file

Rails.application.routes.draw do
  resources :application
end
```

localhost:3000/ is not showing anything.

**Comment by RobertAKARobin** [comment]
`<%= yield %>`!

**Comment by RobertAKARobin** [comment]
...and if not that, open up your Chrome console.
