### ISSUE TITLE
Might be stuck in UnDRY loop

### ISSUE THREAD

**Issue by iamanissa** [ga-wdi-exercises/project4#194]
repo: https://github.com/SuperJones/project2/tree/dual

I am using jQuery to change the values of the duel page. At this point my code is copy and pasting a lot but more importantly I think I need to add setInterval or something so that the paragraph statuses are added one after another and you can see which user is active and things updating. 
Maybe this isn't a question but I need a push in the right direction, because I am feeling a little stuck.

**Comment by RobertAKARobin** [comment]
If you have patches of near-identical code, it almost always indicates something can be extracted into a method.

Look for the things that repeat, and the things that do _not_ repeat.

Example:

``` js
function isAnimated(){
  if(oppweapon.hasClass("active")){
    oppweapon.addClass('animated infinite pulse');
  }else{
    oppweapon.removeClass('animated infinite pulse');
  }

  if(currweapon.hasClass("active")){
    currweapon.addClass('animated infinite pulse');
  }else{
    currweapon.removeClass('animated infinite pulse');
  }
```

In both those "if" blocks, the only thing that doesn't repeat is `currweapon`/`oppweapon`. That indicates the weapon could be an argument passed into a function:

``` js
function isAnimated(weapon){
  var classname = 'animated infinite pulse';
  if(weapon.hasClass("active")){
    weapon.addClass(classname);
  }else{
    weapon.removeClass(classname);
  }
}
isAnimated(currweapon);
isAnimated(oppweapon);
```

**Comment by iamanissa** [comment]
Sooo, yes thank you that works, buuut I realized that the dryness of my code wasn't my real problem. My real problem is that I'm trying to add setTimeout (i think) to add a delay between things, but because I was getting lost in my code, I can't figure out were to begin to implement that. 

I want there to be a delay after each attack and change to health points to users can see what happened instead of my code just jumping to the end.

**Comment by iamanissa** [comment]
I think this should be in a method

```
//opponent attacks user
$('#middleInfo p:last').after("<p></p>");
$('#middleInfo p:last').append(oppUsername + " ATTACKS " + currUsername);
//update status in the middle
$('#middleInfo p:last').after("<p></p>");
$('#middleInfo p:last').append(currentUsername + " loses "+totalOppAtt + " health points");
```

because the "curr" and "opp" is what changes and I need this code over and over.
Then after each I want to wait like 5 seconds before everything happens again.
