### ISSUE TITLE
Create functionality for embedded object: Name of show does not persist first time around

### ISSUE THREAD

**Issue by christine-sm** [ga-wdi-exercises/project4#197]
Link to `app.js` file: https://github.com/cmmovius/playbill-dc/blob/tags/public/js/app.js

I am working on CRUD functionality for my shows, which are embedded objects within theaters. What I am doing is creating a new blank object, and then the user can edit the blank object with a form to add the information about the show.

When I do this:

```
vm.addShow = function(){
      vm.theater.shows.push(Object.create(Object.prototype));
      vm.update();
    };
```

It creates a totally blank object that the user can edit. Every entry on the form can be edited and the information persists upon page refreshes. However, I wanted to do this:

```
vm.addShow = function(){
      vm.theater.shows.push(Object.create(Object.prototype, {
        name: {writable: true, value: 'Edit Me to Add a Show!'}
      }));
      vm.update();
    };
```

So the user would know that they need to then edit the blank object to create the show. However, the first time they replace the `value` with the proper title it does _not_ persist in the database and the `show.name` is blank upon a page refresh. Yet when they add in a `show.name` a second time, that stays in the DB and persists upon refreshes.

Suggestions?

**Comment by RobertAKARobin** [comment]
Hm. What's with this weird `Object.create(Object.prototype` thing?

**Comment by christine-sm** [comment]
That is the syntax that I found online on how to create an empty object.

**Comment by christine-sm** [comment]
https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Object/create

**Comment by RobertAKARobin** [comment]
What's wrong with just:

``` js
vm.theater.shows.push({
  name: {writable: true, value: 'Edit Me to Add a Show!'}
});
```

Sorry to nag -- I think this may be related to the issue you're having. It'll make the code easier to read and write at any rate!

**Comment by christine-sm** [comment]
That solves the refresh problem! But it shows up as an object before I edit it. So I think I need to fix the syntax slightly:
<img width="549" alt="screen shot 2016-04-28 at 12 16 29 pm" src="https://cloud.githubusercontent.com/assets/15206696/14892906/1e152f90-0d3b-11e6-8b51-2a8973a1db7e.png">
<img width="543" alt="screen shot 2016-04-28 at 12 17 42 pm" src="https://cloud.githubusercontent.com/assets/15206696/14892942/478cf380-0d3b-11e6-9ac7-1774fec1bffb.png">

**Comment by RobertAKARobin** [comment]
What did you do to get the second screenshot that's different from the first screenshot?

**Comment by christine-sm** [comment]
I edited the values in the form. So screenshot 1 is what appears when I click the "Add Show" button and then click the "Edit/Delete" Button. Screenshot 2 is the result of me editing the form.

**Comment by christine-sm** [comment]
This is what shows up immediately after hitting the "Add Show" button:
<img width="369" alt="screen shot 2016-04-28 at 12 22 58 pm" src="https://cloud.githubusercontent.com/assets/15206696/14893082/f8ed677c-0d3b-11e6-981a-9d7e0319499a.png">
And then I click "Edit/Delete" to edit the show to my liking.

**Comment by christine-sm** [comment]
Got it!

**Comment by christine-sm** [comment]
I just pruned it down to this: 

```
vm.addShow = function(){
      vm.theater.shows.push({
        name: 'Edit Me to Add a Show!'
      });
      vm.update();
    };
```

Less is more 👍
