### ISSUE TITLE
$http core service in AngularJS

### ISSUE THREAD

**Issue by Curtismn87** [ga-wdi-exercises/project4#20]
So I'm trying to make an API call locally before I move on to a third party API..

my "js/controllers/foodsController.js" file looks like this:

```
  var app = angular.module("MenuBuilder", []);

  app.controller("foodsController",[function(){
    console.log("before getFoods is run");
       this.getFoods = function($scope, $http){
        console.log("button clicked");
        $http.get("/js/foods.json")
        .success(function(response){
          $scope.food = response;
          console.log(response);
        })
        .fail(function(){
          console.log("call has failed");
        });
      };
  }]);
})();
```

I have the call in an HTML button which is coded like this:
`"<button ng-click='foodsCtrl.getFoods()' class='cancel'>Get</button>"`

I am getting the follow error "Cannot read property 'get' of undefined
    at getFoods "

I have read through all the angularJS documentation and tried googling. I still don't understand why the $http isn't working if it's supposed to be a core angular service.

**Comment by RobertAKARobin** [comment]
Please use backtics to format the code in your issues! I'm reading through this now.

**Comment by Curtismn87** [comment]
Awesome, thanks Robin... I just updated with backtics.. thought that was only a slack thing

**Comment by RobertAKARobin** [comment]
First things first: fix the indentation on your code. `this.getFoods...` should be indented as much as the `console.log` before it.

**Comment by RobertAKARobin** [comment]
I'ma close this since we haven't heard from you in a while.
