### ISSUE TITLE
Thought I fixed infinite loop issue but not really 

### ISSUE THREAD

**Issue by iamanissa** [ga-wdi-exercises/project4#200]
repo: https://github.com/SuperJones/project2/tree/dual

I still can't figure out how to say, if a users hp <= 0 stop setInterval 
I tried adding this in the decrementHP but still stuck:

```
    statusUpdate(oppUsername, currUsername, totalOppAtt);

    currhp -= totalOppAtt;
    $("#currhp").html(currhp);
    // FIXME: If currhp == 0 then don't get out of function
    if(currhp === 0){
      // break
    }else{
      toggleActive();
      isAnimated(oppweapon);
      isAnimated(currweapon);
    }
```

**Comment by RobertAKARobin** [comment]
Here's an example of what your code might look like:

``` js
var instanceOfTimer = setInterval(doWhatEverySecond, 1000);

function doWhatEverySecond(){
  console.log("Hello");
  if(user.hp <= 0){
    clearInterval(instanceOfTimer);
  }
}
```

**Comment by iamanissa** [comment]
I thought of that, but I didn't think I could call timerId because it would ...I guess be recursive or out side of scope. I'll give it a try. thx

**Comment by iamanissa** [comment]
Yep that worked. Thank you.
I have got to just start trying things instead of saying "It's not going to work."

**Comment by RobertAKARobin** [comment]
# YES

**Comment by iamanissa** [comment]
If there was an emoji to laugh and stick out my tongue I would use it

**Comment by iamanissa** [comment]
Also I was talking to Adrian the student, and this whole time I thought I couldn't do that because that was something you could do in Ruby, not Javascript.
