### ISSUE TITLE
Error deleting individual entry

### ISSUE THREAD

**Issue by mkernsNCR** [ga-wdi-exercises/project4#201]
``` js
vm.deleteEntry = function(entry) {
      console.log("del Entry:", entry);
      console.log(entry._id);
      Entry.remove({id: entry._id});
    }
```

I am trying to delete one entry from my list. I tried adding a factory for my Entry and then $injecting it into the function. It gives me a 404 error so i even created a route for the function and that doesn't seem to work either.

Repo: https://github.com/mkernsNCR/project_4/tree/error_branch

**Comment by RobertAKARobin** [comment]
Can you show the error you're getting?

**Comment by mkernsNCR** [comment]
```
angular.js:11756 DELETE http://localhost:3001/api/entries/57222559476a3d173d6efab8 404 (Not Found)
```

**Comment by RobertAKARobin** [comment]
Hm. It worked totally fine for me. You sure you're running `nodemon` and not `node`?

**Comment by RobertAKARobin** [comment]
Oh, never mind. I was deleting the wrong thing.

**Comment by RobertAKARobin** [comment]
Well, you can see from your error message it's looking for `/api/entries`. Do you see `app.delete("/api/entries"` anywhere in your `index.js`?

**Comment by mkernsNCR** [comment]
I just switched it and it through me the same error.

**Comment by RobertAKARobin** [comment]
What do you mean "switched it"?

**Comment by mkernsNCR** [comment]
```
app.delete("/api/entries/:id", function (req, res) {
  console.log(req.params.id);
  List.entries.findOneAndRemove(req.params.id).then(function () {
    res.json({success: true});
  });
});
```

**Comment by RobertAKARobin** [comment]
I bet it's not giving you a 404 error anymore. Is it a 500?

**Comment by mkernsNCR** [comment]
Yes it is a 500 actually. What is that telling me?

**Comment by RobertAKARobin** [comment]
http://lmgtfy.com/?q=500+error

😛

**Comment by mkernsNCR** [comment]
I looked it up before I sent that I don't know what it means by not having a more relevant error?

**Comment by RobertAKARobin** [comment]
Ah, darn, I've been waiting for an excuse to use lmgtfy.com.

404 means is can't find that particular route. 500 means that it can find the route, but the server (Express) is responding with an error message -- meaning something's causing Express to break. Read the error message in Terminal where you have `nodemon` running and see what it says.

**Comment by mkernsNCR** [comment]
Ok so nodemon said this `TypeError: Cannot read property 'findOneAndRemove' of undefined`

**Comment by mkernsNCR** [comment]
It's trying to tell me "entries" is undefined but I don't understand how that's possible.

**Comment by RobertAKARobin** [comment]
That `.findOneAndRemove` is attached to `List.entries.`. You need to find the list first before you can find its entries.

**Comment by mkernsNCR** [comment]
Ok let me try and nest it.

**Comment by mkernsNCR** [comment]
I did this 

```
app.delete("/api/entries/:id", function (req, res) {
  console.log(req.params.id);
  List.findOne(req.params).then(function () {
    List.entries.findOneAndRemove(req.params.id).then(function () {
      res.json({success: true});
    });
  });
});
```

And nothing happened and there's no error.

**Comment by RobertAKARobin** [comment]
In this line you look up a list:

``` js
  List.findOne(req.params).then(function () 
```

...but then you don't do anything with that list you looked up. You go back to `List.entries`.

You'll want something like this:

``` js
app.delete("/api/entries/:id", function (req, res) {
  List.findOne({"entries._id": req.params.id}).then(function(list) {
    list.entries.remove(req.params.id);
    list.save().then(function(){
      res.json(list)
    });
  });
});
```
