### ISSUE TITLE
Issue displaying data as text

### ISSUE THREAD

**Issue by LNewsome** [ga-wdi-exercises/project4#202]
I did an app.get and app.post. I want to submit information on a form and I want that information tp show on another page, but I'm getting data in the screen.
Here's my repository:https://github.com/LNewsome/quiet-loud

**Comment by RobertAKARobin** [comment]
Can you show your code, and/or link to your repo?

**Comment by LNewsome** [comment]
Here's my repo:https://github.com/LNewsome/quiet-loud

**Comment by LNewsome** [comment]
Sorry!

**Comment by RobertAKARobin** [comment]
I get `app.js:46 Uncaught ReferenceError: personalities is not defined` when I start up your app. Do you get this too?

**Comment by LNewsome** [comment]
Yes. I got it. I got something to display after I submit my info for the introvert form.

**Comment by RobertAKARobin** [comment]
I'd recommend fixing that error before continuing. Who knows what else it's affecting.

**Comment by LNewsome** [comment]
Ok. I will.
