### ISSUE TITLE
Problem deploying to heroku.

### ISSUE THREAD

**Issue by MattLeeStevens** [ga-wdi-exercises/project4#203]
Anyone recognize these errors?  I googled and couldn't really narrow down what the problem is.

![screen shot 2016-04-28 at 1 54 55 pm](https://cloud.githubusercontent.com/assets/16270426/14895872/ea11835c-0d48-11e6-893f-f2f6553dd5e4.png)

**Comment by RobertAKARobin** [comment]
It can't connect to your Mongo database.

**Comment by RobertAKARobin** [comment]
Same thing you'd get locally if `mongod` wasn't running.

**Comment by MattLeeStevens** [comment]
Do I need to remotely start mongod on the server somehow?

**Comment by RobertAKARobin** [comment]
https://github.com/ga-wdi-lessons/mean-intro/blob/master/2-connecting-mongo.md#added-procfile-and-mongolab-url-for-deployment

**Comment by MattLeeStevens** [comment]
Ah, yeah that's probably it.  Didn't see that in the deploying a MEAN app lesson.  Thanks!

**Comment by RobertAKARobin** [comment]
That lesson does it a different way using a Heroku "addon". The above does it a bit more from-scratch.

**Comment by MattLeeStevens** [comment]
Thanks, I got it working. I have a MONGODB_URI and a MONGOLAB_URL now.  I'm not totally sure what the difference is but the URL one is working.
