### ISSUE TITLE
can't access the login page

### ISSUE THREAD

**Issue by hh747hh** [ga-wdi-exercises/project4#204]
![screen shot 2016-04-28 at 2 00 38 pm](https://cloud.githubusercontent.com/assets/16959988/14896037/c8f89812-0d49-11e6-9e0f-e1907146bed8.png)

**Comment by hh747hh** [comment]
Also I set up
app.set('public', __dirname + '/public');

but still doesn't render the login page

**Comment by RobertAKARobin** [comment]
You can use `.render` only if you have Handlebars set up.
