### ISSUE TITLE
FB login doesn't do anything

### ISSUE THREAD

**Issue by Robizzy27** [ga-wdi-exercises/project4#205]
https://github.com/Robizzy27/steamo.git

**Comment by RobertAKARobin** [comment]
Wow. You have some weird stuff in here. Did you use some sort of a generator for this app?

**Comment by RobertAKARobin** [comment]
The problem is on the Facebook button you have `ng-click="facebookSignIn()"`.

This button is on the login page:

``` js
  state('tabsController.login', {
    url: '/login',
    views: {
      'tab1': {
        templateUrl: 'templates/login.html',
        controller: 'loginCtrl'
      },
      'tab5': {
        templateUrl: 'templates/login.html',
        controller: 'loginCtrl'
      }
    }
  })
```

...which uses the `loginCtrl` controller.

It only has one function attached to it: `$scope.login`.

The `facebookSignIn` function is in the `WelcomeCtrl` controller.
