### ISSUE TITLE
Problem accessing profile images on sign in

### ISSUE THREAD

**Issue by ssatyal** [ga-wdi-exercises/project4#206]
https://github.com/ssatyal/barkr

Currently having difficulty accessing a user's profile image upon login. I'm able to access the username in the browser when they log in by storing it as a cookie, but I'm not sure how to match up that username to retrieve the associated img_url from the database.

here is the sign in function server side:

``` js
app.put('/users/signin', function(req, res, next){
  db.collection('users', function(err, usersCollection){
    usersCollection.findOne({username: req.body.username}, function(err, user){
      bcrypt.compare(req.body.password, user.password, function(err, result){
        if(result){
          var token = jwt.encode(user, JWT_SECRET);
          return res.json({token: token});
        } else {
          return res.status(400).send();
        }
      })
    });
  });
});
```

and here's the sign in function on the front end (note: the checkImg() for loop was an attempted inefficient, non-elegant solution that won't work):

```
$scope.signin = function(){
    console.log("clicked");
    $http.put('/users/signin', {username: $scope.username, password: $scope.password})
    .then(function(res){
      console.log("res:",res);
      $cookies.put('token', res.data.token);
      $cookies.put('currentUser', $scope.username);
      $rootScope.token = res.data.token; //rootScope to access in diff controller
      $rootScope.currentUser = $scope.username; //access user in diff controller
      $rootScope.img_url = checkImg($rootScope.currentUser);
      // $cookies.put('img_url', $scope.img_url);
      console.log("Scope: ", $scope);
      console.log("barks: ", $scope.barks)
      console.log("rootScope: ",$rootScope);
    }, function(err) {
      alert("bad login");
    });
  };
  var checkImg = function(userToCheck){
    for (var i=0; i<$scope.barks.length; i++){
      if(userToCheck==$scope.barks[i].username){
        console.log("match!");
        return $scope.barks[i].img_url;
        break;
      }else{
        return null
      }
    }
  };
```

**Comment by RobertAKARobin** [comment]
The `res` from that `PUT` request doesn't include their `img_url`?

**Comment by ssatyal** [comment]
Here's what the res logs as in the console for the sign in put action: http://i.imgur.com/raxg8K3.png

res.config.data contains the username and password (unencrypted) from the client side
res.data contains the cookie token

**Comment by RobertAKARobin** [comment]
Can you include it in your response in this line?

https://github.com/ssatyal/barkr/blob/master/server.js#L81

**Comment by ssatyal** [comment]
I tried and it crashes the app, I think that line only works for a token because of bcrypt. Console logging 'result' from that code chain also sends 'true' to terminal. Perhaps I need to add a line before that return json that sets an img_url variable?

**Comment by RobertAKARobin** [comment]
Sure! You have `res.json({token: token})`. How about `res.json({img_url: img_url, token: token})` or something?

**Comment by ssatyal** [comment]
yeah, that's what I tried that crashes the app:

```
return res.json({img_url: img_url, token: token});
                                    ^

ReferenceError: img_url is not defined
```

**Comment by RobertAKARobin** [comment]
Well, you're going to have to define `img_url` first. It doesn't magically appear!

**Comment by ssatyal** [comment]
still struggling with retrieving the img_url...

tried adding this code but to no avail:

```
if(result){
          var token = jwt.encode(user, JWT_SECRET);
          var thisUser = usersCollection.findOne({username: req.body.username});
          var img_url = thisUser.img_url;
          console.log(thisUser);
          return res.json({img_url: img_url, token: token});
        } else {
          return res.status(400).send();
        }
```
also, the console log only returns "Promise { <pending> }" in this case but I think the query should still execute properly.
