### ISSUE TITLE
Rendering new "tasks" schema data

### ISSUE THREAD

**Issue by Dibbledl01** [ga-wdi-exercises/project4#207]
Link to repo: https://github.com/Dibbledl01/AppOfHonor

The new schema data is on the brittany_branch.
The origin is on the master branch.

I don't mean to be such a pain in the butt about this! I'm still having a hard time rendering my "tasks."

I've added new schema data to my seeds.json file. Each "month" now has unique tasks associated with it....but it's not rendering in my browser. Everything else still works.

I know there's something I'm missing (to make them render), but since they are specific to their parent "month" I don't think that will require any more directives (considering the directives to make the "months" render are already working fine).

My mind is OFFICIALLY fried and I apologize if the answer is something super obvious!

**Comment by RobertAKARobin** [comment]
Does your data seed successfully?

(Hint: It doesn't for me. www.jsonlint.com)

**Comment by RobertAKARobin** [comment]
Also, this is all I see in your schema:

``` js
var MonthSchema = {
  name: String
};
```

Where is Mongoose supposed to put the lists in there?
