### ISSUE TITLE
I am so many issues that I just don't even know anymore

### ISSUE THREAD

**Issue by LaFrish** [ga-wdi-exercises/project4#208]
Using a mean app... Can't get my data to show. Followed WhenPresidents for format and everything but it is just not working. Can someone please come and assists.

**Comment by RobertAKARobin** [comment]
Can you link to your repo?

**Comment by LaFrish** [comment]
https://github.com/LaFrish/beachhouse

**Comment by RobertAKARobin** [comment]
This isn't the data?

![screen shot 2016-04-28 at 4 50 00 pm](https://cloud.githubusercontent.com/assets/6268177/14901001/4564832c-0d61-11e6-85fb-780ff7f468c7.jpg)

**Comment by LaFrish** [comment]
That one portion is working now thanks to Joe. I can't add the recipes. I think there is an issue w the databases/seed data.

**Comment by RobertAKARobin** [comment]
Your seed data looks fine to me. Here's where I see a problem:

https://github.com/LaFrish/beachhouse/blob/master/public/js/app.js#L189

`.find` isn't an ngResource method. Perhaps you meant `.get`?

**Comment by LaFrish** [comment]
Ok I wll try it out and let you know.

**Comment by RobertAKARobin** [comment]
Also, your API doesn't appear to be working:

```
http://localhost:3001/api/mixologist/Moscow%20Mule
```

Are you stopping to test as you go?

**Comment by LaFrish** [comment]
I didn't want to use the api but the page wouldn't load unless I put that in the url. So I tested that the site was coming up and working yesterday but now that is today's problem.

**Comment by RobertAKARobin** [comment]
I found part of the problem: You need `/` at the beginning of each route.

Right:

```
app.get("/api/mixologist/:drink_name"
```

Wrong:

```
app.get("api/mixologist/:drink_name"
```

**Comment by RobertAKARobin** [comment]
Also, this line is going to cause problems because all your sessions stuff is commented out (which is totally fine), so just make sure to comment it out:

```
mixologist.isCurrentUser = (mixologist._id == req.session.mixologist_id)
```

**Comment by LaFrish** [comment]
BTW: this is why I had find in as a ngResource method 

<img width="916" alt="screen shot 2016-04-28 at 4 59 41 pm" src="https://cloud.githubusercontent.com/assets/15219375/14901284/ad451802-0d62-11e6-88f4-aead26320048.png">

**Comment by RobertAKARobin** [comment]
That's because I defined my own `.find` method, what you see on line 64.

**Comment by RobertAKARobin** [comment]
You're almost there!

![screen shot 2016-04-28 at 5 01 57 pm](https://cloud.githubusercontent.com/assets/6268177/14901376/ee4f8a44-0d62-11e6-88c4-916e94b066f2.jpg)

**Comment by LaFrish** [comment]
lol I had it defined too but it was commented out during the last fix session.

**Comment by LaFrish** [comment]
lol I am not getting the same results as you...

**Comment by RobertAKARobin** [comment]
Show us what you've changed and what you're getting now.

**Comment by LaFrish** [comment]
<img width="975" alt="screen shot 2016-04-28 at 5 17 29 pm" src="https://cloud.githubusercontent.com/assets/15219375/14901786/246b1006-0d65-11e6-9c7c-8c6e24df163a.png">

**Comment by LaFrish** [comment]
Thanks to John  I have the show page working. But I still cannot add to the drink list.
<img width="203" alt="screen shot 2016-04-28 at 5 58 50 pm" src="https://cloud.githubusercontent.com/assets/15219375/14902770/0db56f90-0d6b-11e6-9215-f1e1904f172f.png">

**Comment by LaFrish** [comment]
I also can't edit or delete anything.

**Comment by RobertAKARobin** [comment]
The POST isn't working because it's inside a `<form>`. Forms are for submitting things using HTML. Angular, however, uses AJAX. AJAX and HTML forms are mutually exclusive because they send data in two different ways. So just change the `<form>` to a `<div>` and you'll be good to go.

Then, I see that you have `data-ng-click="create()"`. It's only if you're inside custom directives and `ng-repeat` that you can do that, without anything before the `create()` -- otherwise you'll need `MixIndexVM.create()`.
