### ISSUE TITLE
Cross Origin Request Issue

### ISSUE THREAD

**Issue by jeffjones89** [ga-wdi-exercises/project4#21]
I built an express app that connects to a MongoDB (using MongoJS), and all it does right now is serve a get request and returns the json. 

I went to work on the Angular portion of my application to take a break from the backend, running the python simple server, and I'm running into the following error when Angular tries to build the factory 

XMLHttpRequest cannot load http://localhost:4000/players. No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'http://localhost:8000' is therefore not allowed access.

Should I just deploy my API somewhere? Should I try and merge the two files together for the time being? 

Thanks!

**Comment by RobertAKARobin** [comment]
Argh, Mongo.

How are you running the Mongo server? With `mongod`?

**Comment by jeffjones89** [comment]
Yep, on the default port (27017).

**Comment by RobertAKARobin** [comment]
Hm. So why are you making your requests to `localhost:4000`? Shouldn't it be `localhost:27017`?

**Comment by jeffjones89** [comment]
So Localhost:4000 is running the express application that serves the request (edit: this portion is an attempt to replicate the functionality of grumblr.wdidc.org/grumbles/:id or whatever the link was with the grumblr_angular). All three ports are currently running (27017, 4000, 8000).

When I go to localhost:4000, I get the following...which I think is on the right path? Because I eventually want my program to communicate with an api that serves my database rather than the database directly? 

<img width="477" alt="screen shot 2015-09-15 at 5 38 47 pm" src="https://cloud.githubusercontent.com/assets/11494386/9890872/b6ee065a-5bd0-11e5-9568-4f3a3aaf19bc.png">

**Comment by RobertAKARobin** [comment]
Well, that means your API is running, so that's good. I don't really get why you have 4000 and 8000 both running, though... Shouldn't 4000 be serving your front-end as well?

**Comment by jeffjones89** [comment]
That's what I'm a little confused about. I know in class we ran the SimpleHTTPServer on port 8000 when using Grumbler in class. 

The way I understand the MEAN stack is what you're alluding to, that Node is my server, and I should be able to query the server using Angular. But I'm a bit lost as to where that connection should be made?

**Comment by RobertAKARobin** [comment]
That's because in class we didn't have a back-end. Here, you're providing your own back-end, so you can make it provide your front-end too. Instead of using that Python server, define a route for your back-end to make it serve HTML.

``` js
app.get("/", function(request, response){
  response.sendFile(__dirname + "/index.html");
});
```

Then, when you do `nodemon` to start your back-end, you'll be able to go to `localhost:whatever/` in your browser to see that HTML file, which can contain all your Angular.

**Comment by jeffjones89** [comment]
Okay that definitely makes sense. At least I'm pretty sure.

The idea would be that '/' would serve an Index.html file that mimics our index.html from last week (basically just a skeleton with ng-view). And then in another folder (I think we used Public previously), I could include the angular views/controllers/services/directives?

That way when I nodemon it renders an index.html that's wired up to Angular all in the same project/file tree?

**Comment by RobertAKARobin** [comment]
Bingo.

**Comment by jeffjones89** [comment]
Makes total sense now. Thank you!!
