### ISSUE TITLE
same problem with retrieving profile images

### ISSUE THREAD

**Issue by ssatyal** [ga-wdi-exercises/project4#210]
https://github.com/ssatyal/barkr

still struggling with retrieving the img_url...

tried adding this code but to no avail:

``` js
if(result){
          var token = jwt.encode(user, JWT_SECRET);
          var thisUser = usersCollection.findOne({username: req.body.username});
          var img_url = thisUser.img_url;
          console.log(thisUser);
          return res.json({img_url: img_url, token: token});
        } else {
          return res.status(400).send();
        }
```

also, the console log only returns "Promise { }" in this case but I think the query should still execute properly. The response still looks like just the token.

**Comment by RobertAKARobin** [comment]
`.findOne` is asynchronous. You need to calculate `thisUser.img_url` only after `.findOne` has finished.

**Comment by ssatyal** [comment]
incremental progress! The good news is that now img_url show up in the response. Unfortunately, it returns as the same empty string variable.

```
if(result){
          var token = jwt.encode(user, JWT_SECRET);
          var img_url='';
          var thisUser = usersCollection.findOne({username: req.body.username}).then(function(){
            img_url = thisUser.img_url;
          })
          return res.json({img_url: img_url, token: token});
        } else {
          return res.status(400).send();
        }
```

It's probably still an asynch issue related to findOne?

**Comment by RobertAKARobin** [comment]
Yep, still an async issue. There's nothing saying `res.json` should wait until `.findOne` is done.
