### ISSUE TITLE
Error with deployed version

### ISSUE THREAD

**Issue by CamLatimer** [ga-wdi-exercises/project4#211]
My site works fine locally, and it worked fine when I first deployed it this morning. But deployed now, I get this error: net::ERR_CONNECTION_CLOSED.  

What does that error mean? Haven't been able to figure this one out.  I changed a bunch of things regarding the url for my server and database connections.  Still haven't got it working.  Any thoughts?

Also, here is my site url: https://glacial-savannah-86703.herokuapp.com/#/ref

When a user hits the save button after entering text into the box, that text should be saved to the database and the site redirected to another page.  But when I do that on the deployed version, I get no changes.

**Comment by RobertAKARobin** [comment]
Hm. It seems to be working for me... Can you show a screenshot with the error?

**Comment by CamLatimer** [comment]
Thanks for taking a look at the issue.  I actually got it working and forgot to check back in.  Sorry about that.

**Comment by RobertAKARobin** [comment]
Mazel tov!

**Comment by CamLatimer** [comment]
@RobertAKARobin Thanks for taking a look at the issue. I actually got it working and forgot to check back in. Sorry about that.
