### ISSUE TITLE
Suddenly Rails throwing sass error 

### ISSUE THREAD

**Issue by iamanissa** [ga-wdi-exercises/project4#212]
error: Invalid CSS after "}": expected "}", was ""
repo: https://github.com/SuperJones/project2/tree/styling

I looked it up and everyone keeps saying upgrade SASS version or `use gem 'sass-rails', '~> 5.0'`
but I'm already using 5.0 and I've tried updating it twice. 
Because I'm using rails if there is one css/sass issue then the whole thing "break" and I get the red screen.

Going to keep googling, but so far, no so good.

**Comment by iamanissa** [comment]
I did `bundle show sass-rails` and got 

```
/home/infinity/.rvm/gems/ruby-2.2.3/gems/sass-rails-5.0.4
```

**Comment by RobertAKARobin** [comment]
You're missing a `}` after this line:

https://github.com/SuperJones/project2/blob/styling/app/assets/stylesheets/custom.scss#L195

**Comment by iamanissa** [comment]
Are you kidding me!!?? Ugh, I started deleting things, and checking my gemfile and been googling for the past hour!
Sigh
Thank you

**Comment by RobertAKARobin** [comment]
It said the error was in one of the last few lines, so I just started there and kept going up.

**Comment by iamanissa** [comment]
I started by googling the error and was led astray.
