### ISSUE TITLE
Want to change default sign in error message

### ISSUE THREAD

**Issue by maureenv** [ga-wdi-exercises/project4#213]
Github repo: https://github.com/maureenv/cheatss 
Heroku: https://cheatss.herokuapp.com/

I spent all night yesterday trying to change the default error message on my login/register page. Currently, if there is an error when I log in (username/password doesn't match) it takes me to a white page that says bad request (image attached). Is there anyway for me to send the user an html page with the error message so it's not a scary white page? 

Thank you
![screen shot 2016-04-29 at 10 00 13 am](https://cloud.githubusercontent.com/assets/16403532/14918370/8703fa48-0df1-11e6-91c1-48cba57ed777.png)

**Comment by RobertAKARobin** [comment]
Check out this `failureRedirect` thing:

https://github.com/jaredhanson/passport-local#authenticate-requests
