### ISSUE TITLE
api calls one-to-many not working correctly

### ISSUE THREAD

**Issue by Crunchwrap78** [ga-wdi-exercises/project4#214]
I originally had an initial fix to the problem until I realized I wasn't using data-ng-model in the inptus and then when I added it, it broke it completely. In general I just need/want to get POST to work for trips, but I'm having a hard time with the one to many relation when. 

link to repo https://github.com/Crunchwrap78/TeslaTravels

the trip api calls are in

```
./controllers/trips.js

```

**Comment by joe-gz** [comment]
are you getting an error when you try to post?

**Comment by Crunchwrap78** [comment]
yes

**Comment by joe-gz** [comment]
whats the error?

**Comment by Crunchwrap78** [comment]
<img width="619" alt="screen shot 2016-04-29 at 10 31 30 am" src="https://cloud.githubusercontent.com/assets/14954458/14919183/9d1051c0-0df5-11e6-8795-132bb455a1dc.png">

**Comment by Crunchwrap78** [comment]
it's skipping the id

**Comment by Crunchwrap78** [comment]
we were able to fix the get request for for the factory, but post is still failing

**Comment by joe-gz** [comment]
can you push your most recent code up?

**Comment by Crunchwrap78** [comment]
sure give me a sec.

**Comment by Crunchwrap78** [comment]
all pushed and merge  https://github.com/Crunchwrap78/TeslaTravels

**Comment by RobertAKARobin** [comment]
You don't have a POST route defined in your `index.js`. You need `app.post("/api/cars/trips")` or something similar.
