### ISSUE TITLE
Can't get my mix show page to work. 

### ISSUE THREAD

**Issue by LaFrish** [ga-wdi-exercises/project4#216]
https://github.com/LaFrish/beachhouse

**Comment by RobertAKARobin** [comment]
What's not working?

**Comment by LaFrish** [comment]
<img width="1440" alt="screen shot 2016-04-29 at 10 41 24 am" src="https://cloud.githubusercontent.com/assets/15219375/14919483/1512986c-0df7-11e6-82ff-983cf62b55e8.png">

**Comment by LaFrish** [comment]
<img width="1219" alt="screen shot 2016-04-29 at 10 43 27 am" src="https://cloud.githubusercontent.com/assets/15219375/14919552/5e2fdafa-0df7-11e6-9187-4b5242b62458.png">
this is for the moscow mule

**Comment by RobertAKARobin** [comment]
Can you push your most recent code up to Github?

**Comment by LaFrish** [comment]
Done

**Comment by RobertAKARobin** [comment]
The big issue here is that you're using two mutually-exclusive methods of injecting dependencies:

``` js
  .controller("MixShowCtrl", [
    "Mixologist",
    "$stateParams",
    MixShowCtrlFunction
  ])
```

...and:

``` js
.controller("MixShowCtrl", MixShowCtrlFunction)
// ...
MixShowCtrlFunction.$inject = ["Mixologist", "$stateParams"];
function MixShowCtrlFunction(Mixologist, $stateParams){
```

Use either the first way or the `$inject` way. Personally, I prefer the `$inject` way.

After that, just change `MixologistFactory.get($stateParams)` to `Mixologist.get($stateParams)` (to match the `Mixologist` above) and you should be good!

**Comment by LaFrish** [comment]
<img width="1440" alt="screen shot 2016-04-29 at 11 09 53 am" src="https://cloud.githubusercontent.com/assets/15219375/14920356/001c936e-0dfb-11e6-9259-41c37c8b0088.png">

**Comment by LaFrish** [comment]
It never ends....

**Comment by LaFrish** [comment]
<img width="1414" alt="screen shot 2016-04-29 at 11 15 36 am" src="https://cloud.githubusercontent.com/assets/15219375/14920452/bb358386-0dfb-11e6-8b1c-a8ca7a41a235.png">

now my index page won't list the drinks....

**Comment by jshawl** [comment]
@LaFrish llooks like `Mixologist` is undefined on line 169 of app.js

**Comment by RobertAKARobin** [comment]
Make sure that when you're injecting dependencies everything exactly matches when you're calling the function. You have:

``` js
  .controller("MixShowCtrl", [
    "Mixologist",
    "$stateParams",
    // "$window",
    MixShowCtrlFunction
  ])
```

and:

``` js
function MixShowCtrlFunction($stateParams, Mixologist, $state){
```

**Comment by LaFrish** [comment]
I made the corrections and still am getting: 
<img width="1136" alt="screen shot 2016-04-29 at 12 00 03 pm" src="https://cloud.githubusercontent.com/assets/15219375/14921789/ff050a2c-0e01-11e6-85bc-be6ae4b36bfd.png">

**Comment by RobertAKARobin** [comment]
Push up your changes, please.

**Comment by LaFrish** [comment]
Done

**Comment by RobertAKARobin** [comment]
They're still not in the same order.
