### ISSUE TITLE
How do I prevent users from putting spaces in their username and password?

### ISSUE THREAD

**Issue by maureenv** [ga-wdi-exercises/project4#217]
Github repo: https://github.com/maureenv/cheatss
Heroku: https://cheatss.herokuapp.com/

I want to prevent users from being able to add whitespace in their username and password so I added this into my code on line 240 in index.js 

``` js
  req.body.username = req.body.username.trim();
```

but users are still able to add whitespace which crashes my app on Heroku. Is there another way to fix this issue?

Thank you

**Comment by RobertAKARobin** [comment]
You'll need RegEx!

``` js
req.body.username = req.body.username.replace(/\s/g, "");
```

**Comment by maureenv** [comment]
Hey Robin, thanks for the advice. I tried adding in RegEx but my login form still accepts the empty spaces and then crashes. Am I putting these lines of code in the wrong place? Thank you

`````` js
app.post('/register', function(req, res, next) {
    Account.register(new Account({ username : req.body.username }), req.body.password, function(err, account) {
      req.body.username = req.body.username.replace(/\s/g, ""); // prevent spaces
      req.body.password = req.body.password.replace(/\s/g, ""); //prevent spaces
      req.checkBody("username", "A username must be entered.").notEmpty();
      req.checkBody("password", "A password must be entered.").notEmpty();
      // req.check('username', 'This username is already taken').isUsernameAvailable();
      var errors = req.validationErrors();
      if (errors) {
        Tutorial.find().sort({title:1}).then(function(tutorials){
          res.render('register', {errors: errors, tutorials: tutorials}) // this will render tutorials in nav bar and any errors that may occur
        })
        return;
        /////// end code for form validator
      }
      if (err) {
          return res.render('register', { account : account });
      }
      passport.authenticate('local')(req, res, function () {
          res.redirect('/');
      });
    });
});
```js
``````

**Comment by RobertAKARobin** [comment]
Huh. That's weird. Looks fine to me.

**Comment by RobertAKARobin** [comment]
I'm afraid I don't know why it's not working. I'd suggest posting to StackOverflow, maybe? But remember that until v1.0 of your app is complete, just assume your users will do everything right.

Also, as a temporary fix you could add in some front-end Javascript that strips the spaces.

**Comment by mattscilipoti** [comment]
Weren't you using an input validation library?  This seems like an excellent place to use it.
