### ISSUE TITLE
Loop through each video and auto play with next/prev. buttons

### ISSUE THREAD

**Issue by kairajohnson** [ga-wdi-exercises/project4#218]
I have been able to pull the video urls from my json but haven't accomplished it doing it one at a time. I've tried a forEach but ran into the same problem. I would like to loop through each video link to autoplay one after the other and next/prev buttons.

here is my code and my repo
https://github.com/kairajohnson/gentrification.git

``` js
function homeIndexCtrl(Contributor){
    var vm = this;
    Contributor.query(function(contributors){
      for (var i = 0; i < contributors.length; i ++){
      var video_url   = contributors[i].video_url
      vm.contributors = contributors;
      vm.youTubeURL=  video_url;
      vm.youTubeShareURL = "";
      vm.youTubeEmbededURL = "";
      vm.vimeoURL = "";
      console.log(video_url)
      }
    })
  };
```

**Comment by RobertAKARobin** [comment]
Take advantage of Angular's `ng-repeat` in your HTML. This isn't something you should be doing in your JS file.

For example:

``` js
function ctrl(Contributor){
  var vm = this;
  vm.contributors = Contributor.query();
}
```

``` html
<div data-ng-repeat="contributor in homeVM.contributors">
  {{contributor.video_url}}
</div>
```
