### ISSUE TITLE
Getting error "can't set header after they are sent"

### ISSUE THREAD

**Issue by maureenv** [ga-wdi-exercises/project4#219]
I was trying to fix my whitespace issue with javascript and it is fixed now but I realized that now I can no longer log into my app. Even if I go to old commits before I tried to fix the whitespace I still get the same error message that I've attached below. I think it's really weird that this error message exists even in old commits that didn't have this issue. How could I possibly fix this? 
![screen shot 2016-04-29 at 1 27 19 pm](https://cloud.githubusercontent.com/assets/16403532/14924063/98bf0cce-0e0e-11e6-8828-7f349b6e83fe.png)

My github repo is https://github.com/maureenv/cheatss

Thank you

**Comment by maureenv** [comment]
Never mind the error message disappears if I go back far enough

**Comment by RobertAKARobin** [comment]
Cool! Uh, I'm unsure whether or not this is resolved?
