### ISSUE TITLE
ng-repeat and accessing items from a json response

### ISSUE THREAD

**Issue by msteffan** [ga-wdi-exercises/project4#22]
I am trying to use ng-repeat in one of my views but when I instantiate it, it doesn't display anything in the browser, and I'm not sure if it's because I'm not accessing my object properly.

the response that comes from the server is:

```
[ { id: 1,
    name: 'melissa',
    profession: 'writer',
    location: 'dc',
    userId: 2,
    createdAt: Tue Sep 15 2015 19:41:52 GMT-0400 (EDT),
    updatedAt: Tue Sep 15 2015 19:41:52 GMT-0400 (EDT) },
  { id: 2,
    name: 'pat',
    profession: 'designer',
    location: 'nyc',
    userId: 2,
    createdAt: Tue Sep 15 2015 20:02:32 GMT-0400 (EDT),
    updatedAt: Tue Sep 15 2015 20:02:32 GMT-0400 (EDT) } ]
```

I can't see what it exactly is in pure JSON in the browser (because I can't make a get request to the URL without passing a user id) but this is what logs in the terminal when I `console.log(sources)` before sending it with `res.json(sources)`.

The angular controller code is: 

```
  sourceControllers.controller('sourcesController', ['Source', '$http', function(Source, $http) {
      this.sources =  $http.get("/currentUser").then(function(response){
           Source.query({userId: response.data}, function(sources){
               return sources
           });
      });
  }]);
```

I'm not sure if that ^^ is the right way to query the database to return an array of sources, but basically I have to make the http get request first so angular can know my current user, and then pass that to the `Source.query()` params.

anyway, finally, In my view, I'm trying to use ng-repeat like this (for now I'd just be happy to print out the source name):

```
<div class="honeycombs" id="list" ng-repeat="source in sourceCtrl.sources">
        <div>{{source.name}}</div>
</div>
```

**Comment by RobertAKARobin** [comment]
Cool!

This is because you can only `return` out of one function. If you have a nested function, and your return is in the inner function, a `return` inside it won't stop the outer function.

Instead, try this:

``` js
  sourceControllers.controller('sourcesController', ['Source', '$http', function(Source, $http) {
      var self = this;
      self.sources = {};
      $http.get("/currentUser").then(function(response){
           Source.query({userId: response.data}, function(sources){
               self.sources = sources;
           });
      });
  }]);
```

When that `.query` completes, `sourceCtrl.sources` should be automatically updated, and the individual `{{source.name}}` with it.

**Comment by msteffan** [comment]
uggggghhhhh *shakes fist at JavaScript *

Thanks, Robin. It worked perfectly.
