### ISSUE TITLE
You tube 

### ISSUE THREAD

**Issue by hh747hh** [ga-wdi-exercises/project4#220]
Good morning!

 I am still having an issue with deploying to heroku. Now I am getting this error about youtube embed and not working on the locahost as well... here is my code. Do you have any idea?

```
on my main index page

_<script src="https://www.youtube.com/iframe_api"></script>
  <script src="https://cdn.jsdelivr.net/angular.youtube-embed/0.2.3/ng-youtube-embed.min.js"></script>
  <script src="/js/app.js"></script>
  <base href="/"></base>
```

![screen shot 2016-05-07 at 5 49 49 am](https://cloud.githubusercontent.com/assets/16959988/15113771/49b3f1c2-15c4-11e6-8411-68135738b7e1.png)

**Comment by tylercrosse** [comment]
Hopefully this was resolved, I'm closing because it's super old
