### ISSUE TITLE
Heroku issue

### ISSUE THREAD

**Issue by LNewsome** [ga-wdi-exercises/project4#221]
Hi!
I'm having issues (similar to Yun) when trying to deploy my app to heroku. My error says I'm not connect to my server and I see That I'm haveing problems connecting to mongodb. 
Do you have any idea on what could be wrong? I looked at my nodemon but I don't see any errors.

**Comment by RobertAKARobin** [comment]
Can you give us more specifics about what error you're getting? You're not giving us much to go on.

**Comment by RobertAKARobin** [comment]
Can you share your code?

**Comment by LNewsome** [comment]
Sorry! here's my repo :https://github.com/LNewsome/quietly-loud

**Comment by LNewsome** [comment]
The only error I'm getting is:
![screen shot 2016-05-09 at 3 35 08 pm](https://cloud.githubusercontent.com/assets/13922405/15125593/a977ca48-15fb-11e6-8334-9bad5be3836e.png)

**Comment by RobertAKARobin** [comment]
Found it! Take a look here: https://github.com/ga-wdi-lessons/deploy-MEAN-app#setting-the-server-10-mins

**Comment by LNewsome** [comment]
I've changed  the lines but I'm still getting a similar message
![screen shot 2016-05-09 at 3 54 41 pm](https://cloud.githubusercontent.com/assets/13922405/15126141/9ae52770-15fe-11e6-94e2-368c5b560a9b.png)
![screen shot 2016-05-09 at 3 54 19 pm](https://cloud.githubusercontent.com/assets/13922405/15126145/9e199598-15fe-11e6-89b0-f739d8b56826.png)

![screen shot 2016-05-09 at 3 52 44 pm](https://cloud.githubusercontent.com/assets/13922405/15126153/b1df1526-15fe-11e6-98c0-dd0f1c51937f.png)

![screen shot 2016-05-09 at 3 53 01 pm](https://cloud.githubusercontent.com/assets/13922405/15126156/b5c365a2-15fe-11e6-931e-c0132d21c2cb.png)

**Comment by RobertAKARobin** [comment]
That was hard to find! You're missing just one line:

https://github.com/ga-wdi-exercises/whenpresident/blob/master/index.js#L34

**Comment by LNewsome** [comment]
Sorry, I forgot to push up the changes I made. That was already fixed. I got some new errors but no connection.

**Comment by RobertAKARobin** [comment]
That line still isn't in your code.

**Comment by RobertAKARobin** [comment]
After adding that line and setting the Mongolab environment variable, it's working fine for me: https://thawing-plateau-16215.herokuapp.com/personalities

**Comment by LNewsome** [comment]
Okay. I see where I got mixed up. I just changed it. Thanks!

**Comment by LNewsome** [comment]
I changed the code and set the Mongolab environment but I'm still unable to deploy it. I'm also getting a weird error stating my connection.js line 21 is:
![screen shot 2016-05-10 at 10 00 10 am](https://cloud.githubusercontent.com/assets/13922405/15149074/2378c67c-1696-11e6-80f2-20785d0669bd.png)
I checked my code and it looks right.
![screen shot 2016-05-10 at 10 01 49 am](https://cloud.githubusercontent.com/assets/13922405/15149092/3f75d6b2-1696-11e6-8ca7-cf8342c4fbea.png)
I've done  heroku run rake db:migrate, heroku run rake db:seed, and then git push heroku, and heroku open. 
Any thoughts on this?

**Comment by LNewsome** [comment]
I updated my app.lestion and I got an error that states this:
![screen shot 2016-05-10 at 11 30 22 am](https://cloud.githubusercontent.com/assets/13922405/15152339/dffe3884-16a2-11e6-821c-ac6b91e71482.png)
I'm not sure what I am doing wrong.
