### ISSUE TITLE
Help with moving React components

### ISSUE THREAD

**Issue by 7ruth** [ga-wdi-exercises/project4#223]
My repo:  https://github.com/7ruth/google-maps-react

I need help splitting up a contents class, into a header and map components that communicate with each other.

**Comment by nolds9** [comment]
@7ruth is there someplace in particular you have one big component you are looking to split up, otherwise you could do something like this, where you have one component that renders multiple nested components:

```
var App = React.createClass({
  render: function () {
    return (
       <div>
         <Header />
         <Map />
       <div>
   )
 }
```
