### ISSUE TITLE
Help with undefined Rails method 'each'.

### ISSUE THREAD

**Issue by mvaden** [ga-wdi-exercises/project4#224]
I'm trying to use .each method to get my classmates to appear in the view. Rails says that .each is an undefined method:

When I load 'localhost:3000/classmates/', I get this error from Rails:
![screen shot 2016-06-01 at 11 23 59 am](https://cloud.githubusercontent.com/assets/17731291/15715357/25b4f66a-27ec-11e6-9aec-40a7de55ae39.png)

![screen shot 2016-06-01 at 11 31 09 am](https://cloud.githubusercontent.com/assets/17731291/15715532/c6b9e994-27ec-11e6-965a-3795e2a86c6c.png)
![screen shot 2016-06-01 at 11 26 21 am](https://cloud.githubusercontent.com/assets/17731291/15715358/25c1a630-27ec-11e6-984f-899f2b2d7525.png)

**Comment by mvaden** [comment]
Issue resolved: I pluralized the instance variable @classmate, when it should have been singular.

**Comment by tylercrosse** [comment]
Glad you got it figured out 👍
