### ISSUE TITLE
Issue connecting angular and d3

### ISSUE THREAD

**Issue by lknapalolo** [ga-wdi-exercises/project4#225]
I created a factory to inject the d3 code base into an angular directive.. but I'm getting this error:

![screen shot 2016-06-01 at 12 21 26 pm](https://cloud.githubusercontent.com/assets/17017604/15717146/a5d61f2a-27f3-11e6-8247-8b9517678801.png)

This is the tutorial I'm working from:
https://blog.logentries.com/2014/07/combine-d3-with-angularjs/

Any feedback on this issue or even just the best way to combine angular and d3 (if I should attempt this at all...) would be greatly appreciated! Thanks!

**Comment by tylercrosse** [comment]
Does your factory have a return statement?

**Comment by tylercrosse** [comment]
Closing due to new errors, feel free to create a new issue or reopen with updates on what new problem is.
