### ISSUE TITLE
rake db:migrate results in abort error

### ISSUE THREAD

**Issue by lelandjordon** [ga-wdi-exercises/project4#226]
Trying to add a relation of pets belonging to shelters.

Error given in Terminal:

```
== 20160601230906 AddPetToShelters: migrated (0.0549s) ========================

== 20160601231035 AddShelterIdToPets: migrating ===============================
-- add_column(:pets, :shelter_id, :integer)
rake aborted!
StandardError: An error has occurred, this and all later migrations canceled:

PG::DuplicateColumn: ERROR:  column "shelter_id" of relation "pets" already exists
: ALTER TABLE "pets" ADD "shelter_id" integer
```

Repo:
https://github.com/lelandjordon/pet-seeker-api

**Comment by tylercrosse** [comment]
Try `rake db:reset` to rerun all migrations from scratch, my guess is you edited a migration after it had it had been migrated.

**Comment by lelandjordon** [comment]
Turned out it was a migration conflict -- my third migration tried to address a column which was due to be added by my fourth migration.

**Comment by lelandjordon** [comment]
With Tyler's help, deleted third, fourth, and fifth migration files and started fresh.  Need to work on how to seed data next.
