### ISSUE TITLE
Ghost Comments

### ISSUE THREAD

**Issue by JoshNezi** [ga-wdi-exercises/project4#229]
Hello, I'm having trouble displaying my comments. I don't get an error when I submit, but I'm thrown an error when I try to get the comments to display. 

![screen shot 2016-06-02 at 3 02 25 pm](https://cloud.githubusercontent.com/assets/8755620/15757314/0b843962-28d3-11e6-9734-e88d5d65bb54.png)

git@github.com:JoshNezi/Lingua_Life-.git

**Comment by tylercrosse** [comment]
I think you need to add a column to comments something like this:

```
$ bin/rails generate migration AddUserRefToProducts user:references
```

generates

``` rb
class AddUserRefToProducts < ActiveRecord::Migration[5.0]
  def change
    add_reference :products, :user, index: true, foreign_key: true
  end
end
```
