### ISSUE TITLE
No 'Access-Control-Allow-Origin'

### ISSUE THREAD

**Issue by Ryan-321** [ga-wdi-exercises/project4#23]
Right now, I have two separate apps, rails on the backend and angular on the front.  I have both set up and am trying to pull from rails, but I keep getting this error.  I tried googling it and not am not sure if am going down the wrong path.  Does my rails need to be deployed somewhere???  

error:
XMLHttpRequest cannot load http://localhost:3000/subjects. No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'http://localhost:8000' is therefore not allowed access.

**Comment by RobertAKARobin** [comment]
What URL are you using to access your Angular app? If it's `file:///whatever`, try running `python -m SimpleHTTPServer` and accessing it via `localhost:8000` instead.

**Comment by RobertAKARobin** [comment]
Better yet, merge your apps into one! Have Rails serve the `index.html` that contains all the `<script>` tags for your Angular app.

**Comment by Ryan-321** [comment]
Took a look at the mini-lesson and think I get it.  Can I still use bower to install all the angular stuff I want though.  e.g. ngResource, NgRoute

That's what was tripping me up before.

**Comment by RobertAKARobin** [comment]
Sure, although it might not be a bad idea to use a CDN instead. Fewer files to wrangle; just a bunch of `script` tags: http://cdnjs.com/libraries/angular.js/

**Comment by Ryan-321** [comment]
Was just looking at this, going to go that route.  Let you guys know for any speed bumps, thanks Robin.

**Comment by RobertAKARobin** [comment]
:+1:
