### ISSUE TITLE
App refused access by API

### ISSUE THREAD

**Issue by lelandjordon** [ga-wdi-exercises/project4#230]
Got this error in the browser console:
`XMLHttpRequest cannot load http://localhost:3000/shelters. No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'http://localhost:8080' is therefore not allowed access.`

API loads JSON at `http://localhost:3000/shelters` and `http://localhost:3000/pets`

Hoping to show a second shelter (once I add pet data to seed a second one) and be able to first click a shelter then see the pets in each.
https://github.com/lelandjordon/pet-seeker
https://github.com/lelandjordon/pet-seeker-api

**Comment by tylercrosse** [comment]
Looks like you need rack-cors
https://github.com/cyu/rack-cors

**Comment by lelandjordon** [comment]
Ah!  Forgot all about it.  Necessary when running locally?

**Comment by lelandjordon** [comment]
I'll probably also change my MVP to just being able to see pets, as if the home page was the shelter's individual page.  Not sure if I'm setting up the pet.factory.js correctly, though.

**Comment by lelandjordon** [comment]
rack-cors was it.  Onward to new errors.
