### ISSUE TITLE
CSRF error in Terminal log

### ISSUE THREAD

**Issue by lelandjordon** [ga-wdi-exercises/project4#231]
When trying to create a new pet entry, the browser console gives `POST http://localhost:3000/pets 422 (Unprocessable Entity)` although the form returns an appropriately populated object.

The API server log gives this error:
`Started POST "/pets" for ::1 at 2016-06-03 11:01:15 -0400
Processing by PetsController#create as HTML
  Parameters: {"name"=>"Steve", "species"=>"Insect", "breed"=>"Grasshopper", "age"=>"4", "photo_url"=>"#", "pet"=>{"species"=>"Insect", "breed"=>"Grasshopper", "age"=>"4", "name"=>"Steve", "photo_url"=>"#"}}
Can't verify CSRF token authenticity
Completed 422 Unprocessable Entity in 1ms (ActiveRecord: 0.0ms)`

Front end: https://github.com/lelandjordon/pet-seeker
Rails API: https://github.com/lelandjordon/pet-seeker-api

**Comment by jshawl** [comment]
> Can't verify CSRF token authenticity

you need to POST the authenticity token with the request, or disable checkin in application controller

**Comment by lelandjordon** [comment]
Ah - should I use `:null_session` instead of `:exception` here?
```class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

```
Or would doing this just do the check differently and still block the request?
```

**Comment by jshawl** [comment]
im not sure - what happens if you try it out?

**Comment by lelandjordon** [comment]
I think it worked.  Slightly different errors in log, but it put a new pet into the database, confirmed by checking via rails console.

I think I need to change what's permitted:
`Started POST "/pets" for ::1 at 2016-06-03 11:29:01 -0400
Processing by PetsController#create as HTML
  Parameters: {"id"=>3, "species"=>"Horse", "breed"=>"Appaloosa", "age"=>6, "name"=>"Dave", "photo_url"=>"#", "created_at"=>"2016-06-03T15:28:47.421Z", "updated_at"=>"2016-06-03T15:28:47.421Z", "shelter_id"=>nil, "pet"=>{"id"=>3, "species"=>"Horse", "breed"=>"Appaloosa", "age"=>6, "name"=>"Dave", "photo_url"=>"#", "created_at"=>"2016-06-03T15:28:47.421Z", "updated_at"=>"2016-06-03T15:28:47.421Z", "shelter_id"=>nil}}
Can't verify CSRF token authenticity
Unpermitted parameters: id, created_at, updated_at, shelter_id
Unpermitted parameters: id, created_at, updated_at, shelter_id
   (0.2ms)  BEGIN
  SQL (0.4ms)  INSERT INTO "pets" ("name", "age", "breed", "species", "photo_url", "created_at", "updated_at") VALUES ($1, $2, $3, $4, $5, $6, $7) RETURNING "id"  [["name", "Dave"], ["age", 6], ["breed", "Appaloosa"], ["species", "Horse"], ["photo_url", "#"], ["created_at", "2016-06-03 15:29:01.622159"], ["updated_at", "2016-06-03 15:29:01.622159"]]
   (1.4ms)  COMMIT
Completed 201 Created in 6ms (Views: 0.1ms | ActiveRecord: 2.0ms)`

**Comment by jshawl** [comment]
👍 or not POST the id and created_at, etc...

**Comment by lelandjordon** [comment]
I think the id, created_at, etc, are all automatically coming along for the ride with the scope I've got going in the factory.
