### ISSUE TITLE
Which websockets DB

### ISSUE THREAD

**Issue by wombatdev** [ga-wdi-exercises/project4#233]
Kind of a feeling out question--if I'm planning to use web sockets, would the instructors recommend using Firebase or would a MEAN stack be perfectly OK?

**Comment by jshawl** [comment]
recommend mean stack! might run into issues w/ deploying to heroku, but we have resources and it is totally doable!

**Comment by wombatdev** [comment]
Awesome, that's what I wanted to do.

**Comment by wombatdev** [comment]
Changing tack, if I wanted to use geolocation if some way, would MEAN still be OK? I've heard Postgres is best for storing geo waypoints.

**Comment by nolds9** [comment]
mongo is great for working with geo data https://docs.mongodb.com/manual/applications/geospatial-indexes/
