### ISSUE TITLE
Joined table

### ISSUE THREAD

**Issue by kristinmaripasive** [ga-wdi-exercises/project4#236]
I have three models set up: Artists, Musicians, Collabs. I want my artists and musicians to have a many-to-many relationship with collabs as their joined table. I'm testing out my seed data, but it seems like my collabs aren't showing up when my collab.rb file is this:

```
class Collab < ApplicationRecord
  belongs_to :artist
  belongs_to :musician
end
```

It only shows up on the browser when I don't put anything in there. I'm assuming it's because the collabs table is now dependent on the artists & musicians? I'm quite confused. How can I make it in a way that it still shows up on the browser when I go to localhost:3000/collabs, but having it as a joined table?

**Comment by amaseda** [comment]
Your Collab model definition looks right. Perhaps the problem is elsewhere.

Anything missing / look strange in any of the following...
* `routes.rb`
* `Artist` and `Musician` model definitions
* `index` in your Collabs controller
* `seeds.rb`

**Comment by amaseda** [comment]
Shouldn't your model be inheriting from ActiveRecord?

**Comment by kristinmaripasive** [comment]
Oh yeah I changed it to ActiveRecord, but my seeds for collabs still aren't showing up. Only artists and musicians are. I tried checking the table contents in the database but its empty, so it's really not injecting any data into my db. Would it be something to do with my routes.rb?

```
Rails.application.routes.draw do

  resources :artists
  resources :musicians
  resources :collabs

end
```

**Comment by amaseda** [comment]
`routes.rb` looks fine. What does your index action in your Collabs controller look like?

**Comment by kristinmaripasive** [comment]
```
  def index
    @collabs = Collab.all
  end
```

My collab seeds only show up really when I take out the association in my collab.rb

**Comment by amaseda** [comment]
Hm, how are you creating collabs in your seed file?

Are you able to test using ActiveRecord in the Rails console and/or `psql` in the command line to see if collabs are actually being created in the database?

**Comment by kristinmaripasive** [comment]
This is how my seeds are looking:

```
jessica = Artist.create({name: 'Jessica', description: 'Digital art is my passion.', photo_url:''})

ben = Musician.create({name: 'Ben', description: 'I write alternative rock.', photo_url:''})

cloud = Collab.create({title: 'The Cloud', description: "This was created for Ben's new album. Jessica created this piece with illustrator.", photo_url: ''})
```

Yeah I tried checking in `psql` but it's empty in there. Only Jessica and Ben are showing up in psql.

**Comment by amaseda** [comment]
What happens when you try to create that same Collab via the Rails console? Do you get any errors?

**Comment by kristinmaripasive** [comment]
So I tried creating from the rails console. I tried injecting to artists and musicians, they work perfectly fine. For collabs, though, it is saying ROLLBACK whenever I tried injecting a seed.

**Comment by amaseda** [comment]
Can you push up your code and send a link to your repo? Thx

**Comment by jshawl** [comment]
also ! in active record methods, like `.create!`

**Comment by kristinmaripasive** [comment]
Pushed it up: https://github.com/kristinmaripasive/maestropiece

I tried `!` on `.create` and now it's telling me:
`ActiveRecord::RecordInvalid: Validation failed: Artist must exist, Musician must exist`

but they do exist?

**Comment by nolds9** [comment]
looks like your `collabs` table is missing the foreign keys for `artist` and `musician`

**Comment by kristinmaripasive** [comment]
ohhh, it's showing up now... but I had to hardcode an artist_id and musician_id in there. 

```
cloud = Collab.create({title: 'The Cloud', description: "This was created for Ben's new album. Jessica created this piece with illustrator.", photo_url: '', artist_id: '1', musician_id: '1'})
```

So my question would be, when creating a collab, how would I enter a specific artist and musician if I don't know their IDs in the database?

**Comment by amaseda** [comment]
You could do something like...

``` rb
# define artist and musician when creating
jessica = Artist.create({name: 'Jessica', description: 'Digital art is my passion.', photo_url:''})
ben = Musician.create({name: 'Ben', description: 'I write alternative rock.', photo_url:''})

# or if you're not creating but want to look an existing one up by name
bob = Artist.find_by(name: "Bob")

# reference artist and musician when creating collab
cloud = Collab.create({title: 'The Cloud', description: "This was created for Ben's new album. Jessica created this piece with illustrator.", photo_url: '', artist: bob, musician: ben})
```

**Comment by kristinmaripasive** [comment]
Oh sorry I meant to ask as a user(front-end)... cause whenever I try to create a collab on the browser, it's not allowing it since there has to be an artist and musician. How would I get around actually hardcoding an artist and musician from the back-end?

**Comment by kristinmaripasive** [comment]
![screen shot 2016-08-08 at 11 15 32 am](https://cloud.githubusercontent.com/assets/19437889/17484775/8909603c-5d59-11e6-9a26-2e2dd75c454c.png)

**Comment by nolds9** [comment]
There is no easy way to do this automatically from the back end...One way you could work around this is by having the ability to select an artist and musicians from a pre populated select list

**Comment by nolds9** [comment]
http://guides.rubyonrails.org/form_helpers.html#the-select-and-option-tags see section 3.3

**Comment by kristinmaripasive** [comment]
Perfect!!! Really helpful link... Thank you!

**Comment by amaseda** [comment]
Did you end up getting this to work? If so, please close the issue. If not, let us know how it's going!

**Comment by kristinmaripasive** [comment]
Ok so I have populated my list with artists and musicians to select. I have checked the console if it is actually capturing the ID for each and it does. But still, whenever I try to create a collab, it somehow does not capture it for the created collab.

This is what I was trying to do in my collabs controller:

```
  def collab_params
      params.require(:collab).permit(:title, :description, :photo_url, :artist_id, :musician_id)
    end
```

I required the artist and musician IDs so I was hoping it captures those... I'm confused what I'm missing here...

https://github.com/kristinmaripasive/maestropiece

**Comment by kristinmaripasive** [comment]
![screen shot 2016-08-08 at 12 38 01 pm](https://cloud.githubusercontent.com/assets/19437889/17487933/0596c896-5d65-11e6-8193-b717478e54ed.png)

**Comment by amaseda** [comment]
Because you're hand-rolling the form in your view (i.e., not using a form helper), you need to specify that `musician_id` and `artist_id` are part of a `collab` object (which is what `collab_params` is expecting).

In your collab form, try replacing `name="artist_id"` with `name="collab[artist_id]"` and see if it works. Make sure to do the same with musician.

**Comment by kristinmaripasive** [comment]
It worked! Thanks!
