### ISSUE TITLE
Rails/db/foreign keys issues

### ISSUE THREAD

**Issue by kwg58** [ga-wdi-exercises/project4#237]
1.  I have a Team model and a Player model, Team has_many_players, Player belongs_to team.  When I print the players the team comes up as the number that is the foreign key to the record in the team  table.  How can I tell rails to print the team name rather than the number?  
2.  When I go to ../teams/2/players I get the index that is the list of ALL the players, not just the players for team 2.  Did I set up the routes wrong or is their something I need to do here?  
3.  I'm going to do a front end that has only a few views.  One would be a schedule page, with either the name of the teams and the date/time of the scheduled game or the game results for games in process or complete.  Drilling down from there you'd get either info about the scheduled game or a report on the completed/in process game.  The third would be a front end for entering game data as it occurs.  My plan is to do this with straight rails/html/js rather than React or Angular.   I realize that react components might be helpful here, but I think I've bitten off enough.  Any thoughts?

Thanks

**Comment by amaseda** [comment]
(1) What ActiveRecord query are you using to print out the players?

(2) What does the index action in your Players controller look like?

(3) You can start out with just Rails and get the application working the way you want it to. If you feel a need for a front-end framework / library down the line, consider it then. But use whatever technologies you think best suit your idea!

**Comment by kwg58** [comment]
Thanks, Adrian.  I'm a little slower than usual today.  Where would the ActiveRecord query you seek be?  

The index action in my players controller is: 

```
  def index
    @players = Player.all
  end
```

In my routes.rb I've specified 

```
  resources :teams do
    resources :players
  end
```

However, rake routes doesn't show anything for  ../Teams/n/Players.

**Comment by amaseda** [comment]
So if you want to get all the players that belong to a particular team, you'll need to indicate that in `def index`. You should be able to grab the team based on information in the URL.

**Comment by amaseda** [comment]
As for the nested URLs not appearing after `rake routes`, that's strange. What's the output of `rake routes`?

**Comment by kwg58** [comment]
Actually, there is a route....  

```
team_players GET    /teams/:team_id/players(.:format)          players#index
                 POST   /teams/:team_id/players(.:format)          players#create
 new_team_player GET    /teams/:team_id/players/new(.:format)      players#new
edit_team_player GET    /teams/:team_id/players/:id/edit(.:format) players#edit
     team_player GET    /teams/:team_id/players/:id(.:format)      players#show
                 PATCH  /teams/:team_id/players/:id(.:format)      players#update
                 PUT    /teams/:team_id/players/:id(.:format)      players#update
                 DELETE /teams/:team_id/players/:id(.:format)      players#destroy
```

But when I hit that route I get all the players, not just the players for that team.

**Comment by amaseda** [comment]
Ah okay, in that case fix `index` in your players controller in the way that I suggested earlier and you should be good! Let me know if you need help.

**Comment by kwg58** [comment]
I need help.  Instead of @player.all I need to specify a condition. I've been going through Garnet looking for an example and can't find one.

**Comment by amaseda** [comment]
Define your team first. Use `params` to pull the correct id from the URL.

After that you should be able to do something like `@players = @team.players` to get the players you need, assuming the team has been defined properly.

That should do it, although let me know if it's a different issue you're dealing with now.

**Comment by kwg58** [comment]
Got it.... 

```
@team = Team.find(params[:team_id])
```

I had the syntax wrong and was using :id rather than :team_id.  Stoopid. 

Thanks!

**Comment by jshawl** [comment]
👍
