### ISSUE TITLE
Rails Mailer and format.html

### ISSUE THREAD

**Issue by dcordz** [ga-wdi-exercises/project4#238]
Pretty sure the mailer's setup although I haven't received any test emails from it even after setting my gmail preferences to accepting less secure apps, any tips for that?

Also I'm working with logging in a user, and then redirecting to the user page with a flash message after user save and sending an email but I'm struggling with the options after format.html. Can you guide me on the syntax here?

Controller

```
respond_to do |format|
      if @user.save
        # Tell the UserMailer to send a welcome email after save
        UserMailer.welcome_email(@user).deliver_now

        format.html { log_in(@user) redirect_to(@user, notice: 'Welcome to Ishe, ready to get to work?') }
        format.json { render json: @user, status: :created, location: @user }
      else
        format.html { render action: 'new' }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
```

log_in session helper

```
def log_in(user)
    session[:user_id] = user.id
  end
```

**Comment by jshawl** [comment]
is it in your spam folder?

**Comment by dcordz** [comment]
yeah checked there and All Mail, no dice

**Comment by jshawl** [comment]
can you save the output of this to a variable? `UserMailer.welcome_email(@user).deliver_now` and look at its value with binding.pry?

**Comment by dcordz** [comment]
Yeah here's the output

```
#<Mail::Message:70353272964660, Multipart: true, Headers: <Date: Mon, 08 Aug 2016 09:50:38 -0400>,
<From: from@example.com>,
<To: dcordz2@gmail.com>,
<Message-ID: <57a88e2e99a51_1aed3ffc645311c83811a@Yovotome.local.mail>>,
<Subject: Welcome to My Awesome Site>,
<Mime-Version: 1.0>, <Content-Type: multipart/alternative; boundary="--==_mimepart_57a88e2e9709b_1aed3ffc645311c8380fc"; charset=UTF-8>,
<Content-Transfer-Encoding: 7bit>>
```

**Comment by dcordz** [comment]
There was one thing I was a little confused about in the mailer setup instructions from http://guides.rubyonrails.org/action_mailer_basics.html

What do I put into the username and password fields? My the name and pass for my computer?

```
config.action_mailer.delivery_method = :smtp
config.action_mailer.smtp_settings = {
  address:              'smtp.gmail.com',
  port:                 587,
  domain:               'example.com',
  user_name:            '<username>',
  password:             '<password>',
  authentication:       'plain',
  enable_starttls_auto: true  }
```

**Comment by jshawl** [comment]
the info for your gmail account

**Comment by jshawl** [comment]
please use a gem like figaro to keep those secret

**Comment by dcordz** [comment]
will do, tried the gmail credentials but no luck - follow up - I'm putting the config stuff in my development.rb file, should it be somewhere else?

**Comment by jshawl** [comment]
yes thing to google is figaro gem

**Comment by jshawl** [comment]
also sending email is a total pain! I use a service like sendgrid to interface with an api

**Comment by dcordz** [comment]
yeah it's a pain - ill check out sendgrid

**Comment by jshawl** [comment]
👍 closing for now feel free to open a new issue
