### ISSUE TITLE
jQuery click event not working on page load

### ISSUE THREAD

**Issue by wombatdev** [ga-wdi-exercises/project4#239]
I'm trying to delay my game start until the user clicks a div that just says "Start":

```
window.onload = function() {

var splash = $(".splash");
splash.on("click", function(){
    console.log("click");

<lots of game code>

splash.remove();
// End of jQuery click
});

// End of document on load call
}
```

But the click doesn't register anything. If I copy and paste my entire code file into the console, then it works correctly. It's like it's not loading otherwise. If I remove the click event, the game launches on page load, so it seems to be something with jQuery specifically.

**Comment by amaseda** [comment]
Hm, this looks fine to me. Can you push your code and link me to your repo?

**Comment by wombatdev** [comment]
Here's the code; it's all in `game.js`.
https://github.com/wombatdev/Zed-Defense

However, it looks like I should be doing this with Phaser itself, as opposed to using some random div. So this issue would end up being throwaway code most likely.

**Comment by wombatdev** [comment]
Yeah, I found a tutorial for adding game states in Phaser so you don't need to worry about this guy.

**Comment by wombatdev** [comment]
Can close.

**Comment by amaseda** [comment]
Roger that!
