### ISSUE TITLE
Foreign keys with non-standard names

### ISSUE THREAD

**Issue by kwg58** [ga-wdi-exercises/project4#240]
In my games model I have two fields, hometeam_id and awayteam_id.  These are set up as foreign keys to the team model, but I can't get them to display the team name.  

For foreign keys using the team_id , I'd use something like game.team.fullname to get the team name, but it doesn't recognize game.hometeam_id.fullname.  

The only things I can find via Google refer to setting up the foreign keys, but say nothing about using them (plus they're all several years and a couple versions of Rails old).  

Does anyone have any experience using non-standard foreign key names in Rails?

Thanks.

**Comment by jshawl** [comment]
shouldnt it be `game.hometeam.fullname` and not `game.hometeam_id.fullname`

**Comment by kwg58** [comment]
Neither work.  I get 'undefined method' either way.

**Comment by amaseda** [comment]
Because `hometeam` is not its own model, ActiveRecord does not give you a `.hometeam` method out of the box. You can, however, define that yourself using a model method on the Game model. It could look something like...

``` rb
# game.rb

def hometeam( hometeam_id )
  Team.find(hometeam_id)
end
```

> The method retrieves a team based on a game's `hometeam_id` value.

**Comment by kwg58** [comment]
Looks good.  How do I refer to it?  

```
game.hometeam.fullname
```

gets "invalid number of arguments"

```
game.hometeam(hometeam_id).fullname
```

gets "undefined local variable or method `hometeam_id'"

**Comment by jshawl** [comment]
try

``` rb
def hometeam()
  Team.find(self.hometeam_id)
end
```

**Comment by kwg58** [comment]
No joy.  

No matter how I call it

```
<td><%= game.hometeam(self.hometeam_id) %></td>
<td><%= game.hometeam(hometeam_id) %></td>
```

gets "undefined method `hometeam_id' "

If I use hometeam_id by itself 

```
<td><%= hometeam_id %></td>
```

it prints the correct number.

**Comment by jshawl** [comment]
what about <%= game.hometeam %>

**Comment by kwg58** [comment]
the home team function returns "wrong number of arguments "

**Comment by amaseda** [comment]
Can you push up your code and link to it? Thx

**Comment by jshawl** [comment]
try

``` rb
def hometeam()
  Team.find(self.hometeam_id)
end
```

and  <%= game.hometeam %>

**Comment by kwg58** [comment]
this is the correct branch: 
https://github.com/kwg58/hscore-api/tree/build-rails

**Comment by jshawl** [comment]
please try previous suggestion here https://github.com/kwg58/hscore-api/blob/9cb59835dc6a4e0465969520a1d12abc397e25bc/app/models/game.rb#L9-L11

**Comment by jshawl** [comment]
e.g. remove argument to method

**Comment by kwg58** [comment]
Same thing

game model:

```
def hometeam( hometeam_id )
    return Team.find(self.hometeam_id)
  end

  def awayteam( awayteam_id )
    return Team.find(self.awayteam_id)
  end
```

game view html:

```
      <td><%= game.hometeam %></td>
      <td><%= game.awayteam %></td>
```

going to http://http://localhost:3000/games produces:

```
Showing /Users/kevingolden/wdi/projects/Project4/hscore-api/app/views/games/index.html.erb where line #28 raised:

wrong number of arguments (given 0, expected 1)
```

and it points this line in the game model:

```
 def hometeam( hometeam_id )
```

?????????

**Comment by jshawl** [comment]
remove the word inbetween parentheses:

``` rb
def hometeam()
  Team.find(self.hometeam_id)
end

```

and

<%= game.hometeam %>

**Comment by kwg58** [comment]
GOT IT!

The first thing I got was the name of the hash containing the data.  When I changed the code to:

```
def hometeam()
    home = Team.find(self.hometeam_id)
    return home.fullname
  end
```

it gives me what I need. 

THANK YOU!

**Comment by amaseda** [comment]
Sounds like you're good to go. Closing!
