### ISSUE TITLE
model and migration

### ISSUE THREAD

**Issue by marasanders** [ga-wdi-exercises/project4#241]
A few issues - I ran user_auth_token before I created my data base - I got the following errors:
Installing devise_token_auth 0.1.38
Bundle complete! 17 Gemfile dependencies, 69 gems now installed.
Use `bundle show [gemname]` to see where a bundled gem is installed.
marasanders@Maras-MacBook-Air-2:~/wdi/projects/project-4/baking-minus-the-math  $ rails g devise_token_auth:install User auth
Running via Spring preloader in process 9289
      create  config/initializers/devise_token_auth.rb
      create  db/migrate/20160807232158_devise_token_auth_create_users.rb
/Users/marasanders/.rvm/gems/ruby-2.3.1/gems/activerecord-5.0.0/lib/active_record/connection_adapters/postgresql_adapter.rb:675:in `rescue in connect': FATAL:  database "baking-minus-the-math_development" does not exist (ActiveRecord::NoDatabaseError)

I thought if I create my databases I would just go back and try again soon..

I created my 1st model - no problem - I did not run a migration before creating my second model

and got the following error.....

marasanders@Maras-MacBook-Air-2:~/wdi/projects/project-4/baking-minus-the-math  $ rails g model Recipe title:string 'servings:decimal{5,2}' 'calories:decimal{7,2}''rating:decimal{4,2}' category:reference
/Users/marasanders/.rvm/gems/ruby-2.3.1/gems/activerecord-5.0.0/lib/active_record/connection_adapters/postgresql_adapter.rb:675:in `rescue in connect': FATAL:  database "baking-minus-the-math_development" does not exist
 (ActiveRecord::NoDatabaseError)

I thought it might be because of the decimal {}' so I removed it - it was not the problem

Do I have to run a migration after each model generation?

**Comment by jshawl** [comment]
FATAL: database "baking-minus-the-math_development" does not exist

**Comment by jshawl** [comment]
`rake db:create` to create the database

**Comment by marasanders** [comment]
oh yeah

**Comment by marasanders** [comment]
can you delete a migrate timestamp file before you migrate?

**Comment by jshawl** [comment]
yes!

**Comment by amaseda** [comment]
Sounds like you've got this one covered. Going to close but feel free to re-open if you're still encountering any issues.
