### ISSUE TITLE
Websockets help

### ISSUE THREAD

**Issue by wombatdev** [ga-wdi-exercises/project4#243]
Would someone have 5 minutes to talk sockets? I want to start implementing them and could use some guidance.

**Comment by wombatdev** [comment]
I'm running a MEAN stack with a separate stash of JS files that power the game. Socket.io is called into the play controller, but currently is not accessible in the game files.

**Comment by wombatdev** [comment]
Need help figuring out which to use io or socket.

**Comment by wombatdev** [comment]
And/or how to set up rooms.

**Comment by nolds9** [comment]
personally I really like socket.io but remember that provides interface with both the server and the client.

As far as multiple rooms, socket.io has that built into the library, http://socket.io/docs/rooms-and-namespaces/

**Comment by wombatdev** [comment]
Any gotchas related to deploying websockets to heroku? I'm hitting this error:
`Error R10 (Boot timeout) -> Web process failed to bind to $PORT within 60 seconds of launch`

Here's my listen:

```
http.listen(process.env.PORT || 3001, function() {
    console.log("We're online on *:3001");
});
```

**Comment by wombatdev** [comment]
Never mind about the last question. New question, what's a reliable way to count the number of users connected to one socket? My numbers always seem to be weird, maybe based on refreshing, sometimes I'll have one window open, it says 2 connections, sometimes with two windows it says 4, etc.

**Comment by nolds9** [comment]
@wombatdev looks like you have access to when a user connects, could update a global var whenever that happens, or probably the better route is to use the `.connected` method to get information about each connected user
http://socket.io/docs/server-api/#namespace#connected:object

**Comment by wombatdev** [comment]
Should all my socket transmissions be nested within the connection like I currently have them? (below) Or should they be separated?

```
io.on('connection', function(socket) {
    connectCounter++;
    console.log(socket);
    io.emit('playerJoin', connectCounter);
    console.log('player'+connectCounter+' joined');
    socket.on('zombieDeath', function(msg) {
        console.log(msg);
    });
    socket.on('startGame', function(msg) {
        console.log(msg);
        io.emit('startGame', msg);
    });
    socket.on('bulletFiredOutput', function(msg) {
        console.log("shot fired");
        var incomingMsg = JSON.parse(msg);
        io.emit('bulletFiredInput', JSON.stringify(incomingMsg));
    });
    socket.on('disconnect', function() {
        console.log("player has left");
        connectCounter--;
    });
});
```

**Comment by wombatdev** [comment]
@nolds9 Is that a yes they're OK or yes they should be separated? Also, I figured out how to get the unique ID when the players join, but does every individual socket message reference that ID? Right now they only contain what I'm sending (x/y coordinates, etc.)

**Comment by nolds9** [comment]
Yep, basically anything that you want to have happen whenever a new user goes to your site, will happen inside the `io.on('connection', ....)` callback...it's totally fine to keep them all inside

**Comment by nolds9** [comment]
each socket should have info about its `client` id

**Comment by wombatdev** [comment]
So if I send something like this--`game.socket.emit('bulletFiredOutput', JSON.stringify({x: bullet.x, y: bullet.y, rotation: bullet.rotation, xVel: bullet.body.velocity.y, yVel: bullet.body.velocity.y}));`--and console.log the resulting message, it's just that info:

```
{"x":431.0783106342354,"y":555.7047161807008,"rotation":-0.8536602154503597,"xVel":-376.8455238706204,"yVel":-376.8455238706204}
```

How do I include the ID of the client triggering the message?

**Comment by nolds9** [comment]
wherever you are logging the msg sent back, try logging the `socket.clientId`

**Comment by nolds9** [comment]
idk, just guessing here but think you have access to the individual socket via `this` inside the listener: 

``` js
...
socket.on('bulletFire', function (msg) {
 console.log(this) // should reference the individual socket 
// or console.log(socket)
...
}
...
```

**Comment by wombatdev** [comment]
Awesome, didn't know I could reference the socket whenever. Got it with `socket.client.conn.id`

**Comment by nolds9** [comment]
That's neat! Cool if I close this?

**Comment by wombatdev** [comment]
Yeah
