### ISSUE TITLE
Users Question

### ISSUE THREAD

**Issue by adina-pollack** [ga-wdi-exercises/project4#244]
https://github.com/adina-pollack/travel

I have my facebook login/out working, but I'm having issues with saving my 'users' as well as referencing them as a user within the app. Any advice would be much appreciated. Thanks!

**Comment by amaseda** [comment]
Are you getting any errors? How are you currently trying to save users?

**Comment by adina-pollack** [comment]
In the rails console, when I enter User.all, I get  #<ActiveRecord::Relation []>

**Comment by adina-pollack** [comment]
```
#<ActiveRecord::Relation []> 
```

**Comment by amaseda** [comment]
Do you have any code that converts the information received from Facebook into an instance of your User model? I'm guessing there must be something in your code that is passing in information into `User.create` or `User.new`.

**Comment by adina-pollack** [comment]
I might be missing something. I just found something online that I'm going to tryout.

**Comment by amaseda** [comment]
Word! Let us know how that goes.

**Comment by adina-pollack** [comment]
What I found was basically what I already had done. In my user model I have a method to save users but I'm still getting an empty array in the console.  The branch 'save-users' has a different user model method.

**Comment by jshawl** [comment]
do you have a binding.pry inside your user model method? that should help you get more info about what's not working

**Comment by amaseda** [comment]
Going to close this for now, but let me know if you make any progress or decide to go with Devise. Sorry we couldn't troubleshoot this one!
