### ISSUE TITLE
models

### ISSUE THREAD

**Issue by marasanders** [ga-wdi-exercises/project4#245]
class Ingredient < ApplicationRecord

I am changing it to:

class Ingredient < ActiveRecord::Base
  belongs_to :recipe
  belongs_to :category
end

2 questions - Is this correct if I am only storing the category key in the recipe?
Also 

belongs_to is staying blue instead of turning white - did I do something wrong?

Thanks

**Comment by jshawl** [comment]
> Is this correct if I am only storing the category key in the recipe?

yes!

> belongs_to is staying blue instead of turning white - did I do something wrong?

That should be ok - any errors?
