### ISSUE TITLE
Seeding

### ISSUE THREAD

**Issue by marasanders** [ga-wdi-exercises/project4#246]
Category.destroy_all
Recipe.destroy_all
Ingredient.destroy_all

cake = Category.create(Cat_name:"Cake")
beef = Category.create(Cat_name:"Beef")
pasta = Category.create(Cat_name:"Pasta")
chicken = Category.create(Cat_name:"Chicken")
rice = Category.create(Cat_name:"Rice")
dessert = Category.create(Cat_name:"Dessert")
cookies = Category.create(Cat_name:"Cookies")
potatoes = Category.create(Cat_name:"Potatoes")
turkey = Category.create(Cat_name:"Turkey")
kugel = Category.create(Cat_name:"Kugel")
soup = Category.create(Cat_name:"Soup")
salad = Category.create(Cat_name:"Salad")
vegetable = Category.create(Cat_name:"Vegetables")

chocolateCake = cake.Recipe.create(title:"Bubby's Chocolate Cake",  servings: 12, calories: 250, rating: 10, instructions: "Put all ingredients in bowl mix until fully blended. Bake in greased 9X13 for 40 minutes.")
broiledChicken = chicken.Recipe.create(title:"1-2-3 Broiled Chicken",  servings: 4, calories: 180, rating: 8, instructions: "Portion chicken into 4 - 4 oz. pieces set aside. Mix remaining ingredients in ziploc bag or appropriate sized container until blended, add chicken and marinate no longer than 4 hours, broil on high or grill 7 minutes each side until centers are no longer pink.")
vanillaCake = cake.Recipe.create(title:"Best Vanilla Pound Cake",  servings: 12, calories: 200, rating: 9, instructions: "Mix dry ingredients until blended, add oil and mix for 1 minute, add remaining ingredients and mix until well blended. Bake in greased 9X13 at 350 degrees for 1 hour.")
butternutSquashSoup = soup.Recipe.create(title:"Butternut Squash Soup",  servings: 6, calories: 130, rating: 2, instructions: "Cut butternut squash in half and bake at 375 degrees face down on baking sheet for 1 hour. Dice onion and fry on medium heat  in 4 quart pot until transparent, add crushed galic and continue frying for 2 minutes. Scoop flesh add to pot. Alternately cube and peel raw butternut squash and place in pot.  Add water, salt, pepper and consume mix, bring to a boil. Lower flame to simmer for one hour. Remove from heat and blend with hand blender. Can serve with cinnamon and/or cream garnish.")

marasanders@Maras-MacBook-Air-2:~/wdi/projects/project-4/baking-minus-the-math  $ rake db:seed
rake aborted!
NoMethodError: undefined method `Recipe' for #<Category:0x007fa5b4d668a0>
Did you mean?  recipes
               recipes=
/Users/marasanders/.rvm/gems/ruby-2.3.1/gems/activemodel-5.0.0/lib/active_model/attribute_methods.rb:433:in`method_missing'
/Users/marasanders/wdi/projects/project-4/baking-minus-the-math/db/seeds.rb:31:in `<top (required)>'
/Users/marasanders/.rvm/gems/ruby-2.3.1/gems/activesupport-5.0.0/lib/active_support/dependencies.rb:287:in`load'
/Users/marasanders/.rvm/gems/ruby-2.3.1/gems/activesupport-5.0.0/lib/active_support/dependencies.rb:287:in `block in load'
/Users/marasanders/.rvm/gems/ruby-2.3.1/gems/activesupport-5.0.0/lib/active_support/dependencies.rb:259:in`load_dependency'
/Users/marasanders/.rvm/gems/ruby-2.3.1/gems/activesupport-5.0.0/lib/active_support/dependencies.rb:287:in `load'
/Users/marasanders/.rvm/gems/ruby-2.3.1/gems/railties-5.0.0/lib/rails/engine.rb:549:in`load_seed'
/Users/marasanders/.rvm/gems/ruby-2.3.1/gems/activerecord-5.0.0/lib/active_record/tasks/database_tasks.rb:268:in `load_seed'
/Users/marasanders/.rvm/gems/ruby-2.3.1/gems/activerecord-5.0.0/lib/active_record/railties/databases.rake:196:in`block (2 levels) in <top (required)>'
/Users/marasanders/.rvm/gems/ruby-2.3.1/gems/rake-11.2.2/exe/rake:27:in `<top (required)>'
/Users/marasanders/.rvm/gems/ruby-2.3.1/bin/ruby_executable_hooks:15:in`eval'
/Users/marasanders/.rvm/gems/ruby-2.3.1/bin/ruby_executable_hooks:15:in `<main>'
Tasks: TOP => db:seed
(See full trace by running task with --trace)
marasanders@Maras-MacBook-Air-2:~/wdi/projects/project-4/baking-minus-the-math  $ psql
psql (9.5.2)
Type "help" for help.

marasanders=# \c baking-minus-the-math_development
You are now connected to database "baking-minus-the-math_development" as user "marasanders".
baking-minus-the-math_development=# SELECT \* FROM RECIPES
baking-minus-the-math_development-# SELECT \* FROM RECIPES
baking-minus-the-math_development-# 

changed from recipes to recipe cuz that's what they said last time. got the same error to changes recipes to recipe.

 also shouldn't I get the skeleton of the table with SELECT - I did before I tried to seed.

**Comment by jshawl** [comment]
the error is `undefined method Recipe' for #<Category:0x007fa5b4d668a0>`

**Comment by jshawl** [comment]
broiledChicken = chicken.Recipe.create is one line giving you the error

**Comment by jshawl** [comment]
should be `chicken.recipes.create`...

**Comment by marasanders** [comment]
chocolateCake = Recipe.create(title:"Bubby's Chocolate Cake",  servings: 12, calories: 250, rating: 10, category: cake, instructions: "Put all ingredients in bowl mix until fully blended. Bake in greased 9X13 for 40 minutes.")    Okay I stuck the category in the recipe and got no errors.  

when I do SELECT \* FROM CATEGORIES I get nothing. Any suggestions

**Comment by jshawl** [comment]
use `Recipe.create!` with the exclamation point - any errors?

**Comment by marasanders** [comment]
marasanders@Maras-MacBook-Air-2:~/wdi/projects/project-4/baking-minus-the-math  $ rake db:seed
rake aborted!
ActiveRecord::InvalidForeignKey: PG::ForeignKeyViolation: ERROR:  update or delete on table "categories" violates foreign key constraint "fk_rails_22f4e84158" on table "recipes"
DETAIL:  Key (id)=(40) is still referenced from table "recipes".
: DELETE FROM "categories" WHERE "categories"."id" = $1

**Comment by jshawl** [comment]
http://stackoverflow.com/a/31826756/850825

**Comment by marasanders** [comment]
marasanders@Maras-MacBook-Air-2:~/wdi/projects/project-4/baking-minus-the-math  $ rake db:seed
rake aborted!
ActiveRecord::RecordInvalid: Validation failed: Category must exist
/Users/marasanders/.rvm/gems/ruby-2.3.1/gems/activerecord-5.0.0/lib/active_record/validations.rb:78:in `raise_validation_error'
/Users/marasanders/.rvm/gems/ruby-2.3.1/gems/activerecord-5.0.0/lib/active_record/validations.rb:50:in`save!'
/Users/marasanders/.rvm/gems/ruby-2.3.1/gems/activerecord-5.0.0/lib/active_record/attribute_methods/dirty.rb:30:in `save!'
/Users/marasanders/.rvm/gems/ruby-2.3.1/gems/activerecord-5.0.0/lib/active_record/transactions.rb:324:in`block in save!'
/Users/marasanders/.rvm/gems/ruby-2.3.1/gems/activerecord-5.0.0/lib/active_record/transactions.rb:395:in `block in with_transaction_returning_status'
/Users/marasanders/.rvm/gems/ruby-2.3.1/gems/activerecord-5.0.0/lib/active_record/connection_adapters/abstract/database_statements.rb:232:in`block in transaction'
/Users/marasanders/.rvm/gems/ruby-2.3.1/gems/activerecord-5.0.0/lib/active_record/connection_adapters/abstract/transaction.rb:189:in `within_new_transaction'
/Users/marasanders/.rvm/gems/ruby-2.3.1/gems/activerecord-5.0.0/lib/active_record/connection_adapters/abstract/database_statements.rb:232:in`transaction'
/Users/marasanders/.rvm/gems/ruby-2.3.1/gems/activerecord-5.0.0/lib/active_record/transactions.rb:211:in `transaction'
/Users/marasanders/.rvm/gems/ruby-2.3.1/gems/activerecord-5.0.0/lib/active_record/transactions.rb:392:in`with_transaction_returning_status'
/Users/marasanders/.rvm/gems/ruby-2.3.1/gems/activerecord-5.0.0/lib/active_record/transactions.rb:324:in `save!'
/Users/marasanders/.rvm/gems/ruby-2.3.1/gems/activerecord-5.0.0/lib/active_record/suppressor.rb:45:in`save!'
/Users/marasanders/.rvm/gems/ruby-2.3.1/gems/activerecord-5.0.0/lib/active_record/persistence.rb:51:in `create!'
/Users/marasanders/wdi/projects/project-4/baking-minus-the-math/db/seeds.rb:39:in`block in <top (required)>'
/Users/marasanders/.rvm/gems/ruby-2.3.1/gems/activerecord-5.0.0/lib/active_record/connection_adapters/postgresql/referential_integrity.rb:22:in `disable_referential_integrity'
/Users/marasanders/wdi/projects/project-4/baking-minus-the-math/db/seeds.rb:8:in`<top (required)>'
/Users/marasanders/.rvm/gems/ruby-2.3.1/gems/activesupport-5.0.0/lib/active_support/dependencies.rb:287:in `load'
/Users/marasanders/.rvm/gems/ruby-2.3.1/gems/activesupport-5.0.0/lib/active_support/dependencies.rb:287:in`block in load'
/Users/marasanders/.rvm/gems/ruby-2.3.1/gems/activesupport-5.0.0/lib/active_support/dependencies.rb:259:in `load_dependency'
/Users/marasanders/.rvm/gems/ruby-2.3.1/gems/activesupport-5.0.0/lib/active_support/dependencies.rb:287:in`load'
/Users/marasanders/.rvm/gems/ruby-2.3.1/gems/railties-5.0.0/lib/rails/engine.rb:549:in `load_seed'
/Users/marasanders/.rvm/gems/ruby-2.3.1/gems/activerecord-5.0.0/lib/active_record/tasks/database_tasks.rb:268:in`load_seed'
/Users/marasanders/.rvm/gems/ruby-2.3.1/gems/activerecord-5.0.0/lib/active_record/railties/databases.rake:196:in `block (2 levels) in <top (required)>'
/Users/marasanders/.rvm/gems/ruby-2.3.1/gems/rake-11.2.2/exe/rake:27:in`<top (required)>'
/Users/marasanders/.rvm/gems/ruby-2.3.1/bin/ruby_executable_hooks:15:in `eval'
/Users/marasanders/.rvm/gems/ruby-2.3.1/bin/ruby_executable_hooks:15:in`<main>'
Tasks: TOP => db:seed
(See full trace by running task with --trace)
marasanders@Maras-MacBook-Air-2:~/wdi/projects/project-4/baking-minus-the-math  $ 

ActiveRecord::Base.connection.disable_referential_integrity do
  Ingredient.destroy_all
  Recipe.destroy_all
  Category.destroy_all

cake = Category.create!(Cat_name:"Cake") .....

end

**Comment by jshawl** [comment]
> ActiveRecord::RecordInvalid: Validation failed: Category must exist

**Comment by jshawl** [comment]
is this related? https://github.com/ga-wdi-exercises/project4/issues/236#issuecomment-238250985

**Comment by marasanders** [comment]
what are some reasons it might not exist? I used this method last time - what might be wrong?

cake = Category.create!(Cat_name:"Cake")

chocolateCake = Recipe.create!(title:"Bubby's Chocolate Cake",  servings: 12, calories: 250, rating: 10, category: cake, (SKIPPED DATE AND TIME CREATED STAMPS) instructions: "Put all ingredients in bowl mix until fully blended. Bake in greased 9X13 for 40 minutes.")

**Comment by jshawl** [comment]
can you share the relevant parts of schema.rb?

**Comment by marasanders** [comment]
```
  create_table "categories", force: :cascade do |t|
    t.string   "Cat_name"
    t.datetime "created_at", null: false
    t.datetime "updated_at", null: false
  end

  create_table "ingredients", force: :cascade do |t|
    t.string   "component"
    t.string   "amount"
    t.string   "measurement"
    t.string   "amount2"
    t.string   "measurement2"
    t.string   "amount3"
    t.string   "measurement3"
    t.string   "amount4"
    t.string   "measurement4"
    t.string   "amount5"
    t.string   "measurement5"
    t.integer  "recipe_id"
    t.datetime "created_at",   null: false
    t.datetime "updated_at",   null: false
    t.index ["recipe_id"], name: "index_ingredients_on_recipe_id", using: :btree
  end

  create_table "recipes", force: :cascade do |t|
    t.string   "title"
    t.decimal  "servings",     precision: 5, scale: 2
    t.decimal  "calories",     precision: 7, scale: 2
    t.decimal  "rating",       precision: 4, scale: 2
    t.integer  "category_id"
    t.datetime "created_at",                           null: false
    t.datetime "updated_at",                           null: false
    t.text     "instructions"
    t.index ["category_id"], name: "index_recipes_on_category_id", using: :btree
  end

  add_foreign_key "ingredients", "recipes"
  add_foreign_key "recipes", "categories"
end
```

**Comment by jshawl** [comment]
try those exact same lines in the `rails console` - maybe cake is not being created?

**Comment by marasanders** [comment]
which lines?

**Comment by marasanders** [comment]
cake = Category.create!(Cat_name:"Cake")

**Comment by jshawl** [comment]
```
cake = Category.create!(Cat_name:"Cake")

chocolateCake = Recipe.create!(title:"Bubby's Chocolate Cake", servings: 12, calories: 250, rating: 10, category: cake, (SKIPPED DATE AND TIME CREATED STAMPS) instructions: "Put all ingredients in bowl mix until fully blended. Bake in greased 9X13 for 40 minutes.")
```

**Comment by marasanders** [comment]
marasanders=# \c baking-minus-the-math_development
You are now connected to database "baking-minus-the-math_development" as user "marasanders".
baking-minus-the-math_development=# cake = Category.create!(Cat_name:"Cake")
baking-minus-the-math_development-# chocolateCake = Recipe.create!(title:"Bubby's Chocolate Cake", servings: 12, calories: 250, rating: 10, category: cake, instructions: "Put all ingredients in bowl mix until fully blended. Bake in greased 9X13 for 40 minutes.")
baking-minus-the-math_development-# SELECT \* FROM CATEGORIES
baking-minus-the-math_development-# SELECT \* FROM CATEGORY
baking-minus-the-math_development-#   

Am I selecting wrong?

**Comment by jshawl** [comment]
use `$ rails console` instead of `$ psql`

**Comment by marasanders** [comment]
2.3.1 :008 > baking-minus-the-math_development
SyntaxError: (irb):7: syntax error, unexpected $undefined
    from /Users/marasanders/.rvm/gems/ruby-2.3.1/gems/railties-5.0.0/lib/rails/commands/console.rb:65:in `start'
    from /Users/marasanders/.rvm/gems/ruby-2.3.1/gems/railties-5.0.0/lib/rails/commands/console_helper.rb:9:in`start'
    from /Users/marasanders/.rvm/gems/ruby-2.3.1/gems/railties-5.0.0/lib/rails/commands/commands_tasks.rb:78:in `console'
    from /Users/marasanders/.rvm/gems/ruby-2.3.1/gems/railties-5.0.0/lib/rails/commands/commands_tasks.rb:49:in`run_command!'
    from /Users/marasanders/.rvm/gems/ruby-2.3.1/gems/railties-5.0.0/lib/rails/commands.rb:18:in `<top (required)>'
    from /Users/marasanders/.rvm/gems/ruby-2.3.1/gems/activesupport-5.0.0/lib/active_support/dependencies.rb:293:in`require'
    from /Users/marasanders/.rvm/gems/ruby-2.3.1/gems/activesupport-5.0.0/lib/active_support/dependencies.rb:293:in `block in require'
    from /Users/marasanders/.rvm/gems/ruby-2.3.1/gems/activesupport-5.0.0/lib/active_support/dependencies.rb:259:in`load_dependency'
    from /Users/marasanders/.rvm/gems/ruby-2.3.1/gems/activesupport-5.0.0/lib/active_support/dependencies.rb:293:in `require'
    from /Users/marasanders/wdi/projects/project-4/baking-minus-the-math/bin/rails:9:in`<top (required)>'
    from /Users/marasanders/.rvm/gems/ruby-2.3.1/gems/activesupport-5.0.0/lib/active_support/dependencies.rb:287:in `load'
    from /Users/marasanders/.rvm/gems/ruby-2.3.1/gems/activesupport-5.0.0/lib/active_support/dependencies.rb:287:in`block in load'
    from /Users/marasanders/.rvm/gems/ruby-2.3.1/gems/activesupport-5.0.0/lib/active_support/dependencies.rb:259:in `load_dependency'
    from /Users/marasanders/.rvm/gems/ruby-2.3.1/gems/activesupport-5.0.0/lib/active_support/dependencies.rb:287:in`load'
    from /Users/marasanders/.rvm/gems/ruby-2.3.1/gems/spring-1.7.2/lib/spring/commands/rails.rb:6:in `call'
    from /Users/marasanders/.rvm/gems/ruby-2.3.1/gems/spring-1.7.2/lib/spring/command_wrapper.rb:38:in`call'
    from /Users/marasanders/.rvm/gems/ruby-2.3.1/gems/spring-1.7.2/lib/spring/application.rb:191:in `block in serve'
    from /Users/marasanders/.rvm/gems/ruby-2.3.1/gems/spring-1.7.2/lib/spring/application.rb:161:in`fork'
    from /Users/marasanders/.rvm/gems/ruby-2.3.1/gems/spring-1.7.2/lib/spring/application.rb:161:in `serve'
    from /Users/marasanders/.rvm/gems/ruby-2.3.1/gems/spring-1.7.2/lib/spring/application.rb:131:in`block in run'
    from /Users/marasanders/.rvm/gems/ruby-2.3.1/gems/spring-1.7.2/lib/spring/application.rb:125:in `loop'
    from /Users/marasanders/.rvm/gems/ruby-2.3.1/gems/spring-1.7.2/lib/spring/application.rb:125:in`run'
    from /Users/marasanders/.rvm/gems/ruby-2.3.1/gems/spring-1.7.2/lib/spring/application/boot.rb:19:in `<top (required)>'
    from /Users/marasanders/.rvm/rubies/ruby-2.3.1/lib/ruby/site_ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in`require'
    from /Users/marasanders/.rvm/rubies/ruby-2.3.1/lib/ruby/site_ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
    from -e:1:in`<main>'

**Comment by marasanders** [comment]
I feel like I am missing something basic it has been a while since I worked with rails - what might I have forgotten? Is someone available to take a look?

**Comment by jshawl** [comment]
sure!
