### ISSUE TITLE
Paperclip

### ISSUE THREAD

**Issue by dcordz** [ga-wdi-exercises/project4#247]
Trying to use Paperclip and getting this error when trying to create a Project with an image attachment

`TypeError (can't cast ActionDispatch::Http::UploadedFile)`

Done some googling and haven't turned up much, is this something any of you have seen before?

**Comment by jshawl** [comment]
did you remember to mount the uploader? https://github.com/carrierwaveuploader/carrierwave/issues/1143#issuecomment-27892881

**Comment by dcordz** [comment]
I think that's only for the carrierwave gem?

**Comment by jshawl** [comment]
oops. sorry about that - I'm more familiar w/ carrier wave - also lesson plan! https://github.com/ga-wdi-lessons/rails-file-uploads

**Comment by dcordz** [comment]
heh, guess I'll try it out instead of paperclip ~_~

**Comment by dcordz** [comment]
Just got the same error, here's my full controller - does it have something to do with the params?

```
def create
    # if project doesn't exist create project, if it does take user to that project

    # creating with dup_project_params, which doesn't include action date and complete? Problem?
    @project = Project.find_or_create_by(dup_project_params.merge({project_action_date: Time.new()+(7*60*60*24)}))

    # UserJoinProject does not contain User
    check_user_proj_has_user = 0

    # see if this project exists, if it does then...
    if UserJoinProject.exists?(project_id: @project.id)
      # ...check if user Id is already on project
      UserJoinProject.where(project_id: @project.id).each do |user_proj|

        if user_proj.user_id == current_user.id
          check_user_proj_has_user += 1
          break
        end
      end

      if check_user_proj_has_user == 0
        UserJoinProject.create!({user: current_user, project: @project})
        flash[:success] = "Someone else has already created this Project. Together you can make your community better!"
      end

    else
      UserJoinProject.create!({user: current_user, project: @project})
      flash[:success] = "You are the first person to create this Project but more people are coming soon to help you build your community!"
    end

    redirect_to @project
  end

  def show
    @project = Project.find(params[:id])
    respond_to do |format|
      format.html
      format.json { render json: @project, status: :created, location: @project }
    end
    @user = current_user
  end

  private

  def dup_project_params
    params.require(:project).permit(:project_type, :image, :street1, :street2)
  end
end
```

**Comment by dcordz** [comment]
repo - https://github.com/dcordz/ishe

**Comment by jshawl** [comment]
i can't see you schema file - but check the solution rails app as well -https://github.com/ga-wdi-exercises/file-uploads-carrier-wave-aws/tree/solution

**Comment by jshawl** [comment]
https://github.com/ga-wdi-exercises/file-uploads-carrier-wave-aws/blob/solution/db/migrate/20151110211938_create_posts.rb#L4

vs https://github.com/dcordz/ishe/blob/9ac15ab95995416f00788297eadcc4bfb367e1b2/db/migrate/20160808161258_add_attachment_project_image_to_projects.rb#L3

**Comment by dcordz** [comment]
So file uploads have to sit in their own table? Is that something to do with carrierwave or with rails?

**Comment by dcordz** [comment]
I tried this from the carrierwave docs:

```
Add a string column to the model you want to mount the uploader by creating a migration:

rails g migration add_avatar_to_users avatar:string
rake db:migrate
```

**Comment by jshawl** [comment]
think that's a carrierwave thing but honestly am not sure

**Comment by nolds9** [comment]
@dcordz any luck? If not, feel free to reopen this issue, but for now Im going to close it

**Comment by dcordz** [comment]
Just got it - fyi the find_or_create_by method doesn't seem to work with paperclip - rewrote my controller with some logic in place of that method and re-implemented paperclip with no problems.

Had the same issue with carrierwave so the method probably doesn't work with it either (at least not the way I wanted it to I guess)
