### ISSUE TITLE
A little confused on setting up my Pricing Model attributes.

### ISSUE THREAD

**Issue by jhugheswebdev** [ga-wdi-exercises/project4#249]
I'm doing a price comparison of Crossfit Gyms, which have various plans/packages like Unlimited classes a month with no contract prices, Unlimited classes a month on a 12 month contract prices,  13 classes a month with no contract prices, 13 classes a month on a 12 month contract prices, and etc....

How do i call them as attributes when I have so many different prices?

attaching mockup of my MVC for clarification....
![crossfitmvc](https://cloud.githubusercontent.com/assets/19156146/17494207/b3600746-5d81-11e6-848b-0ffe02fccef2.jpg)

**Comment by nolds9** [comment]
I think you can move the info about pricing to attributes on the `CrossfitGym` model

**Comment by nolds9** [comment]
Or If you feel like you need a separate model, I would break it down like so:

```
User -> Gyms -> Plans
// a user has many gyms, which has many plans
```

each plan might have info like `months, monthly price, num_classes` etc
