### ISSUE TITLE
Major sockets slowdown

### ISSUE THREAD

**Issue by wombatdev** [ga-wdi-exercises/project4#250]
Wondering if someone could help me review my sockets setup. My game now crashes 100% of the time.

**Comment by jshawl** [comment]
any errors in the console?

**Comment by wombatdev** [comment]
Negative.

**Comment by wombatdev** [comment]
Think I got it. Moved the socket "receiver" from update (runs every frame) to a different section (create).

**Comment by wombatdev** [comment]
Exceedingly hard to test sockets on one computer though.

**Comment by jshawl** [comment]
Definitely recommend a testing framework like jasmine or even a simple script that can simulate the manual teztjng
