### ISSUE TITLE
Positioning a page at the middle of a list

### ISSUE THREAD

**Issue by kwg58** [ga-wdi-exercises/project4#251]
Suppose I have a schedule of games over a season that runs from, say, May through September.  My games index is going to display a list of all the games in chronological order.  The games that have been played will show the results, the games that are scheduled are going to show the teams playing and the date/time of the game.  

What I don't want is a user getting to that page today and seeing a list of games that started in May and having to scroll down, down, down to get to today's games.  

I want to position that list so the games for today show on the default page.  The users can scroll up/down as they need, but I want them to start from today's games, rather than starting from game 1.  

I've been unsuccessful googling for help because all I get is information about positioning divs on a page, etc. etc.  

Can anyone offer any advice?  I'm using Bootstrap, if there's anything there that might help.  

Thanks.

**Comment by jshawl** [comment]
When you loop through the games, print an id on each tag. When the page loads, set the window location hash to that Id so the page loads at a specific position. Thing to Google is anchor jumping

**Comment by kwg58** [comment]
AWESOME.  Thanks....

**Comment by amaseda** [comment]
Going to close this one but feel free to re-open if you're still experiencing issues with this.

**Comment by kwg58** [comment]
I think I've got it, thanks.
