### ISSUE TITLE
MVP

### ISSUE THREAD

**Issue by kristinmaripasive** [ga-wdi-exercises/project4#253]
Just wanted to ask for advice. Would you think it is better to set up user sessions before creating other features like comments, likes... or would the ride be smoother if I create those features first before diving into sessions? I plan to experiment with the devise gem, which I've never used before, so which would be a good idea? Thanks!

**Comment by jshawl** [comment]
i say try it out! maybe set the timer for 90 minutes, and use a feature branch. If you're not where you want to be by then, consider leaving that for later, and keep making progress

**Comment by kristinmaripasive** [comment]
okidokes, thank you!

**Comment by jshawl** [comment]
also checkout lesson plan - https://github.com/ga-wdi-lessons/devise
