### ISSUE TITLE
How to prevent an ajax post request from redirecting

### ISSUE THREAD

**Issue by jschultz21** [ga-wdi-exercises/project4#254]
Using React on Rails. 

This function executes when a 'save' button is clicked. The post request is successful, but then rails tries to redirect to a 'show page' for api/jobs/:id. Is there something that can be added to the ajax request so that it stays on the same page and updates another component to reflect the saved job?

```
 handleSaveSubmit(e){
    e.preventDefault()
    let job=this.props.job
    console.log(job)
    $.ajax({
      url: '/api/jobs',
      type: 'POST',
      data: { job: { title: job.title, description: job.description, company: job.company } },
      // success: (job) => {job.handleSubmit(job);
      // }

  });
}
```

repo: https://github.com/SeanTay/hello-react-rails/tree/julia

**Comment by jshawl** [comment]
you need a `format |response| do` block in your rails create method

**Comment by amaseda** [comment]
@jschultz21 Were you able to solve this one?

**Comment by jschultz21** [comment]
yup thanks

**Comment by amaseda** [comment]
:+1:
