### ISSUE TITLE
Need to see all participants related to a given competition

### ISSUE THREAD

**Issue by ayespi** [ga-wdi-exercises/project4#256]

**Comment by jshawl** [comment]
what page do you want to show users on? e.g. what controller and action?

**Comment by jshawl** [comment]
what url do you want to be able to see the users on?

**Comment by ayespi** [comment]
http://localhost:3000/competitions/5

**Comment by jshawl** [comment]
what does the competitions controller show action look like?

**Comment by ayespi** [comment]
def show
   @competition = Competition.find(params[:id])
  end

**Comment by jshawl** [comment]
does a user belong to a competition? if so you should be able to print them out with:

<%= @competition.users %> in your show.html.erb file

**Comment by jshawl** [comment]
👍
