### ISSUE TITLE
passing logic between two unrelated components

### ISSUE THREAD

**Issue by jschultz21** [ga-wdi-exercises/project4#258]
In our tree below, the save-job-button calls a function in save-job-container (w/ the ajax request), but it also includes a function to change the state of savedjobs (bottom left) via a 'handlesubmit' function. Is this even possible?

![img_5550](https://cloud.githubusercontent.com/assets/18902022/17520061/4b718740-5e1c-11e6-9dff-acda5d0ad036.JPG)

**Comment by jshawl** [comment]
![](http://i.makeagif.com/media/2-19-2015/qC9QRe.gif)

**Comment by jshawl** [comment]
but yes this is possible https://facebook.github.io/react/tips/communicate-between-components.html

**Comment by amaseda** [comment]
Going to close this one but let us know if you have any issues implementing this!
