### ISSUE TITLE
I am missing a link in communicating with my database

### ISSUE THREAD

**Issue by marasanders** [ga-wdi-exercises/project4#259]

**Comment by jshawl** [comment]
is this between rails and database or angular and database?

**Comment by marasanders** [comment]
angular

**Comment by amaseda** [comment]
Are you getting any errors?

**Comment by marasanders** [comment]
ActionController::RoutingError (No route matches [GET] "/sockjs-node/info only the one from the last issue

**Comment by amaseda** [comment]
Ok can you please push up your code and link to the appropriate repo/branch in the original issue? 

Going to close this one since it's dealing with the same problem as before. Let's keep the conversation going in the other one.
