### ISSUE TITLE
trouble with jquery not defined error message

### ISSUE THREAD

**Issue by adrianshep** [ga-wdi-exercises/project4#26]
Matt showed me this really cool converter for creating a JSON object from a csv file:

$.csv.toObjects(csv)

When I try running it, I get this error message:

Uncaught ReferenceError: jQuery is not defined

I've got these scripts in my index.html and the top one (0.71) should be the one to the library containing the above jQuery script:

```
<script src="https://cdnjs.cloudflare.com/ajax/libs/jquery-csv/0.71/jquery.csv-0.71.min.js"></script>
  <script src="https://code.jquery.com/jquery-2.1.4.js"></script>
  <script src="script.js"></script>
```

**Comment by RobertAKARobin** [comment]
That's... weird. Where's the line that's throwing that error?

**Comment by adrianshep** [comment]
Comes up as soon as I load it:
jquery.csv-0.71.min.js:73 
Uncaught ReferenceError: jQuery is not defined

**Comment by adrianshep** [comment]
Sorry, here's the whole line:

```
if(!config.callback){return output;}else{config.callback('',output);}}};$.csvEntry2Array=$.csv.toArray;$.csv2Array=$.csv.toArrays;$.csv2Dictionary=$.csv.toObjects;})(jQuery);
```

**Comment by RobertAKARobin** [comment]
OH! Just put the `jquery.csv` thing after where you load `jquery`.

``` html
<script src="https://code.jquery.com/jquery-2.1.4.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/jquery-csv/0.71/jquery.csv-0.71.min.js"></script>
<script src="script.js"></script>
```

**Comment by adrianshep** [comment]
That solved my not defined error message, thanks. I'm back, though, to this error which I began with:

csv is not defined

I'm not getting how to call my data.csv file with this code:
var keywords = $.csv.toObjects(csv);
    console.log(keywords);

I've tried all sorts of variations, but wouldn't $.csv just grab the nearest (in my case, only) .csv file to run?

**Comment by RobertAKARobin** [comment]
Where do you have `var csv = whatever`? Can you show more of your code?

**Comment by RobertAKARobin** [comment]
And nope, you need to actually give it a filename. Javascript isn't great about just looking for nearby files.

**Comment by adrianshep** [comment]
('data.csv') - that did it. I think the script library issue was getting in the way.
Thanks.

**Comment by RobertAKARobin** [comment]
Awesome!
