### ISSUE TITLE
Moving Forward - WayLow 2.0

### ISSUE THREAD

**Issue by ayespi** [ga-wdi-exercises/project4#260]
When user visits WayLoy for the first time, they would need to enter competition details

**Comment by jshawl** [comment]
Maybe have a select menu with all the competitions and a button that says join ?

**Comment by ayespi** [comment]
SInce there is only one competition that the app is aware of, I was thinking something like this...

![screenshot 2016-08-09 12 39 50](https://cloud.githubusercontent.com/assets/17255879/17524947/978b2d0e-5e2e-11e6-8339-8bddb7199c86.png)

**Comment by ayespi** [comment]
Clicking on the "Get Started" button will take the user to a page where they can enter the details of the competition... After entering competition details, they will be able to add participants...

**Comment by ayespi** [comment]
Due to the average number of participants in any given competition, I would probably need to seed  a considerable number of participants to mimic an actual competition.

**Comment by ayespi** [comment]
Since there is one competition, is it still reasonable to have a model for competition???

**Comment by amaseda** [comment]
Sure. It's okay to have a model that only has one instance. You may create more competitions down the line too.

**Comment by ayespi** [comment]
Thanks!
