### ISSUE TITLE
First argument in form cannot contain nil or be empty in form_for

### ISSUE THREAD

**Issue by kwg58** [ga-wdi-exercises/project4#261]
I'm setting up a data entry form using rails form_for in my html file and keep getting this error message.  What it's telling me is in the line 

``` js
<%= form_for @goal do |f| %>
```

the value of @goal is not set.  Well, there's a goal controller and I haven't touched it.  

Any advice?

**Comment by jshawl** [comment]
Does a goal belong to anything? If so, that is nil

**Comment by kwg58** [comment]
there's a goal controller, a goal model, goal views, all created with a scaffold......

**Comment by kwg58** [comment]
When I go to the goal index screen I get a report (it's empty, but...).  When I go to the /new window I can enter the information for a goal, but it will not let me complete it because it's complaining about a foreign_key condition.  I don't think that problem would cause this error, though.

**Comment by amaseda** [comment]
Do you have any ActiveRecord associations set up?

What exactly does the foreign key error say?

**Comment by kwg58** [comment]
Yes, a goal has foreign keys for games, and for players.  It's complaining that the game I entered does not exist, even though I know that it does.  Interestingly, when I look at the server messages, I notice that game_id is not one of the fields in the hash, even though it's specified as one of the goal parms.  This is with the screens come up when I hit the appropriate rails URLs. 

The original problem was with a form_for function in an html page.

**Comment by jshawl** [comment]
the form should reference the game as well - form_for[@game, @goal]

**Comment by amaseda** [comment]
Any luck with this one @kwg58?

**Comment by kwg58** [comment]
That form reference syntax doesn't work.  If I read the doc correctly, you cant do this for two classes, you can do it for a class and a namespace, which I don't have.  Should I be creating one? 

But I found something more.  I looked at the HTML generated by the Rails form for new goal and noticed that the first element (game_id) is configured like this:

``` html
<div class="field">
    <label for="goal_game_id">Game</label>
    <input type="number" name="goal[period]" id="goal_period">
  </div>
```

A few lines down, the period field is defined thusly:

``` html
<div class="field">
    <label for="goal_period">Period</label>
    <input type="number" name="goal[period]" id="goal_period">
  </div>
```

They BOTH refer to the period field, which is probably why the message complains about the value of the game_id.

I'm beginning to wonder if there are problems with  my models.

Any thoughts?

**Comment by jshawl** [comment]
what's your erb from look like?

**Comment by kwg58** [comment]
new.html.erb from the goals model:

```
<h1>New Goal</h1>

<%= render 'form', goal: @goal %>

<%= link_to 'Back', goals_path %>
```

**Comment by kwg58** [comment]
It says waiting fur student response, but I've responded.  Let's see if this resets anything....  :)

**Comment by nolds9** [comment]
What error are you getting? I believe you can accomplish your original intent by using `form_for`. If you are trying to create a new `Goal` for a `Game`, then the form might look something like this: 

``` ruby
<%= form_for([@game, @goal]) do |f| %>
  # fields for goal attributes / values
<% end %>
```

As long as you have both of those variables defined in your controller action, the form should render. If it doesn't work after you submit, try putting a `binding.pry` in the `create` action and poke around with the params

**Comment by kwg58** [comment]
Nick, 

I made the change and ran it.  I got 

```
1 error prohibited this goal from being saved:  Game must exist
```

But once again I looked at the HTML and found that the HTML was created with the wrong references for the game id entry (see my entry from 3 hours ago).

When I edited that HTML to refer to game_id and not period and resubmitted the form, it created a record in the goals table.  

However, after the record was created and the browser was redirected to the show page for this goal,  I get this:

```
undefined method `game_id' for nil:NilClass

<p>
  <strong>Game:</strong>
  <%= @goal.game_id %>
</p>
```

which looks  like @goal is null again.  

I think something is wrong with the way my Rails app is set up, but I can't find anything. 

Thoughts?

BTW, it doesn't matter what's specified in the form_for line; the same thing happens either way.

**Comment by nolds9** [comment]
what does it look like where you are defining `@goal` and `@game` in your controller

**Comment by kwg58** [comment]
I don't understand the question

**Comment by jshawl** [comment]
in goal controller, what are the contents of the `new` method?

**Comment by kwg58** [comment]
New, edit, and create:

```
  def new
    @goal = Goal.new
  end

  # GET /goals/1/edit
  def edit
  end

  # POST /goals
  # POST /goals.json
  def create
    binding.pry
    @goal = Goal.new(goal_params)

    respond_to do |format|
      if @goal.save
        format.html { redirect_to @goal, notice: 'Goal was successfully created.' }
        format.json { render :show, status: :created, location: @goal }
      else
        format.html { render :new }
        format.json { render json: @goal.errors, status: :unprocessable_entity }
      end
    end
  end

```

**Comment by jshawl** [comment]
``` rb
def new
    @goal = Goal.new
end
```

needs to reference a game, like:

``` rb
def new
    @goal = Goal.new
    @game = Game.find(params[:id])
end
```

**Comment by kwg58** [comment]
I added that to the goals controller, and now when I go to ../goals/new I get "Couldn't find Game with 'id'=". 

 HOWEVER, when I get to doing this from a form I imagine I'll be able to pass it a game id?

**Comment by nolds9** [comment]
`@game = Game.find(params[:game_id])`

**Comment by jshawl** [comment]
Shouldn't that be a nested resource? E.g. Games/someid/goals/new ?

**Comment by kwg58** [comment]
I'll set it up as a nested resource and give it a try.....

**Comment by nolds9** [comment]
after the form submits, you should be able to handle the association in the `create` controller

``` ruby
# find the game from url params
# build the association using @game.goals.create making sure to pass in strong params
```

**Comment by kwg58** [comment]
I set up goals and penalties as nested under goals.  I go to ../games/1/goals/new and I had the same problem with the HTML I described earlier.  

I tried the same thing to create a penalty and had the correct html, but got the same message "First argument in form cannot contain nil or be empty".  

I'm going to delete and rebuild my goal scaffold, but I"m going to go home and rest a bit first.  

If I could get one of you to spend a few minutes going over my data  structure tomorrow to see what else I might have missed, I'd be grateful.  

Thanks for all you support.

**Comment by amaseda** [comment]
Let us know when you're in Kevin and somebody can come take a look.

**Comment by kwg58** [comment]
I'm around whenever someone's got a minute or two (or ninety....)

**Comment by kwg58** [comment]
git@github.com:kwg58/hscore-api.git
- [new branch]      games-nested-resources

**Comment by nolds9** [comment]
Looks like you are not building the association in the `game#create` controller
https://github.com/kwg58/hscore-api/blob/games-nested-resources/app/controllers/goals_controller.rb#L29

what about trying something like:

``` ruby
...
def create
 @game = Game.find(params[:game_id])
 @goal = @game.goals.new goal_params
 ...
end
```

**Comment by kwg58** [comment]
I switched the model to put set up goals and penalties as nested resources under games, which is how I should have set it up the first time, and now I'm struggling even more.  Thanks, Nick.

**Comment by jshawl** [comment]
What's the status kevin? any progress? if not let me know id be happy to come help
