### ISSUE TITLE
authorization error

### ISSUE THREAD

**Issue by JuliaNajafi** [ga-wdi-exercises/project4#262]
when I am trying make requests to my rails API from angular, I am getting an error that reads: 
"XMLHttpRequest cannot load http://localhost:3000/playlists. No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'http://localhost:8080' is therefore not allowed access." 

any suggestions ? 
also I'm a bit confused because it says 'XMLHttpRequest' but I thought i'm trying to make a request for json.. but maybe I'm not understanding something

**Comment by JuliaNajafi** [comment]
when i google the error, I keep reading about some error in chrome but not sure if thats correct

**Comment by andrewsunglaekim** [comment]
https://github.com/cyu/rack-cors check out this gem if your making ajax requests to a rails api.

**Comment by amaseda** [comment]
Let us know how it goes with the gem Andy suggested.

Also `XMLHttpRequest` is just the name of the method that Javascript uses under the hood when you make an AJAX call. You can use it to retrieve/send JSON.

**Comment by JuliaNajafi** [comment]
cool thanks!

**Comment by nolds9** [comment]
feel free to reopen if issue persits
