### ISSUE TITLE
Loading external JS file within an angular controller

### ISSUE THREAD

**Issue by wombatdev** [ga-wdi-exercises/project4#263]
I'm running an EAN stack right now (M to come), and built it as a single page app using two handlebar files and two angular states so far. Express has one call:

```
app.get('/*', function(req, res) {
    res.render('game');
});
```

Handlebars has a `layout-main` and `game` file, and there are two angular states, `splash` and `play`, running on top.

My question is how to only kick off the external game JS files when the `play` state loads. Currently, the game files are referenced in `game.hbs`, and it launches in both angular states. I've tried several different stackoverflow solutions, but none have worked, mostly resulting in the files failing to load at all. I don't want to create any more hbs files or express routes yet--how can I load and run external js files from within an individual angular state?

**Comment by wombatdev** [comment]
I feel like it would help to get rid of handelbars entirely but I'm not sure how. 5 minutes requested.

**Comment by wombatdev** [comment]
I removed handelbars, using all angular, but still on the original problem--how to load external JS files within a single Angular state. Putting the `<script>` tags in the template url isn't working.

**Comment by jshawl** [comment]
can you wrap your code inside a script tag in a function, and call that function when a particular state loads? also going into 1-1 but down for huddle at 2 if nobody helps by then!

**Comment by nolds9** [comment]
@wombatdev yeah what if you moved the code you wanted to execute to your `gameController` and then have in run in a method that is called on `ng-init` which will run when a state loads

**Comment by wombatdev** [comment]
The phaser game is spread across 7 files, but only one is the "trigger," so to speak. If I put that code in the controller and pull it out of the index.html head, then the game does indeed wait to load until I'm in the correct state, but then the next file in the phaser chain (boot state) fails because the "game" variable is undefined in the file. Can I export that from the controller to the rest of the ecosystem?

**Comment by jshawl** [comment]
can you attach it to the global object? 🙊  `window.game = function...`
