### ISSUE TITLE
Limit Competitions to only one

### ISSUE THREAD

**Issue by ayespi** [ga-wdi-exercises/project4#264]
To place a limit on the number of competitions, how would that be handled in the Competitions controller??? I'm not sure which action... Would it be some type of validation???

**Comment by nolds9** [comment]
Validations seem like a great place! http://guides.rubyonrails.org/active_record_validations.html#performing-custom-validations

**Comment by ayespi** [comment]
Thanks for the link...

**Comment by amaseda** [comment]
Going to close this one for now, but let us know if you have any issues setting up that validation!
