### ISSUE TITLE
Nested resource

### ISSUE THREAD

**Issue by kristinmaripasive** [ga-wdi-exercises/project4#265]
I just added a child model (art) to my database which belongs to an artist. I'm trying to render the form for creating a new art instance. 

It keeps giving me this error:
![screen shot 2016-08-09 at 2 27 02 pm](https://cloud.githubusercontent.com/assets/19437889/17528543/e64543f8-5e3d-11e6-8de0-5f14836d42f9.png)

I'm understand that arts_path doesn't exist anymore since I nested it... but I'm just confused on where to change that?

https://github.com/kristinmaripasive/maestropiece/tree/child-models

**Comment by nolds9** [comment]
if you are creating a nested resource, need to pass two objects to from for, i.e:

``` ruby
...
form_for([@artist, @play])
...
```

**Comment by kristinmaripasive** [comment]
Oh yes, I realized that but I was doing just parentheses. Bummer. Thanks for that. Now, my form manages to create a new instance but I'm checking my database and it's empty.

```
 id |   name   | description  | photo_url | artist_id |         created_at         |         updated_at         
----+----------+--------------+-----------+-----------+----------------------------+----------------------------
  1 | Serenity | So peaceful. |           |         2 | 2016-08-09 19:17:21.492692 | 2016-08-09 19:17:21.492692
  2 |          |              |           |         2 | 2016-08-09 19:18:32.718274 | 2016-08-09 19:18:32.718274
(2 rows)

```

I'm not getting any errors though... it's just a show page with blank values for each attribute.

https://github.com/kristinmaripasive/maestropiece/tree/child-models

**Comment by nolds9** [comment]
@kristinmaripasive you need to make sure to pass `art_params` wherever you are creating your new instance (`arts_controller`)

**Comment by kristinmaripasive** [comment]
I figured that out, but there's a new issue. Can't seem to get pass this error.  I defined artist and art in my edit action in the arts_controller. But the artist ID is showing up nil. When I don't pass any objects to the edit link below, it shows the artist ID, but then the art ID is missing.

https://github.com/kristinmaripasive/maestropiece/tree/child-models

![screen shot 2016-08-09 at 4 24 23 pm](https://cloud.githubusercontent.com/assets/19437889/17532266/cde9b392-5e4d-11e6-9047-63328949d37d.png)

**Comment by kristinmaripasive** [comment]
Figured it out. Thanks!

**Comment by kristinmaripasive** [comment]
Just kidding. It's still not working. I've tried all sorts of paths but they're just not reading the artist ID and art ID. It's always either, or. 

```
<td><%= link_to 'Show', artist_arts_path %></td>
        <td><%= link_to 'Edit', edit_artist_art_path %></td>
        <td><%= link_to 'Destroy', @artist_path , method: :delete, data: { confirm: 'Are you sure?' } %></td>
```

These are my routes:

```
 artist_arts GET    /artists/:artist_id/arts(.:format)          arts#index
                POST   /artists/:artist_id/arts(.:format)          arts#create
 new_artist_art GET    /artists/:artist_id/arts/new(.:format)      arts#new
edit_artist_art GET    /artists/:artist_id/arts/:id/edit(.:format) arts#edit
     artist_art GET    /artists/:artist_id/arts/:id(.:format)      arts#show
                PATCH  /artists/:artist_id/arts/:id(.:format)      arts#update
                PUT    /artists/:artist_id/arts/:id(.:format)      arts#update
                DELETE /artists/:artist_id/arts/:id(.:format)      arts#destroy
```

**Comment by nolds9** [comment]
@kristinmaripasive you need to make sure to pass the appropriate objects to all your paths in the links. I.e. `edit_artist_art_path(@artist, @art)`

**Comment by kristinmaripasive** [comment]
yeah, that's exactly what I tried to do in the screen shot I last posted. It keeps saying the required keys are missing... I don't get it since I'm passing both objects.

**Comment by nolds9** [comment]
where are you defining `@artist` and `@art` in the controller?

**Comment by kristinmaripasive** [comment]
do you mean my arts controller? 

```
  def show
    @artist = Artist.find(params[:artist_id])
    @art = Art.find(params[:id])
  end
```

**Comment by nolds9** [comment]
what view are these links rendered on? whichever corresponding controller action

**Comment by kristinmaripasive** [comment]
Whoaaaa I just got my edit and delete to work for each art piece! Yay! Just need the show to work now... They're all in my `artists view > show.html.erb`. 
So I'm trying to define them in my artists_controller, but it's not working..

```
  def show
    @artist = Artist.find(params[:artist_id])
    @art = @artist.find(params[:id])
  end
```

**Comment by nolds9** [comment]
if you're in the `artists#show` controller then you need to use `@artist = Artist.find(params[:id])` because theres no `artist_id` in the route. No need to define the art in controller, instead pass the instance `art` where you are looping through all of the artists 'arts'...

**Comment by kristinmaripasive** [comment]
I'm getting the hang of this all of a sudden. I figured it out haha. I think I'm trying to solve the problems with the same mindset I created them.... Thanks a lot, Nick!!!
