### ISSUE TITLE
method not being passed through components 

### ISSUE THREAD

**Issue by jschultz21** [ga-wdi-exercises/project4#266]
we've got a handleSubmit method in our app component and it passes down through the searchContainer, results, and savejobContainer components where it's used. We've got it included as props in each of the components, ie: `<SaveJobContainer
            job={job}
            handleSubmit={(job) => this.handleSubmit(job)}
            />` 

but we're getting this error when save button clicked: `SaveJobContainer.self-d8c9146….js?body=1:36 Uncaught TypeError: _this.props.handleSubmit is not a function`

**Comment by amaseda** [comment]
Can you paste code or link to the relevant components?

**Comment by jschultz21** [comment]
nvm think we've moved on to a new error now 🎉

**Comment by amaseda** [comment]
Wooo! Keep us posted if you need any help with the new one.
