### ISSUE TITLE
Google maps API callback

### ISSUE THREAD

**Issue by alpha2262** [ga-wdi-exercises/project4#267]
Trying to load in google maps API directions, receiving an "uncaught InvalidValueError: initialize is not a function"

**Comment by amaseda** [comment]
No luck yet when we tackled it IRL, but link to your pushed-up code here and I'll take another look.

**Comment by alpha2262** [comment]
https://github.com/alpha2262/carbegone/tree/michael1

**Comment by jshawl** [comment]
move your script tag that ends with `&callback=initialize`

to the bottom of the html

**Comment by alpha2262** [comment]
Seems to be working now, thanks!
