### ISSUE TITLE
MEAN stack user auth

### ISSUE THREAD

**Issue by wombatdev** [ga-wdi-exercises/project4#268]
Do the instructors have a preferred method for user auth in the MEAN stack? Passport.js maybe?

**Comment by amaseda** [comment]
Yeah, Passport is probably the way to go. Here's a lesson plan on local authentication: https://github.com/ga-wdi-lessons/express-passport

**Comment by wombatdev** [comment]
If it were you would you use Passport or go for a Facebook API login?

**Comment by nolds9** [comment]
https://github.com/jaredhanson/passport-facebook
