### ISSUE TITLE
Not routing to user form. 

### ISSUE THREAD

**Issue by adina-pollack** [ga-wdi-exercises/project4#269]
https://github.com/adina-pollack/travel 
-devise branch (I didn't end up using devise)

I'm having issues routing to my new user form I've created. Potentially it's related to all the devise/omniauth things I was trying to use earlier. I thought I had removed everything relating to omniauth/devise/figaro, but I'm not sure. Would it be best just to start from a fresh repo? I can just copy everything over from this branch.

**Comment by jshawl** [comment]
> I'm having issues routing to my new user form I've created

can you provide the steps necessary to reproduce the issue?

e.g. when i click on _____ this happens _____ but i want ______ to happen instead

**Comment by adina-pollack** [comment]
when I click on the "Join now" button on home index view, I get: No route matches [POST] "/users/new", which makes sense from what I see when I do rake routes. But I can't seem to figure out why.

**Comment by jshawl** [comment]
can you change `button_to` to `link_to`? i think buttons make a post request by default - https://github.com/adina-pollack/travel/blob/345c160ecec913ac7d9284604041b22b739aa583/app/views/home/index.html.erb#L3

alternatively, think to google is "get method button_to"
