### ISSUE TITLE
Can't seem to integrate angular into rails

### ISSUE THREAD

**Issue by Ryan-321** [ga-wdi-exercises/project4#27]
Seems like when I leave my rendered JSON in rails controller I can't get Angular to grab and parse that JSON, rails takes over and shows it on the page.  Then when I take out the rendering, Angular won't hook in, get this in response.  

```
Uncaught TypeError: Cannot read property 'module' of undefined(anonymous function) @ angular-route.js:24(anonymous function) @ angular-route.js:6
angular.js:38 Uncaught Error: [$injector:modulerr] http://errors.angularjs.org/1.4.5/$injector/modulerr?p0=flash&p1=Error%3A%2…udflare.com%2Fajax%2Flibs%2Fangular.js%2F1.4.5%2Fangular.min.js%3A19%3A381)
```

can't find the error

**Comment by RobertAKARobin** [comment]
Can you push your code to GH?

**Comment by jkoul** [comment]
FYI Ryan, I ran into a similar problem and just decided to split the backend and frontend into two independent apps. That structure serves my needs better anyway.

I know Eddie Park got it tied together.....you might want to reach out to him too.

**Comment by Ryan-321** [comment]
Been working with Eddie, trying to track down the cause, think my file structure might be off.

**Comment by Ryan-321** [comment]
https://github.com/Ryan-321/Flash

just pushed this up

**Comment by RobertAKARobin** [comment]
Cool. Where's your `index.html` and everything?

**Comment by Ryan-321** [comment]
all my angular files are under assets/javascripts

I hooked those up via application.html.erd with script tags

**Comment by RobertAKARobin** [comment]
Oh, I see.

**Comment by RobertAKARobin** [comment]
You have this:

``` html
  <script src="https://cdnjs.cloudflare.com/ajax/libs/angular.js/1.4.5/angular-route.min.js"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/angular.js/1.4.5/angular.min.js"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/angular.js/1.4.5/angular-resource.min.js"></script>
```

Instead, try this:

``` html
  <script src="https://cdnjs.cloudflare.com/ajax/libs/angular.js/1.4.5/angular.min.js"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/angular.js/1.4.5/angular-route.min.js"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/angular.js/1.4.5/angular-resource.min.js"></script>
```

**Comment by Ryan-321** [comment]
That cleared up the Angular issue.  Thanks Robin.

Still can't get angular to pull down JSON from rails and compile them into angular. Getting this now.

GET http://localhost:3000/app/assets/javascripts/views/subjects/index.html 404 (Not Found)b @

**Comment by jshawl** [comment]
does that file exist? `app/assets/javascripts/views/subjects/index.html`?

**Comment by Ryan-321** [comment]
yeah, its my partial for angular

**Comment by jshawl** [comment]
can you push your code and link to it ill clone it down

**Comment by jshawl** [comment]
actually.... can i see your routes.js file? in particular the template url>?

**Comment by Ryan-321** [comment]
https://github.com/Ryan-321/Flash

``` js
(function(){
  var router = angular.module('subjectRouter', []);
  router.config([
    '$routeProvider',
    function($routeProvider){
      $routeProvider.
      when("/", {
        templateUrl: 'subjects/index.html',
        controller: 'subjectsController',
        controllerAs: 'subjectsCtrl'})
    }
  ])
})();
```

**Comment by Ryan-321** [comment]
When I type "/subjects" the errors go away, but it still doesn't allow me to access my angular view or pull down any JSON from my rails backend

**Comment by jshawl** [comment]
change the templateUrl to `/javascripts/views/subjects/index.html`?

**Comment by jshawl** [comment]
Remove the word "app" from https://github.com/Ryan-321/Flash/blob/884a4310d3e0b1ae3593fb86de4f097f404af8fe/app/assets/javascripts/routes.js#L8

**Comment by Ryan-321** [comment]
no luck, get:

GET http://localhost:3000/assets/javascripts/views/subjects/index.html 404 (Not Found)

**Comment by jshawl** [comment]
I was able to fix the 404 by adding:

``` js
templateUrl: 'assets/views/subjects/index.html'
```

**Comment by Ryan-321** [comment]
dude!

View is working, thanks.  
still not sure why there not talking to each other yet.  will do some research.
thanks.

**Comment by jshawl** [comment]
ok great! closing for now but please open another issue if you'd like assistance!
