### ISSUE TITLE
API calls 

### ISSUE THREAD

**Issue by JuliaNajafi** [ga-wdi-exercises/project4#270]
I'm using $resource to make a call to an api (a foreign api, not mine), and I get an error that
says the following: 

XMLHttpRequest cannot load No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'http://localhost:8080' is therefore not allowed access.

I've read the documentation for the API, and its says it is free for 'get' methods (but need key for other methods). So I think the reason why I'm getting this error is because $resource includes access to methods like put and delete. do you have any suggestions to get around this issue, like for example, specifying only a get method ?

**Comment by nolds9** [comment]
An alternative method is to use Angular's native`$http` service. Just inject it as a dependency to your controller and can make HTTP requests / only a GET request https://docs.angularjs.org/api/ng/service/$http

**Comment by JuliaNajafi** [comment]
cool thanks ill try it out! so i wouldnt need a factory for this, i can use it straight in my controller?

**Comment by nolds9** [comment]
either / or
