### ISSUE TITLE
Flexbox fail

### ISSUE THREAD

**Issue by wombatdev** [ga-wdi-exercises/project4#271]
I'm trying to set up flexbox and I'm failing badly. The lesson we did last week had this:

```
html {
  height: 100%;
}

body {
  min-height: 100%;
  background-color: #ccc;
  margin: 0 auto;
  display: flex;
  flex-direction: row;
  justify-content: center;
  align-items: center;
}

div {
  width: 100px;
  height: 100px;
  outline: 1px solid red;
}
```

So the top level was `height: 100%` and the "flexed" section was `min-height: 100%`. My app has more layers--`html`, then `body` (which calls Angular module), then `main` (which calls `ui-view`), then each state will have a `section` that I want to be full-screen and contain everything for that state. So I just tried to chain the `100%`s down to that `section`, where I introduce the `flexbox`. However, in the code I pasted below, the result is that the `main` block (called `.angularBody`) has a height only equal to what's in it--one div. It does not occupy the full window. `html` and `body` are full window, but it's lost at the `main`. What am I botching here?

```
html {
    height: 100%;
}
body {
    min-height: 100%;
    margin: 0 auto;
}
.angularBody {
    min-height: 100%;
}
.splashSection {
    min-height: 100%;
    margin: 0 auto;
    background: url("/assets/images/background1.jpg") no-repeat center center fixed;
    background-size: cover;
    display: flex;
    flex-direction: column;
    align-items: center;
    justify-content: center;
}
.splashDiv {
    font-family: "Cinzel", sans-serif;
    color: black;
    text-align: center;
    font-size: 7em;
}
```

**Comment by jshawl** [comment]
you need `height` instead of `min-height` on all three - http://codepen.io/jshawl/pen/NAZKjz

**Comment by wombatdev** [comment]
Swore I had tried that...but it works. Thanks.
