### ISSUE TITLE
Many-to-Many Questions

### ISSUE THREAD

**Issue by adina-pollack** [ga-wdi-exercises/project4#272]
https://github.com/adina-pollack/travel
devise branch

I am working on my new user form and am having difficulties establishing the many-to-many relationship with the location a user selects and my location model.  A user is able to select a location, and there is no error upon form submission, but the location id is not being saved. I've tried a few different tutorials/methods. The current code in my repo did not involve my join table (destinations). Please help. Thanks!

**Comment by jshawl** [comment]
can you try the association in your seeds? this will be faster to debug than manually testing. also - any errors when you seed?

**Comment by adina-pollack** [comment]
I haven't had any errors when I seed. I'm also seeding the locations via an api so I'm not entirely sure how to setup an association without a specific location_id.

**Comment by adina-pollack** [comment]
Hey Jesse, I set up an association in my seed file but it doesn't look like the location id was saved there either.

**Comment by nolds9** [comment]
What does your models look like? Also the create controller action...

**Comment by adina-pollack** [comment]
User model:

```
class User < ApplicationRecord
  has_many :destinations
  has_many :locations, through: :destinations
end
```

location model:

```
class Location < ApplicationRecord
  has_many :destinations
  has_many :users, through: :destinations
end
```

destination model:

```
class Destination < ApplicationRecord
  belongs_to :user
  belongs_to :location

  accepts_nested_attributes_for :location
end
```

user controller:

```
  def new
    @user = User.new
    @location = @user.locations.build
    @location_options = Location.all.map { |l| [l.country, l.id]}
  end

  def create
    @user = User.create(user_params)
    session[:user_id] = @user.id
    redirect_to user_path(@user)
  end
```

**Comment by nolds9** [comment]
Interestingly, I was able to make the associations work fine in the console, and i'm not able to reproduce any errors. What are the steps to reproduce?

Also, don't think its related, but you do not need to have `user_id` on a Location or `location_id` on a user
