### ISSUE TITLE
Heroku Error  - Application Error

### ISSUE THREAD

**Issue by adina-pollack** [ga-wdi-exercises/project4#275]
I deployed my app to https://make-friends-will-travel.herokuapp.com/ and I'm getting an `Application Error`. I ran `heroku logs` and it says error `h10`which says that the app crashed "A crashed web dyno or a boot timeout on the web dyno will present this error". Help please. Thanks!

**Comment by nolds9** [comment]
Did you run:

``` bash
$ heroku run rake db:migrate
```

**Comment by adina-pollack** [comment]
Yeah I did. And I did a force drop/reset on my db after I pushed the correct branch up and ran db:migrate and seed again.

**Comment by nolds9** [comment]
and still errors? Check here to see if any of these make sense https://github.com/ga-wdi-lessons/rails-deployment/blob/master/common-errors.md

**Comment by adina-pollack** [comment]
I did some digging and I still have my `application.yml` file from when I had originally installed the figaro gem. Could that be causing the issue? Should I delete it?

**Comment by nolds9** [comment]
sure! if you're not using figaro, but not sure if thats the root of the problem

**Comment by adina-pollack** [comment]
hmm still not working
