### ISSUE TITLE
Ruby Except Method

### ISSUE THREAD

**Issue by dcordz** [ga-wdi-exercises/project4#276]
I'm getting a method undefined error when trying to do the below, UserJoinProject is a join table

```
UserJoinProject.where(project: proj).first.user.except(:password_digest)
```

Here's an example of a user - this is a hash correct? Or is it technically a row in a SQL table (so not a hash)

```
 #<User:0x007ffe206b3e08
 id: 7,
 name: "dave",
 email: "dcordz2@gmail.com",
 created_at: Wed, 10 Aug 2016 15:14:46 UTC +00:00,
 updated_at: Wed, 10 Aug 2016 15:14:46 UTC +00:00,
 password_digest: "$2a$10$zhXQfX79YvwoHSnJFRVe/Omw8U8/GRIbzLDdVle.4TBV2nM2UpIV.">
[16] pry(#<ProjectsController>)> 
```

**Comment by jshawl** [comment]
could try `delete_if` as well

**Comment by amaseda** [comment]
How's this going? Any progress / more questions?

**Comment by dcordz** [comment]
Took care of it in a different place, never got the except method working though
