### ISSUE TITLE
indexing nested resources in rails from angular

### ISSUE THREAD

**Issue by JuliaNajafi** [ga-wdi-exercises/project4#277]
I'm having a little trouble figuring out how to access/create a nested resource to my rails database from angular  (I remember this as a bonus from the blitter lab- a bonus I couldn't figure out - with bleets and comments) 
In my app, words are nested in playlists, so when I'm making a call from angular to access words in my rails api, I would imagine it would look something like this (in my WordFactory): 
return $resource("http://localhost:3000/playlists/:id/words"
Would I somehow use $stateparams to get that playlist id in my controller then? I tried doing this in several different ways but couldnt figure it out  

also, looking back at the blitter api where commnets were nested in bleets, the comments controller (in rails) didn't try to get the bleet_id (ex: params[:bleet_id]) in the index, create, or show like I would expect before referencing comments - does that matter?

**Comment by jshawl** [comment]
yes! what did you try? what didn't work? - can you send a link to the example you're looking at?

**Comment by JuliaNajafi** [comment]
this is what my rails word controller looks like: 
![screen shot 2016-08-10 at 4 39 05 pm](https://cloud.githubusercontent.com/assets/19292741/17570132/2825d6b2-5f19-11e6-8acd-c523f675f7f1.png)

**Comment by JuliaNajafi** [comment]
this is what the factory that is trying to access the nested resource words looks like: 
![screen shot 2016-08-10 at 4 38 15 pm](https://cloud.githubusercontent.com/assets/19292741/17570150/35c92472-5f19-11e6-9762-54867eb7d8d8.png)

**Comment by JuliaNajafi** [comment]
oh sorry that was the show controller where im working with the factory

**Comment by JuliaNajafi** [comment]
this is the factory talking to my api: 
![screen shot 2016-08-10 at 4 37 51 pm](https://cloud.githubusercontent.com/assets/19292741/17570176/538819e6-5f19-11e6-9fbc-d6420b90c991.png)

**Comment by JuliaNajafi** [comment]
and a link to my angular repo : https://github.com/JuliaNajafi/angularWords

**Comment by JuliaNajafi** [comment]
so in my show controller im accessing the playlist correctly so i tried doing something similar with $stateparams with my VocabFactory - thats whats not working right now

**Comment by jshawl** [comment]
$statparams.id is undefined?

**Comment by JuliaNajafi** [comment]
got it! thanks!

**Comment by amaseda** [comment]
Sounds like this one's taken care of. Feel free to re-open if you have any more issues!
