### ISSUE TITLE
Gem devise

### ISSUE THREAD

**Issue by kristinmaripasive** [ga-wdi-exercises/project4#278]
Just wanna ask how can I sign up for a category in an app, and if it's possible in devise? Cause I know by using devise, I can't edit the views... The goal is to have a user sign up and choose whether they are an artist or musician, then their profile gets created on the respective page.

**Comment by jshawl** [comment]
You can edit the views! Rails g devise:views

**Comment by kristinmaripasive** [comment]
I did that but it's not connected. It's not showing the same as what's on the browser

**Comment by jshawl** [comment]
Restart the server?

**Comment by kristinmaripasive** [comment]
Oh cool! It shows now... I do have another question though regarding the `begin rescue end` we did for my show controller, earlier during lunch. So if you remember, I wanted to show my musicians even though they didn't have any music. They were working earlier, but after implementing devise... it broke again somehow? 

This is the error:

![screen shot 2016-08-10 at 5 37 02 pm](https://cloud.githubusercontent.com/assets/19437889/17572173/26975354-5f21-11e6-8786-78395f840f76.png)

This is how my Musicians#show looks like:

```
  def show
    @musician = Musician.find(params[:id])
    begin
    @music = Music.find(params[:id])
    rescue
    end
  end
```

**Comment by kristinmaripasive** [comment]
https://github.com/kristinmaripasive/maestropiece/tree/devise

**Comment by jshawl** [comment]
Inside rescue you can add: @music = Music.new

**Comment by kristinmaripasive** [comment]
Cool! Thanks Jesse!
