### ISSUE TITLE
Help! Devise broke my database!

### ISSUE THREAD

**Issue by jkoul** [ga-wdi-exercises/project4#28]
Good morning! So I just installed devise on my rails back-end app and and now I can't create/migrate the db. Here's the error message for rake db:create

```
could not connect to server: No such file or directory
    Is the server running locally and accepting
    connections on Unix domain socket "/tmp/.s.PGSQL.5432"?
```

I KNOW this isn't a unique problem, but a google search didn't yield anything directly useful. Thoughts?

**Comment by RobertAKARobin** [comment]
Run the blue elephant.

**Comment by jkoul** [comment]
DAMMIT BLUE ELEPHANT. This is why I never restart my computer lol.

Ok thanks :)

**Comment by RobertAKARobin** [comment]
:) I love these.
