### ISSUE TITLE
Many-to-Many

### ISSUE THREAD

**Issue by adina-pollack** [ga-wdi-exercises/project4#281]
https://github.com/adina-pollack/travel
devise branch

My many-to-many relationship is working - when I create a user w/ location, a destination is created with the location_id and the user_id. In my user show.html.erb page I'm trying to reference the location the user chose when they signed up. 

so far I've tried 

```
@current_user.location
```

```
@current_user.location.country
```

```
@current_user.destinations.location
```

```
Destination.location 
```

and probably some others along the way. What's the best way to get to the locations country value.

**Comment by jshawl** [comment]
a user has many locations according to your model - https://github.com/adina-pollack/travel/blob/a1917e4f8dd6f77191dd0ee7914233e9c33ad9a0/app/models/user.rb#L3

what if you try `@user.locations` and then `@user.locations.first`?

**Comment by adina-pollack** [comment]
`@user.locations.first.country` worked! thanks so much!

**Comment by jshawl** [comment]
👍
