### ISSUE TITLE
Linking outside of Angular state

### ISSUE THREAD

**Issue by wombatdev** [ga-wdi-exercises/project4#282]
I have a link in my Angular url template that points to a route that is not controlled by an Angular state. In this case, the state is /signup, and the link is for the route /signup/facebook. In my Express app, I have an `app.get` to handle these requests:

```
app.get('/signup/facebook',
    passport.authenticate('facebook'),
    function(req, res){});
```

But when I click the link, nothing happens. The URL does change, but there isn't a redirect. However, if I then refresh the page, the correct action occurs. It's like the link only changes the URL but doesn't send a fresh get request. Here is the link:
`<a href="/signup/facebook"><img data-ng-src="/assets/images/fblogin.png" alt="Facebook Log In" /></a>`

Any ideas how to fix?

**Comment by jshawl** [comment]
`window.location = '/signup/facebook'` <- does that work?

**Comment by wombatdev** [comment]
Does that belong in the href itself? Or where do I put that?

**Comment by jshawl** [comment]
`<a href="/signup/facebook" onclick='window.location="/signup/facebook">'`

**Comment by jshawl** [comment]
this is extremely hacky btw...

**Comment by wombatdev** [comment]
That works. It seems like there may be a way to use external links with ui-router but it involves setting up something called `$stateChangeStart` which seems like more trouble than it's worth.

http://stackoverflow.com/questions/30220947/how-would-i-have-ui-router-go-to-an-external-link-such-as-google-com

**Comment by jshawl** [comment]
👍
