### ISSUE TITLE
Handling callbacks with passport

### ISSUE THREAD

**Issue by wombatdev** [ga-wdi-exercises/project4#283]
I'm hooking up with Facebook to authenticate my users using `passport-facebook`, and it seems like the first part is working. Besides the problem I raised in my other open issue, I am redirecting to Facebook and logging in. However, I don't really understand the callback process. My callback is set to `http://gentle-retreat-53311.herokuapp.com/callback.html`, which is a completely blank HTML page. My Express routes look like this:

```
app.get('/signup/facebook',
    passport.authenticate('facebook'),
    function(req, res){});

app.get('callback.html',
    passport.authenticate('facebook', { failureRedirect: 'www.yahoo.com' }),
    function(req, res) {
        console.log(res);
        // Successful authentication, redirect home.
        res.redirect('www.google.com');
    });
```

I'm using Yahoo and Google just for testing purposes. Right now, however, after authentication, I'm always taken back to the index page--http://gentle-retreat-53311.herokuapp.com--as opposed to either of the sites I specified for failure/success. Am I missing a piece here? Do I need something in the callback file itself?

**Comment by jshawl** [comment]
passport authenticate has a successRedirect option: http://passportjs.org/docs#redirects
