### ISSUE TITLE
Creating google calendar attachments

### ISSUE THREAD

**Issue by dcordz** [ga-wdi-exercises/project4#286]
I've been looking for a simple way to create a gcal attachment and send it in an email, something like the icalendar gem but I can't find anything.

Most of what I've read talks about implementing OAuth with a Google API and then pushing events to users calendars, which is not exactly what I'm looking for, I think.

Do you know of any good gems or ways to implement google calendar event creation?

**Comment by jshawl** [comment]
this is a problem we've been trying to solve for weeks - please let me know if you find a solution

**Comment by jshawl** [comment]
🙌

**Comment by dcordz** [comment]
Hahaha, reading about it it looks kinda simple but I don't really want to have to ask users permission to send them an email with an attachment.

I wonder if google makes it this difficult though because google calendar doesn't have an offline client? (does it?) So the only way to create a new calendar, and then a new event or interact with an existing one is through the google API

**Comment by amaseda** [comment]
Going to close this one but let us know if you made any progress here. Might end up helping us out!
