### ISSUE TITLE
Express+Angular how to recognize if users are logged in

### ISSUE THREAD

**Issue by wombatdev** [ga-wdi-exercises/project4#288]
I've got FB working saving users to my database! It's tight AF! But, now I need to handle behavior based on whether or not there is an authenticated user logged in. Would someone be able to sit down for 5 minutes to maybe briefly walk through what that would require?

**Comment by wombatdev** [comment]
Made some progress regarding Angular handling. More specific question:

Users will authenticate through Facebook and be added to my User collection entirely on the back end. I'm doing this with Express, Passport & Mongo. I have the following Angular state to control the view based on whether the user is logged in:

```
controller: function($state, user) {
                    if ($state.is("root")) $state.go(user.loggedIn ? "Menu" : "Splash");
                }
```

So my question is how I assign the value of user.loggedIn in Express and then pass it up to the Angular router?

**Comment by wombatdev** [comment]
Still stuck on this.

**Comment by jshawl** [comment]
where does successRedirect send the user? are you including the code we talked about?

**Comment by wombatdev** [comment]
I tried to include some code in the `callback.html` file but it never seemed to load fully--even a simple `console.log` wouldn't register before the page redirected to the root. (Even if I didn't set a `res.redirect` in Express, it would end up at the home page.)

**Comment by jshawl** [comment]
that's ok - what's redirecting to the root?
