### ISSUE TITLE
nested resource question

### ISSUE THREAD

**Issue by marasanders** [ga-wdi-exercises/project4#289]
I have a category which has recipes which has ingredients - to show the ingredients I need my recipe factory which in turn needs a category but when I get the the recipe show page I no longer have access to my category id - Can you please help me paint a better picture? thanks

**Comment by jshawl** [comment]
is there a json url that you can currently access?

e.g. categories/3/recipes/4/ingredients/5.json ?

**Comment by marasanders** [comment]
http://localhost:3000/categories/158/recipes.json

**Comment by marasanders** [comment]
sorry that's http://localhost:3000/recipes/38/ingredients.json

**Comment by jshawl** [comment]
ok and what does your angular resource look like?

**Comment by marasanders** [comment]
``` js
  function RecipeShowControllerFunction(CategoryFactory, RecipeFactory, IngredientFactory, $stateParams, $resource){
    console.log("in the recipe show controller")
    var vm = this;
    console.log("vm "+vm[0])
    console.log("this "+this)
    console.log("cat id"+$stateParams.category_id)
    console.log("id"+$stateParams.id)
    CategoryFactory.get({category_id: $stateParams.id}).$promise.then(function(category) {
      vm.category = category
      console.log("category"+category)
    })
    RecipeFactory.get({id: $stateParams.id}).$promise.then(function(recipe) {
      vm.recipe = recipe
      console.log("category"+recipe)
    })
    vm.ingredients = IngredientFactory.query({recipe_id: $stateParams.id})
    console.log("ingredients "+vm.ingredients)
    this.update = function(recipe){
      category.$update(recipe);
    }
    this.destroy = function(recipe){
      CategoryFactory.remove(recipe);
      this.category.splice(recipe, 1)
    }
  }
  function IngredientFactoryFunction($resource) {
    return $resource("/recipes/:recipe_id/ingredients/id:.json", {}, {
      update: {method: "PUT"}
    });
  }

  function RecipeFactoryFunction($resource) {
    return $resource("/categories/:category_id/recipes/:id.json", {}, {
      update: {method: "PUT"}
    });
  }

  function CategoryFactoryFunction($resource) {
    return $resource("/categories/:id.json", {}, {
      update: {method: "PUT"}
    });
  }
```

**Comment by marasanders** [comment]
just pushed code up

**Comment by nolds9** [comment]
Two things I see right away, but not sure if related. Look at the `url` for RecipeFactoryFunction, it expects a `category_id` and an `id`. So If you want to `Get` one Recipe, you need to make sure to pass both ids...Also, where you are `get` ing a Category, you need to just pass `id` not `category_id` to match the url in your Category factory

**Comment by marasanders** [comment]
the id it passes with just id is the recipe id not category id - and your right category id does not exist - this is the issue I am trying to clarify - in order to use the recipe fatctory I need a category ID but I am losing it along the way ....

**Comment by marasanders** [comment]
also just pushed up a new copy with the ingredients controller sorry

**Comment by marasanders** [comment]
right now I am getting the ingredients on the recipe show page but losing the recipe

**Comment by nolds9** [comment]
Question: Which route is this for? Or is the main goal of this state? If I understand correctly, we are trying to show one Recipe? What does the `url` look like for that state?

**Comment by marasanders** [comment]
right now it is /recipes/:recipe_id/ingredients.json but in theory it should be /category/:category_id/recipes/:recipe_id/ingredients.json

**Comment by marasanders** [comment]
yes it is to show one recipe

**Comment by nolds9** [comment]
I agree that it might be easier to nest recipes under categories, because otherwise it will be very difficult to access one particular `Category`, which you need to access one `Recipe`

**Comment by marasanders** [comment]
thank you - the problem is I don't know how to hold onto the category id

**Comment by nolds9** [comment]
if you change your state's `url` to have a `category_id` in it, then you can access it via `$stateParams.category_id`

**Comment by marasanders** [comment]
I       .state("recipeShow", {
        url: "category/:category_id/recipes/:id",
        templateUrl: "/views/recipes/show.html",
        controller: "RecipeShowController",
        controllerAs: "vm"

**Comment by marasanders** [comment]
ingredients 
angular.js:9866 XHR finished loading: GET "http://localhost:3000/categories.json?category_id=38".(anonymous function) @ angular.js:9866sendReq @ angular.js:9667serverRequest @ angular.js:9383processQueue @ angular.js:13248(anonymous function) @ angular.js:13264$eval @ angular.js:14466$digest @ angular.js:14282$apply @ angular.js:14571(anonymous function) @ angular.js:16308completeOutstandingRequest @ angular.js:4924(anonymous function) @ angular.js:5312
angular.js:11655 Error: [$resource:badcfg] get
http://errors.angularjs.org/1.3.15/$resource/badcfg?p0=object&p1=array&p2=GET&p3=%2Fcategories.json
    at angular.js:63
    at g.then.m.$resolved (angular-resource.js:609)
    at processQueue (angular.js:13248)
    at angular.js:13264
    at Scope.$eval (angular.js:14466)
    at Scope.$digest (angular.js:14282)
    at Scope.$apply (angular.js:14571)
    at done (angular.js:9698)
    at completeRequest (angular.js:9888)
    at XMLHttpRequest.requestLoaded (angular.js:9829)(anonymous function) @ angular.js:11655(anonymous function) @ angular.js:8596processQueue @ angular.js:13256(anonymous function) @ angular.js:13264$eval @ angular.js:14466$digest @ angular.js:14282$apply @ angular.js:14571done @ angular.js:9698completeRequest @ angular.js:9888requestLoaded @ angular.js:9829
angular.js:9866 XHR finished loading: GET "http://localhost:3000/recipes/38/ingredients.json".(anonymous function) @ angular.js:9866sendReq @ angular.js:9667serverRequest @ angular.js:9383processQueue @ angular.js:13248(anonymous function) @ angular.js:13264$eval @ angular.js:14466$digest @ angular.js:14282$apply @ angular.js:14571(anonymous function) @ angular.js:16308completeOutstandingRequest @ angular.js:4924(anonymous function) @ angular.js:5312
angular.js:9866 GET http://localhost:3000/categories/recipes/38.json 404 (Not Found)(anonymous function) @ angular.js:9866sendReq @ angular.js:9667serverRequest @ angular.js:9383processQueue @ angular.js:13248(anonymous function) @ angular.js:13264$eval @ angular.js:14466$digest @ angular.js:14282$apply @ angular.js:14571(anonymous function) @ angular.js:16308completeOutstandingRequest @ angular.js:4924(anonymous function) @ angular.js:5312
angular.js:9866 XHR finished loading: GET "http://localhost:3000/categories/recipes/38.json".

**Comment by nolds9** [comment]
So ignoring everything to do with `ingredients`, the problem is where you are calling CategoryFactory

**Comment by marasanders** [comment]
not sure what you mean - I go to the first page and get all the categories 2nd page recipes in category - third page is the problem - I am not using the CategoryController on the third page but would like to use the CategoryFactory

**Comment by marasanders** [comment]
when i get to the recipe show controller - 
cat id undefined
id 38

**Comment by nolds9** [comment]
sorry, I meant factory,should be able to access `$stateParams.category_id` if the url is right

**Comment by marasanders** [comment]
.state("recipeShow", {
url: "category/:category_id/recipes/:id",
templateUrl: "/views/recipes/show.html",
controller: "RecipeShowController",
controllerAs: "vm"

maybe I didn't understand

**Comment by jshawl** [comment]
What url can i visit to reproduce the issue? I'm visiting http://localhost:3000/#/categories/1/recipes/1 and seeing a blank page

**Comment by marasanders** [comment]
http://localhost:3000/#/category//recipes/38

the category should be 158 - but again I am loosing it

**Comment by jshawl** [comment]
you don't have any routes for /category/id/recipes/id - https://github.com/marasanders/angular-rails-data-base-generator/blob/23ba88cd57684c763118cc18481bf001653f6416/baking-minus-the-math/app/assets/javascripts/app.js#L51-L111

**Comment by marasanders** [comment]
Sorry I changed that
    .state("recipeShow", {
        url: "category/:category_id/recipes/:id",
        templateUrl: "/views/recipes/show.html",
        controller: "RecipeShowController",
        controllerAs: "vm"

**Comment by jshawl** [comment]
url: "category/:category_id/recipes/:id", needs to be url: "/category/:category_id/recipes/:id" with initial slash

**Comment by jshawl** [comment]
still looking at next issue after that

**Comment by jshawl** [comment]
console.log("cat id"+$stateParams.category_id)
    console.log("id"+$stateParams.id)

both of these are correct

**Comment by jshawl** [comment]
```
                                              VVV should be category id
CategoryFactory.get({category_id: $stateParams.id}).$promise.then(function(category) {
      vm.category = category
      console.log("category"+category)
    })

```

**Comment by marasanders** [comment]
will that work the 1st time around? Do I need 2 factories one for id and one for category_id? also my console.log cat id is returning blank

**Comment by marasanders** [comment]
oh sorry you meant in the show controller

**Comment by marasanders** [comment]
but I tried that and again the category_id console log is blank

**Comment by marasanders** [comment]
let me push up my latest copy

**Comment by marasanders** [comment]
can I please show it to you?

**Comment by jshawl** [comment]
![](https://dl.dropbox.com/s/ygl470iwj23q89n/Screenshot%202016-08-11%2014.50.48.png?dl=0)

cat id and id showing in the console

**Comment by marasanders** [comment]
not when I don't hard code them

**Comment by jshawl** [comment]
what url are you visiting to show category_id is blank?

**Comment by marasanders** [comment]
when I leave my recipe show page to go to my ingredient show page the category_id gets lost - see original question from 2 hours ago - so the one I visit renders as http://localhost:3000/#/category//recipes/38

**Comment by jshawl** [comment]
https://github.com/marasanders/angular-rails-data-base-generator/blob/23ba88cd57684c763118cc18481bf001653f6416/baking-minus-the-math/public/views/categories/show.html#L16

you need `recipeShow({id: recipe.id, category_id: vm.category.id})`

**Comment by marasanders** [comment]
that worked - thank you!!!

I am still getting the two errors -

**Comment by jshawl** [comment]
please open a new issue - see ya there!
