### ISSUE TITLE
can't find where error is coming from

### ISSUE THREAD

**Issue by marasanders** [ga-wdi-exercises/project4#290]
angular.js:11655 Error: [$resource:badcfg] get

**Comment by jshawl** [comment]
what url are you visiting / what controller ?

**Comment by marasanders** [comment]
ocalhost:3000/#/category/161/recipes/39 - recipeShow

**Comment by jshawl** [comment]
do you know which line is triggering this error? is it `RecipeFactory.query({category_id: $stateParams.id})`
