### ISSUE TITLE
is there a sample

### ISSUE THREAD

**Issue by marasanders** [ga-wdi-exercises/project4#292]
of updating a whole table at once one line at a time - or could you tell me in general what that would look like - I am having a hard time conceptualizing - how I would update a recipe where each  line is a different id on the table.

**Comment by jshawl** [comment]
you could loop through each of them:

``` rb
Recipe.all.each do |recipe|
  recipe.update ...
end
```

**Comment by marasanders** [comment]
So the concept is I can display the whole recipe on the page - the data returned would be the whole recipe - vm.ingredients then in the  controller would it be more prudent to delete and recreate the ingredient list - because the order may change lines may be removed ... then read the whole vm.ingredients and recreate the recipe?

**Comment by jshawl** [comment]
sorry i dont understand the question. can you phrase in the form of:

I did this _____. i expected _____ to happen. i wanted ______ to happen instead

**Comment by marasanders** [comment]
I did this in my category controller

``` js
      var vm = this;
      vm.new_catgory = new CategoryFactory();
      vm.create = function(){
      vm.new_catgory.$save()(function(response){
       if(response.success) vm.catgory_data.push(response);
       vm.new_catgory = new CategoryFactory();
  })
}
```

the angular side updated - but the database did not

``` rb
  def create
    puts "create"
    @category = Category.create(category_params)
    render json: @category, status: :ok
  end
```

**Comment by jshawl** [comment]
if you `console.log(response)` inside of 

``` js
vm.new_catgory.$save()(function(response){
       if(response.success) vm.catgory_data.push(response);
```

what is the output?

**Comment by marasanders** [comment]
good thought! angular.js:9866 POST http://localhost:3000/categories.json 400 (Bad Request)
but when I check it it has all the data in it

**Comment by nolds9** [comment]
sounds like a problem on the backend, can you check the server logs.

**Comment by marasanders** [comment]
angular.js:9866 POST http://localhost:3000/categories.json 400 (Bad Request)

**Comment by marasanders** [comment]
Started POST "/categories.json" for ::1 at 2016-08-12 09:30:03 -0400
Processing by CategoriesController#create as JSON
  Parameters: {"category"=>{}}
create
Completed 400 Bad Request in 3ms (ActiveRecord: 0.0ms)

ActionController::ParameterMissing (param is missing or the value is empty: category):

app/controllers/categories_controller.rb:48:in `category_params'
app/controllers/categories_controller.rb:22:in`create'
  Rendering /Users/marasanders/.rvm/gems/ruby-2.3.1/gems/actionpack-5.0.0/lib/action_dispatch/middleware/templates/rescues/diagnostics.html.erb within rescues/layout
  Rendering /Users/marasanders/.rvm/gems/ruby-2.3.1/gems/actionpack-5.0.0/lib/action_dispatch/middleware/templates/rescues/_source.html.erb
  Rendered /Users/marasanders/.rvm/gems/ruby-2.3.1/gems/actionpack-5.0.0/lib/action_dispatch/middleware/templates/rescues/_source.html.erb (11.1ms)
  Rendering /Users/marasanders/.rvm/gems/ruby-2.3.1/gems/actionpack-5.0.0/lib/action_dispatch/middleware/templates/rescues/_trace.html.erb
  Rendered /Users/marasanders/.rvm/gems/ruby-2.3.1/gems/actionpack-5.0.0/lib/action_dispatch/middleware/templates/rescues/_trace.html.erb (7.4ms)
  Rendering /Users/marasanders/.rvm/gems/ruby-2.3.1/gems/actionpack-5.0.0/lib/action_dispatch/middleware/templates/rescues/_request_and_response.html.erb
  Rendered /Users/marasanders/.rvm/gems/ruby-2.3.1/gems/actionpack-5.0.0/lib/action_dispatch/middleware/templates/rescues/_request_and_response.html.erb (1.2ms)
  Rendered /Users/marasanders/.rvm/gems/ruby-2.3.1/gems/actionpack-5.0.0/lib/action_dispatch/middleware/templates/rescues/diagnostics.html.erb within rescues/layout (83.0ms)

i

**Comment by marasanders** [comment]
```
}
  var vm = this;
  vm.new_catgory = new CategoryFactory();
  vm.create = function(){
    console.log("category"+vm.new_category.Cat_name)
  vm.new_catgory.$save(function(response){
   console.log("response "+response)
   if(response.success) vm.catgory_data.push(response);
   vm.new_catgory = new CategoryFactory();
```

  })
}

the console log is showing the correct value - when I remove the if it pushes to the angular table correctly

**Comment by marasanders** [comment]
categories.json is totally populated

**Comment by jshawl** [comment]
what does `CategoryFactory();` look like?

**Comment by marasanders** [comment]
function CategoryFactoryFunction($resource) {
    return $resource("/categories/:id.json", {}, {
      update: {method: "PUT"}
    });
  }

**Comment by jshawl** [comment]
can you push your latest code will take a look

**Comment by marasanders** [comment]
done - thanks

**Comment by jshawl** [comment]
this has it working for me:

``` diff
diff --git a/baking-minus-the-math/app/assets/javascripts/app.js b/baking-minus-the-math/app/assets/javascripts/app.js
index 6f1b7c6..9eccefd 100644
--- a/baking-minus-the-math/app/assets/javascripts/app.js
+++ b/baking-minus-the-math/app/assets/javascripts/app.js
@@ -143,16 +143,16 @@
 //       vm.new_catgory = new CategoryFactory();
 //       vm.create = function(){
 //         console.log("category"+vm.new_category.Cat_name)
-//       vm.new_catgory.$save(function(response){
-//        console.log("response "+response)
-//        if(response.success) vm.catgory_data.push(response);
-//        vm.new_catgory = new CategoryFactory();
-//   })
 // }

-    vm.new_category = {};
+      vm.new_category = new CategoryFactory();
       vm.create = function(){
         console.log("category"+vm.new_category.Cat_name)
+       vm.new_category.$save(function(response){
+        console.log("response "+response)
+        if(response.success) vm.catgory_data.push(response);
+        vm.new_catgory = new CategoryFactory();
+   })
         vm.category_data.push(angular.copy(vm.new_category));
         vm.new_category = {};
       }
```

**Comment by marasanders** [comment]
It's hard for me to see what you did differently - what did I miss?

**Comment by jshawl** [comment]
I'm not sure, you commented out the code that was making the post request, so i uncommented it and moved it into create function

**Comment by marasanders** [comment]
Oh well - I was going back and forth between the two code blocks trying to figure it out - oh well I guess I just never got the right combo - will examine your code to see if I can see what I missed - Thank you!

**Comment by marasanders** [comment]
really close to getting results from api search 

using the sample api search from the site

receiving message - 

search?key=8839d43…&q=shredded chicken:1 Uncaught SyntaxError: Unexpected token :
app.self-01516ca….js?body=1:180 Object {data: undefined, status: 404, config: Object, statusText: "error"}

any ideas?

**Comment by marasanders** [comment]
XMLHttpRequest cannot load http://food2fork.com/api/search?key=883...&q=shredded%20chicken. No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'http://localhost:3000' is therefore not allowed access

**Comment by marasanders** [comment]
If I change the request from GET to JSONP I get 
search?key=8839d43…&q=shredded chicken:1 Uncaught SyntaxError: Unexpected token :
app.self-9fc8fe2….js?body=1:179 Object {data: undefined, status: 404, config: Object, statusText: "error"}
