### ISSUE TITLE
Heroku Rake Commands Unsuccessful!!!

### ISSUE THREAD

**Issue by ayespi** [ga-wdi-exercises/project4#295]
See Terminal Error Below:

michaelparks@Michaels-MacBook-Pro-2:~/Desktop/File-Cabinet/_Projects/GA/wlms/waylow2 (master) $heroku rake db:create
Running rake db:create on ⬢ waylow-cms... up, run.9126
FATAL:  permission denied for database "postgres"
DETAIL:  User does not have CONNECT privilege.
Couldn't create database for {"adapter"=>"postgresql", "database"=>"d1if8bc8iikd3m", "pool"=>5, "timeout"=>5000, "username"=>"jxjhtoashzsupd", "password"=>"n7zIUBRx7k0g99GxNLl4v0ByqL", "port"=>5432, "host"=>"ec2-54-235-89-113.compute-1.amazonaws.com"}
rake aborted!
PG::ConnectionBad: FATAL:  permission denied for database "postgres"
DETAIL:  User does not have CONNECT privilege.
/app/vendor/bundle/ruby/2.2.0/gems/activerecord-5.0.0/lib/active_record/connection_adapters/postgresql_adapter.rb:671:in `initialize'
/app/vendor/bundle/ruby/2.2.0/gems/activerecord-5.0.0/lib/active_record/connection_adapters/postgresql_adapter.rb:671:in`new'
/app/vendor/bundle/ruby/2.2.0/gems/activerecord-5.0.0/lib/active_record/connection_adapters/postgresql_adapter.rb:671:in `connect'
/app/vendor/bundle/ruby/2.2.0/gems/activerecord-5.0.0/lib/active_record/connection_adapters/postgresql_adapter.rb:217:in`initialize'
/app/vendor/bundle/ruby/2.2.0/gems/activerecord-5.0.0/lib/active_record/connection_adapters/postgresql_adapter.rb:37:in `new'
/app/vendor/bundle/ruby/2.2.0/gems/activerecord-5.0.0/lib/active_record/connection_adapters/postgresql_adapter.rb:37:in`postgresql_connection'
/app/vendor/bundle/ruby/2.2.0/gems/activerecord-5.0.0/lib/active_record/connection_adapters/abstract/connection_pool.rb:721:in `new_connection'
/app/vendor/bundle/ruby/2.2.0/gems/activerecord-5.0.0/lib/active_record/connection_adapters/abstract/connection_pool.rb:765:in`checkout_new_connection'
/app/vendor/bundle/ruby/2.2.0/gems/activerecord-5.0.0/lib/active_record/connection_adapters/abstract/connection_pool.rb:744:in `try_to_checkout_new_connection'
/app/vendor/bundle/ruby/2.2.0/gems/activerecord-5.0.0/lib/active_record/connection_adapters/abstract/connection_pool.rb:705:in`acquire_connection'
/app/vendor/bundle/ruby/2.2.0/gems/activerecord-5.0.0/lib/active_record/connection_adapters/abstract/connection_pool.rb:501:in `checkout'
/app/vendor/bundle/ruby/2.2.0/gems/activerecord-5.0.0/lib/active_record/connection_adapters/abstract/connection_pool.rb:364:in`connection'
/app/vendor/bundle/ruby/2.2.0/gems/activerecord-5.0.0/lib/active_record/connection_adapters/abstract/connection_pool.rb:875:in `retrieve_connection'
/app/vendor/bundle/ruby/2.2.0/gems/activerecord-5.0.0/lib/active_record/connection_handling.rb:128:in`retrieve_connection'
/app/vendor/bundle/ruby/2.2.0/gems/activerecord-5.0.0/lib/active_record/connection_handling.rb:91:in `connection'
/app/vendor/bundle/ruby/2.2.0/gems/activerecord-5.0.0/lib/active_record/tasks/postgresql_database_tasks.rb:6:in`connection'
/app/vendor/bundle/ruby/2.2.0/gems/activerecord-5.0.0/lib/active_record/tasks/postgresql_database_tasks.rb:15:in `create'
/app/vendor/bundle/ruby/2.2.0/gems/activerecord-5.0.0/lib/active_record/tasks/database_tasks.rb:109:in`create'
/app/vendor/bundle/ruby/2.2.0/gems/activerecord-5.0.0/lib/active_record/tasks/database_tasks.rb:129:in `block in create_current'
/app/vendor/bundle/ruby/2.2.0/gems/activerecord-5.0.0/lib/active_record/tasks/database_tasks.rb:292:in`block in each_current_configuration'
/app/vendor/bundle/ruby/2.2.0/gems/activerecord-5.0.0/lib/active_record/tasks/database_tasks.rb:291:in `each'
/app/vendor/bundle/ruby/2.2.0/gems/activerecord-5.0.0/lib/active_record/tasks/database_tasks.rb:291:in`each_current_configuration'
/app/vendor/bundle/ruby/2.2.0/gems/activerecord-5.0.0/lib/active_record/tasks/database_tasks.rb:128:in `create_current'
/app/vendor/bundle/ruby/2.2.0/gems/activerecord-5.0.0/lib/active_record/railties/databases.rake:27:in`block (2 levels) in <top (required)>'
/app/vendor/bundle/ruby/2.2.0/gems/rake-11.2.2/exe/rake:27:in `<top (required)>'
Tasks: TOP => db:create
(See full trace by running task with --trace)
michaelparks@Michaels-MacBook-Pro-2:~/Desktop/File-Cabinet/_Projects/GA/wlms/waylow2 (master) $

**Comment by jshawl** [comment]
the db is automatically created for you - can you try the next step ? `rake db:migrate`

**Comment by ayespi** [comment]
I ran that command with "heroku" in front of it and all of my data from seed file is not populating... I changed my models manually on in development an I had to do db:migrate:reset... Do you think that is related to this issue???

**Comment by amaseda** [comment]
Try...

``` bash
heroku run rake db:migrate
heroku run rake db:seed
```

> Make sure to use `run`

**Comment by ayespi** [comment]
No go... Any more tricks???

**Comment by jshawl** [comment]
what do you mean by no go - any error messages? how do you know it didn't work?

**Comment by ayespi** [comment]
It did not work and there were nothing apparently wrong...

**Comment by ayespi** [comment]
Thanks for your help!
