### ISSUE TITLE
Re-routing default root after sign up

### ISSUE THREAD

**Issue by kristinmaripasive** [ga-wdi-exercises/project4#296]
Is it possible to customize the default redirect for gem devise after signing up? Since I'm trying to do the alternative for the issue I had yesterday... this is what I thought of doing.

**Comment by nolds9** [comment]
Seems like this is doable, https://github.com/plataformatec/devise/wiki/How-To:-redirect-to-a-specific-page-on-successful-sign-in

**Comment by kristinmaripasive** [comment]
I keep getting uninitialized constant errors with my controllers. I checked the spelling and everything. Is there another reason for this error?

**Comment by jshawl** [comment]
can you paste error message - maybe filename is incorrect?

**Comment by kristinmaripasive** [comment]
All my devise controllers are inside a folder named Users

![screen shot 2016-08-12 at 10 55 21 am](https://cloud.githubusercontent.com/assets/19437889/17626454/52459c8a-607b-11e6-9f18-f13863325d10.png)

**Comment by jshawl** [comment]
what does config/routes.rb look like?

**Comment by kristinmaripasive** [comment]
```
Rails.application.routes.draw do

  root to: "main#show"
    resources :main, only: [:index, :show]

    devise_for :users, controllers: {
         sessions: 'users/sessions'
       }

  resources :artists do
    resources :arts
  end
  resources :musicians do
    resources :musics
  end
  resources :collabs

end
```

**Comment by jshawl** [comment]
do you have a folder named `users` inside `app/controllers`?

**Comment by kristinmaripasive** [comment]
oh it was named `Users`... I now changed it to `users`, now it's giving me this error:
`undefined local variable or method `params' for User::SessionsController:Class`

**Comment by jshawl** [comment]
ok great! progress!

**Comment by jshawl** [comment]
does `User::SessionsController` inherit from application controller?

**Comment by kristinmaripasive** [comment]
It's inheriting from `Devise::SessionsController`

**Comment by kristinmaripasive** [comment]
I added this to the controller, wanting to customize redirect. Is it complaining about that?

```
Add below snippet to new action of Devise::SessionsController if you want to customise redirect url

if params[:redirect_to].present?
  store_location_for(resource, params[:redirect_to])    
end
```

**Comment by nolds9** [comment]
maybe that snippet is throwing the error, try commenting it out and see if it goes away

**Comment by kristinmaripasive** [comment]
If I delete it, it gives me this:

```
Unable to autoload constant Users::SessionsController, expected /Users/kristinpasive/wdi/projects/maestropiece/app/controllers/users/sessions_controller.rb to define it
```
