### ISSUE TITLE
gh-pages deployment issues

### ISSUE THREAD

**Issue by alpha2262** [ga-wdi-exercises/project4#298]
gh-pages re-deployment issues, error message below:

https://github.com/alpha2262/carbegone/tree/master

error: failed to push some refs to 'git@github.com:alpha2262/carbegone.git'
hint: Updates were rejected because the tip of your current branch is behind
hint: its remote counterpart. Integrate the remote changes (e.g.
hint: 'git pull ...') before pushing again.
hint: See the 'Note about fast-forwards' in 'git push --help' for details.

**Comment by jshawl** [comment]
Git pull to update local repo

**Comment by alpha2262** [comment]
It's now saying the submodule 'carbegone' was not properly initialized with a '.gitmodules' file.

https://github.com/alpha2262/carbegone/tree/gh-pages

**Comment by alpha2262** [comment]
Got it working, not entirely sure how I duplicated the file structure, but deleting the carbegone folder solved it
