### ISSUE TITLE
Passport-local authentication in Express, using Angular

### ISSUE THREAD

**Issue by msteffan** [ga-wdi-exercises/project4#3]
I have been stuck since last night trying to get user authentication using Passport to work. I have a form in an Angular view that should send information via a POST request to a particular URL to authenticate via Passport. I've tried to console.log the errors in my terminal, but it doesn't log anything at all.

I followed the Passport-local docs (here: https://github.com/jaredhanson/passport-local), and my code is as follows:

app.js:

```
var passport = require("passport");
var LocalStrategy = require("passport-local");
passport.use(new LocalStrategy(
  function(username, password, done) {
      console.log(username, password);
      db.models.User.findOrCreate({where: {
          name: username,
          pass: password,
          session: true
      }}).then(function(err, user) {
        // console.log(user);
        // console.log(err);
        if (err) { return done(err); }
        if (!user) { return done(null, false); }
        if (user.verifyPassword(password)){ return done(null, false); };
        return done(null, user);
    });
}));

passport.serializeUser(function(user, done) {
  done(null, user);
});

passport.deserializeUser(function(id, cb) {
  db.models.User.findById(id, function (err, user) {
    if (err) { return cb(err); }
    cb(null, user);
  });
});

app.use(passport.initialize())
app.use(passport.session())

app.post('/login',
  passport.authenticate('local', { failureRedirect: '/' }),
  function(req, res) {
      console.log(res);
    //res.redirect('/');
  });
```

User model:

```
module.exports = function(sequelize, Sequelize){
  return sequelize.define("user", {
    name: Sequelize.STRING,
    pass: Sequelize.STRING
  });

}
```

angular users controller: 

```
  userControllers.controller('newUserController', ['User', "$http", "$scope", function(User, $http, $scope) {
      this.createUser = function(){
          var user = {
              username: $scope.user.username,
              pass: $scope.user.password
          }
          console.log(user);
          $http.post("/login", {name: user.username, pass: user.pass}).then(function(response){
              console.log(response);
          })
      }
  }]);

```

**Comment by RobertAKARobin** [comment]
I'd break this down and start adding things in piecemeal to see where things stop working. The first thing I want to do is make sure the POST request is working in the first place. So I'd do something like:

``` js
app.post('/login', function(req, res){
  res.send("The post worked! Here's what I got: " + JSON.stringify(req);
});
```

If that works, then your `$http.post` in Angular should log that `res.send`.

Try that, and let me know what happens.

**Comment by msteffan** [comment]
The post route is working, and the request is sending across name and password data in the request body.

**Comment by RobertAKARobin** [comment]
Cool, one thing to cross off the list. Any chance you could push your code to Github? I'd like to throw some spaghetti at the wall.

**Comment by msteffan** [comment]
Sure. The code is here: https://github.com/msteffan/sourceFourth

If you run `npm install`, then `nodemon app.js` , and go to http://localhost:3000/#/users/new, you'll see the form for adding a new user. Currently, it is adding users to the database but sending a "POST http://localhost:3000/users/ 500 " error. Basically I'm not sure what's happening anymore :/

**Comment by msteffan** [comment]
Oh, sorry—you'll also need to `createdb sourceFourth` and run `node db/migrate` to get the tables set up.

**Comment by RobertAKARobin** [comment]
Man, this is weird. I'm going through all the documentation for this.

**Comment by RobertAKARobin** [comment]
Welp, I'm not sure what the problem is. So in your shoes, what I'd do is copy the working `server.js` [from the example](https://github.com/passport/express-4.x-local-example/blob/master/server.js) and just start copying and pasting my code into it.

**Comment by RobertAKARobin** [comment]
This seems to be working:

``` js
passport.use(new LocalStrategy(
  function(username, password, done) {
    db.models.User.findOrCreate({where:{ username: username, password: password } }).then(function(response){
      return done(null, response[0].dataValues);
    });
  }
));
```

...but I'm not entirely sure why. My guess is just passport-local doesn't play very friendly with Sequelize. You might consider https://github.com/madhurjain/passport-local-sequelize

**Comment by msteffan** [comment]
Ah, ok :( at least it's not just me. Only thing I can thing is that this
particular passport is getting messed up by the Sequelize .findOrCreate()
method, so this afternoon I'll try replacing that with a separate post
request to create an account and just using passport to authenticate after
its created.

Thanks for digging into it!

On Monday, September 14, 2015, Robert Thomas notifications@github.com
wrote:

> Welp, I'm not sure what the problem is. So in your shoes, what I'd do is
> copy the working server.js from the example
> https://github.com/passport/express-4.x-local-example/blob/master/server.js
> and just start copying and pasting my code into it.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/ga-dc/pbj-project4/issues/3#issuecomment-140136820.

## 

_email *// msteffan2012@gmail.com
*cell *// (206) 498-7863
*twitter_ https://twitter.com/melissasteffan // _LinkedIn_
http://www.linkedin.com/pub/melissa-steffan/4b/567/9aa
