### ISSUE TITLE
Can't pass rails JSON to angular

### ISSUE THREAD

**Issue by Ryan-321** [ga-wdi-exercises/project4#30]
I have two controllers that are maintaining my database and rendering JSON to my screen for those models.  I tried setting up angular to the same endpoint as where the JSON was getting rendered, but it kept getting overridden by JSON from rails.

So, I set up another route and empty controller to render my Angular partial to, but now can't get that hooked up.   Just want to make sure this is the right path to go down, before I spend a lot of time trying to figure out why this isn't working.

**Comment by RobertAKARobin** [comment]
Are you getting any errors?

**Comment by jshawl** [comment]
can you paste your controller actions?

**Comment by RobertAKARobin** [comment]
I'm going to close this since we haven't heard from you in a while, Ryan...
