### ISSUE TITLE
Sequelize self joins

### ISSUE THREAD

**Issue by TyRyanR** [ga-wdi-exercises/project4#302]
Having trouble with "through" and "as".

1) Here is my USER model. As you can see in the classMethods.associate function, I am trying to create a self join for users to have friends.. 

```
module.exports = function(sequelize, DataTypes) {
  var user = sequelize.define('user', {
    email: DataTypes.STRING,
    username: DataTypes.STRING,
    password: DataTypes.STRING
  }, {
    hooks: {
      afterValidate: function(user) {
        var hash = bcrypt.hashSync((user.password, bcrypt.genSaltSync(10)));
        user.password = hash;
      }
    }
    classMethods: {
      associate: function(models) {
        user.hasMany(models.friendship);
        user.hasMany(models.user {as: "friends", through: models.friendship});
      }
    }
  });
  return user;
};
```

2) Then here in the friendships join table model, I am trying to connect to users twice, with one column being userId and one being friendID. I know I'm doing something wrong connecting the "as" and "through". Any help? Thanks

```
'use strict';
module.exports = function(sequelize, DataTypes) {
  var friendship = sequelize.define('friendship', {
    userId: DataTypes.INTEGER,
    friendId: DataTypes.INTEGER
  }, {
    classMethods: {
      associate: function(models) {
        friendship.belongsTo(models.user);
        friendship.belongsTo(models.user {as: "friend"});
      }
    }
  });
  return friendship;
};
```

**Comment by nayana487** [comment]
are you getting an error?

**Comment by TyRyanR** [comment]
Not yet. I haven't tried to run the code yet b/c I'm lost but I'll keep researching

**Comment by superbuggy** [comment]
you'll need to include`{foreignKey: "friend_id"}` along with `{as: "friend"}` I think

**Comment by superbuggy** [comment]
I would urge you to test what you have so far

**Comment by superbuggy** [comment]
I'm gonna close this but re-open if you have any more questions along this thread

**Comment by TyRyanR** [comment]
I got a quick question having to do with user self joins creating friendships. I've never done this particular model before, but it seems to me that since the friendship join table has two columns, one for friend1 and one for friend2, when the objective is to display all of any given user's friends on an index page, you have to query BOTH columns in the friendship table for that given user's ID..right? 

Because in one instance the given user could be the inviter to join the friendship, and in anothe rinstance the given user could be the invitee, both in seperate columns. So I would have to query through both columns for any given user's ID, and if that userID exists in friend1 column, I have to display all the users in the adjacent friend2 column, and vice versa.

Is this logic correct? Am I missing something? Thanks
