### ISSUE TITLE
difficulty scraping, either get nothing or [ ] 

### ISSUE THREAD

**Issue by skshultis** [ga-wdi-exercises/project4#303]
Here's my repo: [https://github.com/skshultis/Project4](url)

I'm trying to scrape this crime incident data from DC open data (yes there is an api, I want to write a scraper because I've never done it, and it was fun until like, 11 AM today). [http://opendata.dc.gov/datasets/dc3289eab3d2400ea49c154863312434_8?uiTab=table](url)

In the disgusting mess that scrape.py has become you'll find various attempts to get anything more than an empty array. 

Nayana suggested the lesson repo on web scraping, which led me to these lines, which frustratingly return nothing whatsoever. 

```
soup = BeautifulSoup(html, "lxml")
for data in soup.findAll('div', {'class': 'ui-widget-content slick-row odd'}):
    text = data.findChildren()[0].renderContents()
    print text
```

Please advise.

-Sarah

**Comment by superbuggy** [comment]
Are you targeting the right thing? what is contained in this class? what are you expecting this to return --Nayana

**Comment by skshultis** [comment]
![nesteddivs](https://cloud.githubusercontent.com/assets/18028304/18451032/66aff56c-7903-11e6-8a7a-90902da0e8f8.png)

Each of these row divs contains 13 child divs that contain the data for one crime incident, each looks like this (with different numbers for rows and columns):

```
<div class="slick-cell l0 r0">16152340</div>
```

The rows alternate class names 'ui-widget-content slick-row odd' and 'ui-widget-content slick-row even'; if I change my code to data.renderContents() on one specific child div of a row I get nothing (not even sure if that's supposed to work). I felt like I was closer when I was getting empty arrays?

**Comment by nayana487** [comment]
your code says `slick-row-odd` this is even.

**Comment by skshultis** [comment]
I've tried both with the same result.

**Comment by nayana487** [comment]
you have this stuff in there?

``````
import urllib
from bs4 import BeautifulSoup
url = 'https://your_url_here'

html = urllib.urlopen(url).read()
soup = BeautifulSoup(html,"html.parser")```
``````

**Comment by skshultis** [comment]
```
import requests
# from lxml import etree
import urllib
from bs4 import BeautifulSoup

url = 'http://opendata.dc.gov/datasets/dc3289eab3d2400ea49c154863312434_8?uiTab=table'
# headers = {'User-Agent': 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_11_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/52.0.2743.116 Safari/537.36'}
# response = requests.get(url, headers=headers)
# data = response.text
html = urllib.urlopen(url).read()

#importing lxml was recommended to parse html rather than just soup = bs4.BeautifulSoup(html)
soup = BeautifulSoup(html, "html.parser")
for data in soup.findAll('div', {'class': 'slick-row-odd'}):
    text = data.findChildren()[0].renderContents()
    print text
```

Yes, that's all there. I was originally importing urllib2, using either gets the same result.

Sorry this has so many commented out lines, I wanted to keep the ones that yielded more than others.

**Comment by skshultis** [comment]
when I run it I get this:

Sks-MacBook-Air:p4 skshultis$ python scrape.py
Sks-MacBook-Air:p4 skshultis$ 
So, nothing.
