### ISSUE TITLE
Users and friendships

### ISSUE THREAD

**Issue by TyRyanR** [ga-wdi-exercises/project4#307]
I got a quick question having to do with user self joins creating friendships. I've never done this particular model before, but it seems to me that since the friendship join table has two columns, one for friend1 and one for friend2, when the objective is to display all of any given user's friends on an index page, you have to query BOTH columns in the friendship table for that given user's ID..right? 

Because in one instance the given user could be the inviter to join the friendship, and in anothe rinstance the given user could be the invitee, both in seperate columns. So I would have to query through both columns for any given user's ID, and if that userID exists in friend1 column, I have to display all the users in the adjacent friend2 column, and vice versa.

Is this logic correct? Am I missing something? Thanks

**Comment by andrewsunglaekim** [comment]
I think that's about right. It depends if you have uni directional friendships or not. 

IE, if i friend someone, do they automatically become my friend? (unidirectional, easier less good)

or do they need to accept? Then it works both ways. In which case you will need to query both columns. 

There are lots of different ways to do friending

**Comment by TyRyanR** [comment]
It's definitely bi-directional and figured out I need a status column in the friendship too for pending vs active friendships. Awesome thanks.

**Comment by TyRyanR** [comment]
*New question same subject.
Any reason why I can console log var friends in the first line of the then function, and it shows me the object in the array, yet when I try to log var friends OUTSIDE of the friendships.forEach function...I get an empty array? I am expecting friends to be an array filled with at least one object... Thanks

```
index: function(req, res) {
    friendship.findAll({
      where: {
        status: "pending",
        $and: {
          $or: [
            {
              userId: req.session.user.id
            },
            {
              friendId: req.session.user.id
            }
          ]
        }
      }
    }).then(function(friendships) {
      var friends = [];
      friendships.forEach(function(friendship) {
        if (req.session.user.id === friendship.userId) {
          user.findById(friendship.friendId).then(function(user) {
            friends.push(user);
            console.log(friends); // WORKS
          })
        } else {
          user.findById(friendship.userId).then(function(user) {
            friends.push(user);
          })
        }
      })
      console.log(friends); // DOESN'T WORK
    })
```

**Comment by superbuggy** [comment]
move `var friends = [];` up to first line of the index function

**Comment by TyRyanR** [comment]
Hey thanks for the response but it's still showing an empty array

**Comment by TyRyanR** [comment]
Oh shoot.. just got an idea. Since the .then() is returning a promise, the synchronous nature causes that to return something probably very, very shortly after the entire index function is run. Since I'm console.logging outside of the promise, that console.log is probably getting ran with the empty array before the database query happens.

Any work around for this?

**Comment by TyRyanR** [comment]
Could use some in person help real quick because I think it has to do with my associations setup. I'm having trouble grasping the concept of an inner join and therefore utilizing it.

**Comment by andrewsunglaekim** [comment]
ill take a look
