### ISSUE TITLE
Deploying rails API

### ISSUE THREAD

**Issue by aubreynortham** [ga-wdi-exercises/project4#308]
I have a react app pulling in 2 APIs, one is an outside source and the other I created with rails. The API directory I made is separate from the React app directory, but they are both in a parent directory and that parent directory is where the .git folder is (so both rails and react have been tracked in the same remote repo). I'm now trying to deploy my rails API, but don't want heroku to try and deploy the whole thing. First idea is to clone down my repo and delete all but the rails, then deploy that. Is there a less hacky way you'd recommend doing this, or does this sound ok?

**Comment by andrewsunglaekim** [comment]
so taht sounds fine. And would probably recommend that way. 

An easier way (not recommeneded way) would be to do a `git init` on your rails app. And deploy that repo. You might get into some gitception though. I would go with your original thoughts.

Additionally, I get what you're trying to do as far as putting them both in the same folder, but let's think about this. Are they the same app? As soon as you made a decision to put them in separate folders, you made the decision that they are different apps. In doing so they should be version controlled separately. One is your front end application, the other is your backend application.

**Comment by superbuggy** [comment]
you could also check out a new branch for deploying one part of the app, and removing the other parts. it then becomes very, very important to be aware what branch you are on at all times.

**Comment by andrewsunglaekim** [comment]
going to close this issue, plz reopen if you need further guidance on this. @aubreynortham
