### ISSUE TITLE
showing data

### ISSUE THREAD

**Issue by danielanoir** [ga-wdi-exercises/project4#312]
I am trying to get my data to show on the server localhost:5000/index. When I try to run the server I get an error with the following: 

GET http://localhost:5000/test.js 
GET http://localhost:5000/test.js 404 (Not Found)

I tried creating a test file and just console.logging something but I get the same error and/or the app crashes. I also messed with the path in my index.hbs script, but it didn't help. 

Below is my script tags: 

`<script src="../chart.js"></script>
  <script src="../test.js"></script>`

Here is my file structure: 

![image](https://cloud.githubusercontent.com/assets/20133878/18488107/05fae8bc-79c6-11e6-97b8-41a8711bc9a8.png)

Below is my chart.js ajax request: 

```
$(function () {

  $.ajax({
    url: "http://localhost:5000/index",
    success: function(response){
      console.log(response);
      },
    dataType: "json"
  });

```

and lastly in index.js, this is how I get the data: 

```

`app.get("/index", function(req, res){
  res.render("index");
  connection = new Connection(config.db);
  connection.on('connect', function(err) {
      console.log("Connected for GET");
        getSqlData(connection, function(err, json) {
      res.send(json);
    });
  });
});

function getSqlData(connection, callback) {
  var sql = "select station, x, y from mtr.coordinates for json path"
  var request = new Request(sql, function(err, rowCount) {
    if (err) {
      return callback(err);
    }
    json = JSON.parse(data);
    callback(null, json)
    json = {};
    connection.close();
  });
  request.on('row', function(columns) {
      columns.forEach(function(column) {
          data += column.value;
      });
  });
connection.execSql(request);
}`

```

**Comment by nayana487** [comment]
i'll come look
