### ISSUE TITLE
Help Hiding and Showing React Components

### ISSUE THREAD

**Issue by EvanSanderson** [ga-wdi-exercises/project4#314]
Hiyo,

Would love some help hiding and showing react components based on state. Not urgent, but if anyone has a spare few minutes.

**Comment by superbuggy** [comment]
What about the state determines if it is hidden or shown?

**Comment by EvanSanderson** [comment]
Nothing yet, but for example: I'd ultimately like to only show the Story Create Form component if a prompt component is rendered.

**Comment by EvanSanderson** [comment]
because you should only be able to create stories inside of prompts.

**Comment by nolds9** [comment]
In the the container component `render` method, you could conditionally render something based on state. see https://github.com/ga-wdi-exercises/react-omdb/blob/solution/src/SearchContainer.js#L41 for an example

**Comment by superbuggy** [comment]
Have the prompt component pass a boolean value to  a prop (like `amIVisible` for instance) on the story component state.

**Comment by EvanSanderson** [comment]
got it. basically I used Nicks example and said after render: if(this.state.prompt.body !==undefined) { return (element) } else { return (empty div)}

Thanks guys!
