### ISSUE TITLE
Update Form In React

### ISSUE THREAD

**Issue by EvanSanderson** [ga-wdi-exercises/project4#318]
I'd like the input box in the update form of PROMPTS to contain the current value of the prompt so that users can make edits to the existing prompt (and not have to start from scratch). Currently, it shows the value when the form is invoked, but when I go type in a new value, it reverts to an empty string. Would love some feedback:

```
class UpdatePromptForm extends Component {
  constructor(){
    super()
    this.state = {
      prompt: []
    }
  }
  componentDidMount = () =>{
    this.fetchState()
  }
  fetchState = () => {
    this.setState({
      prompt: this.props.prompt
    })
  }
  updateChange=(e)=> {
      this.setState({
        prompt: e.target.value
      })
  }
  onUpdatePrompt=(e)=> {
    e.preventDefault();
    var promptText = this.state.prompt
    this.props.updatePrompt(promptText);
    this.state.prompt = "";
    this.props.undoUpdate();

  }
  render(){
    return(
      <form className = "updateForm" onSubmit={(e) => this.onUpdatePrompt(e)} >
        <input
          type="text"
          onChange = {(e) => this.updateChange(e)}
          value={(this.state && this.state.prompt.body) || ''}
           />
          <button type="submit"> Update </button>
      </form>
    )
  }
}
```

**Comment by andrewsunglaekim** [comment]
in your set state of `updateChange`, your setting the prompt itself, not the prompts body

**Comment by EvanSanderson** [comment]
Yea i changed that and now its working. The issue now is that i can update, but when i update again, it goes back to the original prompt

**Comment by andrewsunglaekim** [comment]
what do you mean by update again? and what do oyu mean by i can update? is it updating in the database then reverting?

**Comment by EvanSanderson** [comment]
So I update it, its getting updated in back end , no probs. But lets say i update AGAIN. The value provided in the input box is the ORIGINAL value not the value i updated. 

So 
1. In the input box it says "FOX"
2. I update it to "BEAR"
3. I see that its updated.
4. I click update again
5. The value in the input box is "FOX"
