### ISSUE TITLE
Mapbox id not working in rails

### ISSUE THREAD

**Issue by chrislovett03** [ga-wdi-exercises/project4#32]
I've incorporated the mapbox API into my rails app, I successfully had the map rendered on my layout page with the preview coordinates. After choosing my style and saving my map on the website, I took my projects id and incorporated it per tutorial + mapbox instructions into my code. I'm getting the following errors:

GET http://a.tiles.mapbox.com/v3/clovett.ciemz9sg603sbssm2g0v6fm03.json 401 (Unauthorized)
util.js:10 could not load TileJSON at http://a.tiles.mapbox.com/v3/clovett.ciemz9sg603sbssm2g0v6fm03.json
![screen shot 2015-09-16 at 2 29 09 pm](https://cloud.githubusercontent.com/assets/12041606/9914390/b78d59b2-5c7f-11e5-9698-2ed66c504900.png)
![screen shot 2015-09-16 at 2 29 15 pm](https://cloud.githubusercontent.com/assets/12041606/9914391/b790c3a4-5c7f-11e5-9f64-5605522d6ba7.png)

**Comment by adambray** [comment]
Hey Christine, I know Jesse mentioned he might be helping you with this, but I noticed you are loading the mapbox library both through the asset pipeline (in the comments of app.js) and also as a script tag in your index.html. I'm wondering if you need both?

**Comment by chrislovett03** [comment]
Alright! That fixed it! :-) thanks, Adam.

**Comment by adambray** [comment]
Awesome, glad to hear! For the record, which did you delete, and which did you keep?

**Comment by chrislovett03** [comment]
I deleted the //require mapbox  and kept the link
