### ISSUE TITLE
hiding links if current user has not created object/resource

### ISSUE THREAD

**Issue by pamelaolney** [ga-wdi-exercises/project4#320]
Hi,

My repo link is as follows.

https://github.com/pamelaolney/makali/tree/master/makali

I am trying to hide my "edit" link for only the current_user that created that activity(my model).  Currently I have it so that only signed-in users can edit the activities but I am trying to restrict users to only edit what they created.  Not sure how to do that.

I came across this resource but I couldnt get it to work for my code.

http://stackoverflow.com/questions/22443520/how-to-only-edit-and-destroy-my-own-content-only

I would be happier if I could simply hide the edit button for only the user that created that activity.  I am thinking jquery would be good to use but I am not sure how to get jquery to recognize the current user.

A lot of resources keep telling me to use CanCan and/or devise but I dont feel like I have enough time to learn this while trying to get this thing done on time.

Here is my **activity index page**

```
<br>
<div class="activities">

<h2>Check out this list of things to do</h2>

<br>
<%= form_for [@user, @activity] do |f| %>

<%= f.label :title %>
<%= f.text_field :title %>


<%= f.submit :submit %>
<% end %>


<br>
<% @activities.each do |activity| %>
  <% if @current_user %>
    <div class="activelist">
      <%= link_to activity.title, activity_path(activity) %>
      <p id="edit">
        <%= link_to '(edit)', edit_activity_path(activity) %>
      </p>
    </div>
  <% else %>
  <div class="activelist">
    <%= link_to activity.title, activity_path(activity) %>
  </div>
  <% end %>
<% end %>
</div>
```

Here is my activity controller

```
class ActivitiesController < ApplicationController

  def index
    @activities = Activity.all
    @activity = Activity.new
  end

  def show
    @activity = Activity.find(params[:id])
  end

  def new
  end

  def create
    @activity = Activity.new(activity_params)
    @activity.save!
    redirect_to index
  end

  def edit
    @activity = Activity.find(params[:id])
  end

  def update
    @activity = Activity.find(params[:id])
    @activity.update(activity_params)
    redirect_to @activity
  end

  def destroy
    @activity = Activity.find(params[:id])
    @activity.destroy
    redirect_to @activity
  end


  private

  def activity_params
    params.require(:activity).permit(:title, :user)
  end

end

```

Please help.  Thanks

**Comment by andrewsunglaekim** [comment]
activities need user ids

**Comment by pamelaolney** [comment]
it works!!!  thanks so much Andy!!!
