### ISSUE TITLE
npm start error in Angular 2

### ISSUE THREAD

**Issue by RasheedaAlexander** [ga-wdi-exercises/project4#323]
Whenever I run npm start I get an error saying the following: 
"app/app.component.ts(7,36): error TS1005: ',' expected.
app/app.component.ts(7,38): error TS1002: Unterminated string literal.
app/app.component.ts(8,5): error TS1005: ':' expected.
app/app.component.ts(8,15): error TS1005: ',' expected.
app/app.component.ts(9,1): error TS1005: ':' expected.
app/app.routes.ts(9,22): error TS1005: ',' expected.
app/app.routes.ts(10,1): error TS1128: Declaration or statement expected.
app/main.ts(1,56): error TS1002: Unterminated string literal.
"

I've tried all of the suggestions on StackOverflow and even the issue section of the Angular 2 Quickstart repo but nothing works. 

Also, npm run lite works.

**Comment by andrewsunglaekim** [comment]
is there an issue with using npm run lite? you're using angular 2?

**Comment by RasheedaAlexander** [comment]
Npm run lite works fine. And yes, I'm using Angular 2.

**Comment by nolds9** [comment]
are you writing Typescript?

**Comment by RasheedaAlexander** [comment]
@nolds9 Yes I'm writing in TypeScript
