### ISSUE TITLE
XMLHttpRequest cannot load http://localhost:8989/api/miigrate/10. No 'Access-Control-Allow-Origin' header is present 

### ISSUE THREAD

**Issue by TylerRosenberg1** [ga-wdi-exercises/project4#324]
Full error message: 

XMLHttpRequest cannot load http://localhost:8989/api/miigrate/10. No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'http://localhost:8080' is therefore not allowed access. The response had HTTP status code 401.

How do I set that "access-control-allow-origin" header in my cors in express?

Thanks

**Comment by andrewsunglaekim** [comment]
[cors express](https://github.com/expressjs/cors)
