### ISSUE TITLE
Making changes to a Mongoose Schema

### ISSUE THREAD

**Issue by nickoki** [ga-wdi-exercises/project4#327]
First Issue!

I'm trying to make a change to my mongoose Schema (specifically to reference another Schema), but when I attempt to create, for example, new objects under the revised Schema definition it doesn't work.

There are no errors, the newly created object simply doesn't have the new attribute (reference).

Here's my DrinksSchema. I added `glass` and `created_at` as attributes, but when creating a new Drink, only `name` is saved.

```javascript
var DrinksSchema = new Schema({
  name: {
    type:     String,
    required: true,
  },
  glass: {
    ref: 'Glass',
    type: Schema.ObjectId,
  },
  created_at: {
    type:     Date,
    required: true,
    default:  Date.now(),
  }
})
```

**Comment by jshawl** [comment]
let's see the code where you create

**Comment by nickoki** [comment]
I'm creating via a POST request to my API

``` javascript
exports.post = (req, res) => {
  var drink = new Drink()
  drink.name = req.body.name
  Glass.findOne({ name: req.body.glass }, (err, res) => {
    console.log(res)
    if (err) res.send(err)
    else drink.glass = res._id
  })
  drink.save( err => {
    if (err) res.send(err)
    else res.json({ message: `Cheers! Drink posted successfully.` })
  })
}
```

`console.log(res)` returns the correct Glass, `drink.glass` just isn't saved

**Comment by jshawl** [comment]
wait so it's not saving in the database?

**Comment by nickoki** [comment]
Correct

**Comment by jshawl** [comment]
ok perfect - can you confirm that you can create things via postman? e.g. is it a your api issue or your client issue?

**Comment by nickoki** [comment]
I can create objects via Postman. The object still saves, just without a `glass` attribute.

**Comment by nickoki** [comment]
``` javascript
exports.post = (req, res) => {
  var drink = new Drink()
  drink.name = req.body.name
  Glass.findOne({ name: req.body.glass }, (err, res) => {
    if (err) res.send(err)
    else drink.glass = res._id
  })
  console.log(drink.glass)
  drink.save( err => {
    if (err) res.send(err)
    else res.json({ message: `Cheers! Drink posted successfully.` })
  })
}
```

Moving `console.log()` down returns undefined. Perhaps it's an issues with the callback?

**Comment by jshawl** [comment]
doesn't everything after your console.log need to be nested in that callback?

**Comment by nickoki** [comment]
That did the trick! I had to rename my second `res` variable to resolve a scoping issue -- is there a convention for that? #CallbackHell

**Comment by jshawl** [comment]
hmm not that I know of. with mongoose I try to name `res` something like what comes from the db, in this case `glass`

**Comment by nickoki** [comment]
Excellent. Thank you for your help!
