### ISSUE TITLE
ng-click, scope, and other Angular stuff 

### ISSUE THREAD

**Issue by M00staff** [ga-wdi-exercises/project4#33]
So i think i coded myself into a box ..

the ng-click on a show populates the songs from that show (below)

However, i need to click the show in order to get info from it to play and it keeps just firing the original ng-click when i click a show. 

I cannot seem to find a way to display the songs in a different div for some reason (can't i bind it or something?)

```
<div class="showList" ng-controller="showController">
  <ul>
    <li ng-repeat="show in shows" ng-click="go(show.identifier)" ng-controller="songController">
      {{show.title}}
          <ul>
            <li ng-repeat="song in songs | orderBy: 'songFile'">
              {{ song.songTitle }}
              <get-song-d></get-song-d>
            </li>
          </ul>
    </li>
  </ul>
</div>
```

If i try to display {{ song.songTitle }} anywhere else it doesn't work - even if i put it within another songController. 

It seems like it has to be nested under the {{show.title}} to display.  could this be because the ng-click takes an argument from the {{show.title}}?

![screen shot 2015-09-16 at 2 54 22 pm](https://cloud.githubusercontent.com/assets/12723877/9915052/e7714b36-5c82-11e5-9ae9-b637313e05e9.png)

songController

```
app.controller('songController', ['$http', '$scope', function($http, $scope) {
    $scope.go = function getSongNow(showID) {
      console.log('https://archive.org/metadata/' + showID + '?callback=JSON_CALLBACK');
      $http.jsonp('https://archive.org/metadata/' + showID + '?callback=JSON_CALLBACK')
      .then(function(response) {
        //var songs = response.data.files;
        //console.log(songs);
        // var songs = response.data.files;
          var songList = [];
        $.each(response.data.files, function getSong(i, val) {           //iterate and add name and title to variables
          var fileName = val.name;
          var songName = val.title;
          // console.log(songName);
          // console.log(fileName);
          var ext = fileName.substr(fileName.lastIndexOf('.') + 1);   //check file type - looks at everything after '.'

            if ((ext === 'ogg' || ext === 'mp3') && songName != undefined) {
              songList.push({songTitle: songName, songFile: fileName});
              //songList.push({songTitle: songName, songFile: fileName})
              //songList += '<li class="songs-li" data-song-title="' + songName + '" data-song-src="' + fileName + '">' + songName + '</li>';
              //$scope.songs = songList;
              console.log(songList);
              $scope.songs = songList
            }
          })
        })
    }
} ])
```

**Comment by M00staff** [comment]
let me know what clarification you need as that looks really confusing

**Comment by RobertAKARobin** [comment]
What do you mean when you say "it doesn't work"? Are you getting errors? If so, what?

**Comment by M00staff** [comment]
no errors - i just can't click on the individual songs - or put an ng-click on them

**Comment by M00staff** [comment]
oh wait

**Comment by M00staff** [comment]
it doesn't work as in does not display - no errors

**Comment by RobertAKARobin** [comment]
Cool! Have you done `console.log(response)` yet just so see what the response actually looks like?

**Comment by M00staff** [comment]
where would i put that?

I'm gettting the correct responses from my AJAX calls

**Comment by M00staff** [comment]
i want 

```
<li ng-repeat="song in songs | orderBy: 'songFile'">
              {{ song.songTitle }}
```

to display in a separate div on the Index

**Comment by M00staff** [comment]
i tried putting it in a Custom directive and in a partial view and nothing displays (no errors either)

**Comment by RobertAKARobin** [comment]
Right after `.then(function(response) {`. I wanted to make sure the responses are correct. But there's data in the screenshot you included above, so I assume they are working. My mistake!

Can you push your code to GH so I can look at it?

**Comment by M00staff** [comment]
https://github.com/M00staff/bpStreams-Project4/tree/reallyOutThere

**Comment by M00staff** [comment]
oh and theres a lot of throw away and save for later code - let me know if you need me to clear it up

**Comment by RobertAKARobin** [comment]
Sorry, Moose, got caught up with stuff. Investigating now.

**Comment by RobertAKARobin** [comment]
Hm. This seems to be working really well for me... I'm having no trouble playing songs. I'm not sure what the trouble is?

**Comment by M00staff** [comment]
wrong branch

**Comment by M00staff** [comment]
should be the reallyOutThere branch

**Comment by M00staff** [comment]
the master branch was written in jQuery soup to make sure the project was possible

**Comment by RobertAKARobin** [comment]
Niiiiiiiice

**Comment by RobertAKARobin** [comment]
Just to be sure: the problem is that you can't click inside of a show without triggering that `ng-click`, right?

So how about this:

``` html
    <ul>
      <li ng-repeat="show in shows" ng-controller="songController">
        <div ng-click="go(show.identifier)">{{show.title}}</div>
        <ul>
          <li ng-repeat="song in songs | orderBy: 'songFile'">
            {{ song.songTitle }}
          </li>
        </ul>
      </li>
    </ul>
```

That is: putting the `ng-click` in its own little div, instead of on the parent container.

**Comment by M00staff** [comment]
interesting - what does the AAA and BBB do?

**Comment by RobertAKARobin** [comment]
Oh, whoops, I forgot to remove that. It does literally nothing. I just couldn't keep straight what was repeating where.

This is looking really good, by the way!

**Comment by M00staff** [comment]
awesome - that worked!!

i should be able to add an ng-click to this correct?

```
<li ng-repeat="song in songs | orderBy: 'songFile'">
            BBB {{ song.songTitle }}
```

**Comment by M00staff** [comment]
then whats different?

**Comment by RobertAKARobin** [comment]
Before, the `ng-click` was on the top-most `<li>`. Now, the `ng-click` is on a `<div>` inside the `<li>`.

And yes, I think you should, but if that doesn't seem to be working, try doing the above again.

**Comment by M00staff** [comment]
awesome, thank you sir!

**Comment by RobertAKARobin** [comment]
The difference is if I do `<body ng-click="whatever">`, then literally everything on my webpage will fire the click event. So you need to isolate it to one particular element.
