### ISSUE TITLE
Event interval needs to refresh Front end

### ISSUE THREAD

**Issue by merubin** [ga-wdi-exercises/project4#330]
I have an interval in the backend that is getting values every 15 seconds.  I'm not sure from express how to cause the browser to refresh the data or cause it to ask again for the "/" page where it will get  the latest  version.

Here is the interval code:
```js
setInterval(function(){
  request(options)
    .then(function (response){
      console.log(response)
      latestresponse=response
    })
    .catch(function (err) {
      console.log(err)
    })
}, 15 * 1000);
```

Here is the  app.get to display

```js
app.get ("/", (req,res) => {
  console.log("get /")
  console.log("response=",latestresponse)
res.render("main", {latestresponse});
});
```

I cannot call render from the interval event,

Any hints?  or what to google?

Thanks

**Comment by amaseda** [comment]
To make sure I understand correctly (and please tell me if I am not!) are you trying to force the browser to refresh whenever the `latestResponse` value is updated on the back end?

The browser will only respond to something happening on the back-end if a request is sent in the first place.

Sounds like this could be a use case for WebSockets (i.e., you want something to happen on the front-end when something changes on the back-end, but without having to send a request).

**Comment by merubin** [comment]
Yes that is correct.  The back end is monitoring temp pressure and other parameters.  When there is a change, I want ot update display on web page.  I guess I could see web-sockets used.  I’ll look at that now.

**Comment by amaseda** [comment]
:+1: Going to close this one for now but feel free to re-open / submit a new issue depending on where this take you next!
