### ISSUE TITLE
websockets  Client code HTML <script> js file cannot be fournd

### ISSUE THREAD

**Issue by merubin** [ga-wdi-exercises/project4#331]
I moved the javascript that was in a sample code HTML file to its own .js file and put it in the same directory as the .html file.

```
<body>
  <h1>TITLE</h1>
  ...
  <script src="https://code.jquery.com/jquery-1.10.2.js"></script>
  <script src="/socket.io/socket.io.js"></script>
  <script src="client.js"> </script>
</body>
</html>
```

Before the code that was in the client.js file was in the HTML file.  Now the file cannot be found.

![image](https://cloud.githubusercontent.com/assets/19254862/20444566/87eaa5bc-ad9f-11e6-9813-d930167c4d84.png)

I have a lot of code and don't want to put it in the HTML file.

**Comment by jshawl** [comment]
do you have a file names client.js in your public/ folder

**Comment by merubin** [comment]
No I said it was in the root.  I don't have a public folder. so I will create one and try that!

**Comment by jshawl** [comment]
only assuming you're using express - can you provide more info about your file structure?

**Comment by merubin** [comment]
![image](https://cloud.githubusercontent.com/assets/19254862/20444798/7a5f4d2a-ada0-11e6-94f3-595a550263f1.png)

I'm using iosockets and express now

**Comment by merubin** [comment]
I created the public folder now and put in the file but same issue

**Comment by jshawl** [comment]
``` js
app.use(express.static("public"))
```

**Comment by merubin** [comment]
The code sample that I am using has this:

app.use(express.static(__dirname + '/bower_components'));

So I need to move everything that is in /bower_components to public correct?

**Comment by jshawl** [comment]
try it out!

**Comment by merubin** [comment]
Success!
