### ISSUE TITLE
Database not showing

### ISSUE THREAD

**Issue by griffind2009** [ga-wdi-exercises/project4#332]
I am in mongo in the terminal but my database is not showing, I can see other databases that I have created.  When I run node db/seed.js I don't get any errors. I cannot see my db when I go to show dbs but I don't see any errors that the db isn't connected.  In the terminal it says "connected to mongodb.

![screen shot 2016-11-18 at 4 10 43 pm](https://cloud.githubusercontent.com/assets/20979785/20446845/a4a4fd24-ada9-11e6-8aba-c5a16940f967.png)

![screen shot 2016-11-18 at 4 10 17 pm](https://cloud.githubusercontent.com/assets/20979785/20446862/b1083932-ada9-11e6-9645-fe53d6bd54d9.png)

**Comment by nolds9** [comment]
Can you share your `db/seed.js` and any relevant dependent code?

**Comment by griffind2009** [comment]
![screen shot 2016-11-18 at 4 16 35 pm](https://cloud.githubusercontent.com/assets/20979785/20446995/6b879f82-adaa-11e6-94e3-c0c53643bd7e.png)
![screen shot 2016-11-18 at 4 17 01 pm](https://cloud.githubusercontent.com/assets/20979785/20447007/7eca94b4-adaa-11e6-8805-e24bb15a92e1.png)

**Comment by griffind2009** [comment]
the one above is my seed and the code below is my connection file

**Comment by jshawl** [comment]
remove the `process.exit()` from the bottom of your seed file. `.create` is asynchronous

**Comment by nolds9** [comment]
@griffind2009 this issue is the `process.exit()` at the end of your seeds file!

**Comment by griffind2009** [comment]
awesome! that worked, thanks

**Comment by griffind2009** [comment]
will have to ctrl c to exit anytime i change my seed file now?

**Comment by nolds9** [comment]
or call `process.exit()` **after** the last creation happens

**Comment by nolds9** [comment]
or you can use bulk creation following the example we did in class here https://github.com/ga-wdi-lessons/express-mongoose#questions-1

**Comment by griffind2009** [comment]
oh ok, great! thank you
