### ISSUE TITLE
Rendering an object in browser

### ISSUE THREAD

**Issue by griffind2009** [ga-wdi-exercises/project4#333]
I am trying to render the data in my database in the browser, but it showing as an object.
Below I have a screen shot of what it looks like in the browser and my code in index.js and show-questions.hbs.

![screen shot 2016-11-21 at 10 40 00 am](https://cloud.githubusercontent.com/assets/20979785/20489041/356e310c-afd7-11e6-9259-625fe0d15153.png)

![screen shot 2016-11-21 at 10 40 10 am](https://cloud.githubusercontent.com/assets/20979785/20489052/4099f2f0-afd7-11e6-88c2-0ce512973bd8.png)

![screen shot 2016-11-21 at 10 40 24 am](https://cloud.githubusercontent.com/assets/20979785/20489058/4345281c-afd7-11e6-9983-e93dee802e4e.png)

**Comment by nolds9** [comment]
looks like `questions` is an array of question objects. If you are using handlebars, trying using the `each` view helper to view each question in that array

**Comment by griffind2009** [comment]
This is the documentation that I found http://handlebarsjs.com/block_helpers.html. Is there any other documentation that explains the each method within the http request in express?

**Comment by nolds9** [comment]
That looks right, try it out! Since you know you have the data, you should be able to iterate over that array and display each Question

http://handlebarsjs.com/builtin_helpers.html

**Comment by griffind2009** [comment]
What would be the correct syntax for 'each'.  I tried placing it before the the two arguments like so app.get('/questions',  'each', (req, res) but go an error. I tried placing it after (req, res)  and got another error.

**Comment by nolds9** [comment]
That `each` block should go in the view...

**Comment by nolds9** [comment]
It's the same idea of using `<%= questions.each do |question| %>` in ERB like we did in Ruby on Rails, instead we have to use the `each` handlebars helper in the view

**Comment by griffind2009** [comment]
ok, i tried putting the each helper method in the show-question.hbs view, but it still shows as an object.
I tried it without the keys in the schema and then I tried it with the keys.

![screen shot 2016-11-21 at 11 31 25 am](https://cloud.githubusercontent.com/assets/20979785/20491166/83f94292-afde-11e6-9b5b-186216f1f655.png)

![screen shot 2016-11-21 at 11 34 31 am](https://cloud.githubusercontent.com/assets/20979785/20491173/88ebe64c-afde-11e6-8ce8-0bb099176ee1.png)

**Comment by nolds9** [comment]
ok, you're on the right track! I think if you want to refer to the individual `question` you need to use `this` inside of the each block... i.e.

```html
<div class="questions">
 {{#each questions}}
  <p>{{ this._id }}</p>
  <p>{{ this.topics }}</p>
{{/each}}
</div>
```

note that `topics` is also an array

**Comment by griffind2009** [comment]
ok. i am trying to list all of the questions in the database. i just tried that but now I get the id at the top of the page as well as the object still. 
 
![screen shot 2016-11-21 at 11 55 36 am](https://cloud.githubusercontent.com/assets/20979785/20492087/70fa8342-afe1-11e6-9e68-5ae3f36ed07a.png)

**Comment by nolds9** [comment]
so this is great, it looks like each `question` only has `_id` and `topics` properties, and just based on the data output, no question currently has any topics associated to it.

You are still seeing the entire `questions` object, because somewhere in your code you have `{{questions}}` still

**Comment by griffind2009** [comment]
hmm, i don't think i follow.  i thought i needed questions because I want to show all of the questions not just one.  when i changed all of the {{questions}} to {{question}} nothing changed. 

i have a separate view for topics. on the questions page i just want to list all of the questions without topics.

**Comment by amaseda** [comment]
The reason you are not seeing any topics is because none of your questions appear to have any topics. Can you try adding some to your questions? You should start seeing them in your view after that. But as far as I can tell your `each` statement is working properly because we are seeing the `_id`s.

The reason you're seeing that list of objects in your view is probably because you still have `{{questions}}` by itself somewhere in your view.

Hopefully that clarifies, but let me know if not!

**Comment by griffind2009** [comment]
Sorry I may have explained that incorrectly.  In my app.get('/questions') route, I would like to list all of the questions that do not have a topic associated with them. I have another route app.get('/topics') that will list questions by their topics.  Should I just take out the "topics: [topicSchema]" from my Question Schema in my connection file? I added that in the case that so when a user creates new Questions that can give it a topic.

![screen shot 2016-11-21 at 1 16 07 pm](https://cloud.githubusercontent.com/assets/20979785/20494826/b38910ce-afec-11e6-80a7-78d7d2fc82d6.png)

**Comment by nolds9** [comment]
I'm confused, if you're doing a one to many relationship between Topic and Question, so that a question belongs to a topic. That would imply that `questions` should be a sub document of topic

**Comment by griffind2009** [comment]
oh ok, even if not every question belongs to a topic
