### ISSUE TITLE
Arrays in Schema

### ISSUE THREAD

**Issue by pohckuan** [ga-wdi-exercises/project4#334]
I have a recipe schema that includes lists of ingredients and directions. Instead of creating ingredient and direction schema, can I just turn the ingredient and direction into arrays like what I have below? 

![image](https://cloud.githubusercontent.com/assets/15622467/20489595/335edae0-afd9-11e6-8542-eff8487f4eee.png)

**Comment by amaseda** [comment]
Haven't tried that myself but take a look at this StackOverflow post: http://stackoverflow.com/questions/35509611/mongoose-save-array-of-strings

Looks like you can do something along these lines...

```js
var personSchema = new mongoose.Schema({
tags: [{
    type: String
}]
```

Let me know how that goes!

**Comment by pohckuan** [comment]
below are the updated schema and seeds in json format. Could you remind me how to render the json data in the browser? Thanks!
![image](https://cloud.githubusercontent.com/assets/15622467/20490452/0e7e27fa-afdc-11e6-8d6f-0c5829239d39.png)

![image](https://cloud.githubusercontent.com/assets/15622467/20490468/20cdd266-afdc-11e6-8bdc-d0ce5c9fc531.png)

**Comment by amaseda** [comment]
Take a look at this section of the Mongoose + Express lesson plan: https://github.com/ga-wdi-lessons/express-mongoose#you-do-new-10-minutes--150

**Comment by amaseda** [comment]
Going to close this one but feel free to re-open if you have any more questions/comments about it!
