### ISSUE TITLE
Trying to access Own DB but getting this error

### ISSUE THREAD

**Issue by khoitle** [ga-wdi-exercises/project4#335]
<img width="1280" alt="screen shot 2016-11-21 at 11 47 03 am" src="https://cloud.githubusercontent.com/assets/20734065/20491734/4a3676e0-afe0-11e6-8c3d-242ef938ead8.png">

Here is my Schema.js file. I've seeded correctly with no errors.
<img width="1280" alt="screen shot 2016-11-21 at 11 48 13 am" src="https://cloud.githubusercontent.com/assets/20734065/20491765/683d95e2-afe0-11e6-893d-417fa69e62dd.png">

**Comment by khoitle** [comment]
also, here is my seeds.json file
<img width="1280" alt="screen shot 2016-11-21 at 11 49 44 am" src="https://cloud.githubusercontent.com/assets/20734065/20491824/9d634dca-afe0-11e6-974c-bcee6a9c8d18.png">

**Comment by amaseda** [comment]
What does your connection file look like?

**Comment by khoitle** [comment]
<img width="1280" alt="screen shot 2016-11-21 at 12 15 09 pm" src="https://cloud.githubusercontent.com/assets/20734065/20492815/327aa176-afe4-11e6-83b0-0d6efb9769fa.png">

**Comment by khoitle** [comment]
I'm seeding correctly, and checking the db, everything is fine there

**Comment by amaseda** [comment]
So you are able to persist instances of your models successfully?

What does your seed file look like?

**Comment by khoitle** [comment]
<img width="1280" alt="screen shot 2016-11-21 at 12 29 25 pm" src="https://cloud.githubusercontent.com/assets/20734065/20493288/2a445e96-afe6-11e6-96f4-afa5ec62cd9f.png">
<img width="1280" alt="screen shot 2016-11-21 at 12 29 51 pm" src="https://cloud.githubusercontent.com/assets/20734065/20493305/36f21fb6-afe6-11e6-896e-b2331dfbc960.png">

**Comment by amaseda** [comment]
Where are you running Mongoose commands that generates data using `seeds.json`? Looks like you have a `seeds.js` file (not .json) I haven't seen yet...

**Comment by KhoiLe89** [comment]
<img width="1280" alt="screen shot 2016-11-21 at 11 47 03 am" src="https://cloud.githubusercontent.com/assets/20734065/20493442/ccc3f67c-afe6-11e6-81e2-92328e63ffee.png">

**Comment by khoitle** [comment]
In my seed.js file. Its a couple of comments up

<img width="1280" alt="screen shot 2016-11-21 at 12 34 03 pm" src="https://cloud.githubusercontent.com/assets/20734065/20493456/db6aaae0-afe6-11e6-9ce2-33defb6f9824.png">

**Comment by khoitle** [comment]
Sorry its actually right here. 
<img width="1280" alt="screen shot 2016-11-21 at 12 35 44 pm" src="https://cloud.githubusercontent.com/assets/20734065/20493494/10ee0e82-afe7-11e6-8c77-3a026e8c29b5.png">

**Comment by amaseda** [comment]
Can you push up your code and link me to your repo/branch? Will dive in and see what's up.

**Comment by khoitle** [comment]
https://github.com/KhoiLe89/LegendsSplash

**Comment by amaseda** [comment]
Ah, the issue is how you're defining your models in `index.js`. The error disappeared when I modified the top of the file to look like this...

```js
var express = require("express")
var app = express()
var hbs = require("hbs")
var request = require("request")
var Skin = require("./db/schema.js").Skin
var Champion = require("./db/schema.js").Champion
```

**Comment by khoitle** [comment]
Whoa thanks! Could you explain to me what I was doing wrong?

**Comment by amaseda** [comment]
Yeah! So this is what you exporting from your schema file...

```js
module.exports = {
  Champion: Champion,
  Skin: Skin
}
```

So you need to reference the `Champion` and `Skin` key-value pairs (not just the object) in that object if you're going to properly access your model definitions. You weren't doing that.

**Comment by khoitle** [comment]
Ohhh, thanks again :)

**Comment by amaseda** [comment]
:+1:
