### ISSUE TITLE
Editing Nested Arrays Mongoose

### ISSUE THREAD

**Issue by nickoki** [ga-wdi-exercises/project4#336]
I'm having a somewhat similar problem as [Poh](https://github.com/ga-wdi-exercises/project4/issues/334)...

I have a Drink schema with a recipe attribute that is an array of ingredients and an amount. I'm having a problem editing the nested objects at specific array indexes -- instead, the entire array is overwritten. How would I go about updating individual recipe entries?

Here's my Drink schema:

```javascript
var DrinksSchema = new Schema({
  name: {
    type:     String,
    required: true,
  },
  glass: {
    ref:      'Glass',
    type:     Schema.ObjectId,
    required: true,
  },
  description: {
    type: String,
  },
  instructions: {
    type: String,
  },
  recipe: [{
    ingredient: {
      ref:      'Ingredient',
      type:     Schema.ObjectId,
      required: true,
    },
    amount: {
      type:     Number,
      required: true,
    },
  }],
}, {
  timestamps: true
})
```

**Comment by nolds9** [comment]
the trick is to save the parent. What if you tried something along the lines of whats outlined in this SO http://stackoverflow.com/questions/8955910/mongoose-updating-embedded-document-in-array

**Comment by nickoki** [comment]
So I would be saving `recipe` in my case or the `Drink` object?

I'm also having a hard time figuring out how to format the PUT request. Would I send a new array as the value for my `recipe` key?

**Comment by nolds9** [comment]
Yes, so you would update the `recipe` based on what was sent from the request, I think an entirely new array is fine, then you would save the `Drink`. Try it out and see if you get the results you'd expect

**Comment by nickoki** [comment]
I'm still a little bit stuck, could you help me with a specific example?

Here's my target drink object:
![image](https://cloud.githubusercontent.com/assets/15880182/20493903/a284bd2c-afe8-11e6-8873-8637bad5041e.png)

Here's what I have _so far_ for my edit function:
```javascript
exports.edit = (req, res) => {
  Drink.findOne({ _id: req.body._id }, (err, drink) => {
    if (err) res.send(err)
    else if (req.body.recipe) {
      var recipe = drink.recipe.find(ingredientId => {
        return ingredientId.ingredient == req.body.recipe
      })
      console.log(recipe)
    }
  })
}
```

The `console.log(recipe)` for the following PUT request returns the proper entry in the drink array:
![image](https://cloud.githubusercontent.com/assets/15880182/20493948/c9391e9a-afe8-11e6-8bec-514b6cc0dbd9.png)

I am still stuck on how to format the body of the PUT request and edit function so that I can update the proper recipe array item.

**Comment by nolds9** [comment]
I think you want to put request to go to a specific drink no? with a url like `http://localhost:7000/drinks/58332ed6a5a098555785db92` 

When you send the `recipe` param, looks like you are sending back an `id` for that recipe. Has the recipe already been updated? I would imagine that you need to send the updated data for the new recipe as the value

I can't think of any example of the top of my head, but working from the code you have currently...

```js
exports.edit = (req, res) => {
  Drink.findOne({ _id: req.body._id }, (err, drink) => {
    if (err) res.send(err)
    else if (req.body.recipe) {
      drink.recipe.find(recipeItem => {
        return recipeItem.ingredient.id == req.params.recipe
      }).then(item => {
         // what data do you need to change on item
       // think you need to send the updated information so you can perform the update here
      // after you update the item, dont forget to call save on the drink
     }
      console.log(recipe)
    }
  })
}
```

**Comment by nickoki** [comment]
Alright I may have found a solution to this, I think I was overcomplicating things.

Instead of sending a request to find specific array entries, I'm just sending raw json in the body of my request that will update the whole recipe array.

One remaining question: when I do this, it seems that mongoose is assigning an `_id` to every array entry -- should that be happening?

![image](https://cloud.githubusercontent.com/assets/15880182/20495655/fb0778f2-afef-11e6-9ece-fa082de2f4c0.png)

_see the last line of json (`"_id": "58333ef5d3518988847407c7")`_

**Comment by nolds9** [comment]
hmm, thats weird, I'm not sure why that's happening but need to see if there are any options to prevent that default behavior, wherever you are doing the update...

**Comment by nickoki** [comment]
This might be the culprit http://stackoverflow.com/questions/17254008/stop-mongoose-from-creating-id-property-for-sub-document-array-items

**Comment by amaseda** [comment]
@nickoki How you doing with this one?

**Comment by nickoki** [comment]
@amaseda @nolds9 Sorry forgot to close! Everything is working -- sending the requests as `application/json` instead of `x-www-form-urlencoded` fixed the main issue. The ghost `_id`s were fixed by adding `_id: false` to my `Drink.recipe` Schema
