### ISSUE TITLE
Authentification for Node not picking up promise

### ISSUE THREAD

**Issue by MichaelZLai** [ga-wdi-exercises/project4#337]
I'm implementing passport for my app and I'm getting this promise error stating that `isModified` is not a function. Here's my code from my user.js

```js
UserSchema.pre("save", (next) =>{
  var user = this;
  if (user.isModified("password") || this.isNew){
    bcrypt.genSalt(10, (err, salt) =>{
      if (err) {
        return next(err)
      }
      bcrypt.hash(user.password, salt, (err, hash) =>{
        if (err) {
          return next(err)
        }
        user.password = hash
        next()
      })
    })
  } else {
      return next()
  }
})
```

I do have the mongoose promise in my server.js and linking it to my users.model
![image](https://cloud.githubusercontent.com/assets/20713810/20492670/a12922ba-afe3-11e6-865e-1716bc49fa73.png)

Error message
![image](https://cloud.githubusercontent.com/assets/20713810/20492678/b2660bce-afe3-11e6-8250-34f5cf6136be.png)

**Comment by amaseda** [comment]
What is the value of `user`?

**Comment by MichaelZLai** [comment]
Right now a simple name and password

![image](https://cloud.githubusercontent.com/assets/20713810/20492891/912dff7e-afe4-11e6-9ae5-7e4f6d705d30.png)

**Comment by amaseda** [comment]
If you console.log user inside of the callback in your original code snippet, what do you see?

It doesn't seem to know what `isModified` is, which makes me wonder if `user` isn't what we think it is...

**Comment by MichaelZLai** [comment]
hmmm, you're right, it says that user is undefined in my node server logs
![image](https://cloud.githubusercontent.com/assets/20713810/20494997/4e989ff8-afed-11e6-8a74-64d318b416e8.png)

Would I need to define user in my post route?
```
apiRoutes.post("/signup", (req,res)=>{
  console.log(user)
  if (!req.body.name || !req.body.password){
    res.json({success: false, msg: "Please input name and password."})
  } else {
    var newUser = new User({
      name: req.body.name,
      password: req.body.password
    })
    newUser.save( (err) =>{
      if (err) {
        res.json({success: false, msg: "Username already exists."})
      } else{
        res.json({success: true, msg: "Successfully created User!"})
      }
    })
  }
});
```

**Comment by nolds9** [comment]
are you getting any errors? Try moving `mongoose.Promise = global.Promise` **before** you connect to the database

**Comment by MichaelZLai** [comment]
I tried defining `user` in the post and got the undefined in my server logs. 
![image](https://cloud.githubusercontent.com/assets/20713810/20495257/4fcdfd90-afee-11e6-9b96-8839aae35163.png)

Not sure what you mean by moving the `mongoose.Promise = global.Promise`
```
//allows mongoose promises
mongoose.Promise = global.Promise

require("./config/passport.js")(passport);

//bundle for api routes
var apiRoutes = express.Router();

apiRoutes.post("/signup", (req,res)=>{
  console.log(user)
  var user;
  if (!req.body.name || !req.body.password){
    res.json({success: false, msg: "Please input name and password."})
  } else {
    var newUser = new User({
      name: req.body.name,
      password: req.body.password
    })
    newUser.save( (err) =>{
      if (err) {
        res.json({success: false, msg: "Username already exists."})
      } else{
        res.json({success: true, msg: "Successfully created User!"})
      }
    })
  }
});
```

**Comment by MichaelZLai** [comment]
@amaseda 
Repo Link: https://github.com/MichaelZLai/snapmap

All the connections are in `server.js` and the associated import files are from the `config` and `app` folders

**Comment by amaseda** [comment]
@MichaelZLai How do I go about recreating this error?

**Comment by amaseda** [comment]
@MichaelZLai Also try removing the arrow function and pass in a code block as the second argument to `UserSchema.pre` instead. You can reference this: http://blog.mongodb.org/post/32866457221/password-authentication-with-mongoose-part-1

**Comment by MichaelZLai** [comment]
hmm, it's still not working. I'm probably going to restart the app and work on getting the backend crud functionality working before being ambitious again with the user authentication. Thanks!
