### ISSUE TITLE
Mongoose operator opposite of $in

### ISSUE THREAD

**Issue by bcope** [ga-wdi-exercises/project4#338]
I'm trying to use a mongoose Model to find a document. The document has a field that is an array of foreign key references. I have access to an id value and I want to compare the id against the array of fks to see if it is in the array. I've used the `$in` operator to do the opposite comparison, that is checking the id of a document to see if it is in an array of values. I've been reading the documentation for a while now and was wondering if any of you know of `$contains` or `$has` or similar operator for mongoose...

Thanks!

**Comment by amaseda** [comment]
I don't know of any specific Mongoose methods, but could you use Javascript's `.some` method to accomplish this?

https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/some

**Comment by bcope** [comment]
This was a real dumb. Basically Model.find() automatically looks for one value in the array. So no operator is necessary. Thanks!

**Comment by bcope** [comment]
https://docs.mongodb.com/manual/tutorial/query-documents/#match-an-array-element for more info
