### ISSUE TITLE
How do I use an If statement in Handlebars that uses a dynamic reference as the condition itself?

### ISSUE THREAD

**Issue by khoitle** [ga-wdi-exercises/project4#339]
This is what i have but it comes off as an error
<img width="517" alt="screen shot 2016-11-21 at 2 47 45 pm" src="https://cloud.githubusercontent.com/assets/20734065/20498021/823b6140-aff9-11e6-9a1a-661f5c4e429b.png">
 
<img width="1280" alt="screen shot 2016-11-21 at 2 48 32 pm" src="https://cloud.githubusercontent.com/assets/20734065/20498053/9f4d264c-aff9-11e6-8b12-bd2105d2359e.png">

**Comment by nolds9** [comment]
What happens when you wrap the conditions in parens? Alternatively, you could pass in another variable to the view when you render that is the value you want.

**Comment by khoitle** [comment]
Parens doesn't work. Could you explain the alternative?

**Comment by nolds9** [comment]
what is the end goal? Hardcoding the string `'Justicar Aatrox'` seems a little weird.

**Comment by khoitle** [comment]
Thats just the place holder, theoretically Justicar Aatrox is going to be called dynamically in conditional. Once I figure out how to place a handlebar inside the conditional

**Comment by nolds9** [comment]
When will the name be assigned? Why does it have to be dynamic? Sound like you want to "select" a character, and display information about the "selected" character?

**Comment by khoitle** [comment]
Yes exactly!

**Comment by khoitle** [comment]
For example, if the Character name is Aatrox, I want it to show only Aatrox skins. I figure i need a conditional within a loop that only prints out if the name matches

**Comment by khoitle** [comment]
On Line 13, it shows the characters Name (third party API). Ultimately I want a conditional that runs both the thirdparty API character's name pitted against my own DB's name key, if they match I print out the images. I've been searching google for quite some time and can't figure out how to dynamically set them in the conditional via hbs
<img width="1280" alt="screen shot 2016-11-21 at 3 31 40 pm" src="https://cloud.githubusercontent.com/assets/20734065/20499471/9e7b7010-afff-11e6-962d-12853427877d.png">

**Comment by nolds9** [comment]
You can't set them dynamically in the view with handlebars....I would have the filtering on the back-end, so have a property on the object you send to the view like `selectedCharacter` then you can initialize it to a falsey value like `null`. Then in the view you can have a conditional render each `selecdCharacter`'s skins etc...but that is just some pseudo-code - point being I would approach the problem a little differently

**Comment by khoitle** [comment]
alright, will try to figure out a different way. glad to know i cant set them dynamically in the view. thankss

**Comment by amaseda** [comment]
Gonna close this one but feel free to reopen if you have any questions.
