### ISSUE TITLE
calling external Rails API without public endpoint

### ISSUE THREAD

**Issue by jkoul** [ga-wdi-exercises/project4#34]
Following Jesse's previous advice, I went ahead and implemented the `acts_as_votable` gem on top of my backend API, with corresponding controller actions:

```
  def upvote
    @bill = Bill.find(params[:id])
    @bill.upvote_by current_user
    redirect_to :back
  end

  def downvote
    @bill = Bill.find(params[:id])
    @bill.downvote_by current_user
    redirect_to @bill
```

So I want to access the number of votes for each bill on the front end. My current API call to get all bills is:

```
(function(){
  var billServices = angular.module('billServices', ['ngResource'])
  billServices.factory('Bill', ['$resource', function($resource) {
    return $resource('http://legitrackdc.herokuapp.com/bills/:id', {});
  }])
})()
```

Can I work with the same API call, or do I need to build in another one? How would I go about doing so?

**Comment by jshawl** [comment]
yes! I recommend adding to the JSON that your Bill model from the rails backend responds with.

Check out this blog post i wrote - https://jesse.sh/rails-virtual-attributes/

**Comment by jkoul** [comment]
Hmmmm not an ideal answer but workable for the MVP. It does at least keep the Bill model clean, which is necessary for data integrity. So currently, I'm using this controller method to serve the "index" endpoint:

```
  def index
    @bills = Bill.all
    render status: 200, json: @bills.to_json
  end
```

Would it work to attach that "as_json" method from the model in your example without further changes to the controller?

**Comment by jshawl** [comment]
yes!

now open up `bill.rb` (the model) and add that as_json method

**Comment by jkoul** [comment]
alright! Still gotta call it properly but looks good. Thanks!
