### ISSUE TITLE
Inserting Google Authentication code into my Node.js

### ISSUE THREAD

**Issue by brown2206** [ga-wdi-exercises/project4#340]
Hello.  I need help in understanding the best way to insert Google's authentication into my Node.js file.  I can get the app to work from the console, but I'm not quite sure how I'd make the app work in the browser.  I was wondering if I could sit with someone and have a conversation based on the materials that I have.

**Comment by jshawl** [comment]
I am willing to sit with you but I think you have the tools to do this without me.

a few questions:

is your google auth a command line file?

or are you trying to authenticate a user in an express application?

provide some more info and I'll point you in the right direction

**Comment by amaseda** [comment]
@brown2206 Going to close this one but feel free to re-open if you have any particular questions on the matter / want to respond to Jesse's comments from last week 👆
