### ISSUE TITLE
Unable to access variables for handlebars because of scope

### ISSUE THREAD

**Issue by khoitle** [ga-wdi-exercises/project4#341]
I had to drill down into my database through forEach loops but because of that, I am unable to tell the views what each variable means  
<img width="1280" alt="screen shot 2016-11-21 at 4 51 10 pm" src="https://cloud.githubusercontent.com/assets/20734065/20527759/9ad5dfd4-b097-11e6-8125-4124686c5de3.png">

**Comment by jshawl** [comment]
you need to res.render inside of the `Champion.find` callback

but also - are the console.logs correct?

**Comment by khoitle** [comment]
res.render is inside the Champion.find callback, and the console logs are correct

**Comment by jshawl** [comment]
ah ok perfect - what are you trying to access in a handlebars view?

**Comment by khoitle** [comment]
both skinArray and skinArrayKeys. I can only access skinData

**Comment by khoitle** [comment]
when i change line 28 to res.render("home", {champions: championData.data, championPic: championPic, skinData: skinData, skinArrayKeys: skinArrayKeys}), the browser hangs and ultimately errors out

**Comment by nolds9** [comment]
I think you don't want that `return` on 23

**Comment by khoitle** [comment]
if i dont use that return, then i actually can't do another forEach to dive deeper

**Comment by khoitle** [comment]
I refactored the forEach and basically nested a forEach within the intial one, still the same error. Here s the new code 
<img width="1280" alt="screen shot 2016-11-22 at 10 13 26 am" src="https://cloud.githubusercontent.com/assets/20734065/20528977/56a9069c-b09c-11e6-8956-764bc31cdb30.png">

**Comment by jshawl** [comment]
after line 18 can you console.log `championData.data` ?

**Comment by khoitle** [comment]
championData is actually thirdparty API, i'm trying to access my own DB

**Comment by jshawl** [comment]
That's ok! the issue is that you can't access champions in the view, right?

**Comment by khoitle** [comment]
the issue is i can't access the skinArray and skinArrayKeys in the view. The champions are from the thirdparty API, which renders perfectly. The skins however are from my own seedfile

**Comment by jshawl** [comment]
ohhhhh ok can you console.log in your express route? does that work

**Comment by khoitle** [comment]
yeah the console logs work, the data shows in the console but i cannot add the variables to the render object

**Comment by nolds9** [comment]
what is ultimately the data you need to pass to the view?
Here's an potential example of working around scope issues...
```js
....
Champion.find({}).then(skinData => {
   let skinImgs = []
   skinData.forEach(result => {
     result.skins.forEach(skinArrayKey => {
        skinImgs.push(skinArrayKey.skinImg)
     })
   })
 res.render("home", { skinData, skinImgs })
})
```

**Comment by khoitle** [comment]
ultimately, i need to be able to access the array of objects, where one of the key values is an array of objects. The solution you proposed up here is to drill down to the data and push it into a totally new array? Would that solve the scope issue?

**Comment by khoitle** [comment]
In outcomes, I shall try it in a second!

**Comment by khoitle** [comment]
Im getting somewhere! its showing in the view as ",,,"
