### ISSUE TITLE
Cascading problems with api request

### ISSUE THREAD

**Issue by bcope** [ga-wdi-exercises/project4#342]
In my App.js file I am making a call to my API during the componentDidMount portion of the component life cycle. I am getting data from a document that will be used in components that are children of App.js. Some of the child components will use this data to make their own API calls where this information is used. It seems that the API call in App.js is being made after the child components have been rendered and mounted. The result is that the API call in the child component is failing due to the fact that the data needed to make the call has not yet been retrieved for App.js.

Here is my console log timeline: 
![image](https://cloud.githubusercontent.com/assets/3825779/20528107/e752a666-b098-11e6-903f-556cb0e511b4.png)

I am attempting to get the information about a campaign in App.js. I then am trying to pass that info through props through CampaignContainer and into PartyContainer. There is an API call in PartyContainer that is being invoked during componentDidMount that needs campaign._id in order to retrieve the correct data.

My question is, where should I put API calls in components such that the information will be available to the child components?

**Comment by jshawl** [comment]
check this out. put a prop on the child component. When the parent's api call completes, set state on the parent component

**Comment by bcope** [comment]
What do you mean about put a prop on the child component?

This is my App.js api call:
```
setCampaign() {
    getDoc("campaigns","582f2d9af4eab7053111b321").then(res => {
      this.setState({
        campaign: res
      })
    })
  }

  componentDidMount() {
    this.setCampaign()
  }
```

This is my api call in PartyContainer:
```
getParty() {
    Utils.getChildren("campaigns",this.state.campaignId,"party").then(res => {
      this.setState({
        party: res
      })
    })
  }

  componentDidMount() {
    this.getParty()
  }
```

**Comment by bcope** [comment]
This is my App.js https://github.com/bcope/react-dm/blob/master/src/App.js

Here is my PartyContainer: https://github.com/bcope/react-dm/blob/master/src/components/PartyContainer.js

**Comment by nolds9** [comment]
@bcope, i would expect `campaignId` to come from props, not state in your `PartyContainer`

**Comment by bcope** [comment]
That's why I logged props in PartyContainer. It's also undefined.

**Comment by nolds9** [comment]
you passed the value down as `campaign` not `campaignId`

**Comment by nolds9** [comment]
i.e. should be `this.props.campaign`

**Comment by bcope** [comment]
I switch it when I render the PartyContainer from CampaignContainer:
```
<div className="body row">
          <PartyContainer
            campaignId={this.props.campaign._id}/>
          <DisplayContainer
            campaignId={this.props.campaign._id}/>
        </div>
```

**Comment by bcope** [comment]
Here's an update of the trace using props almost exclusively (except for App.js):
![image](https://cloud.githubusercontent.com/assets/3825779/20528824/af1355a4-b09b-11e6-808f-57d675df56c2.png)

**Comment by bcope** [comment]
So my rephrased question is: at what point in a component lifecycle is the most appropriate time to make an API call that is dependent on data from props?

**Comment by nolds9** [comment]
Interesting, looks like if we are following the rendering process, the party container makes an api request, before the parent...I would but a conditional like `if (this.props.campaignId)` in your `componentDidMount` for the `PartyContainer`...Also, in the `partyContainer` I wouldn't use state to track `campaignId` just props

**Comment by bcope** [comment]
Add the conditional removes the error but only because the API call isn't made. When should I make that API call? What component lifecycle hook can I use?

I updated my code to:
```
componentDidMount() {
    if (this.props.campaignId) {
      this.getParty()
    }
  }
```
With this result: 
![image](https://cloud.githubusercontent.com/assets/3825779/20529039/aa7753dc-b09c-11e6-8723-0562177eafa8.png)

**Comment by nolds9** [comment]
So i still would be making the calls in `componentDidMount` the trick is after the App.js fires it's API call, we then want to set state on the top level to force a rendering, which will then theoretically re pass data down props. So where I would go to debug, is to use `this.props.campaignId`  and not store that value in state in `PartyContainer`

**Comment by nolds9** [comment]
i.e. replace this line https://github.com/bcope/react-dm/blob/master/src/components/PartyContainer.js#L15 with `this.props.campaignId`

**Comment by bcope** [comment]
I did that with the same result from above.

**Comment by bcope** [comment]
I just pushed my updated code.

**Comment by bcope** [comment]
My App.js sets state based on the response from an API call. Then all the children are just using that info passed through props. I would expect App.js to rerender then and therefore remount (?) them thus invoking the API call in PartyContainer again once props are available. But that isn't happening.

**Comment by nolds9** [comment]
Yes it does not appear to be happening, I would try to isolate this issue by forgetting about the API issue for right now, and just trying to see if you can force an App update from a child component, and see if it renders itself. When in doubt, you could use `forceUpdate()` after your make the first API call...

**Comment by nolds9** [comment]
If you push your updated api + client code, I could poke around locally

**Comment by bcope** [comment]
Just did. In react-dm and men-dm repos.

**Comment by nolds9** [comment]
think we have a break through! You want `componentDidUpdate` in the `partyContainer` instead of `componentDidMount`....essentially calling `this.setState` on the parent will not remount the child elements, but the children can hook into the parent's state change via a `componentDidUpdate`

**Comment by nolds9** [comment]
also found a little glitch on the back-end that  prevented a `campaign`'s `players` from saving in `campaign_seeds.js`.

Make sure to move `process.exit()` into a promise or callback after you save the campaign 
https://github.com/bcope/men-dm/blob/master/db/seeds/campaign_seeds.js#L27

**Comment by nolds9** [comment]
going to go ahead and close this, but feel free to reopen if issue persists
