### ISSUE TITLE
Turn different lines of inputs into separate strings

### ISSUE THREAD

**Issue by pohckuan** [ga-wdi-exercises/project4#343]
I have  textarea input for ingredients and directions. Is there any way to take every single line of input in the form as separate strings? 
![image](https://cloud.githubusercontent.com/assets/15622467/20528560/b83d0072-b09a-11e6-8fb4-459d7bcec9d5.png)

![image](https://cloud.githubusercontent.com/assets/15622467/20528576/c834a048-b09a-11e6-9052-1a1fa54d1b9d.png)

**Comment by jshawl** [comment]
yes! try:

```js
document.querySelector("name='recipe[ingredient]'").value.split("\n")
```

splits on the empty line

**Comment by pohckuan** [comment]
do I  put that inside my create function?
