### ISSUE TITLE
Can create new object in database but does not post in browser

### ISSUE THREAD

**Issue by griffind2009** [ga-wdi-exercises/project4#344]
I can create a new object and view it in the database via the terminal but it does not show in the browser. Right now I redirect to the same page and it doesn't show, even when I refresh.  When I console.log it or use res.json I see that the object has been created.  

![screen shot 2016-11-22 at 10 13 56 am](https://cloud.githubusercontent.com/assets/20979785/20528999/698935ca-b09c-11e6-9ed3-9b17bc822fd8.png)

![screen shot 2016-11-22 at 10 13 19 am](https://cloud.githubusercontent.com/assets/20979785/20529001/6e1334ec-b09c-11e6-9575-b1901c46b5f3.png)

![screen shot 2016-11-22 at 10 13 05 am](https://cloud.githubusercontent.com/assets/20979785/20529007/75f34efe-b09c-11e6-94fa-4158ff9adda5.png)

**Comment by jshawl** [comment]
can we see `app.get("/")`

**Comment by griffind2009** [comment]
![screen shot 2016-11-22 at 10 30 53 am](https://cloud.githubusercontent.com/assets/20979785/20529629/cc7d59de-b09e-11e6-830b-b436fac55fdb.png)

**Comment by jshawl** [comment]
when you say it does not show in the browser, do you mean the home page  or `/questions`?

can you console.log what comes back from the db? is that working?

**Comment by griffind2009** [comment]
It doesn't show on '/questions'

Yes, the db is working. Nodemon is running and I the topic and question I created "Food", "What is your favorite restaurant".
![screen shot 2016-11-22 at 1 36 42 pm](https://cloud.githubusercontent.com/assets/20979785/20536845/bacf8468-b0b8-11e6-8919-80eb092ab951.png)

When I run mongo I see the same thing.
![screen shot 2016-11-22 at 1 38 10 pm](https://cloud.githubusercontent.com/assets/20979785/20536898/f3fec3e8-b0b8-11e6-9afd-3f6b9d7da616.png)

**Comment by nolds9** [comment]
Can you `console.log` the `questions` you get back from the database in your index route?

Also, right now in create action you are redirecting to `/`, I think you want to redirect to `/questions` after create?

**Comment by griffind2009** [comment]
Sorry I was just checking to see if redirecting to '/' would change anything, but it did not.  Yes, I have it redirecting to /questions.  In my index routes I'm not receiving any questions back.  If console.log(questions) from app.get('/questions') I get the following:

![screen shot 2016-11-22 at 1 58 42 pm](https://cloud.githubusercontent.com/assets/20979785/20537660/f69e2dfc-b0bb-11e6-87fe-a5de3018910b.png)

**Comment by nolds9** [comment]
So, what you are seeing is all the result of calling `Question.find({})` looking at your code, its looks like your are creating a new `Topic`. So that's why the new item is not showing up in your `/questions` route

**Comment by griffind2009** [comment]
Ok, i see it created when i go to '/topics', thank you!

**Comment by griffind2009** [comment]
Is there a way to delete all the instances of that question, I created from the database without having to create a delete request in index.js?

**Comment by nolds9** [comment]
do you mean like one time, or every time a user hits a route. I would say if its just this one time, either re seed or manually delete it from the mongo shell

**Comment by griffind2009** [comment]
ok thanks
