### ISSUE TITLE
Cannot "create" in angular

### ISSUE THREAD

**Issue by pohckuan** [ga-wdi-exercises/project4#346]
My angular is not able to save new data in the create form, seems like it is not connecting to the backend. 
![image](https://cloud.githubusercontent.com/assets/15622467/20672810/89df5134-b550-11e6-992f-ac992a1c079c.png)

![image](https://cloud.githubusercontent.com/assets/15622467/20672724/3e680b42-b550-11e6-9f3d-159b7c6d2611.png)

![image](https://cloud.githubusercontent.com/assets/15622467/20672759/5f020902-b550-11e6-821b-41d9eed3b37c.png)

![image](https://cloud.githubusercontent.com/assets/15622467/20672786/72ab879e-b550-11e6-9a82-456153778c1e.png)

**Comment by nolds9** [comment]
Looks like an issue on the back-end, can you inspect the failed network request, to see a little bit more info on the error

**Comment by nolds9** [comment]
also, double check `req.body`, I think that will have your data, not `req.body.recipe`

**Comment by pohckuan** [comment]
I was able to create and save data from the backend with req.body.recipe before adding angular. 
This is what is shown in the network failure
![image](https://cloud.githubusercontent.com/assets/15622467/20673126/e37f3208-b551-11e6-82db-562f7fd4c43c.png)

**Comment by nolds9** [comment]
Angular changes how the parameters are passed in, try `console.log` ing `req.body`

**Comment by pohckuan** [comment]
in angular?

**Comment by nolds9** [comment]
on the express side
