### ISSUE TITLE
Best way to pass component state to parent component through onClick

### ISSUE THREAD

**Issue by bcope** [ga-wdi-exercises/project4#347]
I have a component that displays data based on an object being passed in through props. I have child components inside of that container. I have a button on those children to 'send them' to the display container. Right now the way it works is that the child container has a data object in its state and there is a button on that child component to set state of the parent component to that data object. I have this working now but the way I'm doing it is by adding the data object as a JSON.stringified attribute on the button element who's function is bound to the parent's context. This works but feels all wrong. Any suggestions about a better way of handling this? Feels extra wrong cause as I add more functionality around buttons in child components I don't want to add the data as attributes to each button...

Code in child component:
```
class ChildContainer extends Component {
  constructor(props) {
    super(props)
    this.state = {
      type: props.data.object_type,
      id: props.data._id,
      data: props.data
    }
  }

  render() {
    return (
      <div className="childContainer container">
        <h3>{this.state.data.name}</h3>
        <button data-x={JSON.stringify(this.props.data)} onClick={this.props.onDisplayChange}>Send to Display</button>
      </div>
    )
  }
}
```

Bound function in parent component:
```
handleDisplayChange(e) {
    let data = JSON.parse(e.target.dataset.x)
    console.log(data)
    if (!data) {
      this.setState({
        mode: "display",
        type: "default",
        id: "",
        data: "",
        path: ""
      })
    } else {
      this.setState({
        mode: "display",
        type: data.object_type,
        id: data._id,
        data: data
      })
    }
  }
```

**Comment by nolds9** [comment]
Definitely feels like a bit of an anti-pattern to bind data to the DOM like that, is there any way you can pass that data as an argument to your handler function when invoked...

haven't actually tested the code but thinking....

```jsx
<button onClick={() => this.props.onDisplayChange(this.state.data)}>Send to Display</button>
```

```js
handleDisplayChange(data) {
 if (!data) {
      this.setState({
        mode: "display",
        type: "default",
        id: "",
        data: "",
        path: ""
      })
    } else {
      this.setState({
        mode: "display",
        type: data.object_type,
        id: data._id,
        data: data
      })
    }
}
```

**Comment by bcope** [comment]
@nolds9 #forthewin !!!

**Comment by amaseda** [comment]
:+1:
