### ISSUE TITLE
MongooseError: Schema hasn't been registered for model "Payee".

### ISSUE THREAD

**Issue by brown2206** [ga-wdi-exercises/project4#349]
I'm getting this error message every time I try to run my node application...

![image](https://cloud.githubusercontent.com/assets/20567326/20691277/dbb4a566-b59d-11e6-9207-871072375411.png)

Here's my code, I'm doing exactly as they've suggested...what am I doing wrong?

![image](https://cloud.githubusercontent.com/assets/20567326/20691296/05cdfc80-b59e-11e6-8ddb-25f634752958.png)

**Comment by amaseda** [comment]
@brown2206 Does anything change when you move `mongoose.connect` before your schema definition?

**Comment by brown2206** [comment]
It worked.  Thank you.
