### ISSUE TITLE
Abstracting to Custom Directives/adding methods

### ISSUE THREAD

**Issue by jeffjones89** [ga-wdi-exercises/project4#35]
This is probably a bit more of a structural/next steps question but basically angular is pulling data from my API and formatting correctly so that's all well and good.

Next steps are to take some of the data associated with each model and run some simple math using the back end data when each instance of a model is created to be used on the front end.

For example, each player has a three-point field goals made and two-point field goals made attribute and total field goals attempted. When each model is generated on the front end, I'd like to do (3ptFGM \* .5 + FGM) / FGA...basically just some simple math with the stock data (all single integers). To me, it seems like that should be a scope.<STAT> = function(x,y,z) method that binds to an element in the template.

Sorry if that's confusing or if there is a better approach to take I'm all ears. Just kinda stuck on how/where to implement this.

**Comment by jshawl** [comment]
no that sounds right!!!

or you can use an attribute:

``` js
function($scope){
  $scope.myCustomDataPoint = someOtherData * moreOtherData
}
```

**Comment by jeffjones89** [comment]
Okay cool...So i'm going down the below route with my directive attempting to replace the index page. Would I just nest a custom attribute or a formula in the "link" portion of the player directive? I'll try and read up on the angular docs as well. 

```
(function(){
  var directives = angular.module('playerDirectives', []);

  directives.directive('player', ['Player', '$routeParams', '$location', function(Player, $routeParams, $location){
    return{
      templateUrl: "public/views/players/_player.html"
    };
  }

]);

});
```

**Comment by jshawl** [comment]
yes! seems like you're heading in the right direction! http://plnkr.co/edit/ZKX9G5Qr8XTtzx1iTJNT?p=preview

**Comment by jeffjones89** [comment]
Not sure if this is best practice...but it works, so I'll take it!

``` js
(function(){
  var directives = angular.module('playerDirectives', []);

  directives.directive('player', ['Player', '$routeParams', '$location', function(Player){
    return{
      templateUrl: "views/players/_player.html",
      link: function($scope){
        var player = $scope.player
        $scope.eFG = (((Number(player.threePtMade) * 0.5  + Number(player.fgm))/ Number(player.fga)) * 100).toFixed(1);
        $scope.TSA =  (0.44 * Number(player.FTA)) + Number(player.fga)
        $scope.TS = ((Number(player.pts)/(2 * $scope.TSA)) * 100).toFixed(1)
      }
    };
  }

]);

})();
```

**Comment by RobertAKARobin** [comment]
Wooooo! Create a new issue linking to this one if things hit the fan again.
