### ISSUE TITLE
Search Box

### ISSUE THREAD

**Issue by griffind2009** [ga-wdi-exercises/project4#350]
I have created a search box and drop down search option to search by topics.  The goal is when the user hits search it will go down to that topic on the page.  However, when I hit search now nothing happens? I am not sure if I am missing something in my search form if it is another issue that I need to address in order to fix it.  Here is what it looks like now
![screen shot 2016-11-29 at 8 31 27 am](https://cloud.githubusercontent.com/assets/20979785/20711546/3f5ee30e-b60e-11e6-981a-ef069a3d178e.png)

And this is what the search box looks like:
![screen shot 2016-11-29 at 8 32 01 am](https://cloud.githubusercontent.com/assets/20979785/20711988/501f98d0-b610-11e6-9eb8-56f56dde587d.png)

**Comment by amaseda** [comment]
@griffind2009 What code is supposed to be executed when you click on the button - a method in your Angular controller?

Can you get a `console.log` statement to show up?

**Comment by griffind2009** [comment]
No, I actually don't have a method in Angular to define what happens on the click event. Would I need to use $scope for that?

**Comment by amaseda** [comment]
Don't see any need for `$scope`. Can just define a method in your controller and reference it using the usual `vm.` notation.

The only reason I suggest this is because it sounds like you want something to happen in response to a button click, but I don't see anything defining that functionality.

**Comment by griffind2009** [comment]
I've looking for examples not using jQuery and all of the examples I have come across use $scope. Do you know of any sites or documents that provide examples on click events in angular?

**Comment by griffind2009** [comment]
I figured it out. Thanks!
