### ISSUE TITLE
Rails Question

### ISSUE THREAD

**Issue by alman92** [ga-wdi-exercises/project4#351]
Hey Guys,

Ive made a User model which my other models are subsequently nested under, but I'm thinking about using Devise instead.  Would I need to run a migration to delete the User model all together? I'm just confused on how to go about this.

**Comment by jshawl** [comment]
devise will handle existing user models. commit and try creating a feature branch for devise

**Comment by amaseda** [comment]
Took care of this IRL so going to close. Feel free to re-open if you have more questions / comments about it.
