### ISSUE TITLE
Weird Rails Error

### ISSUE THREAD

**Issue by alman92** [ga-wdi-exercises/project4#353]
![image](https://cloud.githubusercontent.com/assets/19317100/20726200/7a3c2ed0-b642-11e6-9140-d57874e93baa.png)

I have no clue what this is telling me...

**Comment by amaseda** [comment]
What does GoalsController#index look like?

**Comment by jshawl** [comment]
it is telling me there is no template inside `app/views/goals`

**Comment by jshawl** [comment]
need either an `index.html.erb` or render json in the controller action

**Comment by alman92** [comment]
There was no view....sorry that was a stupid question haha

**Comment by jshawl** [comment]
that's ok! crytpic error messages...
