### ISSUE TITLE
Current User not decoded from token

### ISSUE THREAD

**Issue by MichaelZLai** [ga-wdi-exercises/project4#354]
I'm using passport-local for authentication and I'm getting hung up on deriving the email and name from `payload`.  I'm parsing through the token and getting a response, however the email and name wont show up. The last object with `name` and `email` is from `console.log(currentUser)`

```
var isLoggedIn = function(){
    var token = getToken()
    var payload
    if (token) {
      payload = token.split(".")[1]
      payload = $window.atob(payload)
      payload = JSON.parse(payload)

      console.log(payload)
      return payload.exp > Date.now() / 1000
    } else {
      return false;
    }
  }
  //get current user's details
  var currentUser = function(){
    if (isLoggedIn()) {
      var token = getToken();
      var payload = token.split(".")[1]
      console.log(payload)
      payload = $window.atob(payload)
      console.log(payload)
      payload = JSON.parse(payload)
      console.log(payload)
      return{
        email : payload.email,
        name : payload.name
      };
    }
  }
```

![image](https://cloud.githubusercontent.com/assets/20713810/20735778/518fc630-b670-11e6-85a8-e4ba02168a65.png)

**Comment by jshawl** [comment]
are any of those functions asynchronous?

**Comment by jshawl** [comment]
does `      console.log(payload)` show the right thing?

**Comment by MichaelZLai** [comment]
It seems like it's showing the right decoded token, I'm not sure what `exp` or `iat` means. The two methods above `isLoggedIn` and `currentUser` is within the `authentication` function which is passed through the "navigation controller" function below.

```
//change content based on user status
function navigation($location, authentication){
  var vm = this;
  vm.isLoggedIn = authentication.isLoggedIn();
  vm.currentUser = authentication.currentUser();
  console.log(vm.currentUser)
}
```

**Comment by jshawl** [comment]
in the previous function what if you try:

``` 
console.log(payload.name)
```

does this work correctly?

**Comment by MichaelZLai** [comment]
It's coming back `undefined` and I'm not sure why. In my api, these are what my id's are:

```
{ "_id" : ObjectId("583dfea385a96664e8add24d"), "email" : "bar@bar.bar", "name" : "barrett", "markers" : [ ], "__v" : 0 }
{ "_id" : ObjectId("583e12766cdaa865d57e2395"), "email" : "mike@mike.com", "name" : "michael", "markers" : [ ], "__v" : 0 }
```

```
  //get current user's details
  var currentUser = function(){
    if (isLoggedIn()) {
      var token = getToken();
      var payload = token.split(".")[1]
      payload = $window.atob(payload)
      payload = JSON.parse(payload)
      console.log(payload)
      console.log(payload.name)
      return{
        email : payload.email,
        name : payload.name
      };
    }
  }
```
![image](https://cloud.githubusercontent.com/assets/20713810/20757062/ece6ca62-b6e2-11e6-89bb-f0da7c56efa3.png)

**Comment by MichaelZLai** [comment]
Here is the [repo](https://github.com/MichaelZLai/_snapmap). The affected file is in `public/js/app.js`

**Comment by jshawl** [comment]
ok this is good. is there anything related to a user and email inside this block of code?

```
  var payload = token.split(".")[1]
      payload = $window.atob(payload)
      payload = JSON.parse(payload)
      console.log(payload)
      console.log(payload.name)
```

if not, where can you console.log a user and email?

**Comment by MichaelZLai** [comment]
Would `payload` be related to the user? It's the pwt that needs to be decoded. The return values 
are associated with `payload` and they're still returning as undefined in other functions.
```
return{
        email : payload.email,
        name : payload.name
      };
```

**Comment by jshawl** [comment]
hmm im not sure what `exp` and `iat` are. what front end library are you using?

**Comment by jshawl** [comment]
my guess is that you're getting the token correctly, but there is still one more step to get the user info from that token you get in the payload

**Comment by MichaelZLai** [comment]
yeah, I think so as well. I'm using the `passport` and `passport-local` library. I'm wondering if it is how I'm saving the user object in my db

```
{ "_id" : ObjectId("583dfea385a96664e8add24d"), "email" : "bar@bar.bar", "name" : "barrett", "markers" : [ ], "__v" : 0 }
{ "_id" : ObjectId("583e12766cdaa865d57e2395"), "email" : "mike@mike.com", "name" : "michael", "markers" : [ ], "__v" : 0 }
```

**Comment by MichaelZLai** [comment]
`iat`: The time the JWT was issued. Can be used to determine the age of the JWT

**Comment by jshawl** [comment]
hmm what connects a jwt to a user in the db?

**Comment by MichaelZLai** [comment]
Good question. I'm not sure it does. Do you think this could be how my user `POST` is directing to my backend?

```
function User ($resource) {
  return $resource('http://localhost:5000/users/id/:id', {}, {
    update: {method: 'put'}
  })
}
```

```
  //calling register api
  register = (user) =>{
    return $http.post("http://localhost:5000/register", user).success( data =>{
      saveToken(data.token);
    })
  }
```

p.s. I think im pivoting again and just working off a one model, but this is a good conversation when I do get back to authentication

**Comment by jshawl** [comment]
that looks like the right sort of thing... I know nick oki's group did JWT auth with angular as well - maybe you can grab some idea's from their code base?

**Comment by nolds9** [comment]
I think its a good idea to focus on the single model to start. I haven't looked at this codebase in awhile, but there is a solution branch to WDI Radio in Angular that used the `ng-token-auth` 3rd party library to help on the front-end https://github.com/ga-wdi-exercises/wdi_radio_lab/tree/user-auth-solution/js/users

**Comment by MichaelZLai** [comment]
ah ok, thanks. Definitely going to relook at this later
