### ISSUE TITLE
Better way to structure Express api routes while using Mongoose models

### ISSUE THREAD

**Issue by bcope** [ga-wdi-exercises/project4#355]
I have a bunch of Mongoose models on my api server for which I have 5 routes that are exactly the same for each model except that I use the model name in them. Is there an easy way to abstract this with a variable?

I would love to change `router.get('/items/:id', function(req, res) {...` to `router.get('/:object/:id', function(req, res) {`. But I'm not sure how to reference the right model... maybe I don't need to...? Could you point me in the right direction? Right now I have the routes below duplicated at least 5 times and the code smell is pungent.

```
router.get('/items', function(req, res) {
  Item.find({}, (err, items) => {
    if (err) res.json(err)
    else res.json(items)
  })
})

router.get('/items/:id', function(req, res) {
  Item.findOne({_id: req.params.id}, (err, item) => {
    if (err) res.json(err)
    else res.json(item)
  })
})

router.post('/items', function(req, res) {
  Item.create(req.body, (err, item) => {
    if (err) res.json(err)
    else res.json(item)
  })
})

router.put('/items/:id', function(req, res) {
  Item.findOneAndUpdate({_id: req.params.id}, {$set: req.body}, (err, item) => {
    if (err) res.json(err)
    else res.json(item)
  })
})

router.delete('/items/:id', function(req, res) {
  Item.findOneAndRemove({_id: req.params.id}, (err) => {
    if (err) res.json(err)
    else res.json({'success': true})
  })
})
```

**Comment by nolds9** [comment]
`mongoose.model` takes a string as a getter, wonder if it can be dynamic...

thinking something like:
```js
router.get("/:model", (req, res) => {
  const model = mongoose.model(req.params.model)
  model.find({}).then(results => {
    res.json(results)
 })
})
```

**Comment by amaseda** [comment]
Going to close this one since it's been quiet for a bit, but let us know if you've made any progress / have questions.
