### ISSUE TITLE
Semantic UI React Search bug

### ISSUE THREAD

**Issue by nickoki** [ga-wdi-exercises/project4#356]
I'm using semantic-ui-react for some of my front-end components and I was hoping to use their [Search module](http://react.semantic-ui.com/modules/search) in my Forms, but I've encountered a bug where the Search results are not visually populating.

![image](https://cloud.githubusercontent.com/assets/15880182/20756341/56bd5d3c-b6e0-11e6-9ffa-ff08e70d7451.png)

If I click on the empty result dropdown, it is indeed the correct item, the name just doesn't show -- e.g. the content div is not populating correctly:

![image](https://cloud.githubusercontent.com/assets/15880182/20756586/3816a9fa-b6e1-11e6-98e9-90a3d9b3183d.png)

**Comment by jshawl** [comment]
>where the Search results are not visually populating.

can you get the search results in a console.log somewhere?

**Comment by nickoki** [comment]
The correct results appear in a `console.log`, the search box even populates with the correct name, "Highball" after I click the empty dropdown. The problem is that the dropdown is empty and I can't figure out why.

**Comment by nickoki** [comment]
This is my Search component (following the example from Semantic UI):

```javascript
<Search
  loading={this.state.isLoading}
  onChange={this.handleChange}
  onSearchChange={this.handleSearchChange}
  value={this.state.value}
  results={this.state.results}
  {...this.props}
/>
```

One of the problems could be from `{...this.props}`

**Comment by jshawl** [comment]
are you sure `state` is what you think it is?

**Comment by nolds9** [comment]
I think `{...this.props}` is the problem based on what the output of inspecting your elements, it put `name="highball"` as an attribute on the element, and not as a prop. I would try manually writing it out now like `name={this.props.name}`. 

Also, could be useful to use the react dev tools to inspect props when the component is rendered

**Comment by nickoki** [comment]
@jshawl, I believe so. I don't know how the following from the second screenshot would populate otherwise:
```html
<div name="Highball" class="result">
  <div class="content"></div>
</div>
```

I can't figure out why the `content` div is empty

**Comment by nolds9** [comment]
also, can I see the definition for `Search`

**Comment by nickoki** [comment]
@nolds9, Here's the definition for `Search`

http://react.semantic-ui.com/modules/search

**Comment by nolds9** [comment]
per the docs, are you sure the `results` prop you are passing is in the right format:

> One of:
- array of Search.Result props e.g. `{ title: '', description: '' }` or
- object of categories e.g. `{ name: '', results: [{ title: '', description: '' }]`

**Comment by nickoki** [comment]
Using React dev tools, I'm able to inspect the `<SearchResults>` and `<SearchResult>` tags:

![image](https://cloud.githubusercontent.com/assets/15880182/20757984/659584a0-b6e6-11e6-82b0-e7a9eeca3c69.png)

As expected, the results/props are correct, but still no clue why they aren't rendering:

![image](https://cloud.githubusercontent.com/assets/15880182/20758021/7d411dc6-b6e6-11e6-96eb-78b7f221840c.png)

**Comment by nickoki** [comment]
Got it!

![image](https://cloud.githubusercontent.com/assets/15880182/20758164/f8ed9e36-b6e6-11e6-9fe5-e6a98984cd61.png)

I have to build my `results` with a `title` attribute:

```javascript
var filterResults = _.filter(this.state.glassware, isMatch)
var arr = []
for (let i = 0; i < filterResults.length; i++) {
  let obj = {
    key: i,
    title: filterResults[i].name,
  }
  arr.push(obj)
}
this.setState({
  isLoading: false,
  results: arr
})
```
