### ISSUE TITLE
seed data showing

### ISSUE THREAD

**Issue by brophy2321** [ga-wdi-exercises/project4#357]
![image](https://cloud.githubusercontent.com/assets/21348450/20756891/64f8431a-b6e2-11e6-9246-7de00171505a.png)
![image](https://cloud.githubusercontent.com/assets/21348450/20756899/6c73e662-b6e2-11e6-8912-a6f45e37a1cd.png)
![image](https://cloud.githubusercontent.com/assets/21348450/20756922/76b570dc-b6e2-11e6-8038-b1fccec7a07a.png)

**Comment by jshawl** [comment]
sorry what's your issue?`

**Comment by brophy2321** [comment]
added seed data, i can not get anything to show up except what shows in the browser at the moment

**Comment by jshawl** [comment]
can i see `config/routes.rb`

**Comment by brophy2321** [comment]
![image](https://cloud.githubusercontent.com/assets/21348450/20756997/b03106f0-b6e2-11e6-8e94-b0f54a7408e6.png)

**Comment by jshawl** [comment]
on line 5 of your muscles controller - you're rendering json. what if you remove that line?

**Comment by brophy2321** [comment]
that was it, thank you

**Comment by jshawl** [comment]
👍 excellent!
