### ISSUE TITLE
Sharing Data between modules Best Practice

### ISSUE THREAD

**Issue by merubin** [ga-wdi-exercises/project4#358]
I have a number global data items that I am sharing between my various modules and was wondering what is the best practice to do this.  Because I am using various AJAX calls, I have lots of keys and passwords stored in environment variables as well as connection status between different devices and systems.  The current status would be nice to keep in global variables but I don't want to repeat code in the various modules.

Would the best practice be create a new module that I export those items and require it in the modules I need it in?  I was thinking that everything I need to share between all my modules would be in this new shared module.

Thanks for your input!

**Comment by jshawl** [comment]
yes! try it out! my rule of thumb is to always minimize the number of place i would need to change something

**Comment by amaseda** [comment]
@merubin How did this go?

**Comment by merubin** [comment]
Having some trouble but debugging.  Cannot seem to get calls to internal functions in the module working.

**Comment by merubin** [comment]
Here is my current problem.

I've created a class in my new module   ( say module1)   Module 2 requires module 1 and defines a new instance of this variable clase.     Now Module 3 can require module 1 and get the definition, but not the instance that was created in module 2.  I think I'm getting confused....

**Comment by merubin** [comment]
I made a simple sample here it is.

My main code  index.js

```
var WxConnectStatus =  require('./wxconnection')

var wxCstat= new WxConnectStatus()

console.log(" Connection status at start",wxCstat.wxConnected())
console.log(" setting connected",wxCstat.wxConnect())
console.log(" Connection after connected",wxCstat.wxConnected())
console.log(" setting disconnected",wxCstat.wxDisconnect())
console.log(" Connection after dis connect",wxCstat.wxConnected())
```


Here is the wxconnection .js

```
var  wxConnection = class {
      constructor(){
        this.wxStatus=false
      }
        wxConnected() {
           return(this.wxStatus)
       }

        wxConnect()
       {
         this.wxStatus=true
       }

         wxDisconnect() {
        this.wxStatus=false
       }

   }

module.exports = wxConnection
```

 Now I have code that is located in the PUBLIC folder that is called from the Front End that needs this status.  Can I call this from this code?  Or do I need to create a POST request to to send it to the FE?

**Comment by nolds9** [comment]
I little confused myself on what  you are going for. But you could export the instance from Module 2, so then Module 3 could import the instance...if that make sense

**Comment by merubin** [comment]
I am going to close this  for now.  I have reached a good point with this but I have more pressing issues.
