### ISSUE TITLE
Can't get form for multiple models to work

### ISSUE THREAD

**Issue by tomBeach** [ga-wdi-exercises/project4#36]
Not sure where to begin... I am trying to build a single form to populate the Person and Patient tables for adding a new patient.  Because I have patient belongs_to person and person has_many patients, the only routes available for new person/patient are:

```
new_person_patient GET    /persons/:person_id/patients/new(.:format)      patients#new
new_person GET            /persons/new(.:format)                          persons#new
```

Since new records should be created for both tables, I can't use new_person_patient since it requires a :person_id.  I tried to use the new_person route (anticipating passing form values back as params[:person] and params[:patient] to get submitted values to the right tables.  Here is the error I get when trying to create the form:

```
No route matches {:action=>"index", :controller=>"patients", :person_id=>nil} missing required keys: [:person_id]
```

Here is the controller action:

```
    def new
        @person = Person.new
        @patient = Patient.new
    end
```

Here is the form partial:

```
<%= form_for [@person, @patient] do |f| %>
    <%= f.text_field :["person"]user_name %> <%= f.label :user_name %>
    <%= f.text_field :["person"]password %> <%= f.label :password %>
    <%= f.text_field :["person"]category %> <%= f.label :category %>

   <%= fields_for @patient do |fa| %>
       <%= fa.text_field :["patient"]room %><%= fa.label :room %>
       <%= fa.text_field :["patient"]bed %><%= fa.label :bed %>
        ...
   <% end %>
<% end %>
```

Is this close to the right approach?

**Comment by jshawl** [comment]
shouldn't `@person = Person.new` be `@person = Person.find(params[:id])`?

**Comment by tomBeach** [comment]
I haven't created the person yet so I can't get an id.  (Both records have to be created at the same time.)  Do I need a one-to-one relationship for this?  I intend to have similar relationships for persons<=>doctors, persons<=>nurses, etc.  (trying persons<=>patients first).

**Comment by adambray** [comment]
@tomBeach As I mentioned in our discussion, you'll want to use `form_tag`, and explicitly state the path (action) that the form should submit to.

**Comment by adambray** [comment]
Also, your syntax for the names of your inputs looks off, I'd just do something like:

``` erb
<%= text_field_tag :first_name %>
<%= text_field_tag :last_name %>
<%= text_field_tag :room %>
```

And in your controller, you'd do something like:

``` ruby
@person = Person.create(first_name: params[:first_name], last_name: params[:last_name], etc...)
@patient = Patient.create(room: params[:room, etc)
@patient.person = @person
```

**Comment by RobertAKARobin** [comment]
It's been an hour, so I'm going to close this. Feel free to open a new issue!

**Comment by tomBeach** [comment]
Found a way to make this work with s form_for and fields_for option plus controller processing... Not pretty but working.  Thanks.

**Comment by RobertAKARobin** [comment]
Woo! Glad to hear it!
