### ISSUE TITLE
Adding Angular to MEN stack but cannot use res.json and res.render concurrently 

### ISSUE THREAD

**Issue by khoitle** [ga-wdi-exercises/project4#360]
How would i go about keeping my layout-main.hbs(express) being able to render?

**Comment by nolds9** [comment]
Typically, you would have only one route that render's an `hbs` file. Probably `'/'`. Then you have other routes that serve JSON, which you make AJAX requests to from the front-end when loading different angular states... for an example of this check out the route definitions of whenpresident

**Comment by khoitle** [comment]
I have the template rendering on all pages, but I also need data that was looped through using HBS to go with it

**Comment by khoitle** [comment]
In the example of whenpresident, the only thing that persists through all views is a header that says "When president..." with a link sending it to "/." I need that header or in this case a navbar, to have a populated dropdown menu

**Comment by khoitle** [comment]
<img width="1028" alt="screen shot 2016-11-30 at 11 31 38 am" src="https://cloud.githubusercontent.com/assets/20734065/20761353/b4e759c0-b6f0-11e6-832a-d01bb00c0370.png">

**Comment by nolds9** [comment]
Can I see what you are trying so far - meaning the route where you are rendering your `hbs` file?
 Do you not have access to the variables you pass to the view like you used to?

**Comment by khoitle** [comment]
Heres the route that renders json
<img width="538" alt="screen shot 2016-11-30 at 11 34 07 am" src="https://cloud.githubusercontent.com/assets/20734065/20761428/f4d86592-b6f0-11e6-9ae7-e97da0598862.png">

and heres the route that i no longer have access to the variable (basically copy/pasted but with a new app.get url
<img width="1002" alt="screen shot 2016-11-30 at 11 35 11 am" src="https://cloud.githubusercontent.com/assets/20734065/20761467/150efcc2-b6f1-11e6-8524-a9e5489bd5af.png">

**Comment by nolds9** [comment]
What is the `app.get` url for this `res.render` route? Which view is using the handlebars variables (the snippet your shared earlier)?

**Comment by khoitle** [comment]
For this res.render route, the app.get url is app.get("/champions") and the view that is using the handlebars variable is 
<img width="198" alt="screen shot 2016-11-30 at 11 44 17 am" src="https://cloud.githubusercontent.com/assets/20734065/20761834/5915771a-b6f2-11e6-9f69-911b63e95cd1.png">

**Comment by khoitle** [comment]
Does the url for this res.render route particularly matter?

**Comment by nolds9** [comment]
Essentially, I would be careful of the number of routes that are loading express view - In my mind, it should be only one -`"/"` - that is the only time you will call `res.render()` and that is where I would pass my variables to handlebars.

**Comment by khoitle** [comment]
So I would move all my javascript into that "/" route?

**Comment by khoitle** [comment]
It worked. Thanks Nick!

**Comment by khoitle** [comment]
One more question. My drop down bar only works on the home page. After navigating to a different view, it no longer populates. Any ideas as to why?

**Comment by khoitle** [comment]
Is it because after changing views, that specific view no longer as access to those variables?

**Comment by nolds9** [comment]
that's why Angular should be taking care of the views - you shouldn't have to load another express view

**Comment by khoitle** [comment]
I'll see what I can do. Thankss
