### ISSUE TITLE
Rails will not seed data

### ISSUE THREAD

**Issue by brophy2321** [ga-wdi-exercises/project4#361]
![image](https://cloud.githubusercontent.com/assets/21348450/20760575/694a1cb6-b6ee-11e6-8062-040bc074a60d.png)

![image](https://cloud.githubusercontent.com/assets/21348450/20760618/829c685e-b6ee-11e6-8cc6-fa9338ac8475.png)

**Comment by nolds9** [comment]
It's complaining about a missing column `muscle_id` on your `exercises` table. I would double check your `schema` and make sure you have your relationships set up in your model definitions

**Comment by brophy2321** [comment]
![image](https://cloud.githubusercontent.com/assets/21348450/20761461/11685afa-b6f1-11e6-9285-dd6efe2b4e0a.png)

**Comment by jshawl** [comment]
you need to add a column for muscle_id on exercises table

**Comment by brophy2321** [comment]
when i ran my rails g model Exercise, i should have added muscle:references?

**Comment by brophy2321** [comment]
I can't just write that in, can I?

**Comment by nolds9** [comment]
Not really, i would make a new migration to add that references

**Comment by brophy2321** [comment]
rails g migration exercise muscle:references

**Comment by brophy2321** [comment]
like this?

**Comment by nolds9** [comment]
try it out! look at the file that is generated, then I'd look at after you run your migrations, does the schema look how you would expect...

**Comment by brophy2321** [comment]
![image](https://cloud.githubusercontent.com/assets/21348450/20761922/8a8591a4-b6f2-11e6-98f8-4ec30dc82430.png)

**Comment by brophy2321** [comment]
schema looks exactly the same

**Comment by jshawl** [comment]
you migration file needs

```
add_column
```

to fix this:

```
rake db:rollback
```

then add the following line:

```
add_column :muscles, :exercise_id, :integer
```

then remigrate

**Comment by brophy2321** [comment]
![image](https://cloud.githubusercontent.com/assets/21348450/20762142/70739b84-b6f3-11e6-9d63-5c32a5368031.png)

**Comment by jshawl** [comment]
let's see schema.rb

**Comment by brophy2321** [comment]
![image](https://cloud.githubusercontent.com/assets/21348450/20762211/a3c06756-b6f3-11e6-863d-b039c1261dd1.png)

**Comment by jshawl** [comment]
ohh im sorry it needs to be the other way around - you need a muscle id on exercises table, not an exercise_id on muscles table - that was my fault

**Comment by brophy2321** [comment]
do a roll back and change that to add_column :exercises, :muscle_id, :integer?

**Comment by brophy2321** [comment]
it worked thank you
