### ISSUE TITLE
Angular router not routing

### ISSUE THREAD

**Issue by marks828** [ga-wdi-exercises/project4#362]
I can't get anything to render through $stateProvider. I've tried renaming, different templateUrl routes, and just templating the route and nothing is appearing on "/#/bets"
code:
![image](https://cloud.githubusercontent.com/assets/15305847/20762182/8ca6ec3e-b6f3-11e6-965c-5423c9f563ab.png)

![image](https://cloud.githubusercontent.com/assets/15305847/20762205/9edf49f0-b6f3-11e6-9712-f6beb3396fb7.png)

**Comment by nolds9** [comment]
solved IRL because of issue with Angular CDN
