### ISSUE TITLE
Angular Strange Linking

### ISSUE THREAD

**Issue by alman92** [ga-wdi-exercises/project4#363]
![image](https://cloud.githubusercontent.com/assets/19317100/20764802/d1925b4e-b6fd-11e6-9d2e-70dded926be3.png)

![image](https://cloud.githubusercontent.com/assets/19317100/20764817/e160f242-b6fd-11e6-9c6e-b54991f93d2b.png)

When I click on any of those links, they are all connected as one link, don't really know how it happened or how to fix it.

**Comment by jshawl** [comment]
you must be missing a closing a tag

**Comment by nolds9** [comment]
what is making them links?

**Comment by jshawl** [comment]
time.ly maybe?

**Comment by alman92** [comment]
![image](https://cloud.githubusercontent.com/assets/19317100/20764878/233d878e-b6fe-11e6-99bc-3f32d61475ef.png)

Here is the only link tag I wrote

**Comment by alman92** [comment]
In the index.html file

**Comment by jshawl** [comment]
yeah you gotta close it before the closing h1

**Comment by alman92** [comment]
Oh my god I forgot the closing tag -_____-

**Comment by alman92** [comment]
Thanks......

**Comment by jshawl** [comment]
👍
