### ISSUE TITLE
Accessing ENV variables from Front End

### ISSUE THREAD

**Issue by merubin** [ga-wdi-exercises/project4#364]
In moving my keys out of my code to environment variables, I now cannot access two that I need in the front end.
process variable does not exist  Any Idea's on what to do to get variables?
```
var rubin_channel_id=parseInt(process.env.THINGSPEAK_RUBIN_CHANNEL_ID)
var thingspeak_api_key=process.env.THINGSPEAK_API_READ_KEY


console.log("rubin_channel 176785=" ,rubin_channel_id)
console.log("thingspeak_api_keyYXYMDONR71M6WO7Y=",thingspeak_api_key)
```

**Comment by jshawl** [comment]
unfortunately this is not possible - you'll need to either print it out in the html server-side or make an HTTP request to get those variables

**Comment by merubin** [comment]
I have it tracking now and can figure out I'm offline and it updates web page and sends text msg!
YEA!

<img width="1280" alt="screen shot 2016-11-30 at 3 47 40 pm" src="https://cloud.githubusercontent.com/assets/19254862/20770697/8eb862e8-b714-11e6-95a3-d8b1e1621ff4.png">

![image](https://cloud.githubusercontent.com/assets/19254862/20770716/a5131f7e-b714-11e6-9184-84281ef67225.png)

**Comment by amaseda** [comment]
🤘
