### ISSUE TITLE
How would I go about preventing my api keys viewable on my github repo?

### ISSUE THREAD

**Issue by khoitle** [ga-wdi-exercises/project4#367]

**Comment by amaseda** [comment]
What stack are you using? Where are you currently keeping your API keys?

**Comment by khoitle** [comment]
I'm using the MEAN stack and the keys are in my index.js

**Comment by amaseda** [comment]
You can either...
1. Define those keys in a separate JS file, `module.exports` the keys and then require that file in `index.js`. To keep them from being uploaded to Github, you would need to include the keys file in a `.gitignore`
2. Define them as environment variables. More on that [here](https://medium.com/@rafaelvidaurre/managing-environment-variables-in-node-js-2cb45a55195f#.aidtdqi8x).

**Comment by amaseda** [comment]
@KhoiLe89 Any luck with this?

**Comment by amaseda** [comment]
@KhoiLe89 Going to close assuming you made progress, but if not feel free to re-open. Happy to help.
