### ISSUE TITLE
Cannot Get the Google Map to Display On Screen

### ISSUE THREAD

**Issue by LWatsonlm** [ga-wdi-exercises/project4#368]
heyo! I'm hoping someone could help (oh hey, @AWhitleyGA feel free to chime in ;)) with displaying the Google map. 

```js
.controller("mapController", [
    "Drink",
    initMap
  ])
```
and the function:

```js
  function initMap(Drink) {
    var map;
    window.onload = function() {
      console.log(document.getElementById('map'));
      map = new google.maps.Map(document.getElementById('map'), {
        zoom: 2,
        center: new google.maps.LatLng(2.8,-187.3),
        mapTypeId: 'terrain'
      });
      // Create a <script> tag and set the API URL as the source.
      var script = document.createElement('script');
      script.src = 'http://localhost:3000/api/drinks/';
      document.getElementsByTagName('head')[0].appendChild(script);

      // Loop through the results array and place a marker for each
      // set of coordinates.
      window.eqfeed_callback = function(results) {
        for (var i = 0; i < results.features.length; i++) {
          var coords = results.features[i].geometry.coordinates;
          var latLng = new google.maps.LatLng(coords[1],coords[0]);
          var marker = new google.maps.Marker({
            position: latLng,
            map: map
          });
        }
      }
    }
  }
```
When I check the console, I see ``` document.getElementById('map') ``` is appearing but any help on why it's not showing on the page?
 
![screen shot 2016-11-30 at 8 31 28 pm](https://cloud.githubusercontent.com/assets/6773087/20778598/9f625f72-b73c-11e6-8116-5fe5dcbe4cca.png)

**Comment by LWatsonlm** [comment]
Just in case this is helpful: I'm looking at the first example in this Google API doc:
https://developers.google.com/maps/documentation/javascript/earthquakes

**Comment by AndyWhitley** [comment]
<img width="905" alt="screen shot 2016-11-30 at 10 21 48 pm" src="https://cloud.githubusercontent.com/assets/21045394/20780745/7891a6f0-b74b-11e6-821b-d77abc9566aa.png">

**Comment by AndyWhitley** [comment]
Notice in their example the second script where '&callback=initMap' is attached to the second script's src. What it means is that it is not actually calling initMap (thus rendering the map on the screen) UNTIL the google maps API has been loaded in. Check your code to make sure that initMap isn't triggered until all necessary scripts have been processed

**Comment by amaseda** [comment]
@LWatsonlm pinging in case you didn't see @AWhitleyGA's comment! ☝️☝️☝️

**Comment by LWatsonlm** [comment]
Thanks guys! So, I have that line with the rest of my scripts...Looks like you're right that it's getting triggered the function runs but I can't put a script tag inside my function. Where/what could I do to ensure that script is ran after the function? 

```html
<script src="https://ajax.googleapis.com/ajax/libs/angularjs/1.5.7/angular.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/angular.js/1.5.0-beta.2/angular-resource.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/angular-ui-router/0.2.15/angular-ui-router.min.js"></script>
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.1.1/jquery.min.js"></script>
<script src="/assets/js/app.js"></script>
<link rel="stylesheet" type="text/css" href="css/styles.css">
<script async defer
src="https://maps.googleapis.com/maps/api/js?key=xxxxxxxx&callback=initMap">
</script>

<div ng-app="Sip">
  <main data-ui-view></main>
</div>
```

**Comment by nolds9** [comment]
Is there any way to manually call your `initMap` function when an angular state loads with `ng-init`

i.e. in whichever view loads that placeholder div for the map, I would have something like: 

```js
<div ng-init="vm.initMap()">
  <div id="map"></div>
</div>
```
**Note**: with this approach you would need to bind `initMap` to your controller like:

```js
// in your map controller

this.initMap = initMap
```

**Comment by LWatsonlm** [comment]
okay, I have something like that now, Nick. And not getting a new error, still no map:
![fail](https://cloud.githubusercontent.com/assets/6773087/20799657/d54f931a-b7b0-11e6-9e77-950f050e6aff.png)

```js
  function initMap() {
    this.initMap = initMap
    console.log("can u see mE?");
    var map;
    map = new google.maps.Map(document.getElementById('map'), {
      zoom: 2,
      center: new google.maps.LatLng(2.8,-187.3),
      mapTypeId: 'terrain'
    });

    // Create a <script> tag and set the USGS URL as the source.
    var script = document.createElement('script');
    // This example uses a local copy of the GeoJSON stored at
    // http://earthquake.usgs.gov/earthquakes/feed/v1.0/summary/2.5_week.geojsonp
    script.src = 'https://developers.google.com/maps/documentation/javascript/examples/json/earthquake_GeoJSONP.js';
    document.getElementsByTagName('head')[0].appendChild(script);
  }

  // Loop through the results array and place a marker for each
  // set of coordinates.
  window.eqfeed_callback = function(results) {
    for (var i = 0; i < results.features.length; i++) {
      var coords = results.features[i].geometry.coordinates;
      var latLng = new google.maps.LatLng(coords[1],coords[0]);
      var marker = new google.maps.Marker({
        position: latLng,
        map: map
      });
    }
  }
```

```html
<div ng-init='vm.initMap()'>
  <div id='map'></div>
</div>
```

and controller and state:

```js
  .controller("mapController", [
    "Drink",
    initMap
  ])
```

```js
      .state("map", {
        url: "/sip",
        templateUrl: "js/ng-views/maps.html"
        controller: "mapController",
        controllerAs: "vm",
      })
```

**Comment by LWatsonlm** [comment]
that errors sounds like it can't find the id=map  .. making id=map null.
but i'm not sure why

**Comment by nolds9** [comment]
you need to remove the`&callback=initMap` from the script tag

**Comment by nolds9** [comment]
so not `this.initMap = initMap` inside of that function, but inside of whichever controller is attached to the view

**Comment by amaseda** [comment]
@LWatsonlm This one was solved IRL, right? If so, could you close the issue plz.

**Comment by LWatsonlm** [comment]
thanks for everyone's help!
