### ISSUE TITLE
Please DeveloperGods have mercy of my soul! I AM TIRED!

### ISSUE THREAD

**Issue by a-espinoza** [ga-wdi-exercises/project4#369]
Hi, just passing by after a couple of couple of hours trying to fix this problem!
Im about to deploy through AmazonS3..
According to there Documentation, and after following the steps I am currently facing a NPM dependecy problem!
When I try to install " npm install --save-dev gulp-s3 " I get a million errors! Tried from MAC, tried from windows running as administrator and I keep getting the same problem. Googled away for a couple hours and nothing seems to fix the problem!

Here I run the build:
![image](https://cloud.githubusercontent.com/assets/19412086/20782301/9de08806-b758-11e6-9cac-b326ed08cead.png)

Here I have my aws.json with my keys ():
![untitled-1](https://cloud.githubusercontent.com/assets/19412086/20782351/03f92f08-b759-11e6-942d-a6871c5d3072.jpg)

Then I run $Gulp Deploy , and this jibrish happens:
![image](https://cloud.githubusercontent.com/assets/19412086/20782369/362330fa-b759-11e6-8ec4-48cc125b162d.png)

Seems impossible to me! :( MadNinja

**Comment by a-espinoza** [comment]
just in case this is my pnm debug log
![image](https://cloud.githubusercontent.com/assets/19412086/20782403/8fa67524-b759-11e6-99be-eaad195c1c56.png)

**Comment by jshawl** [comment]
Operation not permitted indicates you don't have permission to install node modules on the server.

Where are you trying the npm install?

**Comment by a-espinoza** [comment]
I'm not sure I follow the question? But maybe this is the answer! Im running npm Install on my folder directory because I need it to install the Amazons3 dependencie so it can then call my aws.json with that info and then run "gulp-s3" which is a gulp task to connect to a AWS bucket where all my files will be stored!

I'm a mess I know ! Let me know if you need to see a snipet of code or anything else! Thx!

**Comment by jshawl** [comment]
>on my folder directory 

I see that you're on windows now - but im not sure what the windows equivalent of `sudo` is...

**Comment by a-espinoza** [comment]
I can run it from my mac laptop!" $ sudo npm install --save gulp-s3" ??

**Comment by jshawl** [comment]
yeah try that

**Comment by amaseda** [comment]
@a-espinoza how'd this go?

**Comment by a-espinoza** [comment]
Hey! Did not work, so I will work on scalability and that specific feature on a later time! Meanwhile, I'll deploy with ghPages!

**Comment by a-espinoza** [comment]
Thk you guys!
