### ISSUE TITLE
Nodemon just freezing up

### ISSUE THREAD

**Issue by brown2206** [ga-wdi-exercises/project4#370]
![image](https://cloud.githubusercontent.com/assets/20567326/20791066/412c1266-b789-11e6-8f8a-3d214c26620e.png)

This isn't an error but for some reason, Nodemon is getting hung up with my index.js file.  It was working perfectly fine an hour ago, now all of a sudden I can't get the node app to run.  Can someone please help me?

**Comment by amaseda** [comment]
What do you mean gets hung up?

Try placing a `console.log` statement at the top of `index.js`. Does that print out in the terminal? Trying to see if the file is running but it's getting hung up on a particular piece of your code.

**Comment by brown2206** [comment]
This issue has been resolved now.  Please close this issue.  Thanks.

**Comment by amaseda** [comment]
Will do. (FYI you can close the issue too!)
