### ISSUE TITLE
Making a POST request in Postman

### ISSUE THREAD

**Issue by brown2206** [ga-wdi-exercises/project4#371]
Hello.  I'm having an issue with my POST request to my backend API in Postman.  I have fields such as Name, Address, Account_No that aren't being added to the JSON when I make a post request to my backend API.  Here's a snippet of what I've submitted.

![image](https://cloud.githubusercontent.com/assets/20567326/20797000/fcd16e54-b7a6-11e6-9ae6-9c1bffd8aa56.png)
 
...and here's a copy of my schema...
![image](https://cloud.githubusercontent.com/assets/20567326/20797020/106927ea-b7a7-11e6-906c-af4a5149ece6.png)

I would like to make it so that all of my schema fields are displayed when I make a post request to Postman.  Why is this happening?

**Comment by jshawl** [comment]
can I see the code that handles the post request? `app.post...`

**Comment by brown2206** [comment]
![image](https://cloud.githubusercontent.com/assets/20567326/20797227/ddf58384-b7a7-11e6-9969-62520e2c554f.png)

**Comment by jshawl** [comment]
and do you have seed data? seeds will verify if this issue is a mongoose issue or an express issue

**Comment by brown2206** [comment]
![image](https://cloud.githubusercontent.com/assets/20567326/20797251/f81c46b2-b7a7-11e6-99d4-0889a8b7bf5c.png)

**Comment by jshawl** [comment]
yeah and running the seeds again works correctly?

**Comment by brown2206** [comment]
![image](https://cloud.githubusercontent.com/assets/20567326/20797264/05b3e5b4-b7a8-11e6-8297-4326855b1bc6.png)

**Comment by brown2206** [comment]
The seeds work just fine...it's just when I try to make a test post request that this happens.

**Comment by brown2206** [comment]
Let me show you...

**Comment by jshawl** [comment]
ok excellent! unfortunately - im not sure how node-restful works. is there anything like strong params witht aht module?

**Comment by brown2206** [comment]
![image](https://cloud.githubusercontent.com/assets/20567326/20797300/2a81bae2-b7a8-11e6-82cd-28040ed986f5.png)

**Comment by brown2206** [comment]
Could this possibly be similar to strong params?

rest.register(app, route)

**Comment by jshawl** [comment]
honestly i have no idea

**Comment by brown2206** [comment]
As you can see, General Electric is perfect, Honda Finance is perfect, Capital One incomplete.

**Comment by brown2206** [comment]
Can we discuss this as a group?  Maybe someone else has encountered this?

**Comment by jshawl** [comment]
sure come on over
