### ISSUE TITLE
Issue getting this console log to show up

### ISSUE THREAD

**Issue by alman92** [ga-wdi-exercises/project4#372]
![image](https://cloud.githubusercontent.com/assets/19317100/20800031/0761eeba-b7b2-11e6-9d1d-c988caf2612d.png)

URL: http://localhost:9000/#/goals/1

There is a goal id at 1 in my seeds in rails so I feel like something should show up.

**Comment by jshawl** [comment]
what connects `http://localhost:9000/#/goals/1` to that console.log?

**Comment by alman92** [comment]
Nothing as of yet, still needs a factory.  I just thought if you console logged before the factory it should still work.  It worked before I built my factory for the index.

**Comment by jshawl** [comment]
currently nothing is invoking that function - it won't get called. you can test this without a factory by using a router function

**Comment by alman92** [comment]
Well i have the controller function and it set in the router already.

![image](https://cloud.githubusercontent.com/assets/19317100/20800260/e4da02aa-b7b2-11e6-95c3-593d215eed09.png)

**Comment by jshawl** [comment]
does "hitting router" get logged?

**Comment by alman92** [comment]
Yea it does

**Comment by jshawl** [comment]
and do you have `angular.controller("goalsShowController")` somewhere?

**Comment by alman92** [comment]
Yup!

![image](https://cloud.githubusercontent.com/assets/19317100/20800334/2c7dfe2c-b7b3-11e6-906e-e98cbe9f13bc.png)

**Comment by jshawl** [comment]
do you have a ui-view in your html?

**Comment by alman92** [comment]
Sorry I was talking to Nick, yes I do 

![image](https://cloud.githubusercontent.com/assets/19317100/20800747/8402af52-b7b4-11e6-81a9-f6c18de8b78d.png)

**Comment by jshawl** [comment]
any errors in the console?

**Comment by alman92** [comment]
No the console is clean

**Comment by jshawl** [comment]
hmm wanna push what you have not sure im seeing anything obvious

**Comment by alman92** [comment]
Both are pushed up on my repo's

**Comment by alman92** [comment]
https://github.com/alman92/time.ly-angular

https://github.com/alman92/time.ly

**Comment by jshawl** [comment]
do you need the initial slash for goals show? https://github.com/alman92/time.ly-angular/blob/master/js/app.js#L33-L39

**Comment by jshawl** [comment]
e.g. `/goals/:id` instead of `goals/:id`

**Comment by alman92** [comment]
No I don't think so, let me check

**Comment by alman92** [comment]
Ok yes I do actually, now im getting a console error

![image](https://cloud.githubusercontent.com/assets/19317100/20801842/2825b0b8-b7b8-11e6-9566-0a1ffc93f591.png)

**Comment by alman92** [comment]
Does this mean now I need a factory for the GET request?

**Comment by jshawl** [comment]
ok excellent!

**Comment by jshawl** [comment]
what? no that issue means you're trying to load `show/html` instead of `show.html`, right?

**Comment by alman92** [comment]
Oh my god what a stupid syntax error.....

**Comment by alman92** [comment]
Ok im still getting the same error

**Comment by jshawl** [comment]
which error

**Comment by alman92** [comment]
![image](https://cloud.githubusercontent.com/assets/19317100/20802072/d257d87c-b7b8-11e6-9600-4a41c2eb5814.png)

**Comment by alman92** [comment]
I feel like that means I either am not serving the JSON correctly in rails or I need to make some sort of GET request

**Comment by jshawl** [comment]
you need to change this line - https://github.com/alman92/time.ly-angular/blob/75e10bf712b2eecf8f1d041de754852d1e6da155/js/app.js#L40

instead of `show/html`, you need `show.html`

**Comment by alman92** [comment]
Oh i did that I just didnt push

**Comment by jshawl** [comment]
maybe you need to clear the cache? code looks good!

**Comment by alman92** [comment]
Hmmm ok let me try

**Comment by alman92** [comment]
That didn't work :/ If the code looks good then I feel like I'm missing something to pull the JSON.  Do you gave any ideas on a next step?

**Comment by jshawl** [comment]
yeah do you still have the show/html error? if so - try opening an incognito window and testing - do you still get the same error?

**Comment by alman92** [comment]
Yea I do but the HTTP requests are different, I'm going to go get food but I'll come back to this later.

**Comment by nolds9** [comment]
closing this for now since we talked about this IRL!
