### ISSUE TITLE
Cannot update or delete

### ISSUE THREAD

**Issue by marks828** [ga-wdi-exercises/project4#373]
I'm running into a problem with update and delete

error:
![image](https://cloud.githubusercontent.com/assets/15305847/20801494/22e0163a-b7b7-11e6-8f20-5a391bffa15b.png)

controllers:
![image](https://cloud.githubusercontent.com/assets/15305847/20801475/13243a00-b7b7-11e6-852b-f0589c2b3e7b.png)

forms:
![image](https://cloud.githubusercontent.com/assets/15305847/20801545/4d7137bc-b7b7-11e6-8664-1611ab2bc510.png)

**Comment by jshawl** [comment]
you need to enable CORS check out http://enable-cors.org/server_expressjs.html

**Comment by marks828** [comment]
Oh sorry, it's in rails

![image](https://cloud.githubusercontent.com/assets/15305847/20801655/9de91c1e-b7b7-11e6-996d-fb5f377eb36d.png)

**Comment by jshawl** [comment]
ok looks great! did you stop and restart the server?

**Comment by marks828** [comment]
Yup

**Comment by jshawl** [comment]
methods are specified in your code as only get, post, and options - what if you add patch and delete

**Comment by marks828** [comment]
Did not work

**Comment by jshawl** [comment]
did you restart your server

**Comment by marks828** [comment]
Yup

**Comment by jshawl** [comment]
can i see what you tried and what error message you'r getting

**Comment by marks828** [comment]
console error: 
![image](https://cloud.githubusercontent.com/assets/15305847/20802153/19a9d31a-b7b9-11e6-8552-af1536a50535.png)

**Comment by marks828** [comment]
tried adding patch, delete, put, and destroy into rack cors. Tried taking out the options from there as well.

**Comment by jshawl** [comment]
can i see the code

**Comment by jshawl** [comment]
you need options because the error message is "no route matches options"

**Comment by marks828** [comment]
my routes?

![image](https://cloud.githubusercontent.com/assets/15305847/20802283/99e7ff3e-b7b9-11e6-8c33-2b3b456d1de2.png)

**Comment by jshawl** [comment]
sorry no where you enabled cors

**Comment by marks828** [comment]
is this it? it's in application.rb

![image](https://cloud.githubusercontent.com/assets/15305847/20802407/ee550512-b7b9-11e6-8f4f-fd0965245cdd.png)

**Comment by jshawl** [comment]
yeah! you need `:methods => [:get, :post, :options, :delete, :patch, :put]` right?

**Comment by marks828** [comment]
Worked. I tried variations of that but never the whole list.
