### ISSUE TITLE
Whenever I go to look at a particular exercise i keep getting no method error

### ISSUE THREAD

**Issue by brophy2321** [ga-wdi-exercises/project4#374]
![image](https://cloud.githubusercontent.com/assets/21348450/20802112/f60ee260-b7b8-11e6-9fc9-8911ad87de36.png)
![image](https://cloud.githubusercontent.com/assets/21348450/20802117/fbd5bd0e-b7b8-11e6-94dc-3042d9ccec20.png)
![image](https://cloud.githubusercontent.com/assets/21348450/20802127/03948db8-b7b9-11e6-8e69-7f2088eb7521.png)

**Comment by brophy2321** [comment]
![image](https://cloud.githubusercontent.com/assets/21348450/20802165/252fa5ca-b7b9-11e6-86ff-dffae95a723b.png)
meant to send this screen

**Comment by nolds9** [comment]
Can you inspect `@exercise` and make sure it is what you think it is?

**Comment by brophy2321** [comment]
my mistake i didnt define show in the controller
