### ISSUE TITLE
Ajax callbacks not working, though Ajax post is

### ISSUE THREAD

**Issue by lizafloyd** [ga-wdi-exercises/project4#375]
Back end: https://github.com/lizafloyd/wanderfully_db
Front end: https://github.com/lizafloyd/Wanderful.ly

The dreams controller is the best place to see this issue at work. 

![image](https://cloud.githubusercontent.com/assets/20960160/20801898/506fb62c-b7b8-11e6-8555-e719e0164f93.png)

Though the ajax is posting to my db, none of the callbacks are being triggered.

**Comment by nolds9** [comment]
What do you mean by not working? Are you getting an error?

**Comment by lizafloyd** [comment]
Nope! Getting nothing at all.

**Comment by amaseda** [comment]
Ah, the issue might be that you're note sending any JSON back (i.e., `res.json`) [here](https://github.com/lizafloyd/wanderfully_db/blob/master/index.js#L296). You need to send something back for a callback to be triggered.

Is there a particular reason you're not using a factory / ngResource to do this? Would make your code more concise.

**Comment by lizafloyd** [comment]
WAIT! When I refresh the page, I see the callback error briefly.

Ok, I will try that. Thanks!

I am not using a factory for the moment because it's a custom address and so I built it that way to get it working.  Yes, I would love to refactor to a factory but haven't built it yet.  One failing at a time :)

**Comment by lizafloyd** [comment]
No luck, gentleman. I added the res.json, and can see it successfully at localhost, but still no callbacks showing up when they should.  However, when I enter a trip and then manually refresh the page, I see the console logs show up for just a moment in the refresh. Why wouldn't they show up when the ajax call is complete?

**Comment by jshawl** [comment]
hmm let's backtrack a second - if you look at the network tab - can you see your server responding with the JSON correctly?

**Comment by lizafloyd** [comment]
Oh! It's showing a status of pending. Any thoughts why?

**Comment by jshawl** [comment]
`res.json` must not be completing

**Comment by jshawl** [comment]
what happens if any of these lines fail? https://github.com/lizafloyd/wanderfully_db/blob/master/index.js#L297-L301

**Comment by lizafloyd** [comment]
But the instance is being created correctly, and is showing up later, and also at localhost of my db. Leads me to believe that those lines aren't failing. If res.json weren't working, why would I be able to see the json at localhost?

**Comment by jshawl** [comment]
that is the question...

**Comment by jshawl** [comment]
can you drop some more console.log's in there to see how far the request is getting before the res.json?

**Comment by lizafloyd** [comment]
IT'S ALIVE!! Thank you, it was the res.json.  THANKS EVERYONE!
