### ISSUE TITLE
Error Deploying

### ISSUE THREAD

**Issue by khoitle** [ga-wdi-exercises/project4#376]
Says it has deployed correctly 
<img width="509" alt="screen shot 2016-12-01 at 11 53 07 am" src="https://cloud.githubusercontent.com/assets/20734065/20803322/c2c91b92-b7bc-11e6-9f92-3e91c6aa6a49.png">

but...
<img width="1280" alt="screen shot 2016-12-01 at 11 53 53 am" src="https://cloud.githubusercontent.com/assets/20734065/20803349/e115e9cc-b7bc-11e6-9bb1-28286dfadb98.png">

**Comment by nolds9** [comment]
Can you check your logs?

**Comment by nolds9** [comment]
my guess is that there was an error starting your app

**Comment by khoitle** [comment]
How do i check my logs?

**Comment by nolds9** [comment]
`$ heroku logs -t`

**Comment by khoitle** [comment]
whoa.. i just got a HUGE error list 
<img width="1280" alt="screen shot 2016-12-01 at 12 05 23 pm" src="https://cloud.githubusercontent.com/assets/20734065/20803793/7578b026-b7be-11e6-9be2-0a51333c2185.png">
<img width="1280" alt="screen shot 2016-12-01 at 12 05 40 pm" src="https://cloud.githubusercontent.com/assets/20734065/20803810/7f51e11c-b7be-11e6-8f4f-4d5d357d371e.png">

**Comment by nolds9** [comment]
so the important stuff is `npm ERR! missing script: start`

**Comment by nolds9** [comment]
You need to tell heroku how to start your app, and you can do this by adding a script `start` to your `package.json` like https://github.com/heroku/node-js-getting-started/blob/master/package.json#L10

**Comment by khoitle** [comment]
After placing that in my package.json do i add and commit and repush?

**Comment by khoitle** [comment]
Uh oh getting another error, It says it cant find the module request 
<img width="847" alt="screen shot 2016-12-01 at 12 15 57 pm" src="https://cloud.githubusercontent.com/assets/20734065/20804193/f784ec50-b7bf-11e6-859f-5201643133cb.png">

but heres my index.js 

<img width="571" alt="screen shot 2016-12-01 at 12 16 34 pm" src="https://cloud.githubusercontent.com/assets/20734065/20804212/056479da-b7c0-11e6-93ea-8d6d0fdd6da3.png">

**Comment by nolds9** [comment]
make sure you see `request` as a `dependency` in your `package.json`. Maybe missed the `--save` when you install the package locally

**Comment by khoitle** [comment]
should i run npm install --save request?

**Comment by khoitle** [comment]
nooo, yet another error!
<img width="1280" alt="screen shot 2016-12-01 at 12 21 44 pm" src="https://cloud.githubusercontent.com/assets/20734065/20804405/c1461668-b7c0-11e6-81fc-c3463319e2d5.png">

**Comment by nolds9** [comment]
So you need to setup your mongo db for production. To do this, heroku recommends using mongolab to do this...

I would recommend reading through [this issue](https://github.com/ga-wdi-exercises/project4/issues/359#issuecomment-263917315) to see all of the steps involved

**Comment by khoitle** [comment]
alright! thanks for the help :)

**Comment by khoitle** [comment]
I'm now getting this error 
<img width="1111" alt="screen shot 2016-12-01 at 3 08 58 pm" src="https://cloud.githubusercontent.com/assets/20734065/20810574/37f8db3a-b7d8-11e6-8681-d6a9a63641bb.png">
