### ISSUE TITLE
Adventures in localStorage!

### ISSUE THREAD

**Issue by lizafloyd** [ga-wdi-exercises/project4#377]
Hi Team!

Here's another little one for you: in the user authentication process, I have saved some data in localStorage.  I am therefore trying to use an ng-if directive to determine whether to show the 'log out' link or the 'sign in' link.  Please see below: 

![image](https://cloud.githubusercontent.com/assets/20960160/20804597/7d635234-b7c1-11e6-999d-2e4e9f2d02b6.png)

When I check in console, the data object localStorage.currentUserId is appearing exactly as I want it to. But the ng-if is acting like it's undefined, and showing the sign up link when there's already an active user.  Am I misunderstanding ng-if?

![image](https://cloud.githubusercontent.com/assets/20960160/20804649/bdaf3e48-b7c1-11e6-80bd-ff8d8eb86974.png)

Thanks!

**Comment by jshawl** [comment]
isn't the syntax `localStorage.getItem("something")` and not `localStorage.something`

**Comment by lizafloyd** [comment]
OK, changed it.  While that syntax works in the console (they both do), neither works in the code.  Since I have no errors, I'm not sure where to look for that problem.

**Comment by jshawl** [comment]
can i see what you tried

**Comment by lizafloyd** [comment]
![image](https://cloud.githubusercontent.com/assets/20960160/20811878/77c604ea-b7dd-11e6-9e71-3af9fad42739.png)

How does this look?

**Comment by jshawl** [comment]
does that work as you expect it to? looks good to me...

**Comment by lizafloyd** [comment]
No, it is still treating the value as falsey, when it does exist. So it's returning the wrong option.

**Comment by jshawl** [comment]
ok can you `cmd-opt-j` open up the dev tools and type `localStorage.getItem('currentUserId')` ? 

is that what you expect it to be?

**Comment by lizafloyd** [comment]
Sorry, do you mean in console?

**Comment by jshawl** [comment]
yea!

**Comment by lizafloyd** [comment]
Yeah, I've done that! It gives me the correct value with both sytaxes

**Comment by jshawl** [comment]
ok this is promising - maybe what you can do is use JS to set a vm variable - so instead of executing local storage query in the view you do that in your controller - know what i mean?

**Comment by lizafloyd** [comment]
Ok, that makes sense! Would I have to do that in every controller for every page I want it to appear on?

**Comment by jshawl** [comment]
that does sound like a pain... maybe try it out for one - and explore ways to share state across angular controlloers

**Comment by lizafloyd** [comment]
Cool. I'll get it working in one state and google from there.  Thanks!

**Comment by jshawl** [comment]
👍

**Comment by lizafloyd** [comment]
Yeah!
