### ISSUE TITLE
Having trouble creating new exercises

### ISSUE THREAD

**Issue by brophy2321** [ga-wdi-exercises/project4#378]
![image](https://cloud.githubusercontent.com/assets/21348450/20807595/9b5b14a0-b7cd-11e6-994a-8cf0a4f5d5d8.png)
![image](https://cloud.githubusercontent.com/assets/21348450/20807607/a6c304d8-b7cd-11e6-9a1f-a0df6dce2d8e.png)
![image](https://cloud.githubusercontent.com/assets/21348450/20807625/b44129a0-b7cd-11e6-89b0-1b9c19ee8b25.png)

**Comment by brophy2321** [comment]
hit a wall, went over with a few people and cant figure this out

**Comment by jshawl** [comment]
can I see config/routes.rb?

**Comment by brophy2321** [comment]
![image](https://cloud.githubusercontent.com/assets/21348450/20809610/980c008c-b7d4-11e6-937e-6b47b4bef9be.png)

**Comment by amaseda** [comment]
How are you getting to this error?

I would not expect `/muscles/new` to be a post request. `/new` usually responds with having to GET a form.

Would be helpful to see your muscles controller as well.

**Comment by brophy2321** [comment]
well Im trying to update the exercise within that specific muscle group. I have 4 groups. Should my new.html.erb form be in the exercises folder? I moved it just to see if itd work that way?

**Comment by brophy2321** [comment]
![image](https://cloud.githubusercontent.com/assets/21348450/20810163/953a226a-b7d6-11e6-9a0c-5379748fc92a.png)

**Comment by brophy2321** [comment]
![image](https://cloud.githubusercontent.com/assets/21348450/20810170/9a8ed3aa-b7d6-11e6-95e3-5a35529280ca.png)

**Comment by brophy2321** [comment]
here is the exercise controller as well 
![image](https://cloud.githubusercontent.com/assets/21348450/20810339/65c1a908-b7d7-11e6-90da-91c47d75f5ec.png)

**Comment by amaseda** [comment]
What are you doing to get to this error? Submitting the form that you included in your original issue?

**Comment by brophy2321** [comment]
yes, on the muscles show page I have add new exercise. it goes to the form page and when i click submit it gives me the no route error

**Comment by brophy2321** [comment]
![image](https://cloud.githubusercontent.com/assets/21348450/20810441/c41492e0-b7d7-11e6-92af-18c1c974bce3.png)
![image](https://cloud.githubusercontent.com/assets/21348450/20810450/cf794b80-b7d7-11e6-9d7f-b0903d1247d1.png)
![image](https://cloud.githubusercontent.com/assets/21348450/20810464/d8f45308-b7d7-11e6-91ac-d728f7482406.png)
![image](https://cloud.githubusercontent.com/assets/21348450/20810472/e022612e-b7d7-11e6-9568-8e290c50ac54.png)

**Comment by brophy2321** [comment]
so i click show, it takes me to chest exercises. at the bottom i added the add new exercise
which is meant for it to be added to that particular muscle group

**Comment by amaseda** [comment]
What happens if in the form you replace `:exercise` at the top with `@exercise`?

**Comment by brophy2321** [comment]
sends the same error

**Comment by amaseda** [comment]
Oh, can you show me the form code for a new muscle -- not exercise? Because that's the form you're submitting.

**Comment by brophy2321** [comment]
I didnt create a form for that since i wouldnt be adding a new muscle group. Could that be the problem

**Comment by amaseda** [comment]
`/muscles/new` is going to correspond with creating a new muscle. A form for a new exercise, based on your routes, would be found at `/muscles/:muscle_id/exercises/new`. The form would then trigger whatever is in `exercises#create`.
