### ISSUE TITLE
Cannot deploy in heroku

### ISSUE THREAD

**Issue by pohckuan** [ga-wdi-exercises/project4#379]
I tried to deploy through github and CLI and both says that the app has been deployed, but I get application error when i open the link.

Following is the build log
![image](https://cloud.githubusercontent.com/assets/15622467/20808011/08de0202-b7cf-11e6-9266-f0ba197be237.png)

**Comment by jshawl** [comment]
I think this is the same as https://github.com/ga-wdi-exercises/project4/issues/352

**Comment by pohckuan** [comment]
i checked the log and the following is the first half of the log. 
I see that it cannot find the module "express-handlebars", but those are already in my index.js and package.json

![image](https://cloud.githubusercontent.com/assets/15622467/20811281/14549874-b7db-11e6-8bd0-4a9a8fa0859d.png)

**Comment by jshawl** [comment]
did you commit and push `package.json` with `express-handlebars` in there?

**Comment by pohckuan** [comment]
yes i did

**Comment by pohckuan** [comment]
![image](https://cloud.githubusercontent.com/assets/15622467/20811761/e819a86a-b7dc-11e6-93e1-9d83eec28d1a.png)

**Comment by jshawl** [comment]
yes this does look promising

**Comment by jshawl** [comment]
hmm locally can you try `node index.js` - do you get any errors?

**Comment by pohckuan** [comment]
oh yea there's error

![image](https://cloud.githubusercontent.com/assets/15622467/20812015/00abd78a-b7de-11e6-9aa6-cc55e4790c38.png)

**Comment by jshawl** [comment]
sorry i mean stop the other server and try `node index.js`

**Comment by pohckuan** [comment]
I think i can deploy my app on heroku now after entering my billing info. However, my seeds are not showing up, and when i run nodemon in my terminal there's an error 

![image](https://cloud.githubusercontent.com/assets/15622467/20812675/768d2dd0-b7e0-11e6-899b-968dee4bf43b.png)

**Comment by jshawl** [comment]
well this is somethin else. can i see `mongo.connect` line?

**Comment by pohckuan** [comment]
![image](https://cloud.githubusercontent.com/assets/15622467/20813082/441ec87a-b7e2-11e6-93bc-bd4f1f6fc91e.png)

**Comment by jshawl** [comment]
ok can you change that to `mongoose.connect(process.env.MONGODB_URI || 'mongodb://localhost/recipes')`

**Comment by jshawl** [comment]
and then try restarting the server

**Comment by pohckuan** [comment]
The page is showing now, but not the seed. Do i need to run seed in heroku?

**Comment by jshawl** [comment]
yes! try it out

**Comment by pohckuan** [comment]
I couldn't find the heroku way to seed. I ran node db/seed.js, the seeds are not showing up in the deployed app.

**Comment by jshawl** [comment]
`heroku run node db/seed.js`

**Comment by pohckuan** [comment]
IT WORKS!! 
THANKS JESSE!!!

**Comment by jshawl** [comment]
aw heck yeah! 👍
