### ISSUE TITLE
Adding a class via javascript to a text input

### ISSUE THREAD

**Issue by msteffan** [ga-wdi-exercises/project4#38]
I am having trouble getting CSS styles to correctly apply to form inputs when I add the class in JS after a click. 

The CSS rule I want to apply is: 

```
.strikeout {
    color: transparent;
    text-shadow: 0 0 5px rgba(0,0,0,0.5);
}

.strikeout:hover {
    color: black;
    text-shadow: none;
}
```

This blurs the text but displays it normally on hover. I'm adding it to my form input with this function: 

```
    $(".privacy-button").on("click", function(){
            $("p.source").toggleClass("strikeout");
            $("input[type=text]").toggleClass("strikeout");
        })
```

I know the class is getting added, and, if I add text to the input, it does turn black when I hover on it, but it does not blur out when I mouse or click off of it. The style correctly works when I apply it to a p tag (i.e. the `p.source` in the first part of the function.

**Comment by RobertAKARobin** [comment]
Ah, yeah, these are fun. Try making Chrome "force" the hover state so it's easier to diagnose and tinker with:

![screen shot 2015-09-17 at 10 19 47 am](https://cloud.githubusercontent.com/assets/6268177/9935618/bc42fe8e-5d25-11e5-8408-6799728c5aee.png)

**Comment by msteffan** [comment]
So it was actually the non-hover state that wasn't working, but I solved it by making my CSS rule apply to `input.strikeout` and now that works, but just `'.strikeout'` didn't work. Whatever, CSS.
