### ISSUE TITLE
RAILS issue

### ISSUE THREAD

**Issue by bkeating55** [ga-wdi-exercises/project4#380]
Originally I had my routes

resources :garages do
    resources :vehicles do
      resources :services
end
end

So I ended up with a huge url garages/:garage_id/vehicles/:vehicle_id/services but could never get it to 'services/new' or ':id' when I would submit the services form.  I chalked that up to a deep nesting issue so I changed it to 

<img width="1280" alt="screen shot 2016-12-01 at 2 43 13 pm" src="https://cloud.githubusercontent.com/assets/20100536/20809607/97542cbe-b7d4-11e6-9e5c-842f2c41da6a.png">

Im still getting the issue when I submit from here

<img width="1280" alt="screen shot 2016-12-01 at 2 44 36 pm" src="https://cloud.githubusercontent.com/assets/20100536/20809653/bc607d64-b7d4-11e6-913e-266a3d7f4d34.png">

It just takes me to 

<img width="1280" alt="screen shot 2016-12-01 at 2 45 33 pm" src="https://cloud.githubusercontent.com/assets/20100536/20809700/e116e968-b7d4-11e6-9452-317739093e8e.png">

Here is my services controller

<img width="1280" alt="screen shot 2016-12-01 at 2 47 22 pm" src="https://cloud.githubusercontent.com/assets/20100536/20809814/3b292c9a-b7d5-11e6-96a7-de5b28b58c2a.png">

rails routes

<img width="1280" alt="screen shot 2016-12-01 at 2 48 58 pm" src="https://cloud.githubusercontent.com/assets/20100536/20809847/550b143e-b7d5-11e6-8f96-cfcf9104bce1.png">

im using a  'services/form'
<img width="1280" alt="screen shot 2016-12-01 at 2 49 32 pm" src="https://cloud.githubusercontent.com/assets/20100536/20809896/75a88cda-b7d5-11e6-8b37-6fd8c74adcef.png">

thats used here in vehicles show.html.erb
<img width="1280" alt="screen shot 2016-12-01 at 2 51 12 pm" src="https://cloud.githubusercontent.com/assets/20100536/20809968/b5ae1f52-b7d5-11e6-90a5-36470a838834.png">

It is also no saving in the db

<img width="1280" alt="screen shot 2016-12-01 at 2 53 29 pm" src="https://cloud.githubusercontent.com/assets/20100536/20810035/fa6f61be-b7d5-11e6-99f9-249310fb98c7.png">

There are no errors it just takes me to '..../services' and just renders the background image.

**Comment by jshawl** [comment]
where do you want to go instead?

**Comment by jshawl** [comment]
on line 25, you could `redirect_to vehicle_path(@vehicle)`

**Comment by bkeating55** [comment]
I want to be able to display the vehicle and what I entered in the form as a "log" of sorts so a services show view?

**Comment by jshawl** [comment]
when on the services show page - if you view the source, command option u - can you see anything useful in there?

**Comment by bkeating55** [comment]
<img width="1280" alt="screen shot 2016-12-01 at 3 08 52 pm" src="https://cloud.githubusercontent.com/assets/20100536/20810548/20a51ebc-b7d8-11e6-8dce-0fa0696ef288.png">

**Comment by jshawl** [comment]
ohhh what is the contents of `app/views/services/show`?

**Comment by bkeating55** [comment]
<img width="1280" alt="screen shot 2016-12-01 at 3 10 34 pm" src="https://cloud.githubusercontent.com/assets/20100536/20810619/584cfe2a-b7d8-11e6-9a50-3e3aa176d7c2.png">

**Comment by jshawl** [comment]
hmm what is `app/views/services/index`?

**Comment by bkeating55** [comment]
<img width="1280" alt="screen shot 2016-12-01 at 3 17 07 pm" src="https://cloud.githubusercontent.com/assets/20100536/20810809/403ab420-b7d9-11e6-8115-7a3b2f60749d.png">

**Comment by jshawl** [comment]
ok this is it! try adding some text before the table tag - can you see that in the browser?

**Comment by bkeating55** [comment]
yes

**Comment by jshawl** [comment]
HELL YES

**Comment by jshawl** [comment]
ok so just some disconnect what data you're getting and how you're displaying it

**Comment by jshawl** [comment]
can i see `index` action of `services` controller?

**Comment by bkeating55** [comment]
<img width="1280" alt="screen shot 2016-12-01 at 3 26 40 pm" src="https://cloud.githubusercontent.com/assets/20100536/20811155/936a925e-b7da-11e6-9c42-174098452146.png">

**Comment by jshawl** [comment]
ok ok so this code looks correct - are you sure you have any services in your database?

**Comment by bkeating55** [comment]
Yesterday they were saving in the db but I messed with some code between now and then and no commits....they are not saving today

**Comment by bkeating55** [comment]
My main issue now is the data is not being saved from the form

**Comment by jshawl** [comment]
ah ok - i thought the issue was displaying sorry about that

**Comment by bkeating55** [comment]
It was both

**Comment by jshawl** [comment]
my recommendation is to create a seed to make sure it's not a database issue - can you narrow it down to either a problem with the html or a problem with the controller?

**Comment by bkeating55** [comment]
<img width="1280" alt="screen shot 2016-12-01 at 3 37 54 pm" src="https://cloud.githubusercontent.com/assets/20100536/20811553/248adb8a-b7dc-11e6-8897-e0074ec60bc1.png">

save and db:seed?

**Comment by bkeating55** [comment]
<img width="1280" alt="screen shot 2016-12-01 at 3 39 35 pm" src="https://cloud.githubusercontent.com/assets/20100536/20811620/62142a56-b7dc-11e6-8a33-e51852082ac2.png">

**Comment by bkeating55** [comment]
I got it to seed but it didn't show up
<img width="1280" alt="screen shot 2016-12-01 at 3 39 35 pm" src="https://cloud.githubusercontent.com/assets/20100536/20811680/a549c4de-b7dc-11e6-9e41-3ed29c0d74a2.png">

**Comment by bkeating55** [comment]
<img width="1280" alt="screen shot 2016-12-01 at 3 42 08 pm" src="https://cloud.githubusercontent.com/assets/20100536/20811705/be3e246c-b7dc-11e6-8f17-651663a8cff0.png">

**Comment by jshawl** [comment]
ok this seed looks right - but it says `vehicle` is not defined.

Try

```rb
vehicle = Vehicle.last
vehicle.services.create ...
```

**Comment by bkeating55** [comment]
Didn't save

**Comment by jshawl** [comment]
any errors? try `create!`

**Comment by bkeating55** [comment]
<img width="1280" alt="screen shot 2016-12-01 at 4 02 51 pm" src="https://cloud.githubusercontent.com/assets/20100536/20812466/af1f11aa-b7df-11e6-8671-02394f1459bb.png">

**Comment by nolds9** [comment]
interesting, can I see your `schema.rb` please?

**Comment by bkeating55** [comment]
<img width="1280" alt="screen shot 2016-12-01 at 4 04 48 pm" src="https://cloud.githubusercontent.com/assets/20100536/20812533/e9fa4e5c-b7df-11e6-98a3-9d63a2582346.png">

"maintenances" was a controller I created yesterday but deleted it and instead opted for 'services'

**Comment by jshawl** [comment]
Have you created any vehicles? can you make this your seed data:

```rb
Vehicle.last.services.create! ...
```

**Comment by bkeating55** [comment]
<img width="1280" alt="screen shot 2016-12-01 at 4 23 33 pm" src="https://cloud.githubusercontent.com/assets/20100536/20813169/8e59659e-b7e2-11e6-8418-5eab48f6b7bf.png">

not from seeding through the form, yes

**Comment by bkeating55** [comment]
Same error when I tried 'Vehicle.last.services.create!....'

**Comment by jshawl** [comment]
wtf

**Comment by jshawl** [comment]
can i see your seed data again

**Comment by bkeating55** [comment]
<img width="1280" alt="screen shot 2016-12-01 at 4 26 37 pm" src="https://cloud.githubusercontent.com/assets/20100536/20813263/faa8be02-b7e2-11e6-86d4-34666e3b0c76.png">

**Comment by jshawl** [comment]
and the error message is vehicle must exist?

**Comment by bkeating55** [comment]
ActiveRecord::RecordInvalid: Validation failed: Vehicles must exist

**Comment by jshawl** [comment]
does a `Vehicle` `belong_to` a `Service`?

**Comment by bkeating55** [comment]
<img width="1280" alt="screen shot 2016-12-01 at 4 31 38 pm" src="https://cloud.githubusercontent.com/assets/20100536/20813458/acb6f7d0-b7e3-11e6-9181-b0705d61696e.png">

i just changed this from has_many and got this error

NameError: uninitialized constant Vehicle::Services

**Comment by bkeating55** [comment]
<img width="1280" alt="screen shot 2016-12-01 at 4 32 46 pm" src="https://cloud.githubusercontent.com/assets/20100536/20813489/d35fb426-b7e3-11e6-821d-48e06320caf8.png">

**Comment by jshawl** [comment]
ah should be `belongs_to :vehicle` (singular)

**Comment by bkeating55** [comment]
smh

**Comment by bkeating55** [comment]
<img width="1280" alt="screen shot 2016-12-01 at 4 36 33 pm" src="https://cloud.githubusercontent.com/assets/20100536/20813638/5d1dc00e-b7e4-11e6-8041-e56e0780a0ed.png">

**Comment by bkeating55** [comment]
When I remove delete the seeds do show up...Thank you!

**Comment by jshawl** [comment]
aw hell yeah! gonna close out 👍
