### ISSUE TITLE
Angular not "refreshing" when things are added and deleted

### ISSUE THREAD

**Issue by marks828** [ga-wdi-exercises/project4#382]
When I create new bet or delete one, I need to manually refresh the page before links are created or taken away.

on creation: 
![image](https://cloud.githubusercontent.com/assets/15305847/20810387/86eec372-b7d7-11e6-8c88-3d0fdffdf590.png)

after manual reload:
![image](https://cloud.githubusercontent.com/assets/15305847/20810399/95743ac6-b7d7-11e6-9d68-3f820a584c46.png)

ng-views index.html code
![image](https://cloud.githubusercontent.com/assets/15305847/20810452/d0018f9a-b7d7-11e6-9d73-ad26b4630d96.png)

When I delete a bet, I go back to my index page but the thing I deleted until I reload the page.

**Comment by amaseda** [comment]
Can you show the related Angular controller code?

**Comment by marks828** [comment]
![image](https://cloud.githubusercontent.com/assets/15305847/20810556/27885a00-b7d8-11e6-9609-7c6726c11c69.png)
![image](https://cloud.githubusercontent.com/assets/15305847/20810565/3008bdf0-b7d8-11e6-9c7e-4b7c421911e8.png)

**Comment by amaseda** [comment]
Are you already in the state associated with `betIndex`?

What happens if you do `$state.go('betIndex', {}, { reload: true })`?

**Comment by marks828** [comment]
Didn't work

![image](https://cloud.githubusercontent.com/assets/15305847/20811145/86d13b10-b7da-11e6-8a8e-3f647e878bd8.png)

**Comment by amaseda** [comment]
Are you currently in the "betIndex" state? If so, try using `$state.reload()` instead of `$state.go()`. If that doesn't work try...

```js
$state.go("betIndex").then(function(){
    $state.reload();
});
```

**Comment by marks828** [comment]
Still not relaoding

**Comment by jshawl** [comment]
```js
$state.go("betIndex").then(function(){
    console.log("does this work")
});
```

**Comment by marks828** [comment]
it's now logging the new bet does not appear until I reload the page

**Comment by marks828** [comment]
```  
$state.go("betIndex").then(function(){
        console.log("does this work")
        $state.reload()
    })
```

works now

**Comment by amaseda** [comment]
Word!

And just to confirm, you tried `$state.reload()` by itself, completely in place of `$state.go()`?

**Comment by marks828** [comment]
I did. But doesn't this fix undermine the reason for angular?

**Comment by amaseda** [comment]
Tbh I'm not sure why this fix is necessary. I thought `$state.reload()` would have worked since you're already at the state you're trying to load.

But hey, it's working for now. Enough to move forward with!

**Comment by marks828** [comment]
https://github.com/marks828/project_4_ng

**Comment by marks828** [comment]
back end
https://github.com/marks828/project_4_rails

**Comment by marks828** [comment]
do you need the links to my repos again?

**Comment by amaseda** [comment]
Sorry for the delay here. At the moment getting a lot of errors when I try to `bundle` your Rails app. Troubleshooting. Did this happen for you at first?

**Comment by marks828** [comment]
No didn't get any errors from rails. I'm not getting any errors anywhere and the information is getting to my db, it's just not appearing when I create a new instance so I'm thinking it could be something with my how my forms and controllers are created.

**Comment by amaseda** [comment]
@marks828 Had to debug some major Rails issues last night. Anyways, the following solutions worked for me...

```js
this.bet.$save().then(() => {
  $state.go("betIndex", {}, {reload: true})
})
```

```js
this.bet.$save().then(() => {
  $state.reload()
})
```

Made sure to trigger the state change/refresh once it was done saving.

**Comment by amaseda** [comment]
@marks828 Were you able to get this code working? ☝️

**Comment by marks828** [comment]
Oh sorry, yea it works. Thanks for the help!
