### ISSUE TITLE
API call in controller losing focus

### ISSUE THREAD

**Issue by MichaelZLai** [ga-wdi-exercises/project4#383]
I'm hitting a roadblock with my main feature of calling the "markers" in my API and placing it on the map. I'm able to render the array of objects with `Marker.query()` in a callback in my `mapController` function and pass it to  `setMarkers` function.
```
function mapController($state, Marker){
  var vm = this;
  vm.markers = Marker.query({}, markerapi =>{
    setMarkers(map,markerapi)
    })
  }
```

I'm also able to call the array in the `setMarkers` function further down in the code and get it to render. Originally, it was saying `markerapi` is undefined so i set a global variable of `markerapi = []`
```
//function to find and set markers on map
function setMarkers(map,markerapi) {
  console.log(markerapi)
  let mexico = markerapi;
  for (var i = 0; i < mexico.length; i++) {
    //defines the image
    var image = {
      url: mexico[i].imageurl,
      scaledSize: new google.maps.Size(40, 40),
    };
    .......
```
![image](https://cloud.githubusercontent.com/assets/20713810/20810661/8a00f30e-b7d8-11e6-943d-93d92736200b.png)

However when calling `setMarkers` as a method inside `initMap`. That's where my scope is lost and Im hit with undefined
```
function initMap() {

  // Defines Map and sets it to Mexico City
  var map = new google.maps.Map(document.getElementById('map'), {
    center: {lat: 19.432608, lng: -99.133209},
    zoom: 4,
    mapTypeId: "roadmap"
  });

  //sets picture markers on the map
  setMarkers(map,markerapi);
```

**Comment by jshawl** [comment]
what is `markerapi` supposed to be?

**Comment by MichaelZLai** [comment]
The array of objects returned from my API

**Comment by jshawl** [comment]
oooo can you do this:

```js
function mapController($state, Marker){
  var vm = this;
  vm.markers = Marker.query({}, markerapi =>{
    initMap()
    setMarkers(map,markerapi)
    })
  }
```

**Comment by jshawl** [comment]
explicitly call init map only after the api data has loaded?

**Comment by MichaelZLai** [comment]
hmmm, now it seems like `markerapi` is called multiple times and the variable is being refreshed to []. I'm assuming it's doing this to place the markers on the map. If that's the case, I would expect one to show up but none is

```
//global variables
var markerapi = []
var map


//function to find and set markers on map
function setMarkers(map,markerapi) {
  console.log(markerapi)
  let mexico = markerapi;
  for (var i = 0; i < mexico.length; i++) {
 .........
}

function initMap() {

  // Defines Map and sets it to Mexico City
  var map = new google.maps.Map(document.getElementById('map'), {
    center: {lat: 19.432608, lng: -99.133209},
    zoom: 4,
    mapTypeId: "roadmap"
  });

  //sets picture markers on the map
  setMarkers(map,markerapi);
```
![image](https://cloud.githubusercontent.com/assets/20713810/20811011/0292ce90-b7da-11e6-9d86-09e2f7398bf9.png)

**Comment by jshawl** [comment]
remove `&callback=initMap` from the URL

**Comment by MichaelZLai** [comment]
I'm not sure where to remove it. I checked my `initMap` and `setMarkers` functions and they don't have anything with `&callback=initMap`. 

![image](https://cloud.githubusercontent.com/assets/20713810/20811109/6531f8d2-b7da-11e6-8eea-17ae92ca8d6c.png)

**Comment by jshawl** [comment]
try command-shift-f to look for `&callback=initMap`

**Comment by MichaelZLai** [comment]
ah, it was located in my googlemaps CDN. I removed it and the repeat log of markerapi is not showing the empty brackets! However the markers are still not rendering. I'm also logging the `markerapi` in `initMap()`, but its returning as a blank []. Is this due to `markerapi` being defined [] as a global variable
```
function initMap() {

  // Defines Map and sets it to Mexico City
  var map = new google.maps.Map(document.getElementById('map'), {
    center: {lat: 19.432608, lng: -99.133209},
    zoom: 4,
    mapTypeId: "roadmap"
  });
  console.log(markerapi)
  //sets picture markers on the map
  setMarkers(map,markerapi);
```
![image](https://cloud.githubusercontent.com/assets/20713810/20811813/19e33f32-b7dd-11e6-8de1-a89d2efc4e7d.png)

**Comment by jshawl** [comment]
ok this is progress where are you defining markerapi?

**Comment by MichaelZLai** [comment]
I have it defined as a global variable as `var markerapi = []` and I have it set to call the API in my `mapcontroller` function

```
//logic for rendering photos on map
function mapController($state, Marker){
  var vm = this;
  vm.markers = Marker.query({}, markerapi =>{
    initMap()
    setMarkers(map,markerapi)
    })
  }

//=========================
//           MAP
//=========================
//global variables
var markers = []
var contents = []
var infowindows = []
var markerapi = []
var map
```

**Comment by jshawl** [comment]
if you remove that global var definition - can you console.log(markerapi) inside your mapController?

**Comment by MichaelZLai** [comment]
hmm, no logs are coming back
```
function mapController($state, Marker){
  var vm = this;
  vm.markers = Marker.query({}, markerapi =>{
    initMap()
    console.log(markerapi)
    setMarkers(map,markerapi)
    })
  }

var markers = []
var contents = []
var infowindows = []
// var markerapi = []
var map
```

![image](https://cloud.githubusercontent.com/assets/20713810/20812160/905af0b4-b7de-11e6-8332-47b281ad1867.png)

**Comment by MichaelZLai** [comment]
however when the global `markerapi` is defined. The log for `markerapi` in `mapController` is there

![image](https://cloud.githubusercontent.com/assets/20713810/20812232/ce96d64a-b7de-11e6-9ab3-ebeaa3256e7e.png)

**Comment by jshawl** [comment]
ok Reference error is good. what if you use promise instead of callback `Marker.query().then()...`

**Comment by MichaelZLai** [comment]
Got the same result

```
function mapController($state, Marker){
  var vm = this;
  vm.markers = Marker.query({}).$promise.then( markerapi =>{
    initMap()
    console.log(markerapi)
    setMarkers(map,markerapi)
    })
  }
```

![image](https://cloud.githubusercontent.com/assets/20713810/20812406/7227a33e-b7df-11e6-9312-8f8bd1c1429e.png)

**Comment by MichaelZLai** [comment]
just had to pass a global function and nest the other two functions inside and it works! thanks
