### ISSUE TITLE
Still having deployment issues

### ISSUE THREAD

**Issue by khoitle** [ga-wdi-exercises/project4#384]
I'm now getting this error. The "nopes" i believe are my console.logs
<img width="1111" alt="screen shot 2016-12-01 at 3 08 58 pm" src="https://cloud.githubusercontent.com/assets/20734065/20810623/5e6860ba-b7d8-11e6-93a0-6468635d3990.png">

**Comment by jshawl** [comment]
anything else beside the nopes? try visiting the heroku website

**Comment by khoitle** [comment]
Nothing besides the nopes

<img width="1280" alt="screen shot 2016-12-01 at 3 17 34 pm" src="https://cloud.githubusercontent.com/assets/20734065/20810825/4ecf6030-b7d9-11e6-9c64-2738238aec30.png">

**Comment by khoitle** [comment]
<img width="1280" alt="screen shot 2016-12-01 at 3 18 31 pm" src="https://cloud.githubusercontent.com/assets/20734065/20810868/7272bcf8-b7d9-11e6-96fa-a43370f54f99.png">

**Comment by khoitle** [comment]
It hangs for quite some time and ultimately shows that Application Error page with no errors to work with in the console

**Comment by jshawl** [comment]
can you go to herokuapp.com and scroll through the logs

**Comment by khoitle** [comment]
-----> Node.js app detected
-----> Creating runtime environment
       
       NPM_CONFIG_LOGLEVEL=error
       NPM_CONFIG_PRODUCTION=true
       NODE_ENV=production
       NODE_MODULES_CACHE=true
-----> Installing binaries
       engines.node (package.json):  unspecified
       engines.npm (package.json):   unspecified (use default)
       
       Resolving node version (latest stable) via semver.io...
       Downloading and installing node 6.9.1...
       Using default npm version: 3.10.8
-----> Restoring cache
       Loading 2 from cacheDirectories (default):
       - node_modules
       - bower_components (not cached - skipping)
-----> Building dependencies
       Installing node modules (package.json)
-----> Caching build
       Clearing previous node cache
       Saving 2 cacheDirectories (default):
       - node_modules
       - bower_components (nothing to cache)
-----> Build succeeded!
       ├── express@4.14.0
       ├── express-handlebars@3.0.0
       ├── mongoose@4.7.1
       └── request@2.79.0
       
-----> Discovering process types
       Procfile declares types     -> (none)
       Default types for buildpack -> web
-----> Compressing...
       Done: 16.8M
-----> Launching...
       Released v7
       https://serene-dawn-74133.herokuapp.com/ deployed to Heroku

**Comment by khoitle** [comment]
The Build Log

**Comment by jshawl** [comment]
anything else? there should be some kind of error somewhere

**Comment by khoitle** [comment]
Thats everything in the latest build log

**Comment by jshawl** [comment]
is there a separate log? like an application log?

**Comment by jshawl** [comment]
those nopes should be showing up somewhere

**Comment by khoitle** [comment]
So far, after the initial error I've added, 
Hereis my workflow: 
 heroku addons:create mongolab
 heroku config | grep MONGODB_URI
mongoose.connect('mongodb://dbuser:dbpass@host:port/leagueskins')

**Comment by khoitle** [comment]
Where would those logs be? Let me remove the nopes from my console to see if its blocking out the errors

**Comment by khoitle** [comment]
here we go, I can now see the errors 
<img width="1280" alt="screen shot 2016-12-01 at 3 28 11 pm" src="https://cloud.githubusercontent.com/assets/20734065/20811200/cbbc606a-b7da-11e6-91bf-02c677fdba61.png">

**Comment by jshawl** [comment]
failed to connect to server

**Comment by khoitle** [comment]
I think this was actually my initial error, but then i followed the steps from mLab deployments. Perhaps i did them wrong?

**Comment by jshawl** [comment]
can i see your `mongoose.connect` statement?

**Comment by khoitle** [comment]
<img width="1280" alt="screen shot 2016-12-01 at 3 32 16 pm" src="https://cloud.githubusercontent.com/assets/20734065/20811357/598f22b0-b7db-11e6-8ec5-b6c56758c2cc.png">

**Comment by jshawl** [comment]
i don't think that's right. what is the output of 

```
$ heroku config:get MONGOLAB_URI
```

**Comment by khoitle** [comment]
There is no output

**Comment by khoitle** [comment]
<img width="1280" alt="screen shot 2016-12-01 at 3 34 09 pm" src="https://cloud.githubusercontent.com/assets/20734065/20811421/9de88d52-b7db-11e6-9cdb-b0d8d9fd690b.png">

**Comment by nolds9** [comment]
What is the output of `$ heroku config`

**Comment by khoitle** [comment]
<img width="1280" alt="screen shot 2016-12-01 at 3 35 09 pm" src="https://cloud.githubusercontent.com/assets/20734065/20811457/c0f67142-b7db-11e6-9d9e-f0735782526b.png">

**Comment by khoitle** [comment]
Do i Need this? 
if(process.env.NODE_ENV == "production"){
  mongoose.connect(process.env.MONGOLAB_URI);
}else{
  mongoose.connect("mongodb://localhost/whenpresident");
}

**Comment by jshawl** [comment]
you need MONGOLAB_URI

**Comment by nolds9** [comment]
Yes you are going to want some condition in your connection depending on the environment. In order for that to work though, you need to properly set your MONGOLAB_URI environment variable. Are you following this guide https://devcenter.heroku.com/articles/mongolab#connecting-to-existing-mlab-deployments-from-heroku

**Comment by khoitle** [comment]
Yes, I'm now looking at this part, and I'v efollowed it
<img width="1280" alt="screen shot 2016-12-01 at 3 38 13 pm" src="https://cloud.githubusercontent.com/assets/20734065/20811594/4d73d7a4-b7dc-11e6-9870-4ba6d6802117.png">

**Comment by jshawl** [comment]
`heroku config:get MONGODB_URI`

**Comment by khoitle** [comment]
<img width="1280" alt="screen shot 2016-12-01 at 3 40 30 pm" src="https://cloud.githubusercontent.com/assets/20734065/20811646/812a5442-b7dc-11e6-90e0-96a8c1229f4b.png">

**Comment by jshawl** [comment]
you need to set the mongodb_uri

**Comment by jshawl** [comment]
did you `heroku addons:create ...`

**Comment by khoitle** [comment]
Yah

**Comment by jshawl** [comment]
can you try it again and paste the output of your terminal

**Comment by khoitle** [comment]
Should i do something like this?
<img width="689" alt="screen shot 2016-12-01 at 3 42 41 pm" src="https://cloud.githubusercontent.com/assets/20734065/20811729/d226a468-b7dc-11e6-9ae3-834739388d5e.png">

**Comment by khoitle** [comment]
<img width="984" alt="screen shot 2016-12-01 at 3 43 35 pm" src="https://cloud.githubusercontent.com/assets/20734065/20811772/f221fee8-b7dc-11e6-88d3-40cc6c7bee0d.png">

**Comment by nolds9** [comment]
so it never was added to heroku because you do need to put down a credit card. 
At this scale, it should be free but `heroku` does need one on file

**Comment by khoitle** [comment]
Just to be clear, It won't charge me anything right?

**Comment by jshawl** [comment]
not yet!

**Comment by jshawl** [comment]
sorry i meant not unless you upgrade

**Comment by khoitle** [comment]
Heres the new set of errors haha
<img width="1280" alt="screen shot 2016-12-01 at 3 49 45 pm" src="https://cloud.githubusercontent.com/assets/20734065/20811981/d10f228e-b7dd-11e6-90e1-2200d8952c97.png">

**Comment by nolds9** [comment]
awesome! Now you can use that variable in your `mongoose.connect` call. You should have access to that value through: `process.env.MONGODB_URI`

**Comment by khoitle** [comment]
I'm not following the second portion. I would pass in mongodb://heroku_wcfgnhm2:497t721boiaangh3mnn2ih2hdb@ds119768.mlab.com:19768/heroku_wcfgnhm2 in my mongoose connect, and then what about the process.env?

**Comment by jshawl** [comment]
try

```js
mongoose.connect(process.env.MONGODB_URI)
```

**Comment by khoitle** [comment]
it worked! although i passed in mongodb://heroku_wcfgnhm2:497t721boiaangh3mnn2ih2hdb@ds119768.mlab.com:19768/heroku_wcfgnhm2

rather than process.env, is that ok?

**Comment by khoitle** [comment]
Also, It didnt initially have my seeds, so i went ahead and did node seed.js but didnt add/commit/push to heroku, and it was fully seeded

**Comment by khoitle** [comment]
AND! the app is called serene-dawn, if i change the app name via heroku, will the new URL be the new name+herokuapp?

**Comment by nolds9** [comment]
for security reasons, it is highly advisable to using environment variables ie. `process.env`

**Comment by jshawl** [comment]
yeah but remove that username and pass from your codebase so other's can't see that. it should be the process.env

**Comment by khoitle** [comment]
Remove that username and pass from my codebase? Where Would I have that? Also the app is called serene-dawn, if i change the app name via heroku, will the new URL be the new name+herokuapp?

**Comment by jshawl** [comment]
use `process.env.MONGODB_URI` instead of what you currently have in `mongoose.connect`

**Comment by khoitle** [comment]
Gotcha, Thanks for all the help!
