### ISSUE TITLE
Deliverables for Project 4

### ISSUE THREAD

**Issue by merubin** [ga-wdi-exercises/project4#385]
It is not clear in the instructions on what we actually need to turn in for Project 4.  I know it is stated that this project is not graded, but do we need to do a Pull Request?  I know you want it deployed, I I will put that address in my readme. but what about any other requirements.  I don't want to be doing things at the last minute.  Thank you for the clarification.

**Comment by jshawl** [comment]
""

**Comment by jshawl** [comment]
zero deliverable - this is _your_ project

**Comment by amaseda** [comment]
Closing this but let us know if you have any more questions.
