### ISSUE TITLE
Doing CSS to regain a modicum of control over my life

### ISSUE THREAD

**Issue by alman92** [ga-wdi-exercises/project4#386]
![image](https://cloud.githubusercontent.com/assets/19317100/20813026/07ec0340-b7e2-11e6-87b5-d665b7917856.png)
 
![image](https://cloud.githubusercontent.com/assets/19317100/20813034/103998c8-b7e2-11e6-8dd3-6545209d3ad3.png)

Found a cool button I want to use but it's not showing up at all

**Comment by jshawl** [comment]
md-button is an element 

.md-button is a class

**Comment by alman92** [comment]
This was the documentation angular.com said worked though..

**Comment by alman92** [comment]
![image](https://cloud.githubusercontent.com/assets/19317100/20813135/630e65ba-b7e2-11e6-8869-7a9616a94ff3.png)

How about in this situation?

**Comment by jshawl** [comment]
ok do you see the words show up?

**Comment by alman92** [comment]
The words do but none of the styling does

**Comment by jshawl** [comment]
ok does any of the css show?

```css
body{
  background: red;
}
```

**Comment by alman92** [comment]
![image](https://cloud.githubusercontent.com/assets/19317100/20813266/fc6df9c8-b7e2-11e6-9bf8-de4e45effe29.png)

**Comment by jshawl** [comment]
ok progress! it looks like the buttons are round on the left and orange - is that what you want?

**Comment by alman92** [comment]
No lol they were supposed to look very different, the colors are right though.  I'll tinker with it.

**Comment by jshawl** [comment]
👍 feel free to open a nother issue
