### ISSUE TITLE
Registering a keypress event to Window in React

### ISSUE THREAD

**Issue by timfoley** [ga-wdi-exercises/project4#387]
Hey team! 

Here's some pseudocode I'm trying to implement:
- when a user presses `space` anywhere on the page
- call `this.refreshMovies`

There's an `onKeyPress` handler in React, but I'm not sure how to register it. Thoughts? 

I've done some googling, but all the examples I have found show registering it on an input form, or using something like jQuery to call $(window).addEventListener.

**Comment by jshawl** [comment]
literally JUST had this problem

**Comment by jshawl** [comment]
I could never get `onKeyPress` to work correctly - so I did `window.addEventListener` and then in that callback just call wahtever compoentn method i wanted

**Comment by timfoley** [comment]
Coolio. I'll give that a shot. Thanks!

**Comment by timfoley** [comment]
Ooh. One more question. Would this belong in the `render` function of my component? Or would it make sense to check out the other lifecycle stages

**Comment by jshawl** [comment]
i think render is a fine place for this code!

**Comment by jshawl** [comment]
feel free to open another!
