### ISSUE TITLE
Angular templates not showing up

### ISSUE THREAD

**Issue by brown2206** [ga-wdi-exercises/project4#390]
Just as an example, when I go to http://localhost:3000/Payee, I expect to see my index template, but for some reason, the page keeps giving me back the JSON data.  Can you assist me with this?

![image](https://cloud.githubusercontent.com/assets/20567326/20816786/f85b68de-b7f1-11e6-8b54-a72fa9b0f633.png)

**Comment by amaseda** [comment]
I imagine `http://localhost:3000/Payee` is triggering a route you've defined on the back-end.

With the way your Angular app is set up, shouldn't you be visiting `http://localhost:3000/#/Payee`?
