### ISSUE TITLE
Show button

### ISSUE THREAD

**Issue by brophy2321** [ga-wdi-exercises/project4#391]
![image](https://cloud.githubusercontent.com/assets/21348450/20817533/527c07e8-b7f6-11e6-938f-ff1e00e98b1a.png)
![image](https://cloud.githubusercontent.com/assets/21348450/20817539/5a363620-b7f6-11e6-9592-0937e78f4f71.png)

**Comment by brophy2321** [comment]
kind of lost at the moment, no matter what muscle group im in when i hit show exercise, there is only one coming up which is the bench press

**Comment by amaseda** [comment]
What does the code for your show button/link look like?

**Comment by amaseda** [comment]
@brophy2321 Any word on this? :point_up:
