### ISSUE TITLE
Deployment question!

### ISSUE THREAD

**Issue by a-espinoza** [ga-wdi-exercises/project4#392]
Hey, good morning! 
Question, I can't figure out what "prefix" in this git command means: "git subtree push --prefix dist origin gh-pages"..

Im pretty sure it is a relative path, but I keep getting errors when trying to use the comand!

This is the source : http://yeoman.io/learning/deployment.html    under git subtree command!

the path is :  **src/index.html**
![image](https://cloud.githubusercontent.com/assets/19412086/20826125/c8448ed8-b836-11e6-909a-b23f3ae7df50.png)

Thankyouuuuuu!!!

**Comment by jshawl** [comment]
what problem are you trying to solve with git subtree?

**Comment by a-espinoza** [comment]
Deployment throught gh-pages! So the issue is that since im using Gulp && Yeoman, the file structure places the file "index.html" inside the drc folder! And from what I understand, gh-pages looks for the index file in the root directory! So if I'm not mistaken, you can assign this subtree as a root path to the specific gh-pages branch.
Am I on the right train of thought?

**Comment by jshawl** [comment]
can you change the output folder of the build files?

**Comment by a-espinoza** [comment]
That is what I am trying to avoid, I guess my question is, can you sort off give me a clue of what the "prefix means"?
https://github.com/git/git/blob/master/contrib/subtree/git-subtree.txt

Thx!

**Comment by jshawl** [comment]
prefix looks like the folder name you're pushing - https://github.com/git/git/blob/454cb6bd52a4de614a3633e4f547af03d5c3b640/contrib/subtree/git-subtree.txt#L134-L138

instead of

```
git subtree push --prefix dist origin gh-pages
```

do you need the equals sign?

```
git subtree push --prefix=dist origin gh-pages
```
