### ISSUE TITLE
issue with deployment

### ISSUE THREAD

**Issue by marlungu** [ga-wdi-exercises/project4#393]
i'm trying to deploy my react app to heroku , but i'm getting this eror. 
![image](https://cloud.githubusercontent.com/assets/18635698/20836629/41ecde34-b86e-11e6-9f7a-a9843469ed30.png)

**Comment by jshawl** [comment]
cannot find module `/app/index.js` <- do you have this anywhere in your code?

**Comment by marlungu** [comment]
no, i have src/ index.js

**Comment by jshawl** [comment]
maybe use the deployment guide for create-react-app? https://github.com/facebookincubator/create-react-app/blob/master/packages/react-scripts/template/README.md#deployment

I'm not sure why heroku is giving this error
