### ISSUE TITLE
Angular not defined.

### ISSUE THREAD

**Issue by brown2206** [ga-wdi-exercises/project4#394]
I need assistance with my app.js file.  I keep encountering the error, Angular not defined.

![image](https://cloud.githubusercontent.com/assets/20567326/20837766/848847ec-b873-11e6-842e-d8e748b34a61.png)

![image](https://cloud.githubusercontent.com/assets/20567326/20837755/770354ae-b873-11e6-9ba3-6699b59b4909.png)

**Comment by jshawl** [comment]
it looks like angular is not defined in your terminal - are you doing anything with node and angular? like executing an angular file with node?

**Comment by jshawl** [comment]
did opening html in the browser solve this?

**Comment by brown2206** [comment]
Jesse, this is my index.html that I opened in the browser.  I don't remember us doing it this way for Grumblr but it's been a while.

![image](https://cloud.githubusercontent.com/assets/20567326/20838290/eab8db06-b875-11e6-8251-b62f80af1f44.png)

**Comment by brown2206** [comment]
Can we do a short review?

**Comment by brown2206** [comment]
I think I'm on the right track, can we briefly talk about my PayeeFactoryControllerFunction

![image](https://cloud.githubusercontent.com/assets/20567326/20838557/1f998a18-b877-11e6-963c-cdab85667573.png)

**Comment by nolds9** [comment]
Are able to see the data that was returned? Did you inject your `PayeeFactory` into your `controller`

**Comment by brown2206** [comment]
hi Nick...can I come over?

**Comment by brown2206** [comment]
here's the snippet.

**Comment by brown2206** [comment]
![image](https://cloud.githubusercontent.com/assets/20567326/20838894/815a192e-b878-11e6-8dfc-9a665cdd02ed.png)

**Comment by nolds9** [comment]
you got this! Are you getting any errors?

**Comment by brown2206** [comment]
no errors...but I am getting this...

![image](https://cloud.githubusercontent.com/assets/20567326/20839083/2edf6f72-b879-11e6-9ce5-21c2b798492b.png)

**Comment by brown2206** [comment]
Then also, I don't remember going to the index.html to look at our pages.  Can you talk a little bit about this process again.

**Comment by nolds9** [comment]
we ran `hs` from the CLI, to start an http-server to serve our Angular apps in class. I think you need to do so here for your API requests to work

**Comment by nolds9** [comment]
By default this will serve your app on `localhost:8080`

**Comment by brown2206** [comment]
let me try that

**Comment by brown2206** [comment]
Nick, this doesn't look familiar.  But the local host 8080 does.  I do remember that.  The rest of this garbage doesn't look familiar.

![image](https://cloud.githubusercontent.com/assets/20567326/20839449/a4b1f14c-b87a-11e6-95c7-a41ce48e1e5d.png)

**Comment by brown2206** [comment]
Here's the error.

![image](https://cloud.githubusercontent.com/assets/20567326/20839502/e78f2c1e-b87a-11e6-8141-6b2ca7895f3f.png)

**Comment by amaseda** [comment]
You need to run `hs` from the app's root directory. Not `public`

**Comment by jshawl** [comment]
sometimes public is picked up automatically - try `hs .`

**Comment by brown2206** [comment]
I ran it from my meanpay directory.  Isn't this the way we did it for the Ngresources lesson a few weeks back?

**Comment by nolds9** [comment]
Yes, in class we had an API that we ran locally on some other port, and then used `hs` to serve our Angular app on a different port.

**Comment by brown2206** [comment]
I'm stuck gentleman.  What can I send you so we can walk through step by step.  I feel like I'm close but I'm missing a step or two.  When I ran hs, it seemed whacky.

**Comment by jshawl** [comment]
did you run `hs .`?

**Comment by jshawl** [comment]
what do you mean by whacky?

**Comment by brown2206** [comment]
by whacky, I mean that I shouldn't see this

![image](https://cloud.githubusercontent.com/assets/20567326/20840111/131ba7b6-b87d-11e6-9c16-323f0f4521f6.png)

**Comment by jshawl** [comment]
did you run `hs .`?

**Comment by brown2206** [comment]
![image](https://cloud.githubusercontent.com/assets/20567326/20840159/3a44b0bc-b87d-11e6-99e2-2b328019367a.png)

**Comment by jshawl** [comment]
ok great - stop the other server first

**Comment by brown2206** [comment]
Okay, I stop the other server first and still got the same issue.

**Comment by jshawl** [comment]
after stopping the server, did you run `hs .` and is there an index.html file in the current directory?

**Comment by brown2206** [comment]
yes

**Comment by brown2206** [comment]
I did as you've instructed.

**Comment by brown2206** [comment]
Can I sit with one of you guys for 5 minutes?

**Comment by jshawl** [comment]
@brown2206 you 100% got this - keep givin us info we can work with - share your repo?

**Comment by nolds9** [comment]
maybe try running `hs` on a different port:
```
$ hs . -p 8000
```

**Comment by jshawl** [comment]
I got it working by:

```
cd meanpay/client/app
hs .
```

**Comment by brown2206** [comment]
jsahwl, you used my old repo.  I've since deleted that client folder because I wanted to redo it with the way we learned it in class.

**Comment by brown2206** [comment]
let me add and push to my repo

**Comment by brown2206** [comment]
Running hs . from this path gives me this error.

![image](https://cloud.githubusercontent.com/assets/20567326/20841695/b9b95622-b882-11e6-8006-caf572acc699.png)

**Comment by amaseda** [comment]
Do you have a server already running in a separate tab?

**Comment by brown2206** [comment]
Yes, I have the server for the backend API running.

**Comment by jshawl** [comment]
can you psuh your code? ill clone down?

**Comment by brown2206** [comment]
I just did.

**Comment by jshawl** [comment]
do you need hs any more? this looks like an express app now - `nodemon`

**Comment by brown2206** [comment]
Jesse, I wanted the angular piece to work.  The goal was to make this into
a MEAN app.

**Comment by brown2206** [comment]
I have the angular model in app.js.

**Comment by jshawl** [comment]
things to fix:

```
1. app.use("/*")
2. app.use(express.static).... 
3. angular is missing from layout-main file
4. Router should be RouterFunction
```
