### ISSUE TITLE
User Auth

### ISSUE THREAD

**Issue by alman92** [ga-wdi-exercises/project4#395]
![image](https://cloud.githubusercontent.com/assets/19317100/20837808/b242b460-b873-11e6-8cc7-76109294f090.png)

getting this while running rails c

**Comment by alman92** [comment]
![image](https://cloud.githubusercontent.com/assets/19317100/20837857/f70fde7e-b873-11e6-9cf0-7f58544d554f.png)

NVM now this

**Comment by jshawl** [comment]
it looks like youre trying a terminal command in rails c - try exiting the rails console before curl

**Comment by alman92** [comment]
Nvm i skipped a step, i forgot to create a user

But now im getting this

![image](https://cloud.githubusercontent.com/assets/19317100/20837927/41714250-b874-11e6-9ef8-891fe6869749.png)

**Comment by jshawl** [comment]
you typed `rails>`

**Comment by alman92** [comment]
![image](https://cloud.githubusercontent.com/assets/19317100/20837969/6bd5c6ba-b874-11e6-9342-4c0723725bb9.png)

Ok now im getting this error

**Comment by jshawl** [comment]
You typed the word rails

**Comment by alman92** [comment]
is it supposed to be raise?

**Comment by nolds9** [comment]
no need for the word `rails` in your command?!

**Comment by jshawl** [comment]
It should just be User.create...

**Comment by alman92** [comment]
OH gotcha

**Comment by alman92** [comment]
curl http://localhost:3000/goals

after running this in the terminal i got the weirdest error ive ever seen

**Comment by alman92** [comment]
It reiterated my entire rails app in the terminal

**Comment by jshawl** [comment]
what is the error

**Comment by alman92** [comment]
![image](https://cloud.githubusercontent.com/assets/19317100/20838147/44e8d23a-b875-11e6-8fc5-b248d2de70b3.png)

its really long

**Comment by jshawl** [comment]
try visiting `http://localhost:3000/goals` in a browser so it will render the html

**Comment by alman92** [comment]
I'm supposed to be getting 
{"errors":["Not Authenticated"]}

**Comment by alman92** [comment]
Ah i had a syntax error, just fixed it

**Comment by jshawl** [comment]
try visiting `http://localhost:3000/goals` in a browser so it will render the html and you can read the error message

**Comment by jshawl** [comment]
👍

**Comment by alman92** [comment]
![image](https://cloud.githubusercontent.com/assets/19317100/20838241/ad1e53fc-b875-11e6-999c-a11e62be15ca.png)

ran this and got another long error
