### ISSUE TITLE
More Auth Errors

### ISSUE THREAD

**Issue by alman92** [ga-wdi-exercises/project4#396]
![image](https://cloud.githubusercontent.com/assets/19317100/20838252/bfdca0fc-b875-11e6-9abf-ee0b1ed3b9fb.png)

Ran this and got a new long error

**Comment by jshawl** [comment]
can you send this post request in postman so that you can view the rendered html?

**Comment by alman92** [comment]
Yea I can

**Comment by alman92** [comment]
![image](https://cloud.githubusercontent.com/assets/19317100/20838371/3ce52dbc-b876-11e6-99d7-849f9afd32d0.png)

**Comment by jshawl** [comment]
now click preview so you can see the rendered html

**Comment by alman92** [comment]
![image](https://cloud.githubusercontent.com/assets/19317100/20838384/55cfc828-b876-11e6-9017-72c8e93630fe.png)

**Comment by jshawl** [comment]
ok excellent! you can remove the verification in `ApplicationController` - the protect from forgery line

**Comment by alman92** [comment]
Ok new rails error!

![image](https://cloud.githubusercontent.com/assets/19317100/20838421/83a4309a-b876-11e6-88b5-d8143fe27b12.png)

**Comment by alman92** [comment]
I thought password was a method created by devise..?

**Comment by jshawl** [comment]
ok this is telling me `user` is nil

**Comment by alman92** [comment]
What does that mean in context of this process? Do i need to hardcode something into the User controller?

**Comment by jshawl** [comment]
it means that `User.find_for_database...` is returning nil

**Comment by alman92** [comment]
Does this mean I need to hardcode a user into my seeds?

**Comment by jshawl** [comment]
well it's looking for a user with `params[:email]` - what if you supply an email in params?

**Comment by alman92** [comment]
![image](https://cloud.githubusercontent.com/assets/19317100/20838727/ca94ea8e-b877-11e6-8612-2d03e81a3276.png)

I have this in an Authentication Controller, do I need to do a migration to add this model?

**Comment by jshawl** [comment]
i think you need to send an email in your post request

**Comment by alman92** [comment]
I'm blanking on how to do that..

**Comment by jshawl** [comment]
click on postman > click on the body tab

**Comment by alman92** [comment]
Ok thats where I'm getting the rails error

**Comment by jshawl** [comment]
yeah! but what do you have in body

**Comment by alman92** [comment]
4331 lines of HTML code haha

**Comment by jshawl** [comment]
![](https://dl.dropbox.com/s/aa71okhen5n495s/Screenshot%202016-12-02%2010.17.05.png?dl=0)

the thing underlined in orange

**Comment by alman92** [comment]
Yea thats where I am

**Comment by alman92** [comment]
![image](https://cloud.githubusercontent.com/assets/19317100/20838937/a93a1016-b878-11e6-86c4-0d386061dbfe.png)

These are the lines in it that pertain to email

**Comment by jshawl** [comment]
![](https://dl.dropbox.com/s/17cl46hvtwplb5e/Screenshot%202016-12-02%2010.18.51.png?dl=0)

click on form data

**Comment by alman92** [comment]
Ok theres a key/value form that's empty

**Comment by jshawl** [comment]
key should be email  - value should be a value in your db

**Comment by alman92** [comment]
I have some weird stuff in postman...Theres grumbles stuff still in here in my app and I have no idea where it came from

**Comment by alman92** [comment]
![image](https://cloud.githubusercontent.com/assets/19317100/20839100/4196f2c0-b879-11e6-9dde-a574eabdb87c.png)

**Comment by alman92** [comment]
![image](https://cloud.githubusercontent.com/assets/19317100/20839142/6e5a6922-b879-11e6-9f50-beba7a2f1128.png)
Also getting this

**Comment by alman92** [comment]
![image](https://cloud.githubusercontent.com/assets/19317100/20839527/fdfe06aa-b87a-11e6-90e6-98034d2d6c3a.png)

Got it, needed to reseed and I had something weird in my postman from grumbles

**Comment by jshawl** [comment]
excellent!
