### ISSUE TITLE
Angular User Auth

### ISSUE THREAD

**Issue by alman92** [ga-wdi-exercises/project4#399]
![image](https://cloud.githubusercontent.com/assets/19317100/20841565/3f5c7e4a-b882-11e6-95bc-15b4d626e254.png)

So far I have this set up to put in my front end, Just want to make sure I'm not missing anything

**Comment by jshawl** [comment]
looks good! any errors?

**Comment by alman92** [comment]
Not so far, just don't really know what to do next.

**Comment by alman92** [comment]
![image](https://cloud.githubusercontent.com/assets/19317100/20842407/7da115dc-b885-11e6-9e70-910f0a3de33a.png)
![image](https://cloud.githubusercontent.com/assets/19317100/20842416/83ef6786-b885-11e6-9a22-b7e71176358f.png)
![image](https://cloud.githubusercontent.com/assets/19317100/20842424/8b9a5e46-b885-11e6-8789-b3bdf1be4a44.png)
![image](https://cloud.githubusercontent.com/assets/19317100/20842434/9213f872-b885-11e6-9ff0-be5680ff0637.png)
![image](https://cloud.githubusercontent.com/assets/19317100/20842445/9a67904c-b885-11e6-9af7-4931069974a8.png)

Still getting errors here saying something isn't connected correctly

**Comment by alman92** [comment]
Any next steps?

**Comment by amaseda** [comment]
Yo! Talking a look now.

**Comment by alman92** [comment]
Ok lol thanks!

**Comment by amaseda** [comment]
Is that `auth_token` error the only one you're getting? If so, you need to define it. Then see if you can communicate with your API and can deal with any errors that result from that.

Otherwise, I don't see anything wrong with your Angular set up at the moment.

**Comment by alman92** [comment]
How and where do I define it?  That's the main part I am confused about haha

**Comment by amaseda** [comment]
tbh I don't know, I haven't implemented this before. But if you said that you were trying to do this with Devise then I imagine the token would be originally generated on the back-end after somebody logs in through a server-side log-in page.

Did you come up with this setup yourself or did that come from some other resource?

**Comment by alman92** [comment]
I did the backend through a tutorial but the front end myself.

**Comment by amaseda** [comment]
I would look for a similar resource for the front-end, or one that covers both front and back end.

If it helps, we have a branch of WDI Radio that implements auth in Angular. 
* Front-end: https://github.com/ga-wdi-exercises/wdi_radio_lab/tree/user-auth-solution
* Back-end: https://github.com/ga-wdi-exercises/wdi_radio_api/tree/devise_token_auth_gem

It makes use of the `devise_token_auth` gem: https://github.com/lynndylanhurley/devise_token_auth
