### ISSUE TITLE
working with API that enforces pagination

### ISSUE THREAD

**Issue by jkoul** [ga-wdi-exercises/project4#4]
I'm planning to build a database that draws directly from OpenLIMS (https://openlims.herokuapp.com/index.html), which is in turn built on an undocumented REST API that underlies the DC Council's legislative info management system (http://lims.dccouncil.us/).

Problem is, that API enforces pagination and the fellow who built OpenLIMS told me he couldn't find a simple way around that. I need to be able to grab everything from this Council session and have it update automatically in order to get to my MVP, which parses and queries legislation on a number of parameters (introducing councilmember, status, type of bill, assigned committee, etc). Any ideas? I could probably use brute force (hand-compiling my own database) as a last resort, but I'm pretty far from last resorts at the moment as the auto-updating component would probably involve a burdensome amount of API calls.

Thanks!

**Comment by RobertAKARobin** [comment]
The problem is OpenLIMS isn't getting all the data because the API developer didn't know how to paginate? Doesn't that mean you'd need to not use OpenLIMS but instead use the lims.dccouncil.us thing? If so, pagination isn't hard!

**Comment by jkoul** [comment]
Actually the problem is the other way around. I need to "de-paginate" the underlying API.

I have an offer to pair program from the OpenLIMS developer in order to update OpenLIMS directly, which might be ideal, but of course there are time limitations on this project so I don't know if that'd be feasible.

**Comment by RobertAKARobin** [comment]
Can you tell me how the API lets you access different pages? Does it just send back a response with `&page=2` at the end or something?

**Comment by jkoul** [comment]
I wish! Just tried digging under the hood.....looks like the pagination is happening on the back end.

By way of update, I downloaded an Excel file with full results, and can re-construct an API from that file. I'd say that's the brute force method.

**Comment by RobertAKARobin** [comment]
Yeah, that's pretty brutal. Weird. So how do the people who use this API on a regular basis get more than 1 page of data?

**Comment by jkoul** [comment]
They don't, from what I can tell. Anyone who needs legislative info has just used the Council's "official" front end interface. But that interface has its limitations vis-a-vis analytical capacity, hence my project.

**Comment by RobertAKARobin** [comment]
Wat.

Have you tried just adding `&page=2` or whatever onto the end of your request URLs?

Failing that, I'd say build your app with dummy data. Once you have a functioning front-end, the structure of your back-end, and the preliminary design decisions worked out, it'll be much simpler to change where you're getting your data from. A front-end without a back-end is still pretty good; a back-end without a front-end isn't much good at all.

**Comment by jkoul** [comment]
&page=2 didn't work and neither did pageIndex=2, so yep I'm leaning in that direction (dummy data, or to put it differently, static downloaded data). Thanks for the guidance. Closing this issue pending further developments.
