### ISSUE TITLE
Using ng-hide based on $state

### ISSUE THREAD

**Issue by ericacomfort** [ga-wdi-exercises/project4#40]
When a user creates an event and is on the event (url changes to something like `/events/55fabf8a5e73b5732deaa049`) I would like to hide other divs that aren't relevant.

To start I created a hide controller `HideCtrl` with the method `isStateHome` that checks the `$state`: https://github.com/andersenek/gracious.guest/blob/master/gracious_guest/public/javascripts/angularApp.js#L300-L310

That way I could use `ng-hide="isStateHome()"` on the `div` I wanted to hide: https://github.com/andersenek/gracious.guest/blob/master/gracious_guest/views/index.ejs#L182

This div should be hiding when the URL is `http://localhost:3000/#/home` but I'm not having any luck. When I console log `console.log($state.is('home'))` it's coming up false but I'm not understanding why.

To use my app you'll need to run:
`npm install` for dependencies
And run `mongod` and `npm start`

Any help would be greatly appreciated!

**Comment by RobertAKARobin** [comment]
Try this instead:

``` js
$scope.state = $state;
```

``` html
ng-hide="state.current.name == 'home'"
```

**Comment by ericacomfort** [comment]
That did the trick! Thank you :)
