### ISSUE TITLE
Combining API requests

### ISSUE THREAD

**Issue by ghost** [ga-wdi-exercises/project4#410]
For my project, I'm making 2x API requests. One for Uber fares. One for Lyft fares. When I originally set up my backend, I did api/uber/fares and api/lyft/fares. Rather than doing that, I'd like to combine both requests so that api/fares pulls both Uber & Lyft fares.

Here's an example of the controller making a request to the Uber API. The Lyft request is identical other than the actual url itself.

How can I combine the 2 requests? 

```
var scoopController = {

    get: (req, res) => {

        var request = require('request');

        var headers = {
            'Authorization': 'Token 3MZVsEWHLGKQIUzk_H7gGI4mMrBWeU23wxb9yUry'
        };

        var options = {
            url: 'https://api.uber.com/v1/estimates/price?start_latitude=38.905015&start_longitude=-77.034050&end_latitude=38.918380&end_longitude=-77.023223',
            headers: headers,
            json: true
        };

        function callback(error, response, body) {
            if (!error && response.statusCode == 200) {
                res.json(body)
            }
        }

        request(options, callback);
    }
}
module.exports = scoopController;
```

**Comment by nayana487** [comment]
Try using the concat method to get the data returned in one array. here's an example: http://stackoverflow.com/questions/38924055/how-to-combine-json-data-from-multiple-apis-using-nodejs-server
