### ISSUE TITLE
Issue with Sum Calculation

### ISSUE THREAD

**Issue by avalant** [ga-wdi-exercises/project4#411]
I am trying to get a sum total of debt. I wrote the code under the ng-repeat and it works (see below) but, wanted to move the logic it to the index controller of my application. I am writing the application in AngularJS and the backend is in ruby/rails. The key of the object I'm writing about is under lunchdebt.

```
<div ng-init="schools.total = {}">
  <div data-ng-repeat="school in vm.schools">
    <div ng-init="schools.total.lunchdebt = schools.total.lunchdebt + school.lunchdebt"></div>
  </div>
  <div>Total: {{schools.total.lunchdebt}}</div>
</div>
```

I tried the following within my index controller. I've placed my schools into a variable schools to make it easier to iterate through the objects. Schools is returned as null. I then added $scope per a stackoverflow suggestion but, the sum doesn't display. The function is being called within the HTML as {{Sum Total()}}
```
function SchoolIndexControllerFunction(SchoolFactory, $scope){
  this.schools = SchoolFactory.query();

  var schools = this.schools;
  // console.log("these are schools: ", schools);
  console.log("this is scope: ", $scope)

  $scope.SumTotal = function(schools){
    console.log("this worked");
    // var total = 0;
    // for(var i = 0; i < schools.length; i++){
    //   console.log(schools.lunchdebt[i]);
    //   total = total + schools.lunchdebt;
    // }
    // return total;
  }
}
```

Repo (HTML): https://github.com/avalant/project4/blob/master/SumZero/js/ng-views/schools/index.html 

Repo (App.js): https://github.com/avalant/project4/blob/master/SumZero/js/app.js

**Comment by andrewsunglaekim** [comment]
can you try this in your controller:

```js
this.sumTotal = function() {
  let total = 0;
  // logic  to total schools
  for (let i = 0; i < this.schools.length; i++){
    total = total + this.schools[i].lunchdebt;
  }
  return total
}
```

Then in your view:

```html
 <div>Total: {{vm.sumTotal()}}</div>
```
