### ISSUE TITLE
Server-side user authentication w/ third-party API

### ISSUE THREAD

**Issue by donovanallen** [ga-wdi-exercises/project4#412]
I am attempting to use Spotify's API for a significant part of my project that requires a spotify user authentication in order to complete other actions in my application (creating a playlist). Spotify's dev documentation is useful and has a lot of information on how to implement this, but I have a question about a more specific issue. The user authorization process seems to be broken down into three main steps: authenticating a user, getting an authorization token, and retrieving user data from an API endpoint. 

In the steps outlined in their reference docs specific to this issue (https://developer.spotify.com/web-api/tutorial/), they mention creating an index.html file which essentially acts as the login form for the user and collects their credentials. 

My problem is that I want all of this to happen in my backend Express side, so how can I implement these steps in my MEAN stack application? Clearly my Angular front end will have to render the actual login form at some point, but what is the most efficient way to complete this process between Angular and Express separately?

**Comment by nayana487** [comment]
gonna close for now...feel free to reopen with more specific questions other than what we talked about
