### ISSUE TITLE
Child component can't call prop function from parent component

### ISSUE THREAD

**Issue by nguyendthinh** [ga-wdi-exercises/project4#414]
In the parent component, as I am passing the function as a prop to the child:

```
<Cell returnValues={this.returnValues.bind(this)} />
```

In the child component, when I call for that prop function within another function:

```
userClick(e) {
.............
this.props.returnValues(currentColor, blocks) *the function takes two parameters*
}
```
React saids that it cannot read the property of bind (undefined) within the parents.

I have also tried this variation in the parent and child

```
<Cell returnValues={(value1, value2) => this.returnValues(value1, value2)}
```

```
userClick(e) {
...........
      this.props.returnValues.bind(currentColor, blocks)
}
```

this variation does not give any error but it does not run the function either. Not sure of what to try?

**Comment by superbuggy** [comment]
do you have a function `returnValues(){` defined in the parent component (`GameBoard`, right?)?

**Comment by nguyendthinh** [comment]
Yes I do and I just solved the issue LOL thanks!

**Comment by superbuggy** [comment]
Nice
