### ISSUE TITLE
updating dom with conditionals

### ISSUE THREAD

**Issue by drewswinburne** [ga-wdi-exercises/project4#423]
I am able to update the dom with user input - adding class "red" with a checkbox here:

```js
 <div class="cell" ng-class="{red: sell}">
     Ask : {{alert.Ask}}
   </div>
   <input type="checkbox" ng-model="sell">
```

but I'm unsure of how to update this model using conditionals on the js side. Where would I connect this sort of logic to the ng-model?

```js
if (alert.Ask > 50){
        alert.status = "sell"
      }
```

**Comment by andrewsunglaekim** [comment]
reopen if you're having issues.
