### ISSUE TITLE
React/Redux: How to have data on first render?

### ISSUE THREAD

**Issue by bradleycravens** [ga-wdi-exercises/project4#425]
In a file a have a WorkoutPage component. In it I have:

```javascript
componentDidMount() {
    this.props.getWorkout(this.props.user.id, this.props.params.workout)
  }
```

I'm getting props from a mapStateToProps function
```javascript

function mapStateToProps(state) {
  return {
    workout: state.workout,
    user: state.auth.user
  }
}
```
In my store, workout's initial state is an empty array. The `getWorkout` function in my componentDidMount sets a new state to workout.

If I console.log (this.props.workout)  it returns:
```
[]
[Object]
```
In the lesson plan you say `That's because a re-render will always happen because fetching data happens asynchronously`

Is there a way to avoid this and have it return just `[Object]` because In the component I'd like to render `{ this.props.workout[0].name }` and .name returns undefined because of the first rendering and errors out the entire component.

I would also like to use { this.props.workout[0].id } for a `getExercises` function where I pass the id as an argument and it is currently passing in undefined from the first render which errors it out. 

I feel like the answer is somewhere in a  `componentWillMount` or something but it doesn't seem to be working. 

File in question: https://github.com/bcravens/WorkoutsClient/blob/master/src/components/workouts/WorkoutPage.js

**Comment by andrewsunglaekim** [comment]
map your props to state in the components constructor. Then have it conditionally populate if the props exist or not. Something like this:

```js
constructor(props){
  super(props)
  emptyWorkouts= [{name: ""}]
  this.state = {
    workouts: props.workouts ? props.workouts : emptyWorkouts
  }
}
```

It's a bit hacky, but should do the trick potentially, if i'm understanding your issue correctly.

**Comment by andrewsunglaekim** [comment]
and use state instead of props

**Comment by bradleycravens** [comment]
Thanks I'll try this out!
