### ISSUE TITLE
500 (Internal service error)

### ISSUE THREAD

**Issue by bradleycravens** [ga-wdi-exercises/project4#429]
Shot in the dark here but I have this error when i try a post request to my back end and I don't know know what it's trying to tell me. was wondering if you could point me in the right direction if not thats fine.

In console:
`xhr.js:175 POST http://localhost:3000/api/exercises 500 (Internal Server Error)`

Response I get:

```
{"error "{"name":"error","length":121,"severity":"ERROR","code":"42703","position":"78","file":"parse_target.c","line":"943","routine":"checkInsertTargets"}}
```

**Comment by superbuggy** [comment]
is there an error in the console? you want to head over to the work area?

**Comment by bradleycravens** [comment]
I actually just figured it out, spent like 2 hours on it. i was passing user_id into exercises when i didnt have it defined on its schema...i hate my life.

**Comment by superbuggy** [comment]
arghhhh, congrats on nailing the bug tho
