### ISSUE TITLE
error seeding db with user_id

### ISSUE THREAD

**Issue by chrislovett03** [ga-wdi-exercises/project4#43]
I'm trying to get my seed data functional but am having issues connecting a user_id to a separate model, 'ride'. 

I've run a separate migration adding Ride to User and am able to successfully seed the user info. When I try to seed the 'ride' info with manual user_id added to the objects, I get the following error:
PG::ForeignKeyViolation: ERROR:  insert or update on table "rides" violates foreign key constraint "fk_rails_922df144cd"
DETAIL:  Key (user_id)=(1) is not present in table "users".

this is an example of what I'm trying to seed:
rides = Ride.create([{user_id: 1, title: 'Rock creek ride'}

This is a screenshot of what my schema looks like. I've also tried to check out my DB on psql and the only table I see is current user, with no other info. Not sure what that's about. 

![screen shot 2015-09-17 at 12 30 47 pm](https://cloud.githubusercontent.com/assets/12041606/9939382/f3168d24-5d37-11e5-9fd9-2f780ea37f10.png)

**Comment by alexbannon** [comment]
I can't speak to why psql doesn't reflect your schema - that's definitely a problem - but the error sounds like it's trying to create a Ride, but you're feeding it a user_id that doesn't exist. Can you show your seed file? My guess is while it's creating the user, it moves onto creating the ride, and because the user isn't in there yet it throws an error.

I fixed that with a .done(function() after creating the parent seed. It can also be done by adding variables to your users and then doing something like...

variable = User.create({blah})
variable.rides.create({})

But I'm not positive on the syntax.

Edit:

Here's what I did last time:

DB.models.User.create({twitter_id: 0})
.done(function(){DB.models.Pin.create({title: "London, UK", latitude: 51.5072, longitude: -0.1275, userId: 1, isRed: "t", description: "This was my wondeful trip to the UK. It was amazing in every way. The end."})
})

**Comment by chrislovett03** [comment]
I had the same thought, I went ahead and seeded the user data independently (successful) and then tried to do it again with the rides but it hit the same errors. That's a good thought to add .done, I'll try that now. Here's my seed data:

And thank you :-) 

![screen shot 2015-09-17 at 12 52 07 pm](https://cloud.githubusercontent.com/assets/12041606/9939988/0aa73b34-5d3b-11e5-9fc5-1e346a40f9d4.png)

**Comment by alexbannon** [comment]
After you create users it shows up in psql? In the terminal you can view the user? If so, then the issue is either the model Ride or psql really doesn't like you hardcoding a foreign key - in which case I would try var user = User.create(one instance)
Ride.create(user_id: user.id)

**Comment by alexbannon** [comment]
Actually you might be able to just change all the user_id spots with just users[0].id users[1].id and so on?

**Comment by RobertAKARobin** [comment]
Hey, @christinelovett , any success?

**Comment by chrislovett03** [comment]
@alexbannon I still only just current_user in the user table when seeding it alone. Good idea with the using the index spot but still doesn't work. 

.done + function does not work either. 

@RobertAKARobin No success - any ideas?

**Comment by RobertAKARobin** [comment]
Ah, got it. It's because Rails doesn't let you tell it what a row's ID should be.

Instead, do something like `User.where(email: "rocksolid@gmail.com").rides.create({ data goes here })`

**Comment by chrislovett03** [comment]
@RobertAKARobin thanks Robin, that should work. Now I'm hitting this in the terminal: 

```
NoMethodError: undefined method `ride' for #<ActiveRecord::Relation []>
```

but I see it in my migration:

``` rb
class AddUserToRides < ActiveRecord::Migration
  def change
    add_reference :rides, :user, index: true, foreign_key: true
  end
end
```

**Comment by chrislovett03** [comment]
NoMethodError: undefined method `ride' for #<ActiveRecord::Relation []>
 is the full error

**Comment by chrislovett03** [comment]
I feel like a "parents who text" example right now. It's not showing up when I send the comment, but heres the screen shot:
![screen shot 2015-09-17 at 1 58 24 pm](https://cloud.githubusercontent.com/assets/12041606/9941570/2f2c7c36-5d44-11e5-9f88-bca93362f475.png)

**Comment by RobertAKARobin** [comment]
Did you do:

```
User.where(email: "rocksolid@gmail.com").rides.create({ data goes here })
```

or:

```
User.where(email: "rocksolid@gmail.com").ride.create({ data goes here })
```

Note the `s`!

**Comment by chrislovett03** [comment]
@RobertAKARobin I had tried both with no success

**Comment by RobertAKARobin** [comment]
Can you paste your whole seed file, or provide a link to it on Github? Note that it says the error is on line 12 of your seed file.

**Comment by chrislovett03** [comment]
![screen shot 2015-09-17 at 2 16 15 pm](https://cloud.githubusercontent.com/assets/12041606/9941992/b4cb593c-5d46-11e5-92bb-8c5c2840e506.png)
![screen shot 2015-09-17 at 2 16 19 pm](https://cloud.githubusercontent.com/assets/12041606/9941993/b4cb7066-5d46-11e5-92a4-6798f41bfe05.png)

**Comment by alexbannon** [comment]
and class Ride belongs_to :user, right?
