### ISSUE TITLE
View Issue?

### ISSUE THREAD

**Issue by avalant** [ga-wdi-exercises/project4#431]
Front: AngularJS, Back: Rails

I want to display the name of the school that received the donation on my donor page but, I'm unsure of how to covert that from the school ID that is currently being displayed. I've done this before but, can't recall at the moment.

This is my donations received table:
```
<div class="row">
  <div class="col s12">
    <table class="table3 bordered responsive-table">
      <thead>
        <tr>
          <th>ID</th>
          <th>Donor</th>
          <th>Donation</th>
          <th>Recipient</th>
        </tr>
      </thead>
      <tbody>
        <tr ng-repeat="donation in vm.donations">
          <td>{{donation.id}}</td>
          <td>{{donation.donor}}</td>
          <td>{{donation.money | currency}}</td>
          <td>{{donation.school_id}}</td>
        </tr>
      </tbody>
    </table>
  </div>
</div>
```

My API is structured so that the school_id is captured under the donations schema.

REPO: https://github.com/avalant/project4

**Comment by superbuggy** [comment]
Your backend should also include in its response the school that the donation is attached to. It looks like this would be `index` in your `DonationsController`. Try leveraging (includes)[http://apidock.com/rails/ActiveRecord/QueryMethods/includes]

This may not work but try:

```rb
@donations = Donation.includes(:school).all
```

**Comment by avalant** [comment]
I've put the following in my donations controller:
`@donations = Donation.includes(:school).all`

This still allowed me to render a view on my front end.

My understanding of includes is that it brings everything but, I want to limit it so I tried:
`@donations = Donation.includes(school: [:name]).all`

This did not allow me to render a view on my front end.

Also, I'm unclear on how to get the school name to show using .includes

**Comment by superbuggy** [comment]
ah okay. did that last expression cause an error? With the first code snippet, you'd be able to access the school name via `{{donation.school.name}}` on the angular side, in that ng-repeat in your first post in this thread.

**Comment by avalant** [comment]
With `@donations = Donation.includes(:school).all`
I wasn't able to display the school name using `{{donation.school.name}}`  but, no error is displayed. It does render the other fields.

With `@donations = Donation.includes(school: [:name]).all`
I'm unable to display anything and an error is thrown. The error isn't decipherable and very long:

`Possibly unhandled rejection: {"data":"<!DOCTYPE html>\n<html lang=\"en\">\n<head>\n  <meta charset=\"utf-8\" />\n  <title>Action Controller: Exception caught</title>\n  <style>\n    body {\n      background-color: #FAFAFA;\n      color: #333;\n      margin: 0px;\n    }\n\n    body, p, ol, ul, td {\n      font-family: helvetica, verdana, arial, sans-serif;\n      font-size:   13px;\n      line-height: 18px;\n    }\n\n    pre {\n      font-size: 11px;\n      white-`

**Comment by superbuggy** [comment]
be sure to specify `.json` when you are requesting a json resource. you got back an HTML page instead of JSON object.

i.e. `/schools/82/donations.json`

**Comment by avalant** [comment]
The solution was to include the school into the render:
   ` render json: @donations, include: :school`
