### ISSUE TITLE
Displaying returned json object with jquery

### ISSUE THREAD

**Issue by justwes2** [ga-wdi-exercises/project4#438]
I'm working on an angular app, but I have a function manipulating the DOM with jquery, which I was able to get to work in the movie-browser homework, but now the server log is throwing an error that is doesn't like the `$`. I checked the factory solution on the movie browser homework, and am not getting a sense of how to build the table I want with angular. Can I force jquery and angular to hold hands or are there additional resources for adding dom manipulation callbacks to an ajax request?

**Comment by phantomhaircuts** [comment]
http://stackoverflow.com/questions/12496834/jquery-and-angularjs-not-working-together

**Comment by justwes2** [comment]
The error that I am getting is that the `$` is not defined. I don't think that there is conflict. All of the $states and $resources are defined in app.js, and the jquery is used in index.js. I brought jquery in as a dependency and have the cdn in the index.html, so I'm not sure how else to bring that library into the app. When I wrap the functionality in the $.noConflict(), like the SO suggests, the app crashes because $ is not defined...

**Comment by superbuggy** [comment]
if `$` defined it usually means jQuery isn't accessible where you are using `$`

**Comment by superbuggy** [comment]
Do you have your dependencies in the right order?

**Comment by justwes2** [comment]
Here is my `package.json`:
```
{
  "name": "watson_node2",
  "version": "1.0.0",
  "description": "",
  "main": "index.js",
  "scripts": {
    "test": "echo \"Error: no test specified\" && exit 1"
  },
  "keywords": [],
  "author": "",
  "license": "ISC",
  "dependencies": {
    "body-parser": "^1.17.1",
    "express": "^4.15.2",
    "express-handlebars": "^3.0.0",
    "jquery": "^3.1.0"
  }
}
```
Here are my script tags:
```
<script src="https://ajax.googleapis.com/ajax/libs/jquery/2.2.4/jquery.min.js"></script>//this is the jquery cdn
  <script type="text/javascript" src="https://ajax.googleapis.com/ajax/libs/angularjs/1.5.6/angular.min.js"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/angular.js/1.5.0-beta.2/angular-resource.min.js"></script>
  <script src="assets/js/app.js"></script>
```

**Comment by justwes2** [comment]
Since this is in index.js, I feel like it hits the dependencies up, and jquery is that last one listed, so that should make it the most recently parsed one, right?

**Comment by justwes2** [comment]
Moved onto a different error, opening new issue
