### ISSUE TITLE
React router state not changing

### ISSUE THREAD

**Issue by justwes2** [ga-wdi-exercises/project4#439]
I'm building a portfolio in react, and I want the projects to list like the stocks lab we did. I've used that as a template but when I click on a project, the state isn't changed. I console log state and props in the project/:key page, and both return undefined.  
This is the map function for that defines the links: 
```
let tiles = data.map(function(a) {
      let url = '/projects/'+a.key
      let alias ='project_'+a.key
      return (
        <Link
          to={{
            pathname: url,
            state: {selectedProject: a}
          }}
          key={a.key}>
          <div className='project' id={alias}>
            {a.name}
          </div>
        </Link>
      )
```
this is the render statement
```
render(){
    console.log(this.props);
    console.log(this.state);
    return(
      <div className="portfolio">
        {this.props.project}

      </div>
    )
  }
``` 
here is the repo: https://github.com/justwes2/portfolio_page

Any idea what I'm missing? It has the same structure as the lab...

**Comment by amaseda** [comment]
What does the `<Route>` for an individual project page look like?

**Comment by justwes2** [comment]
```
<Route
              path='/projects/:key'
              render={() => {
                return(
                  <Project
                    project= {this.state.project}
                  />
                )
              }}
            />
```

**Comment by amaseda** [comment]
Instead of using `render=` can you see if this works when you use `component={Project}`?

Reference: https://reacttraining.com/react-router/web/api/Route/component

**Comment by justwes2** [comment]
When I make that switch, and alter the render to a return, the route looks like
```
            <Route
              path='/projects/:key'
              component = {Project}
            />
```
and the component return looks like this: 
```
const Project = ({ match }) => {
    return <p>{match.params.name}</p>
  }
```
if I'm understanding the documentation correctly. However, the const Project is flagged as an unexpected token. Did I misunderstand the documentation?

**Comment by amaseda** [comment]
Just try the first part (i.e., replacing `render=` with `component=`). No need to change what your actual component looks like.

**Comment by justwes2** [comment]
I just ran that. The render is still empty. The log of state has the data, but its buried and I can't access it in the console.

**Comment by amaseda** [comment]
Can you add a constructor to your Project component and log `props` in there? So something like...

```js
constructor(props){
  super(props)
  console.log(props)
}
```

Is it still undefined?

**Comment by justwes2** [comment]
Here is the full constructor as I have it:
```
import React, { Component } from 'react'

class Project extends Component {
  constructor(props){
    super(props)
    this.state={
      project: this.props.location
    }
  }
  render(){
    console.log(this.props);
    console.log(this.state);
    return(
      <div className="portfolio">
        {this.props.project}

      </div>
    )
  }
}

export default Project
```

The object from the log looks like this:
<img width="328" alt="screen shot 2017-03-31 at 3 55 25 pm" src="https://cloud.githubusercontent.com/assets/24883096/24567163/81682842-162a-11e7-9437-04977dcf4f1f.png">

**Comment by amaseda** [comment]
Is the `selectProject` what you're trying to access? If so, you can see that it's not located at the root level of `props`. It's a bit deeper -- try digging into that `location` object.

**Comment by justwes2** [comment]
Sweet that got it working. Thanks. 
Any idea why the object configuration was different than the object in the lab? The json files were the same...

**Comment by amaseda** [comment]
When you're passing information through a `<Link>` the data's location inside of `props` changes. But that's good for you to know moving forward!
