### ISSUE TITLE
New Controller, Service, and routes.js in Angular causing injector error

### ISSUE THREAD

**Issue by alexbannon** [ga-wdi-exercises/project4#44]
I have users and desks as models. Desks works fine. Adding users not so much.

Things I checked: scripts listed on index.html, app injecting dependencies, everything is spelled right.

here's the actual error: I go to a route localhost:8080/#/profile, and the angular routes knows it's a route and renders the template profile.html, which at this moment only has helloworld. Step two of the route, 

controller: 'userController'

is producing an error. Error: $injector:unpr
Unknown Provider. Which basically just means it can't find it. But I've legit checked it all 10 times. I'm tempted to just incorporate it into the desk controller instead and just misname it. I'll just give all the relevant code here:

userroutes.js:

``` js
(function(){
  var router = angular.module('userRouter', []);
  router.config([
    '$routeProvider',
    function($routeProvider){
      $routeProvider.
      when("/profile", {
        templateUrl: "views/users/profile.html",
        controller: 'userController',
        controllerAs: 'editUserCtrl'
      })
    }
  ])
})();
```

app.js:

```
'use strict';

(function() {
  var app = angular.module('empty_desks', [
    'ngRoute',
    'ngResource',
    'deskControllers',
    'userControllers',
    'deskRouter',
    'userRouter',
    'deskServices',
    'userServices',
    'ngCookies'
  ]);
})()
```

services/user.js:

```
(function() {
  var userServices = angular.module('userServices', ['ngResource']);

  userServices.factory('User', ['$resource', function($resource) {
    return $resource('/api/users/:id', {}, {
      update: {method:'PUT'}
    });
  }]);
})();
```

controllers/users.js:

```
(function() {
  var userControllers = angular.module('userControllers', ['ngRoute'])

  userControllers.controller('userController', ['User', function(User) {
    var self = this;
    AuthService.current_user().then(function(response){
      self.user = [response.data]
    });

  }]);

})();
```

**Comment by RobertAKARobin** [comment]
Did you link to it in your `index.html` with `<script>`? If so, are you sure it's loading?

**Comment by alexbannon** [comment]
Yeah I was. I put console.logs everywhere.

The good news is I found out the issue. I duplicated a service by accident and it only loaded one and the error it was giving in response was the very definition of unhelpful. But hopefully solved. Closing now.
