### ISSUE TITLE
throw new error(msg);

### ISSUE THREAD

**Issue by mitchellcarroll** [ga-wdi-exercises/project4#441]
This is the error I am getting in git: 
```
throw new Error(msg);
        ^

Error: Route.get() requires callback functions but got a [object Undefined]
    at Route.(anonymous function) [as get] (/Users/mitchell/wdi/projects/project-4-backend/node-express-app/node_modules/express/lib/router/route.js:196:15)
```

I have a route.js file but I don't have 196 lines of code in it.. This is my route.get() is below. 

```
router.get('/user', auth.required, function(req, res, next){
  User.findById(req.payload.id).then(function(user){
    if(!user){ return res.sendStatus(401); }

    return res.json({user: user.toAuthJSON()});
  }).catch(next);
});
```

Thanks for your help!

**Comment by amaseda** [comment]
What exactly are you trying to do? What is `Route.get( )`?

**Comment by mitchellcarroll** [comment]
I am essentially trying to set up user authentication for users. I have a router.get which I included about but the route.get error that I am getting in the terminal is tripping me up because I don't have route.get() anywhere in my code.

**Comment by amaseda** [comment]
What documentation are you referencing for `router.get`? Sounds like it's expecting a function but reading an object instead. Wondering if you need to rearrange your arguments for `router.get`

**Comment by mitchellcarroll** [comment]
I have been following along a tutorial in setting up JSON web token authentication. I'm going to spend a little more time trying to figure it out, but if I can't find the solution I may scratch authentication all together. Thanks for your help.

**Comment by amaseda** [comment]
Gotcha, no problem.

And yeah, I would focus on other aspects of your app instead of diving into auth so soon.

**Comment by amaseda** [comment]
Going to close this for now but feel free to re-open if you have more questions/comments.
