### ISSUE TITLE
[nodemon] app crashed - waiting for file changes before starting . . .

### ISSUE THREAD

**Issue by rodneycurl** [ga-wdi-exercises/project4#443]
How can I get this to fix? I tried doing 

$ npm install 

and still had no luck any advice/direction is greatly appreciated.

[nodemon] app crashed - waiting for file changes before starting . . .

<img width="948" alt="screen shot 2017-03-31 at 2 23 56 pm" src="https://cloud.githubusercontent.com/assets/23087353/24564031/8a028a30-161e-11e7-8b12-61618a2a7f82.png">
<img width="830" alt="screen shot 2017-03-31 at 2 22 40 pm" src="https://cloud.githubusercontent.com/assets/23087353/24564032/8a049eb0-161e-11e7-84c4-29d06cd21ccc.png">

**Comment by amaseda** [comment]
Do you have `mongod` running?

**Comment by amaseda** [comment]
@rodneycurl Any luck with this?

**Comment by rodneycurl** [comment]
Thanks Adrian that worked! Totally forgot to use mongod.
