### ISSUE TITLE
Pushing to heroku

### ISSUE THREAD

**Issue by rodneycurl** [ga-wdi-exercises/project4#444]
Hey do you guys have any idea how to get past this blank screen and have it reveal my project?

![screen shot 2017-03-31 at 10 43 26 pm](https://cloud.githubusercontent.com/assets/23087353/24574657/2dc3498a-1664-11e7-9887-b8bb8883dde1.png)
![screen shot 2017-03-31 at 10 45 07 pm](https://cloud.githubusercontent.com/assets/23087353/24574656/2dc2af2a-1664-11e7-9f45-af1f68fd1840.png)
![screen shot 2017-03-31 at 10 45 23 pm](https://cloud.githubusercontent.com/assets/23087353/24574655/2dc28cf2-1664-11e7-83d3-253cd97fb43d.png)

**Comment by amaseda** [comment]
#### 1

Is your app working locally? If not, need to address that first.

#### 2

Do you get an error when you try visiting your Heroku app (not the dashboard - the actual app) in the browser? Try running `heroku open` from your app directory in the terminal.

#### 3 (if Rails)

Is this a Rails app? If so, do you have the 12factor gem installed?

If not, follow the instructions [here](https://github.com/heroku/rails_12factor#install).

When it's installed, run `heroku logs` and see if there any errors that appear in there. Should be helpful in addressing the problem.

#### 3 (if MEAN)

Deploying a MEAN app to Heroku is a bit more complex. Here are some resources...

- [Deploying Node apps to Heroku](https://devcenter.heroku.com/articles/deploying-nodejs)
- [Heroku add-on for using Mongo](https://devcenter.heroku.com/articles/mongolab)

@rodneycurl

**Comment by rodneycurl** [comment]
It's actually a MEAN app so I'm not sure running ruby commands would work.

**Comment by rodneycurl** [comment]
Showing node.js on the heroku page.

**Comment by amaseda** [comment]
So are you seeing that "application error" screenshot when you visit your app in the browser? Or do you see that when you visit your Heroku dashboard (i.e., `https://dashboard.heroku.com/apps/...`)?

I would still recommend following the instructions in the links I listed under `3`. Start here: https://devcenter.heroku.com/articles/deploying-nodejs

**Comment by amaseda** [comment]
Were you able to check out that link?

**Comment by amaseda** [comment]
Going to close this for now but please re-open if you have any issues/questions on this!
