### ISSUE TITLE
AXIOs

### ISSUE THREAD

**Issue by evalaidc** [ga-wdi-exercises/project4#445]
![image](https://cloud.githubusercontent.com/assets/24941303/24580259/fec62408-16d2-11e7-8b8b-9616fd932ad1.png)
I am trying to extract my data using axios, but keep getting an empty array and my desired array with my object. However since it is reading the empty array first, my data isn't showing up.

Is there a way to get around this?

```
// the component where i make my request, but i am trying to send the info to a child component
class SpotsContainer extends Component {
  constructor(props){
    super(props)
    this.state = {
      data: []
    }
    this.loadSpotsFromAPI = this.loadSpotsFromAPI.bind(this);
  }

  componentDidMount() {
   this.loadSpotsFromAPI();
  //  setInterval(this.loadSpotsFromAPI(), this.props.interval);
   }

  loadSpotsFromAPI() {
    axios.get(this.props.url).then(res => {
      this.setState({
        data: res.data
      })
    }).catch(err => {
      console.log(' api request failed')
   })

  };

  render(){
    console.log(this.state.data)
    return(
      <div>
      <h1> Spots Container </h1>
      <SpotList spots={this.state.data} />
      </div>
    )
  }
}
```

**Comment by amaseda** [comment]
Does it eventually replace the rendered empty data with the contents of the desired array? Or does the correct data never render at all?

**Comment by evalaidc** [comment]
the correct data appears but it is the second array. rendered with the 4 objects. however it is always reading the first empty array first.

**Comment by evalaidc** [comment]
for instance when I change the method to return the 2nd object

I get the 2nd object but only after it runs through the first array and is undefined
![image](https://cloud.githubusercontent.com/assets/24941303/24580367/e008359a-16d4-11e7-98ec-176b1fda2181.png)

```
 render(){
// this is the part i altered to return the first object
    console.log(this.state.data[1])
    return(
      <div>
      <h1> Spots Container </h1>
      <SpotList spots={this.state.data} />
      </div>
    )
  }
}
```

**Comment by evalaidc** [comment]
oops just reread your question. no the 2nd array of objects never render. but it prints out in the console.

**Comment by amaseda** [comment]
And what does your SpotList component look like?

**Comment by evalaidc** [comment]
```
import React, {Component} from 'react';

class SpotList extends Component {


  render(){
    let locations = this.props.spots.map((spot, index) => {
      return (
        <div key={index}>
        <h3> spot.title </h3>
        </div>
      )
    })
    return (
      <div>
      <h1> SpotList </h1>
        <div> {locations} </div>
      </div>
    )
  }

}

export default SpotList

```

**Comment by evalaidc** [comment]
I think it has something to do with setting the state the constructor as an array first. it's like it runs through the component twice: once with the initial constructor's empty array and then another time with the new state

That is just my assumption though

**Comment by evalaidc** [comment]
oops Erica just helped me realize my error. spot.title needed to be in {} to render correctly. :) thanks though @amaseda
