### ISSUE TITLE
MongoDB model and data inheritance

### ISSUE THREAD

**Issue by atflick** [ga-wdi-exercises/project4#446]
I'm trying to figure out if there is an easy way for a data collection to inherit data fields AND the values from another 'parent' collection.

For example if you have a collection for Vehicles which has an attribute of 'make' and another collection of Cars with the attribute 'model'.  Could you set something up in your database/schema so that when a Car is created it will also receive the 'make' field and value from the Vehicle for which the Car is created?  This is a pretty simple example, but for my project  I am looking to pass 4 data fields and values from the parent to the 'child.'  

Or is it possible to have a field in the 'child' receive a full object of the parent under a single attribute.  That way you could query based off that attribute in the child collection?

I think I have a way of doing what I need but just wondering if it's the correct or best way to do it.  That would be to just pass the attribute fields from the parent to the child and then auto complete them using the particular parents data when a child is being created.

Hopefully this makes sense.  Thanks!

**Comment by amaseda** [comment]
You can pass parent attributes down to the child. It really depends on the context in which you're doing this. For example, are you creating a child instance in the callback for retrieving an instance of the parent? If so, chances are there will be some `parent` variable that contains the information you're trying to store in the child.

You could also store a reference to the parent in the child (e.g., have a `parent` attribute that contains the id of the parent). MongoDB isn't ideal for hierarchical relationships but there are definitely ways to create that structure.

Hopefully that helps. Happy to elaborate.

@atflick

**Comment by atflick** [comment]
So right now I am storing a unique id of the parent on the child, so I'm able to reference the parent from the child, but this seems clunky for what I'm trying to do so it might be easier to pass some of the attributes and values I need to the child as well anytime a child is created.  

May also help to explain my project:  I am building a platform where you can compare/benchmark health insurance plans across employers by employer size, industry and location.  So I will need to perform calculations on subsets of medical plans based on their employers attributes.  So I am thinking it may just be easier to pass the size/industry/location data from the employer to each plan that is created underneath and employer.  

I guess I am just wondering if this is a good approach or if there is an easier way to perform this.  I think a join table is probably what I am looking for but I really wanted to use Mongo/Express for this project and not exactly sure the $lookup query is what I want.  Or maybe it is?

**Comment by amaseda** [comment]
To my knowledge, there is not an easier way to do this. That being said, will do some research on the matter now.

If `$lookup` works, then don't see why not!

To be honest, it sounds like using a relational database would make your life easier here. But if you really want to use Mongo/Express, keep exploring the approaches you've already mentioned. If you find a more efficient way of doing things down the line, then that'll be the time to refactor!

**Comment by atflick** [comment]
Ok thanks, I will play around with $lookup and see if I can get it to do what I want.  If you find anything in your research, let me know.
