### ISSUE TITLE
I am an issue. pls halp me

### ISSUE THREAD

**Issue by SavrajSingh** [ga-wdi-exercises/project4#447]
Hey guys so I embedded comments which is its own model into the Products model and I populated in it seeds.json but it is not showing up when I open it up on local host. I am attaching some pics to better illustrate what I am saying. Is the way I coded it incorrect?
<img width="1109" alt="screen shot 2017-04-03 at 10 15 02 am" src="https://cloud.githubusercontent.com/assets/24595749/24613918/ba6e5718-1857-11e7-8ac0-c0bcbf60b291.png">
<img width="1228" alt="screen shot 2017-04-03 at 10 15 23 am" src="https://cloud.githubusercontent.com/assets/24595749/24613925/bf7e4966-1857-11e7-8196-337063fbb8e2.png">

**Comment by SavrajSingh** [comment]
another one of the schema
<img width="794" alt="screen shot 2017-04-03 at 10 25 02 am" src="https://cloud.githubusercontent.com/assets/24595749/24613961/d82bc22c-1857-11e7-8779-abcf1b87ba1a.png">

**Comment by amaseda** [comment]
Can you confirm whether you can create a Comment on its own (i.e., not attached to a Product)? That way we can narrow down whether it has something to do with your schema/model definition or the way you're seeding data.

**Comment by amaseda** [comment]
Also what does your seed file (not the `.json` data file) look like?

**Comment by SavrajSingh** [comment]
I want to be able to make comments on each Product page but it is its own model. Here is the seed.js. I do not have full crud yet I dont think at least. Have not rendered front end to test. 
<img width="689" alt="screen shot 2017-04-03 at 10 30 02 am" src="https://cloud.githubusercontent.com/assets/24595749/24614227/9f69a124-1858-11e7-89cc-403ac2f49dac.png">

**Comment by amaseda** [comment]
Try creating a Comment (e.g., `Comment.create(...)`) in your seed file. Then, check your database via Mongo CLI to see if it's in there...

```bash
# in mongo
use products
db.comments.find()
```

**Comment by SavrajSingh** [comment]
yessir

**Comment by amaseda** [comment]
That worked?

**Comment by SavrajSingh** [comment]
trying it now

**Comment by SavrajSingh** [comment]
Yes I can create one and it has populated in the database

**Comment by amaseda** [comment]
Word! So that means your schema/model definitions are good.

Instead of using `.collection.insert`, what happens if you try doing something like this...

```js
Product.create( ... ).then((product) => {
  product.comments.push({ ... })
})
```

You would need to loop the above if doing it for multiple products.

I'm wondering if the `.collection.insert` doesn't take embedded documents into account...

**Comment by SavrajSingh** [comment]
So the comments populate within the mongo database but not in the browser. The process in the seed.js is working for both. I do not think it is a problem with the insert method. Hab has it exactly like mine and his is showing.

**Comment by SavrajSingh** [comment]
<img width="1431" alt="screen shot 2017-04-03 at 11 26 42 am" src="https://cloud.githubusercontent.com/assets/24595749/24616943/86c85cf2-1860-11e7-8230-79c153197ba9.png">

**Comment by amaseda** [comment]
I think we figured this one out IRL. Closing for now but feel free to re-open if you have more issues/questions.
