### ISSUE TITLE
Connecting React to Rails

### ISSUE THREAD

**Issue by laurkgol** [ga-wdi-exercises/project4#448]
What is the best way to connect React with a Rails API? I've seen several techniques online.

Right now my component is rendering without any of the data from the API and component did mount:
**localhost:3000/trips**
```
Location:
Time Span:
Photo Url:
```

Here is where I'm at:

**Trip Component (trip.js.jsx)**
```
var Trip = React.createClass({
  propTypes: {
    location: React.PropTypes.string,
    timeSpan: React.PropTypes.string,
    photoUrl: React.PropTypes.string
  },
  componentDidMount() {
        console.log('Component mounted');
    },
  render: function() {

    return (
      <div>
        <div>Location: {this.props.location}</div>
        <div>Time Span: {this.props.timeSpan}</div>
        <div>Photo Url: {this.props.photoUrl}</div>
      </div>
    );
  }
});
```

**Rails trips_controller.rb**

```
class TripsController < ApplicationController
  def index
    @trips = Trip.all
     render component: 'Trip', props: { trips: @trips }, tag: 'span', class: 'trip'
  end
end
```

**Comment by amaseda** [comment]
The most stress-free way to do this it to keep your front-end and back-end separate.

Otherwise, there are a number of gems out there that can help you with this...
- [`react_on_rails`](https://github.com/shakacode/react_on_rails) (readme includes tutorials)
- [`react-rails`](https://github.com/reactjs/react-rails)

**Comment by amaseda** [comment]
Going to close this one for now but please re-open if you have any additional issues/questions on this!
