### ISSUE TITLE
Can't get app to load

### ISSUE THREAD

**Issue by pdoulatshahi** [ga-wdi-exercises/project4#45]
Saying angular is not defined in my js/app.js file.

I have the scripts loading in my html file. Not sure what's wrong.

**Comment by RobertAKARobin** [comment]
Hmm. It's probably loaded in the wrong order in your HTML. Can you show me your `<script>` tags?

Incidentally, if you heard us mention your name in here, Brian was talking about the conversations he'd had with various students about their projects. He said "Paul D", and we heard "Pauli D", and were like, "holy crap, Brian knows Jersey Shore?" You probably get that a lot.

**Comment by pdoulatshahi** [comment]
Ha. Yeah - haven't gotten that in a while.

``` html
<script src="bower_components/angular/angular.min.js"></script>
<script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.3/jquery.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/angular.js/1.4.5/angular-route.min.js"></script>
<script src="https://cdn.firebase.com/js/client/2.2.4/firebase.js"></script>
<script src="https://cdn.firebase.com/libs/angularfire/1.1.2/angularfire.min.js"></script>

<script src="js/app.js"></script>
<script src="js/firebaseFactory.js"></script>
<script src="js/list/listFactory.js"></script>
<script src="js/list/index/listIndexController.js"></script>
<script src="js/list/show/listShowDirective.js"></script>
<script src="js/list/save/listSaveDirective.js"></script>

<script src="js/word/wordFactory.js"></script>
<script src="js/word/save/wordSaveDirective.js"></script>
<script src="js/word/show/wordShowDirective.js"></script>
```

On Thu, Sep 17, 2015 at 1:43 PM, Robert Thomas notifications@github.com
wrote:

> Hmm. It's probably loaded in the wrong order in your HTML. Can you show me
> your <script> tags?
> 
> Incidentally, if you heard us mention your name in here, Brian was talking
> about the conversations he'd had with various students about their
> projects. He said "Paul D", and we heard "Pauli D", and were like, "holy
> crap, Brian knows Jersey Shore?" You probably get that a lot.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/ga-dc/pbj-project4/issues/45#issuecomment-141163395.

## 

Paul Doulatshahi
(206) 818-5550

**Comment by RobertAKARobin** [comment]
Can you look inside the actual `angular.min.js` for me and make sure there's something in there? Oddly enough, someone yesterday had an `angular.min.js` that was totally blank. I'd just use a CDN for it.

**Comment by pdoulatshahi** [comment]
It isn't empty.

I tried a CDN as well - I feel like the error is somewhere else but I'm
just missing something.

On Thu, Sep 17, 2015 at 1:48 PM, Robert Thomas notifications@github.com
wrote:

> Can you look inside the actual angular.min.js for me and make sure
> there's something in there? Oddly enough, someone yesterday had an
> angular.min.js that was totally blank. I'd just use a CDN for it.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/ga-dc/pbj-project4/issues/45#issuecomment-141164407.

## 

Paul Doulatshahi
(206) 818-5550

**Comment by RobertAKARobin** [comment]
Huh. That's odd. Can you push your code to GH?

**Comment by pdoulatshahi** [comment]
https://github.com/pdoulatshahi/project4

On Thu, Sep 17, 2015 at 1:54 PM, Paul Doulatshahi <
paul.doulatshahi@gmail.com> wrote:

> On it!
> 
> On Thu, Sep 17, 2015 at 1:53 PM, Robert Thomas notifications@github.com
> wrote:
> 
> > Huh. That's odd. Can you push your code to GH?
> > 
> > —
> > Reply to this email directly or view it on GitHub
> > https://github.com/ga-dc/pbj-project4/issues/45#issuecomment-141166097.
> 
> ## 
> 
> Paul Doulatshahi
> (206) 818-5550

## 

Paul Doulatshahi
(206) 818-5550

**Comment by RobertAKARobin** [comment]
Thanks. While I'm pulling this app, did it _stop_ working, or just not work to begin with?

**Comment by pdoulatshahi** [comment]
Not work to begin with. I'm a bit behind the ball because I was stressed
about coming up with an idea, but I should still be fine time-wise.

On Thu, Sep 17, 2015 at 2:01 PM, Robert Thomas notifications@github.com
wrote:

> Thanks. While I'm pulling this app, did it _stop_ working, or just not
> work to begin with?
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/ga-dc/pbj-project4/issues/45#issuecomment-141167762.

## 

Paul Doulatshahi
(206) 818-5550

**Comment by RobertAKARobin** [comment]
Got it! In `app.js`, un-comment `// firebase`. On `index.html`, make sure inside the first `<script>` you've defined a Firebase URL.

**Comment by pdoulatshahi** [comment]
I created my Firebase URL and added it and uncommented firebase in app.js -
still not working :(

On Thu, Sep 17, 2015 at 2:06 PM, Robert Thomas notifications@github.com
wrote:

> Got it! In app.js, un-comment // firebase. On index.html, make sure
> inside the first <script> you've defined a Firebase URL.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/ga-dc/pbj-project4/issues/45#issuecomment-141168880.

## 

Paul Doulatshahi
(206) 818-5550

**Comment by RobertAKARobin** [comment]
That's weird. It fixed it on my computer:

``` js
(function(){
  angular.module('translatr', [
    'ngRoute',
    'firebase',
  ])
```

``` html
    <script>var firebaseURL = "https://wdidc.firebaseio.com";</script>
    <script src="bower_components/angular/angular.min.js"></script>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.3/jquery.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/angular.js/1.4.5/angular-route.min.js"></script>
    <script src="https://cdn.firebase.com/js/client/2.2.4/firebase.js"></script>
    <script src="https://cdn.firebase.com/libs/angularfire/1.1.2/angularfire.min.js"></script>
```

**Comment by pdoulatshahi** [comment]
That is very weird. Not sure how to proceed.

On Thu, Sep 17, 2015 at 2:10 PM, Robert Thomas notifications@github.com
wrote:

> That's weird. It fixed it on my computer:
> 
> (function(){
>   angular.module('translatr', [
>     'ngRoute',
>     'firebase',
>   ])
> 
> ```
> <script>var firebaseURL = "https://wdidc.firebaseio.com";</script>    <script src="bower_components/angular/angular.min.js"></script>    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.3/jquery.min.js"></script>    <script src="https://cdnjs.cloudflare.com/ajax/libs/angular.js/1.4.5/angular-route.min.js"></script>    <script src="https://cdn.firebase.com/js/client/2.2.4/firebase.js"></script>    <script src="https://cdn.firebase.com/libs/angularfire/1.1.2/angularfire.min.js"></script>
> ```
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/ga-dc/pbj-project4/issues/45#issuecomment-141169872.

## 

Paul Doulatshahi
(206) 818-5550

**Comment by RobertAKARobin** [comment]
I'll come have a gander in a sec

**Comment by pdoulatshahi** [comment]
Thanks!

On Thu, Sep 17, 2015 at 2:13 PM, Robert Thomas notifications@github.com
wrote:

> I'll come have a gander in a sec
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/ga-dc/pbj-project4/issues/45#issuecomment-141170620.

## 

Paul Doulatshahi
(206) 818-5550
