### ISSUE TITLE
Publishing to gh-pages

### ISSUE THREAD

**Issue by justwes2** [ga-wdi-exercises/project4#450]
I'm trying to replace my gh-page. I changed the name of the old one, and named the new one justwes2.github.io, like were supposed to. But when I go to publish, the settings page won't let me: 
<img width="741" alt="screen shot 2017-04-03 at 11 39 02 am" src="https://cloud.githubusercontent.com/assets/24883096/24617599/56bdb532-1862-11e7-91ae-32ab741f0a0e.png">
I'm on the branch gh-pages, and google/stackoverflow have been unhelpful. Is there an intermediate step I'm missing?

**Comment by amaseda** [comment]
You can upload any repo to gh-pages -- not only one with the reponame `username.github.io`.

Say you have a `project4` repo. If the `gh-pages` branch is properly set up you can visit `username.github.io/project4`

Otherwise, I'm not sure why Github is complaining about the renaming of repos. Maybe you need to wait a bit until you can do that?

**Comment by amaseda** [comment]
Any luck?

**Comment by justwes2** [comment]
Nope. No change. I'm combing through the user settings to see if I have to do anything else to take down my old page. Right now, https://justwes2.github.io/ is a 404 page, so I'm not sure where the conflict is.

**Comment by amaseda** [comment]
Can you rename the repo to project4, make sure it has a `gh-pages` branch, and then visit `http://justwes2.github.io/project4`?

> You can use whatever repo name in place of `project4`

**Comment by justwes2** [comment]
So that worked, sort of. https://justwes2.github.io/portfolio_page/ now shows the readme, instead of the app...

**Comment by amaseda** [comment]
Do you have an `index.html` in the root directory?

**Comment by justwes2** [comment]
Its a react app, the index.html is in the public file.

**Comment by amaseda** [comment]
Ah, right. We're going to need to take some additional steps to get this to work.

I've found this to be a helpful resource when deploying a React app to a static file hosting service like Github pages: https://medium.freecodecamp.com/surge-vs-github-pages-deploying-a-create-react-app-project-c0ecbf317089

There are instructions for Github Pages there. There are also instructions for a service called Surge, which I've recently become a fan of. I'll leave you to explore that link.

Let me know if you have any questions as you're going through it.

**Comment by justwes2** [comment]
Where in the `package.json` should I put the homepage url? My current json file:
```
{
  "name": "portfolio_page",
  "version": "0.1.0",
  "private": true,
  "dependencies": {
    "react": "^15.4.2",
    "react-dom": "^15.4.2",
    "react-router-dom": "^4.0.0"
  },
  "devDependencies": {
    "react-scripts": "0.9.5"
  },
  "scripts": {
    "start": "react-scripts start",
    "build": "react-scripts build",
    "test": "react-scripts test --env=jsdom",
    "eject": "react-scripts eject"
  }
}
```

**Comment by amaseda** [comment]
Try putting it at the root level of the object (i.e., same level as "name" and "version")

**Comment by justwes2** [comment]
Okay, that got the page up, but now the router paths are messing with the host. Its hosted at https://justwes2.github.io/portfolio_page/, however, it still goes to https://justwes2.github.io/ as the home route, but you can only get there from the portfolio link otherwise it throws a 404. Is there a workaround or do I need to rename all my routes?

**Comment by amaseda** [comment]
What URL did you put in `package.json`?

You might need to change your route URLs, but this would only be on the `gh-pages` branch.

**Comment by justwes2** [comment]
here is the `  "homepage": "https://justwes2.github.io/portfolio_page",`. Can I just host it to the justwes2.github.io? Since its a portfolio, that would make the most sense semantically.

**Comment by amaseda** [comment]
Go for it. I only suggested the alternate approach because of the errors you were getting from Github before.

**Comment by justwes2** [comment]
Ok. So I tried changing the homepage, and that didn't work, so I went back and switched all the routes, which you can see here: https://github.com/justwes2/portfolio_page/blob/master/src/Home.js, but on the deployed page, https://justwes2.github.io/portfolio_page/, none of the links contain the /portfolio_page/ that the code wants them to have, so none of the routes work. What am I doing wrong?

**Comment by amaseda** [comment]
Were you able to successfully rename the repo to `justwes2.github.io`? If so, there should be no need for `/portfolio_page` in any URL.

**Comment by justwes2** [comment]
When I try that, it errors out at the build, with this lovely error: 
```
npm ERR! Darwin 16.3.0
npm ERR! argv "/usr/local/Cellar/node/7.4.0/bin/node" "/usr/local/bin/npm" "run" "deploy"
npm ERR! node v7.4.0
npm ERR! npm  v4.0.5
npm ERR! code ELIFECYCLE
npm ERR! portfolio_page@0.1.0 deploy: `npm run build&&gh-pages -d build`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the portfolio_page@0.1.0 deploy script 'npm run build&&gh-pages -d build'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the portfolio_page package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     npm run build&&gh-pages -d build
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs portfolio_page
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls portfolio_page
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/wescoffay/wdi/projects/portfolio_page/npm-debug.log
```

**Comment by amaseda** [comment]
Hm, can't say I've encountered this error before.

Have you replaced all references to the `portfolio_page` repo with `justwes2.github.io`?

Maybe try starting from Step 1 in that gh-pages tutorial again, although this time we know we're working with `justwes2.github.io` from the beginning (instead of fiddling around with a repo with a different name).

**Comment by amaseda** [comment]
@justwes2 Able to make any progress?

**Comment by justwes2** [comment]
Not so far. I have confirmed everything for the build is routed for justwes2.github.io, but that build fails. When I rename the repo to portfolio_page and adjust the routes accordingly, I now get the same error

**Comment by amaseda** [comment]
Yeah, I would recommend starting the gh-pages deployment process from scratch using `justwes2.github.io` from Step 1 (and not switching it) and see if you get the same error.

If that doesn't work, step away from this for a bit and work on some different functionality. Can revisit this down the line but don't want it to take up too much of your time right now.

**Comment by justwes2** [comment]
So set the homepage to `justwes2.github.io`, build the routes as just `/`, and `npm run deploy`? I've tried that. And since this is my portfolio page, getting it up and working is kind of a priority since I need to be able to showcase my other work. It seems like a sensible investment of my time.

**Comment by amaseda** [comment]
There's a link on that page to the `create-react-app` documentation that talks about problems encountered when deploying a React app that uses React Router to Github Pages.

https://github.com/facebookincubator/create-react-app/blob/master/packages/react-scripts/template/README.md#notes-on-client-side-routing

Not sure if you've checked that out yet but read through it and see if either of the solutions help.

If that's not the issue at hand, let me know and we can keep looking into it.

**Comment by justwes2** [comment]
I got a chance to take a look at this, and I feel like I'm reaching a point of diminishing returns on gh-pages. If I go with surge, can I pick a domain name as long as it ends with the surge extension? I feel like at this point I just want the page deployed so I can focus on my project.

**Comment by amaseda** [comment]
Yup, you can pick the surge domain. Take a look at the video here: https://surge.sh/help/getting-started-with-surge

**Comment by justwes2** [comment]
So umm, any thoughts?
<img width="1157" alt="screen shot 2017-04-04 at 4 11 16 pm" src="https://cloud.githubusercontent.com/assets/24883096/24676562/73591cd2-1951-11e7-8d9c-88abe6aa6d32.png">

**Comment by amaseda** [comment]
Did you run `npm run build` prior to deploying? And when you deploy, you need to make sure `project path:` includes `/build` at the end

**Comment by justwes2** [comment]
Ah missing the /build. You are my Yoda!

**Comment by amaseda** [comment]
Hooray!
