### ISSUE TITLE
git won't ignore .gitignore folder

### ISSUE THREAD

**Issue by justwes2** [ga-wdi-exercises/project4#452]
I put my api key in a .env file, which I then put in a .gitignore file, however, git isn't ignoring it. I have tried removing the cache, I have even tried rm -rf'ing the .git and reinitializing with the .gitignore folder, but when I do an initial commit, it still creates a .gitignore in the repo. How do I tell git to ignore this folder so I can push to a remote repo without risking my api key?

**Comment by superbuggy** [comment]
can you run `$ cat .gitignore` and paste the result here?

**Comment by justwes2** [comment]
`cat: .gitignore: Is a directory`
I need it to be a directory so I can store the .env file with the api key in it.

**Comment by amaseda** [comment]
`.gitignore` should be a file, not a directory. How did you go about creating it?

If you want to have git ignore a file or a directory, just put its name in the `.gitignore` file...

```
file_name.js
directory_name
directory_name/sub_directory
```

**Comment by justwes2** [comment]
So the `.gitignore` should where i want to ignore `.env` in the root directory should look like:
```
/.env
```
That seems too  easy.

**Comment by amaseda** [comment]
`.gitignore` should sit in your app's root directory. You should be able to just say...

```
.env
```

It will then look in the root directory and see if any file or directory name matches. It's supposed to be easy!

**Comment by justwes2** [comment]
Ok, I did that,and when I ran `git init` and committed, `create mode 100644 .gitignore` showed up on but not the .env. Is that the expected outcome here?

**Comment by justwes2** [comment]
Looks like it. Thanks, I was missing the key concept of .gitignore
