### ISSUE TITLE
Need Help Connecting my database to my react app

### ISSUE THREAD

**Issue by bgalladian** [ga-wdi-exercises/project4#453]
I'm at my wits end, and can't figure out how to connect my mongoose DB with my react app.  Can someone please look at my code or point me in the right direction?

**Comment by superbuggy** [comment]
Do you have Express routes that render json? What does your back end code look-like?

**Comment by bgalladian** [comment]
just pushed up my most recent code.
https://github.com/bgalladian/kickSStarter/tree/master/kicksstarter

This is the tutorial im using:
https://medium.com/@bryantheastronaut/react-getting-started-the-mern-stack-tutorial-feat-es6-de1a2886be50

**Comment by amaseda** [comment]
What specific problems/errors have you run into?

A couple of notes/questions...
- Your `server.js` file isn't using your model definitions. All you have right now is a route that sends back `{message: 'API Connected'}`. So one thing you'll need to do is create some Express routes that correspond with CRUD actions. The existing Mongoose and Express-Mongoose lesson plans will be helpful here.
- When it comes to communicating with your back-end in your React app, you'll need to use some outside tool. You guys learned about **Axios** in the React Router lesson. You can also use jQuery. [There are some tips on how to use that in the React Router lab](https://github.com/ga-wdi-exercises/react-router-lab/blob/master/part-ii.md#search-for-a-stock).

**Comment by AndyWhitley** [comment]
Check out how I set up the `index.js` (equivalent to your `server.js`) for the Mongo/Express back-end I built for the React Translator App from class. I then used Axios on my front-end to send requests to this back-end:

https://github.com/ga-wdi-exercises/react-translator-api/blob/master/index.js
> Note that I configured cors to allow for requests from my separate React front-end app

**Comment by amaseda** [comment]
Able to make any progress? Let us know if you have any additional questions.

@bgalladian

**Comment by bgalladian** [comment]
Thanks for the tips guys, I guess my brain fried itself yesterday.  I'll try these today and let you know!

**Comment by superbuggy** [comment]
Check out the when president exercise for creating `/api/` routes if you need a reference!

**Comment by amaseda** [comment]
@bgalladian Sounds good. Going to close this one for now but please re-open if you have any questions/issues today!

**Comment by bgalladian** [comment]
I keep getting this error when I run nodemon server.js


events.js:160
      throw er; // Unhandled 'error' event
      ^

Error: Trying to open unclosed connection.
    at NativeConnection.Connection.open (/Users/bedig/wdi/projects/project-04/kicksstarter/node_modules/mongoose/lib/connection.js:240:11)
    at Mongoose.connect (/Users/bedig/wdi/projects/project-04/kicksstarter/node_modules/mongoose/lib/index.js:242:47)
    at Object.<anonymous> (/Users/bedig/wdi/projects/project-04/kicksstarter/server.js:12:10)
    at Module._compile (module.js:571:32)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Module.runMain (module.js:605:10)
    at run (bootstrap_node.js:420:7)
    at startup (bootstrap_node.js:139:9)
    at bootstrap_node.js:535:3

**Comment by amaseda** [comment]
Are you running `nodemon` in multiple tabs?

**Comment by bgalladian** [comment]
I am not

**Comment by superbuggy** [comment]
what is the output of `$ ps -ax | grep mongo`?

**Comment by bgalladian** [comment]
55870 ttys000    0:00.00 grep mongo
55323 ttys001    0:08.56 mongod

**Comment by superbuggy** [comment]
try `$ kill -9 55323`

**Comment by bgalladian** [comment]
Tried that, then tried doing nodemon server.js again, still got the same error.  About to pull hair out.

**Comment by superbuggy** [comment]
lemme pop over
