### ISSUE TITLE
MEAN: getting second model to show up

### ISSUE THREAD

**Issue by Nykke** [ga-wdi-exercises/project4#455]
I'm trying to get my second model to populate but I'm getting this error:

```
angular.js:11655 TypeError: Cannot read property 'get' of undefined
    at new UserShowControllerFunction (http://localhost:3001/assets/js/app.js:113:60)
    at e (https://ajax.googleapis.com/ajax/libs/angularjs/1.3.15/angular.min.js:36:315)
    at Object.instantiate (https://ajax.googleapis.com/ajax/libs/angularjs/1.3.15/angular.min.js:36:432)
    at https://ajax.googleapis.com/ajax/libs/angularjs/1.3.15/angular.min.js:76:49
    at https://cdnjs.cloudflare.com/ajax/libs/angular-ui-router/0.2.15/angular-ui-router.min.js:7:23333
    at $ (https://ajax.googleapis.com/ajax/libs/angularjs/1.3.15/angular.min.js:70:197)
    at B (https://ajax.googleapis.com/ajax/libs/angularjs/1.3.15/angular.min.js:59:255)
    at g (https://ajax.googleapis.com/ajax/libs/angularjs/1.3.15/angular.min.js:51:335)
    at https://ajax.googleapis.com/ajax/libs/angularjs/1.3.15/angular.min.js:50:444
    at k (https://cdnjs.cloudflare.com/ajax/libs/angular-ui-router/0.2.15/angular-ui-router.min.js:7:22678) <main data-ui-view="" class="ng-scope">
```

this is what I have in express
```
//route defined to show users attached to request
app.get("api/maintenance_requests/:tenant_name/users", function(req, res){
  Maintenance_Request.findOne({tenant_name: req.params.tenant_name}).then(function(){
    res.json(maintenance_request)
  })
})
```

this is what I have in angular
```
  .controller("UserShowController", [
    "$stateParams",
    "Factory",
    "$state",
    UserShowControllerFunction
  ])

//link to our backend api
  function FactoryFunction($resource) {
    return {
      maintenance_requests: $resource("/api/maintenance_requests/:tenant_name", {}, {
        update: {method: "PUT"}
      }),
      users: $resource("/api/maintenance_requests/:tenant_name/users/:category", {tenant_name: "@tenant_name", category: "@category"}, {
        get: {method: "GET", params: {tenant_name: "@tenant_name", category: "@category"}, isArray: false},
        update: {method: "PUT"}
      })
    }
  }

  function UserShowControllerFunction ( $state, $stateParams, Factory ) {
    this.maintenance_request = Factory.maintenance_requests.get({tenant_name: $stateParams.tenant_name}, (maintenance_request) =>{
      this.users = maintenance_request.users
    })
  }
```

**Comment by amaseda** [comment]
Make sure the order of the arguments to `UserShowControllerFunction` match the order in which you're injecting dependencies to `UserShowController`

**Comment by Nykke** [comment]
that fixed that error but now i'm back to this, is there a way to prevent this error in the future?

```
Error in resource configuration for action `get`. Expected response to contain an object but got an array (Request: GET /api/maintenance_requests)
```

**Comment by amaseda** [comment]
This might be happening because you are not replacing `:tenant_name` in the URL with an actual value. What happens when you `console.log($stateParams.tenant_name)`?

**Comment by Nykke** [comment]
so I gave up on that a while ago and tried to make my life easier by using different factories and I'm getting this error 

```
TypeError: Cannot read property 'indexOf' of undefined
    at f (https://cdnjs.cloudflare.com/ajax/libs/angular-ui-router/0.2.15/angular-ui-router.min.js:7:13111)
    at m (https://cdnjs.cloudflare.com/ajax/libs/angular-ui-router/0.2.15/angular-ui-router.min.js:7:13202)
    at Object.y.get (https://cdnjs.cloudflare.com/ajax/libs/angular-ui-router/0.2.15/angular-ui-router.min.js:7:19570)
    at new UserShowControllerFunction (http://localhost:3001/assets/js/app.js:112:59)
    at e (https://ajax.googleapis.com/ajax/libs/angularjs/1.3.15/angular.min.js:36:315)
    at Object.instantiate (https://ajax.googleapis.com/ajax/libs/angularjs/1.3.15/angular.min.js:36:432)
    at https://ajax.googleapis.com/ajax/libs/angularjs/1.3.15/angular.min.js:76:49
    at https://cdnjs.cloudflare.com/ajax/libs/angular-ui-router/0.2.15/angular-ui-router.min.js:7:23333
    at $ (https://ajax.googleapis.com/ajax/libs/angularjs/1.3.15/angular.min.js:70:197)
    at B (https://ajax.googleapis.com/ajax/libs/angularjs/1.3.15/angular.min.js:59:255) <main data-ui-view="" class="ng-scope">
```

this is my express
```
//route defined to show users attached to request
app.get("/api/maintenance_requests/:tenant_name/users", function(req, res){
  Maintenance_Request.user.find({}).then(function(users){
    res.json(users)
  })
})
```
this is my angular
```
.controller("UserShowController", [
    "$state",
    "$stateParams",
    "UserFactory",
    UserShowControllerFunction
  ])

//view for users
  function UserShowControllerFunction (Maintenance_RequestFactory, UserFactory, $stateParams ) {
    this.maintenance_request = Maintenance_RequestFactory.get({tenant_name: $stateParams.tenant_name})
    this.users = UserFactory.query()
  }
```

**Comment by amaseda** [comment]
Are you using `.indexOf` anywhere?

**Comment by Nykke** [comment]
I am not, my guess is, the .query is making that happen?

**Comment by amaseda** [comment]
Could be. What does your `UserFactory` look like now?

**Comment by Nykke** [comment]
```
.factory("UserFactory", function($resource){
    return $resource ("/api/maintenance_requests/:tenant_name/users/:category", {}, {
        update: {method: "PUT"}
      })
  })
```

**Comment by amaseda** [comment]
In this case, if you're trying to get all the users associated with a particular `tenant_name`, you're going to have to pass a value into query that replaced `:tenant_name` in the URL. So something like this...

```js
function UserShowControllerFunction (Maintenance_RequestFactory, UserFactory, $stateParams ) {
    this.maintenance_request = Maintenance_RequestFactory.get({tenant_name: $stateParams.tenant_name})
    this.users = UserFactory.query({tenant_name: $stateParams.tenant_name})
  }
```

Otherwise `:tenant_name` would just be blank.

**Comment by Nykke** [comment]
it's still not grabbing it, I think that's why I ended up taking that out of the query

**Comment by amaseda** [comment]
If you do pass that into `.query`, do you still get the same error?

Does your back-end receive the request? If so, what route is it hitting? It should say which in the terminal window that's running your server.

**Comment by Nykke** [comment]
I get the same error when I pass it into query and it's not hitting my backend. Also changed my backend code to 

```
//route defined to show users attached to request
app.get("/api/maintenance_requests/:tenant_name/users", function(req, res, next){
  req.maintenance_request.populate("users", function(err, maintenance_request){
    if(err) {
      return next(err);
    }
    res.json(maintenance_request)
  })
})
```

**Comment by amaseda** [comment]
Can you send me the link to your repo(s)? Make sure to push up your most recent code. Will dive in and take a look.

**Comment by Nykke** [comment]
repo added, it's on the tester branch: https://github.com/Nykke/project_04/tree/tester

**Comment by amaseda** [comment]
Okay, so it's not working yet BUT it is now hitting the back-end, which I think is a great place for you to continue working from. Had to make a few changes to get here...

#### The `ui-sref` to the users page was missing parameters

```html
<!-- maintenance_show.html -->

<h4><a ui-sref="userShow({tenant_name: vm.maintenance_request.tenant_name})">users</a></h4>
```

#### `UserShowControllerFunction` arguments

The arguments being passed into `UserShowControllerFunction` did not match the order in which dependencies were being injected into `UserShowController`

```js
function UserShowControllerFunction ($state, $stateParams, UserFactory) {
  // ...
}
```

#### Modify API calls

This is what you had before...

```js
function UserShowControllerFunction ($state, $stateParams, UserFactory) {
  this.maintenance_request = Maintenance_RequestFactory.get({tenant_name: $stateParams.tenant_name}, (maintenance_request) => {
    this.users = maintenance_requests.UserFactory.query({tenant_name: $stateParams.tenant_name})
  })
}
```
> `UserFactory` does not belong to `maintenance_requests` (which in its plural form does not exist in your code). You can just do `UserFactory.query( ... )`

This got it to work...

```js
function UserShowControllerFunction ($state, $stateParams, UserFactory) {
  this.users = UserFactory.query({tenant_name: $stateParams.tenant_name})
}
```
> You actually don't need to use the `Maintenance_RequestFactory` since all you're doing is retrieving users that belong to a particular maintenance request.

**Comment by Nykke** [comment]
question: 

would it be 
```
this.users = UserFactory.query({tenant_name: $stateParams.tenant_name.user})
```

also I keep getting an undefined when I do .user. when it's just tenant_name I get the name of the tenant form. But either way they're not loading the actual form. I changed my seed data to reference user

```
var kitchen = new Maintenance_Request({
  tenant_name: "Rachel",
  building_number: 20033,
  apt_number: 204,
  type: "kitchen",
  urgency: "medium",
  description: "light is flickering",
  completed: "no",
  users: [maria, rachel]
});
```

but it still won't load the users

**Comment by amaseda** [comment]
Yeah, you can set the result of `.query` to `this.users`

`$stateParams.tenant_name.user` does not exist. `$stateParams.tenant_name` returns a string corresponding with what is in the URL. It is not an object so you cannot drill into it using `.user`

**Comment by Nykke** [comment]
it's still not loading and now I'm getting a 500 internal server error

**Comment by amaseda** [comment]
Is the request hitting your back-end though? Take a look at the terminal window running the server.

If that is the case, now you need to diagnose what the problem on the back-end is. What route is it trying to trigger? Is it the correct route? If so, what does the incoming `req` look like?

**Comment by Nykke** [comment]
so I got this to work but my create is not giving an error nor is it storing the inputs?

backend 

```
//route defined to create users attached to a request
app.post("/api/maintenance_requests/:tenant_name/users", function(req, res){
  Maintenance_Request.findOne({tenant_name: req.tenant_name}).then(function(){
    User.create({name: req.body.name, category: req.body.category, division: req.body.division}).then((user) => {
      res.json(user)
    })
  })
})
```

app.js

```
.controller("UserShowController", [
    "$state",
    "$stateParams",
    "UserFactory",
    UserShowControllerFunction
  ])

//need a different user factory
  function UserFactoryFunction($resource){
    return $resource ("/api/maintenance_requests/:tenant_name/users", {tenant_name: "@tenant_name"}, {
      //need to specify which methods are being used for the second model, users
        get: {method: "GET", params: {}, isArray: false},
        create: {method: "POST"}
      })
    }


  //view for users for one maintenance_request
  function UserShowControllerFunction ($state, $stateParams, UserFactory ) {
      this.tenant = UserFactory.get({tenant_name: $stateParams.tenant_name}, (tenant) => {
        this.users = tenant.users

        //create new user attached to one maintenance_request
        this.newUser = new UserFactory()
        this.newUser.create = function(){
          this.newUser.$save({tenant_name: $stateParams.tenant_name}).then(function(user){
            this.maintenance_request.UserFactory.push(user)
            // this.maintenance_request = maintenance_request.UserFactory.push(user)
            $state.reload()
          })
        }
    })
}
```

**Comment by amaseda** [comment]
Is the user you are creating supposed to be attached to a maintenance request (maybe as an embedded/nested document)? If so, how are you doing that on the back-end? Unless `division` takes care of that, I don't see anything in `User.create` that links that new user with a maintenance request.

Also notice you are saying `maintenance_request.UserFactory` on the front-end. `UserFactory` is not located inside of `maintenance_request`. You can just say `UserFactory`.

**Comment by Nykke** [comment]
on my backend, my user.create I just listed the keys that corresponds to my user schema. I thought i was telling my backend to find one maintenance request and attach those things that belong to the user to it. 

are you saying for my angular, I can just say 
```
 this.UserFactory.push(user)
``` ?

**Comment by Nykke** [comment]
changed my app. js to 

```js
this.newUser = new UserFactory()
this.newUser.create = function(){
  this.newUser.$save(function(user){
    $state.reload()
  })
```
changed my express to 
```js
//route defined to create users attached to a request
app.post("/api/maintenance_requests/:tenant_name/users", function(req, res, next){
//   Maintenance_Request.findOne({tenant_name: req.tenant_name}).then(function(){
//     User.create(req.body).then(function(user){
//       res.json(user)
//     })
//   })
// })

  var user = new User(req.body)
  User.maintenance_request = req.maintenance_request
  User.save(function(err, user){
    if(err){ return next(err);
    }
    req.maintenance_request.users.push(user);
    req.maintenance_request.save(function(err, maintenance_request){
      if(err){ return next(err);
      }
      res.json(user);
    })
  })
})
```

still doesn't work or give an error

**Comment by amaseda** [comment]
Some notes/questions...

  1. You won't find anything in `req.maintenance_request`. Did you mean `req.body.maintenance_request`?

 2. Ideally, what does `req.maintenance_request` contain? Is it an id or some number? If so, that means you cannot call `.push` or `.save` on it since it's just a number -- not an array or instance of your `Maintenance_request` model.


#### Suggested back-end workflow

1. `.findOne` the correct `Maintenance_Request`
2. Create a new `User` using the contents of `req.body`
3. Push that new `User` into the `users` array of the `Maintenance_Request` you found earlier
4. Save that `Maintenance_Request`
5. Decide what you want to send back to the front-end and place that inside `res.json( )`

**Comment by Nykke** [comment]
it still doesn't work

```
//route defined to create users attached to a request
app.post("/api/maintenance_requests/:tenant_name/users", function(req, res){
  Maintenance_Request.findOne({tenant_name: req.tenant_name}).then(function(){
     User.create({name: req.body.name, category: req.body.category, division: req.body.division}).then(function(user){
       Maintenance_Request.User.push(users).save(function(maintenance_request){
        res.json(user);
        })
     })
  })
})
```

**Comment by superbuggy** [comment]
`req.tenant_name` should be `req.body.tenant_name`. This omission has been plaguing your code in different places over the past couple issues.

Take a couple minutes to reflect on what `body-parser` does, and to review your code. With `.urlencoded(true)`, `bodyparser` takes data and makes it available as a object that is a property of `req.body`.

**Comment by amaseda** [comment]
You've got things happening in the right order, but some changes need to be made (including the one James mentioned in the last post).

`Maintenance_Request` and `User` represent your model definitions - not instances of those models.

If you want to, for example, access the particular maintenance request you retrieved using `.findOne`, you need to pass an argument into `.findOne`'s callback like so...

```js
 Maintenance_Request.findOne({tenant_name: req.body.tenant_name}).then(function(maintenance_request){
  // you can now access that particular instance with the `maintenance_request` argument
})
```
> The above also applies to `User`.

When you get to pushing a user into a particular maintenance request's users array, it will look something like this...

```js
maintenance_request.users.push(user)
```
> In this example, both `maintenance_request` and `user` correspond with the callback arguments for `Maintenance_Request.findOne( )` and `User.create( )` respectively.

**Comment by Nykke** [comment]
I made the necessary changes and I changed my app js several times and it's still not doing what it's supposed to do. Nor am I getting any error AT ALL. Is there ANY thing else I need to do to get this work because honestly I don't know anymore. Does my app js look correct? is my form correct?

**Comment by amaseda** [comment]
What's the latest version of your code look like?

**Comment by Nykke** [comment]
```
app.post("/api/maintenance_requests/:tenant_name/users", function(req, res){
  Maintenance_Request.findOne({tenant_name: req.body.tenant_name}).then(function(){
    User.create({name: req.body.name, category: req.body.category, division: req.body.division}).then((user) => {
      res.json(user)
    })
    //  User.create({name: req.body.name, category: req.body.category, division: req.body.division}).then(function(user){
    //    maintenance_request.users.push(user).save(function(maintenance_request){
    //     res.json(user);
    //     })
    //  })
  })
})
```

```
function UserFactoryFunction($resource){
    return $resource ("/api/maintenance_requests/:tenant_name/users", {tenant_name: "@tenant_name"}, {
      //need to specify which methods are being used for the second model, users
        get: {method: "GET", params: {}, isArray: false},
        create: {method: "POST", params: {tenant_name: "@tenant_name"}}
      })
    }

  function UserShowControllerFunction ($state, $stateParams, UserFactory ) {
      let vm = this;
      this.tenant = UserFactory.get({tenant_name: $stateParams.tenant_name});


        //create new user attached to one maintenance_request
        this.newUser = new UserFactory()
        this.newUser.create = function(){
          vm.newUser.$save(function(user){
            vm.users.push(user)
            vm.users.$update({tenant_name: $stateParams.tenant_name}, () => {
            $state.reload()

        // this.newUser = new UserFactory()
        // this.newUser.create = function(){
        //   this.newUser.$save({tenant_name: $stateParams.tenant_name}).then(function(user){
        //     this.UserFactory.push(user)
        //   // this.maintenance_request = maintenance_request.UserFactory.push(user)
        //     $state.reload()
        //   })

          // ({tenant_name: $stateParams.tenant_name}).then(function(user){
          //   this.UserFactory.push(user)
          //   // this.maintenance_request = maintenance_request.UserFactory.push(user)
          //   $state.reload()
          // })
        })
    })
  }
}
```

this is my latest version... nothing works
