### ISSUE TITLE
MEAN app - getting upvotes to save in the database

### ISSUE THREAD

**Issue by hschuster9** [ga-wdi-exercises/project4#457]
repo: https://github.com/hschuster9/project_4 

I am trying to get upvotes to persist in the database. Currently, when the icon is clicked, it only increments the upvote on the page, but when you refresh it's back to 0. I tried a bunch of different ways, but something is still missing. 

I tried adding a save method to the schema in connection.js:

```
const ItemSchema = new mongoose.Schema({
  title: String,
  photo_url: String,
  upvotes: {type: Number, default: 0},
  maker: String,
  description: String,
  price: Number
})

ItemSchema.methods.upvote = function(cb){
  this.upvotes += 1;
  this.save(cb)
}
```

in my index.js I tried a bunch of app.put and router.put but they don't seem to be doing anything?:

```
//increase upvote?
app.put('/api/items/upvote', function(req, res, next){
  req.item.upvote(function(err, item){
    if(err){return next(err)}
    res.json(item)
  })
})

//increase upvote?
app.put('/api/items/:title/upvote', function(req, res, next){
  req.item.upvote(function(err, item){
    if(err){return next(err)}
    res.json(item)
  })
})


//increase upvote?
router.put('/items/:title/upvote', function(req, res, next){
  req.item.upvote(function(err, item){
    if(err) {return next(err)}
    res.json(item)
  })
})
```

and in my app.js:

```
.factory("ItemFactory", [
  "$resource",
  "$http",
  ItemFactoryFunction
])
.controller("ItemIndexController", [
  "ItemFactory",
  "$state",
  "$scope",
  ItemIndexControllerFunction
])

function ItemFactoryFunction( $resource, $http){
  return $resource("/api/items/:title", {}, {
    update: {method: "PUT"}
  })
  var items_array = {
    items: []
  }
  items_array.upvote = function(item){
    return $http.put('/items/'+ item.title+"/upvote").success(function(data){
    item.upvotes += 1
  })
}
  return items_array
}

function ItemIndexControllerFunction(ItemFactory, $state, $scope){
  this.items = ItemFactory.query()
  $scope.items = ItemFactory.items
  $scope.increaseUpvotes = function(item){
      item.upvotes +=1
     this.item.update= function(){
        this.item.$update({title: $stateParam.title})
      }
  }

}
```
In the show controller, I am able to update all the fields and have them save to the database, so I'm not sure why the upvotes won't work on the index page?

I spent way too much time on this yesterday and I feel like I'm missing something so simple. Any suggestions?

**Comment by amaseda** [comment]
Is the problem that none of your Express routes are being triggered at all? If you put a `console.log("testing")` in them, do you see that message in the terminal window running your server after triggering an upvote in the browser?

**Comment by hschuster9** [comment]
I put console.log in the express routes and it's not doing anything so I guess they aren't being triggered by an upvote. Would that mean the routes are wrong?

**Comment by amaseda** [comment]
What happens if you change your factory definition so that `update` has a `$` before it, like so...

```js
return $resource("/api/items/:title", {}, {
    $update: {method: "PUT"}
  })
```

**Comment by hschuster9** [comment]
That prevents it from updating in the show controller. I think the issue is that on the index page, when the upvote is triggered, it doesn't have a route or method(?) to find that specific item in the database to update/save. When I console.log the upvote in the index controller:

```
function ItemIndexControllerFunction(ItemFactory, $state, $scope){
  this.items = ItemFactory.query()
  $scope.items = ItemFactory.items
  $scope.increaseUpvotes = function(item){
      item.upvotes +=1
      console.log(item)

      }
  }
```

I get: 

![screen shot 2017-04-04 at 12 17 29 pm](https://cloud.githubusercontent.com/assets/24527140/24667243/cee3c898-1930-11e7-9a40-5199e2067d7c.png)


So it is reading it, but I'm not sure how to store it with the correct route? If I manually update the value on the show controller (from an input field) it stores it to the database, but not when I update it on the index controller

I thought this route would make sense, but I'm not sure why it's not updating it:
```


app.put('/api/items', function(req, res, next){
  req.item.upvote(function(err, item){
    if(err){return next(err)}
    res.json(item)
    console.log('test')
  })

})

//also substituted this route:
//app.put('/api/items/upvote')
```

**Comment by amaseda** [comment]
I don't believe you can take one item in a collection retrieved by `.query` and call `.$update` on it.

What about if inside of the method triggered by clicking upvote, you `.get` a particular item from the database. You can then update that item with the new data (in this case, upvotes increased by 1).

From there confirm that your backend is receiving some sort of request. We can tackle defining the correct route afterwards.

**Comment by hschuster9** [comment]
Dan and I figured it out. Thanks for your help though!

**Comment by amaseda** [comment]
Good to hear! :+1:
