### ISSUE TITLE
Select Options update variable

### ISSUE THREAD

**Issue by Curtismn87** [ga-wdi-exercises/project4#46]
```
<HTML>
  <select>
  <option value="0100" id="dairy">Dairy and Egg Products</option>
  <option value="0200" id="spices">Spices and Herbs</option>
</select>

<Javascript>
this.getFoods = function(){
      var foodsURL = "http://api.nal.usda.gov/ndb/nutrients/?format=json&api_key=M4zdaQiev4SOfYzye5gC3xhVTanoFD4uKXt1TNe8&max=500&fg=2100&nutrients=205&nutrients=204&nutrients=203";
        console.log("button clicked");
        $http.get(foodsURL)
        .success(function(response){
          $scope.jsonfoods = response.report.foods;
        });
      };
```

So my API has a "food groups" category, which takes in a 4 digit number param. I assigned that number param to the value of each option. I want when that option is selected, the value is put into my foodsURL variable.

I've many many different ways. For example:

```
var foodsURL = "http://api.nal.usda.gov/ndb/nutrients/?format=json&api_key=M4zdaQiev4SOfYzye5gC3xhVTanoFD4uKXt1TNe8&max=500&fg=
+ $("select:selected).val() +
&nutrients=205&nutrients=204&nutrients=203"
```

```
var option = $("select:selected).val()
var foodsURL = "http://api.nal.usda.gov/ndb/nutrients/?format=json&api_key=M4zdaQiev4SOfYzye5gC3xhVTanoFD4uKXt1TNe8&max=500&fg=
+ option +
&nutrients=205&nutrients=204&nutrients=203"
```

I've tried grabbing them by id $("#dairy).options

I just can't get the right combination of jquery selectors and methods.

**Comment by RobertAKARobin** [comment]
What's happening that's different from what you expect? Are you getting any sort of error?

Also, I see some missing quotes. `$("select:selected).val()` should be `$("select:selected").val()`

**Comment by Curtismn87** [comment]
the values are always "undefined"?

**Comment by RobertAKARobin** [comment]
Oh. That's because `select:selected` means "Look for the `<select>` element that is selected." `<select>` is never selected; it's the `<option>` elements _inside_ `<select>` that are selected.

So you'd need to to `$("option:selected")` -- OR, because jQuery's smart, you can just do `$("select").val()`, which automatically gets the value of the `<option>` that is selected.

**Comment by Curtismn87** [comment]
$("select option:selected").val() ... uuugh! *shoots self in foot"

you were right thanks!
