### ISSUE TITLE
Rendering Display Component with Map 

### ISSUE THREAD

**Issue by SavrajSingh** [ga-wdi-exercises/project4#460]
I am not sure where to set the data that is being imported from my seeds.json. I need the array to be defined in the child ProductDisplay.js component but I have it defined in my parent App.js, is it not being seen by the child? Or do I set it as a variable in the child and go from there?

**Comment by SavrajSingh** [comment]
<img width="635" alt="screen shot 2017-04-04 at 3 34 18 pm" src="https://cloud.githubusercontent.com/assets/24595749/24675197/3f50d970-194c-11e7-8271-a81051140016.png">

**Comment by SavrajSingh** [comment]
<img width="841" alt="screen shot 2017-04-04 at 3 34 34 pm" src="https://cloud.githubusercontent.com/assets/24595749/24675203/44424e5a-194c-11e7-97a9-e88d848d1483.png">

**Comment by amaseda** [comment]
I would recommend including it in the `state` of your App component and then passing it down to whatever components need that data through their `props`.

**Comment by SavrajSingh** [comment]
Could you elaborate? Add state where?

**Comment by amaseda** [comment]
Sure! Meant in the `state` object of your App component. So in its constructor you would do something like...

```js
constructor(props){
  super(props)
  this.state = {
    products: // your products data would be referenced here
  }
}
```

**Comment by SavrajSingh** [comment]
and then remove it from after the <ProductDisplay /> or leave it there

**Comment by SavrajSingh** [comment]
im sorry man im like not getting this at all. I thought i did

**Comment by amaseda** [comment]
It's all good. So here are the steps to follow...

1. Import JSON data
2. Include it in your `App` component's `state`
3. Pass that state value down to your child component through `props`
4. Reference that data in the child component

#### Step 1

You've already taken care of (1) with `import Products from ...`

#### Step 2

```js
constructor(props){
  super(props)
  this.state = {
    products: // reference product data here
  }
}
```
> You need to replace that comment with the variable you defined at the top of the page.

#### Step 3

We know that we can pass data down to a child component via props like so...

```js
<ProductDisplay products={ data goes here } />
```

You need to replace the `data goes here` with the value you defined in state in Step 2.

#### Step 4

You can then reference data in the child component with `this.props.products`

**Comment by SavrajSingh** [comment]
Hey so I tried to do this but it is still undefined
am i missing something?

**Comment by amaseda** [comment]
What exactly is `undefined`?

**Comment by SavrajSingh** [comment]
<img width="696" alt="screen shot 2017-04-04 at 4 42 58 pm" src="https://cloud.githubusercontent.com/assets/24595749/24677746/d84f135e-1955-11e7-8c02-4172cb956f0c.png">

**Comment by SavrajSingh** [comment]
<img width="696" alt="screen shot 2017-04-04 at 4 43 23 pm" src="https://cloud.githubusercontent.com/assets/24595749/24677754/dec61ec6-1955-11e7-8d7c-6346adf5268d.png">

**Comment by SavrajSingh** [comment]
the state maybe?
<img width="360" alt="screen shot 2017-04-04 at 4 44 05 pm" src="https://cloud.githubusercontent.com/assets/24595749/24677774/f142031c-1955-11e7-9bcd-2f070096baf7.png">

**Comment by SavrajSingh** [comment]
this is the error. I dont have state defined anywhere?

**Comment by SavrajSingh** [comment]
I just want a list of products before I leave

**Comment by amaseda** [comment]
You don't need the `{}` around `Products` in state. So just do...

```js
this.state = {
  products: Products
}
```

Does that change anything?

**Comment by SavrajSingh** [comment]
no it doesnt

**Comment by amaseda** [comment]
Can you get rid of the commented-out code in `render( ){ }`? Because it's JSX it's reading that.

**Comment by SavrajSingh** [comment]
how do i set up this iterator function properly? I looked at the examples from class as well as the todo hw

   let products = this.props.products.map((product , index) => {
      
   })

**Comment by SavrajSingh** [comment]
and yes I can

**Comment by amaseda** [comment]
`.map` should return whatever you want each product to look like in your JSX/HTML. So a very simple return value would be...

```html
let products = this.props.products.map((product, i) => {
  return (
    <div>{ product.name }</div>
  )
})
```

**Comment by SavrajSingh** [comment]
right and I have that but it is showing an empty bullet point. Progress lol

**Comment by amaseda** [comment]
If you `console.log(product)` inside of `.map` but before the `return`, what do you see in the console?

**Comment by SavrajSingh** [comment]
undefined

**Comment by amaseda** [comment]
Oh, also change this...

```js
<ProductDisplay products={ Products } />
```

...to this...

```js
<ProductDisplay products={ this.state.products } />
```

We want to pass in the data in state to the child component, not the actual data from the JSON file. That's because this data's going to change and we want to keep track of it in state.

**Comment by SavrajSingh** [comment]
done. I see what it is doing.
like going to the props of App and trying to map it out

**Comment by amaseda** [comment]
A state value of `App` is becoming a props value of `ProductDisplay`.

Is it working now?

**Comment by SavrajSingh** [comment]
chyea i get that and no it isnt

**Comment by SavrajSingh** [comment]
When I log Products on the APP level I get an array with 5 objects which makes sense

**Comment by SavrajSingh** [comment]
There is a disconnect of the information between levels

**Comment by amaseda** [comment]
What do your `App` and `ProductDisplay` components look like right now?

**Comment by SavrajSingh** [comment]
I rm rf the project
starting again
talk to you guys soon

**Comment by SavrajSingh** [comment]
will keep you updated

**Comment by amaseda** [comment]
You're so close though!

**Comment by SavrajSingh** [comment]
I think so but the app is not made properly. I needed to put more thought into it

Right now I have it set up so 
Hierarchy is as follows:

App (PARENTTTTTT)

ProductConatiner(Product Parent)
ProductListing(Child of ^^)
ProductDisplay(Child of ^^? or of ProductContainer?)

Product Container will bring in the data and then pass it down.

**Comment by SavrajSingh** [comment]
No worries dude. I want to learn this proper not just have it work.

**Comment by SavrajSingh** [comment]
James sent me a ton of articles on how to think about it. :D

**Comment by amaseda** [comment]
Gotcha! Depending on the purpose of each of those product components, that hierarchy could work.

**Comment by SavrajSingh** [comment]
As per james recommendation I made a product container to hold all of the product logic? idk what it is for really

and this is what I have so far. the iterator is still not displaying the list of products. 
<img width="697" alt="screen shot 2017-04-04 at 6 44 39 pm" src="https://cloud.githubusercontent.com/assets/24595749/24682310/ff9fdc84-1966-11e7-967f-a14020e44e8b.png">
<img width="705" alt="screen shot 2017-04-04 at 6 44 49 pm" src="https://cloud.githubusercontent.com/assets/24595749/24682315/03f2747c-1967-11e7-9b56-59db3a2c231c.png">

**Comment by SavrajSingh** [comment]
Is the logic supposed to be in the product container in the render??

**Comment by SavrajSingh** [comment]
I feel like im so close man. But i want to be able to send this up to the parent so this has only the listing. but the array is defined in the console here
<img width="860" alt="screen shot 2017-04-04 at 7 39 07 pm" src="https://cloud.githubusercontent.com/assets/24595749/24683654/766e4c86-196e-11e7-8de4-e37136ab98ec.png">

**Comment by amaseda** [comment]
You need a `return` statement in `.map`. Otherwise, nothing will be saved to `let products =`.

**Comment by SavrajSingh** [comment]
<img width="924" alt="screen shot 2017-04-05 at 9 14 40 am" src="https://cloud.githubusercontent.com/assets/24595749/24707107/60d4390e-19e0-11e7-9a08-526e929ddc7f.png">

**Comment by SavrajSingh** [comment]
is this how it is supposed to be done? I want it to iterate through the data and display the name of the product in a list.

**Comment by superbuggy** [comment]
yeah `products` will just be undefined. sometimes you will see the whole expression wrapped in parentheses 
```js
let products = this.props.productsData.map((product, index)=> (
  key = {index}
  product = {productsData.name}
) )

**Comment by superbuggy** [comment]
> is this how it is supposed to be done? I want it to iterate through the data and display the name of the product in a list.

yes.

**Comment by amaseda** [comment]
The return value of `.map` should be exactly what you want the HTML/JSX of each individual product to look like.

Reference my earlier comment: https://github.com/ga-wdi-exercises/project4/issues/460#issuecomment-291627805

**Comment by SavrajSingh** [comment]
Hey so I got it to render!!!! Thanks
Im just not sure why it works lol. But progress :D 

Why do I have to wrap it in a div in the return statement of the map function? I thought that would just be setting up the data to be fed into the html in the return of the actual class?


<img width="740" alt="screen shot 2017-04-05 at 9 24 41 am" src="https://cloud.githubusercontent.com/assets/24595749/24707528/e9d3ec6c-19e1-11e7-8ca2-75dd8e3b7e1d.png">

**Comment by amaseda** [comment]
React isn't going to make assumptions about what the HTML/JSX that represents each `product` is going to look like. You have to define that yourself. We do that in `.map`. It's a combination of data and how it's going to be presented.

Sometimes we'll end up rendering a new component inside of `.map`...

```js
let products = this.props.productsData.map((product, index)=> {
  return <ProductDisplay productData={ product } />
})
```

**Comment by SavrajSingh** [comment]
righto. Ima try to move it up a level and bring it down into the product listing.

**Comment by SavrajSingh** [comment]
When you render the component inside of a map it then gains the this.props from that method correct?

**Comment by SavrajSingh** [comment]
I copied the structure from another example and it works but I am not entirely sure why

**Comment by SavrajSingh** [comment]
<img width="669" alt="screen shot 2017-04-05 at 9 46 02 am" src="https://cloud.githubusercontent.com/assets/24595749/24708411/bd19b30c-19e4-11e7-8095-4c80980dd14a.png">

**Comment by SavrajSingh** [comment]
<img width="656" alt="screen shot 2017-04-05 at 9 46 16 am" src="https://cloud.githubusercontent.com/assets/24595749/24708415/c2183fe0-19e4-11e7-833f-ef569353d04a.png">

**Comment by amaseda** [comment]
Try adding a constructor to the component. Does that fix it?

```js
constructor(props){
  super(props)
}
```

**Comment by SavrajSingh** [comment]
I dont know if there is anything to fix. It lists the names like I wanted. Just trying to understand. Can you add the constructor to the compnent like that?

**Comment by amaseda** [comment]
Oh sorry, misread before. Thought it wasn't working. Don't worry about the constructor thing then. (Although yes, any component can have a constructor. If your `ProductListing` had a state, that's where you would initialize it.)

Yes, just like when you pass data into `ProductContainer` as props, you can do the exact same thing inside of `.map`. The only difference is that now it's happening multiple times - once for each item in `productsData`

**Comment by amaseda** [comment]
Gonna close this one for now but feel free to re-open if you have more questions/comments/issues.

@SavrajSingh
