### ISSUE TITLE
Deploying a MERN app

### ISSUE THREAD

**Issue by ghost** [ga-wdi-exercises/project4#461]
I want to deploy my MERN app early (today or tomorrow) in case I run into difficulties. Will Heroku work for this? Should I deploy the front and back ends together, or should I, say, put my back end on Heroku and my front end on gh-pages? What should my file structure look like?

Obviously I'm not stuck, since I haven't tried yet, but it would be nice if you sent me in the right direction so I can burn my precious hours on problems more unique to my project.

Thanks,
Nat

**Comment by amaseda** [comment]
Yeah, you can do this with Heroku. If it's a single app then you only need Heroku. If you've separated your front-end and back-end then the latter goes on Heroku and the former on some static file hosting service.

These are good places to start...
- https://devcenter.heroku.com/articles/getting-started-with-nodejs
- https://devcenter.heroku.com/articles/mongolab

**Comment by amaseda** [comment]
Going to close this one for now but re-open if you have any questions/issues during that process.
