### ISSUE TITLE
Bring Old Web Project in the the Modern Age

### ISSUE THREAD

**Issue by laburr27** [ga-wdi-exercises/project4#463]
I FINALLY found my web project from 2003/4(!!!) that I created for a college course.  The project is on the history of recording media (8-tracks, cassette tapes, and CDs) along with fads of the respective eras.

The project was created using Netscape Composer, a WYSIWYG HTML tool.  It uses an XML structure, many HTML files, and LOTS of graphics and a few music files.  I don't even know how to get it to functionally load in Chrome...just individual html files.

My goal is to "convert" this ugly thing into a modern SPA.

Any guidance on how to tackle this would be appreciated...not looking for someone to do the work...just look at what I have and give me an option or two for approaching this.

**Comment by superbuggy** [comment]
Is there a common or shared DOM structure? If so you could structure your project according to that. If that isn't the case, I would draft a template that best fits the files you are adapting. Angular and React would be the front-end technologies for a SPA.

**Comment by superbuggy** [comment]
Closing for now!
