### ISSUE TITLE
Create the same component multiple times, number determined by user input

### ISSUE THREAD

**Issue by fanelenan7** [ga-wdi-exercises/project4#464]
How can I create a number of identical components inside of the parent component? The number of components is determined by user input. We did something similar in labs/homework, but we had an array of stuff to map through. I only have user input, not quite sure what to do.

So, if a user puts in 3 in the input box, I need 3 paragraphs printed.

**Comment by amaseda** [comment]
You could create a for loop that runs 3 times. The content of loop would add some chunk of HTML/JSX (presumably the component tag) to an array that you would then reference inside of your render method's return statement.

**Comment by superbuggy** [comment]
If you wanted to use only higher order functions you could use the Array constructor `let componentsArray = new Array(userInputNum)` and map over that array, also.

**Comment by fanelenan7** [comment]
So, I have
```
  printOutput() {
    let i = 0
    for(i = 0; i < this.state.inputNum; i++){
      return(
        <Output
          output={this.state.output}
          onFormSubmit={() => this.handleSubmit()}
        />
      )
    }
  }
```
and below it inside of render:
```
<Route
  path="/type=random"
  render={printOutput}
/>
```
and getting an error that says that {printOutput} is not defined.

**Comment by amaseda** [comment]
Think about scope here. How do you access a separate method that is attached to the component?

**Comment by superbuggy** [comment]
`this.printOutput`

**Comment by fanelenan7** [comment]
So I got the just "hello world" to print 3 times on the screen, but having issues doing the same with the component. I can console.log it 3 times, but it displays only one.

And I know it's because of render only having one {this.props.output} but how can I make it use that for loop?

```
  render() {
    console.log(this.props.output);
    return(
      <div className="outputContainer">
        <div className="output">{this.props.output}</div>
      </div>
    )
  }
```

**Comment by amaseda** [comment]
Looking at your earlier code snippet, the for loop is returning something right away (i.e., the first iteration of the loop).

What if instead, you pushed an `<Output />` to some array local to that function. Once the loop is done, it could then return that array, which presumably will have multiple component references inside of it.

**Comment by fanelenan7** [comment]
I already did that, sorry, should have put the changed version of the loop
```
  printOutput() {
    let i = 0
    let allParagraphs = []
    for(i = 0; i < 3; i++){
      allParagraphs.push(<Output
      output={this.state.output}
      onFormSubmit={() => this.handleSubmit()}
    />)
      console.log(allParagraphs);
    }
    return <div>{allParagraphs}</div>
  }
```

That returns only 1 paragraph to the page, even though console log prints 3.

**Comment by amaseda** [comment]
What about if you just return `allParagraphs` from the function? Take care of the `<div>` in your component's render method.

**Comment by fanelenan7** [comment]
<img width="304" alt="screen shot 2017-04-05 at 5 09 58 pm" src="https://cloud.githubusercontent.com/assets/21371639/24727209/394346da-1a23-11e7-8179-0f8c0aec2b86.png">
It returns the objects alright, I'm just having trouble getting them to display.

Tried to save the array of objects into the output, and it loops forever. Weird stuff.

**Comment by amaseda** [comment]
What does your render statement look like?

**Comment by fanelenan7** [comment]
Which one?

**Comment by fanelenan7** [comment]
main page
```
  render() {
    return (
      <Router>
        <div className="render">
          <nav>
            <h1><Link to="/home">Coder_Ipsum</Link></h1>
            <Link to="/home">return</Link>
            <Link to="https://github.com/fanelenan7/coder_ipsum">github</Link>
          </nav>
          <main>
            <Route
              path="/home"
              render={() => <OptionsContainer
                inputNum={this.state.inputNum}
                onFormInput={(e) => this.handleInput(e)}
              />
          // }
            }
              />
            <Route
              path="/type=random"
              render={() => this.printOutput()}
            />
            <Route
              path="/*"
              render={() => {
                return <Redirect to="/home" />
              }}
            />
          </main>
        </div>
      </Router>
    )
  }
```
form state
```
  render() {
    let inputNum = this.props.inputNum
    return(
      <div>
        <div className="options">
          <form onSubmit={(e) => this.props.onFormSubmit(e)}>

            <h2>Scaffold some lipsum</h2>
            <div><h3>Number of paragraphs</h3>

              <div className="num">
                <input type="number" placeholder="3" value={inputNum} onChange={(e) => this.props.onFormInput(e)} />
              </div>

            </div>

            <Link className="generate-button" to="/type=random"><button type="submit" id="generate">Generate</button></Link>

          </form>
        </div>
      </div>
    )
  }
```
output
```
  render() {
    console.log(this.props.output);
    return(
      <div className="outputContainer">
        <div className="output">{this.props.output}</div>
      </div>
    )
  }
```

**Comment by amaseda** [comment]
Oh, forgot that you were passing `printOutput` directly into your route's `render=`.

Assuming that is still the case, render needs to return one container (e.g., a single React component, a single `<div>`).

Instead of saying `render={this.printOutput}`, what if you did something like this...

```js
<Route
  path="/type=random"
  render={() => {
    return (
      <div>{ this.printOutput( ) }</div>
    )
  }}
/>
```

If you are no longer using this approach, let me know and we can try a different solution.

**Comment by fanelenan7** [comment]
<img width="667" alt="screen shot 2017-04-05 at 5 27 30 pm" src="https://cloud.githubusercontent.com/assets/21371639/24727863/9310bc18-1a25-11e7-94fe-840d9c1131c4.png">

**Comment by amaseda** [comment]
That actually makes sense, since each item in the array is an object.

I think the move is to create an `<OutputContainer />` component that is rendered by this `<Route>`. You can pass the collection of outputs as props. 

This component in turn will take care of rendering individual `<Output />` components using the usual `.map` strategy.

**Comment by fanelenan7** [comment]
Oh, that makes sense. I'm going to try that now.

**Comment by fanelenan7** [comment]
also, I've been digging around those objects, any tips on where to find the text itself? Those objects are huge and I have no idea where it is.

**Comment by amaseda** [comment]
What do the objects look like? Going to need an example to figure out where the text might be.

**Comment by fanelenan7** [comment]
<img width="344" alt="screen shot 2017-04-06 at 11 13 25 am" src="https://cloud.githubusercontent.com/assets/21371639/24761691/2a7c72a6-1aba-11e7-9ddd-3278287b4fc2.png">

**Comment by amaseda** [comment]
Can't tell from that, but I imagine if this is custom data then it'd be somewhere in `props`.
