### ISSUE TITLE
Data not showing on show page

### ISSUE THREAD

**Issue by kkeller93** [ga-wdi-exercises/project4#465]
Having the problem that the data is not populating on the show page but all the data will populate on the index page.

Been stuck on this problem for about a day and a half. Completely stumped as to why the data won't load.

Link to repo: https://github.com/kkeller93/expenseTracker_angular

**Comment by amaseda** [comment]
Are you able to access the data you're trying to display on the show page? Can you `console.log` it successfully in your show controller?

**Comment by superbuggy** [comment]
In your expenseShowController, you may also want to `console.log(ref)` and make sure it returns the reference URI you are expecting.

**Comment by kkeller93** [comment]
so i got the data to show now and apparently the data was just calling and trying to display the object and now i am able to display by calling on the key of the object specifically

**Comment by amaseda** [comment]
Does that mean the issue has been solved?

**Comment by superbuggy** [comment]
If not, reopen. Closing for now.
