### ISSUE TITLE
Redirect issues 

### ISSUE THREAD

**Issue by nrc0004** [ga-wdi-exercises/project4#466]
Repo: https://github.com/nrc0004/project4

I am having issues getting my page to refresh when I hit submit on the "add a new blog" form. Here is the relevant code. Also, I should note the addNew function works, I just have to refresh the page manually to get it to show up and I would like it to reload or appear as soon as I hit submit. 

```js
.controller ("BlogIndexCtrl",[
    "$state",
    "Blog",
    BlogIndexController
  ])

  .state("BlogIndex", {
    url: '/blogs',
    templateUrl: "/assets/js/ng-views/blog/index.html",
    controller: "BlogIndexCtrl",
    controllerAs: "vm"
  })
function BlogIndexController($state, Blog){
  this.blogs = Blog.query()
  this.newBlog = new Blog()
  this.create = function(){
    this.newBlog.$save().then(function(blog){
      $state.go("BlogIndex", {title: blog.title})
    })
  }
}
```

Blog Index.html 

<div class="blogBox">
  <h3 data-ng-repeat="blog in vm.blogs">
    <div class = "blogs" >
      <a class="title" data-ui-sref="show({title: blog.title})">{{blog.title}}</a>
      <p class="content">{{blog.content}}</p>
    </div>
  </h3>

    <form class="addBlog"ng-submit="vm.create()">
      <input class ="add" type="text" ng-model="vm.newBlog.title" placeholder="title" /> </br>
      <textarea type="text" ng-model="vm.newBlog.content" placeholder="Content"></textarea> </br>
      <button class ="add"  ng-click ="vm.addBlog()"> + Blog </button>
    </form>

</div>

**Comment by superbuggy** [comment]
What console error are you getting?

**Comment by superbuggy** [comment]
```js
function BlogIndexController($state, Blog){
  this.blogs = Blog.query()
  this.newBlog = new Blog()
  this.create = function(){
    this.newBlog.$save().then(function(blog){
      //add a console log (console log blog, dog) here, see if it fires
      $state.go("BlogIndex", {title: blog.title})
    })
  }
}

**Comment by nrc0004** [comment]
Nothing >.>

**Comment by nrc0004** [comment]
jk it was just slow— it is saying there is an empty response 

POST http://localhost:4000/api/blogs net::ERR_EMPTY_RESPONSE
(anonymous) @ angular.js:11630
n @ angular.js:11423
g @ angular.js:11133
(anonymous) @ angular.js:15757
$eval @ angular.js:17025
$digest @ angular.js:16841
$apply @ angular.js:17133
(anonymous) @ angular.js:24813
Pf @ angular.js:3417
d @ angular.js:3405

**Comment by superbuggy** [comment]
what response is the back end returning?

**Comment by nrc0004** [comment]
[nodemon] restarting due to changes...
[nodemon] starting `node index.js`
Listening on 4000
make some programs
(node:55075) DeprecationWarning: Mongoose: mpromise (mongoose's default promise library) is deprecated, plug in your own promise library instead: http://mongoosejs.com/docs/promises.html <http://mongoosejs.com/docs/promises.html>

**Comment by superbuggy** [comment]
You're using Express right? My thought was that the response (most likely `res`, the local variable in the callback) is sending an empty response.

**Comment by nrc0004** [comment]
I am. I'm also no longer receiving any errors, its just not redirecting. It's def capturing the data, it just isnt redirecting/ refreshing the index page so I can immediately see it.

**Comment by superbuggy** [comment]
what about that console.log from earlier, is that firing?

**Comment by nrc0004** [comment]
Its not

**Comment by nrc0004** [comment]
Got it! I just took out the state.go (...)and replaced it with $state.current, {}, {reload: true} and it works now. Thanks :)

**Comment by amaseda** [comment]
:+1:
