### ISSUE TITLE
Two models not communicating 

### ISSUE THREAD

**Issue by nrc0004** [ga-wdi-exercises/project4#467]
Repo: https://github.com/nrc0004/project4

Hello, 

I have 2 models that are related: programs and exercises. Exercises are supposed to belong to programs, however, I dont think I've wired them correctly and I'm not sure what I'm missing. Below is the relevant code: 

Models.js 
```js
const mongoose = require('./connection.js')

const Schema = mongoose.Schema
const ObjectId = Schema.ObjectId

const ProgramSchema = new mongoose.Schema({
    name: String,
    body: String,
    exercise: [{type: Schema.ObjectId, ref: "Exercise"}]
})

const ExerciseSchema = new mongoose.Schema({
    name: String,
    sets: Number,
    reps: Number
})

const BlogSchema = new mongoose.Schema ({
    title: String,
    content: String
})

const Program = mongoose.model("Program", ProgramSchema)
const Exercise = mongoose.model("Exercise", ExerciseSchema)
const Blog = mongoose.model("Blog", BlogSchema)

module.exports = {
  Program,
  Exercise,
  Blog
}

```

**Comment by amaseda** [comment]
What exactly isn't working? How do you know they're not wired up correctly?

**Comment by nrc0004** [comment]
I figured it out-- I ended up nesting the exercise model in the program model and I think that solved my issue.

**Comment by nrc0004** [comment]
Actually-- sorry, I dont think I did. I'm chatting with Nyketha now and I think we are having similar issues and she had an issue open earlier. Basically, we have nested models and the data for the nested model is in the DB, the issue is that when we call the data to be rendered on the page its not showing up.

**Comment by amaseda** [comment]
What do your schema/model definitions look like now?

**Comment by nrc0004** [comment]
So, the more I look at it, I think my issue is  they way I am trying to call the information to display on the page. Here is the model info and the ProgramShow code : 

const ExerciseSchema = new mongoose.Schema({
  name: String,
  sets: Number,
  reps: Number
})

const ProgramSchema = new mongoose.Schema({
    name: String,
    body: String,
    exercises: [ExerciseSchema]
})


============ See highlighted for where I think my issue is =========
<div ng-show="vm.program">
  <h2>Program Focus: </h2>
  <p>{{vm.program.name}}</p>
  <h2>Description:</h2>
  <p>{{vm.program.body}}</p>

</div>

  <div class ="Edisplay">
    <h2>Exercises</h2>
      **<h3 data-ng-repeat="exercise in vm.exercises">
        <p>{{exercises.name}}</p>
      </h3>**
    </div>
  </div>
</div>

<div>
  <input type="text" ng-model="vm.program.name" placeholder="Name" /></br>
  <input type="text" ng-model="vm.program.body" placeholder=" description" /> </br>
  
  <button data-ng-click="vm.update()">Update</button>
  <button data-ng-click="vm.destroy()">Remove Program from list</button>
</div>

**Comment by amaseda** [comment]
`exercises` is an array of objects, each of those objects being a singular exercise. It's each of those individual objects that have a `name` property.

So you're going to need to `ng-repeat` through those exercises and access the `name` in there.

**Comment by nrc0004** [comment]
Thanks, thats what I thought I was trying to do— currently my attempt looks like this, but I’m assuming I’m calling it wrong: 

  <div class ="Edisplay">
    <h2>Exercises</h2>
      <h3 data-ng-repeat="program in vm.programs">
        <p>{{program.exercises.name}}</p>
      </h3>
    </div>
  </div>
</div>

I also tried 


  <div class ="Edisplay">
    <h2>Exercises</h2>
      <h3 data-ng-repeat=“exercise in vm.exercises">
        <p>{{program.exercises.name}}</p>
      </h3>
    </div>
  </div>
</div>

**Comment by amaseda** [comment]
You can say `exercise.name` instead of `program.exercises.name`. The ng-repeat gives you access to that `exercise` value.

**Comment by nrc0004** [comment]
Just tried it and still no dice. Here is the updated repo if you want to see it: 

https://github.com/nrc0004/project4 <https://github.com/nrc0004/project4>

public>js>ng-views> program>show.html

**Comment by amaseda** [comment]
It should be `exercise` singular, not `exercises` plural. Right now you have the following...

```html
<h3 data-ng-repeat="exercise in vm.exercises">
  <p>{{exercises.name}}</p>  <!-- make this singular -->
</h3>
```

**Comment by nrc0004** [comment]
Nothing T_T

Also, when I include the input both for exercises, It doesn’t auto populate like the program name and description do. Not sure if that is helpful. I’ve tried playing with the ng-model I’m using for that but haven’t had any luck. I was hoping if I could get that to populate with something from the exercise array that would point me in the right direction for ng-repeat.

**Comment by amaseda** [comment]
Is this the controller associated with this view?

```js
function showController($state, $stateParams, Program){
  this.program = Program.get({name: $stateParams.name})
  this.update = function(){
    this.program.$update({name: $stateParams.name})
  }
  this.destroy = function(){
    this.program.$delete({name: $stateParams.name}).then(function(){
      $state.go("index")
    })
  }
```

If so, I don't see `this.exercises` defined anywhere. You need to update your `ng-repeat` statement so that the right side of the statement references the collection of exercises. Are they stored in `this.program.exercises` by any chance?

**Comment by amaseda** [comment]
Any progress here?

**Comment by nrc0004** [comment]
Hey Adrian-- that was this issue, thank you!

**Comment by amaseda** [comment]
Excellent! Closing but feel free to re-open if you have more questions.
