### ISSUE TITLE
Can't add posts

### ISSUE THREAD

**Issue by bgalladian** [ga-wdi-exercises/project4#470]
Having trouble adding new posts, can't even console.log.  No errors, and preventdefault isn't even working.  Here is the repository:

https://github.com/bgalladian/kickSStarter2

and the tutorial I am using:

https://github.com/bryantheastronaut/mernCommentBox

**Comment by superbuggy** [comment]
Where is this in your codebase?

**Comment by bgalladian** [comment]
It's in my DesignBox and my DesignForm in the src folder...post works in postman

**Comment by superbuggy** [comment]
you a `catch` method for error handling, but no `.then()`

add this in between `axios.post()` and `.catch()`
```js
 .then(function (response) {
    console.log(response);
  })
```

**Comment by bgalladian** [comment]
errr where exactly?

**Comment by superbuggy** [comment]
in one of the two files you mentioned 😉

**Comment by superbuggy** [comment]
The reason I'm being cheeky is because with remote issues-based workflows, one should include specific line-of-code numbers in specific files.

**Comment by bgalladian** [comment]
duuuuude...lol

**Comment by superbuggy** [comment]
lol did that work tho?

**Comment by bgalladian** [comment]
im trying it now, but should i delete code i already have in there to test it out?

**Comment by superbuggy** [comment]
also testing w/ postman was a good call

**Comment by superbuggy** [comment]
just insert that `then` like so

> [from axios docs](https://github.com/mzabriskie/axios)

```js
// Make a request for a user with a given ID
axios.get('/user?ID=12345')
  .then(function (response) {
    console.log(response);
  })
  .catch(function (error) {
    console.log(error);
  });

```

**Comment by bgalladian** [comment]
i got nothing, page still reloads despite preventdefault

**Comment by superbuggy** [comment]
can you reference line numbers/files?

**Comment by superbuggy** [comment]
either that or include code snippets

**Comment by bgalladian** [comment]
oh yeah...i should get in the habit of doing that 
```js
//DesignBox.js
handleDesignSubmit(design) {
  let designs = this.state.data;
  design.id = Date.now();
  let newDesigns = designs.concat([design]);
  this.setState({ data: newDesigns });
  axios.post(this.props.url, design)
    .then(function (response) {
      console.log(response);
      this.setState({ data: design });
    });
}

//DesignForm.js
handleSubmit(e) {
   e.preventDefault();
   let designer = this.state.designer.trim();
   let text = this.state.text.trim();
   if (!text || !designer) {
     return;
   }
   this.props.onDesignSubmit({ designer: designer, text: text})
   this.setState({ designer: '', text:''})
 }

  render() {
    return(
      <form>
        <input
          type='text'
          placeholder='Your Name'
          value={ this.state.designer }
          onChange={this.handleDesignerChange } />
        <input
          type='text'
          placeholder='Your Comment'
          value={ this.state.text }
          onChange={this.handleTextChange } />
        <input
          type='submit'
          value="Post" />
      </form>
    )
  }
}
```
EDIT: this did not render the way i wanted it to

**Comment by superbuggy** [comment]
no `e.preventDefault()` present

```js
handleDesignSubmit(design) {
  let designs = this.state.data;
  design.id = Date.now();
  let newDesigns = designs.concat([design]);
  this.setState({ data: newDesigns });
  axios.post(this.props.url, design)
    .then(function (response) {
      console.log(response);
      this.setState({ data: design });
    });
}
```

**Comment by bgalladian** [comment]
Nothing happened.

**Comment by superbuggy** [comment]
```js
        <input
          type='submit'
          value="Post" />
```
you haven't attached your submission-handling function here.

**Comment by bgalladian** [comment]
Is it me, or does this tutorial suck?

**Comment by superbuggy** [comment]
In the tutorial, that handler is actually on the form element, rather than the input. You could use onClick as well. 

If you're hitting a wall, or are having trouble concentrating due to frustration, I'd take a break.

**Comment by bgalladian** [comment]
i got it working...the thing that sucks is that i wont have time to work tomorrow, so i gotta do as much as i can today.  thanks for the help james! I'll see you on the next issue! lol

**Comment by superbuggy** [comment]
glad you got it working. hang in there!

**Comment by superbuggy** [comment]
A 5 min break is still a break; fairly often one doesn't need more than that. You can get up and walk around, clear your head, and avoid *actively* thinking about code.
