### ISSUE TITLE
How to set up a listing based off of axios request

### ISSUE THREAD

**Issue by SavrajSingh** [ga-wdi-exercises/project4#472]
So I can get and post onto my backend. The problem is setting the state of the key value pair that is being iterated to set up the listing. I have the following code but it does not populate the array properly. Then I tried to set a function to set the state of the component. Any ideas/suggestions??????
<img width="576" alt="screen shot 2017-04-05 at 4 11 35 pm" src="https://cloud.githubusercontent.com/assets/24595749/24724835/97fecc5c-1a1a-11e7-8f63-2ef81d596a40.png">

**Comment by amaseda** [comment]
What should I be looking at in this screenshot? The axios call at the top or bottom?

And when you say it doesn't populate the "array", is that the array at the top or an array in state?

**Comment by amaseda** [comment]
Did you see my earlier note? Any progress here?

**Comment by amaseda** [comment]
Going to close this one for now but plz re-open if you have any questions/comments/issues.

@SavrajSingh
