### ISSUE TITLE
Redirect for React create with Axios

### ISSUE THREAD

**Issue by evalaidc** [ga-wdi-exercises/project4#473]
I'm trying to get redirect after clicking... but it's not really working. I have tried `window.location.href()` (as seen below) and `window.location.replace()` to try to redirect it, however it's not working. Any suggestions? It also has a really slow layover time, when I click create, it takes a good 30seconds to a minute for the api to get the response. Is that normal?

```js
addNewSpot(e) {
    e.preventDefault();
    let author = this.state.author.trim();
    let blurb = this.state.blurb.trim();
    let title = this.state.title.trim();
    let photo_url = this.state.photo_url.trim();
    let longitude = this.state.longitude;
    let latitude = this.state.latitude;

    axios.post("http://localhost:3101/api/spots/new", {title, blurb, author, photo_url, longitude, latitude})
    .then(res => {
      window.location.href = '/spots'

      this.setState({
        author: '',
        blurb: '',
        photo_url: '',
        title: '',
        longitude: 0,
        latitude: 0
      })
    })
    .catch((err) => {
      console.log(err)
    })

  }
```

**Comment by superbuggy** [comment]
30 seconds seems pretty long. What is going with your application's back-end?

**Comment by evalaidc** [comment]
Mongoose, Express, but It was probably just a slow connection earlier. it seems like the only problem is now the redirect/reload

**Comment by superbuggy** [comment]
Are you using `react-router`?

**Comment by evalaidc** [comment]
yes, and the new creations are being created but anything after the axios.post is not running.

```
 axios.post("http://localhost:3101/api/spots/new", {title, blurb, author, photo_url, longitude, latitude})
    .then(res => {
      window.location.href = '/spots'

      this.setState({
        author: '',
        blurb: '',
        photo_url: '',
        title: '',
        longitude: 0,
        latitude: 0
      })
    })
    .catch((err) => {
      console.log(err)
    })
```

**Comment by superbuggy** [comment]
I'm wondering if your backend isn't responding. Andy is replying with a specific approach for react-router

**Comment by AndyWhitley** [comment]
You will need to have state be updated with some sort of boolean (maybe `hasPosted` ?) set to true. Then, because `render` will be called anytime state is updated, you need to intercept the render method of the relevant component to render react router's `Redirect` component instead of the standard component:

```js
render() {
  if(this.state.hasPosted) {
    return <Redirect to='/url' />
  }
  
  return (
    // regular jsx
  )
}
```

**Comment by AndyWhitley** [comment]
https://reacttraining.com/react-router/web/example/auth-workflow

**Comment by evalaidc** [comment]
Thanks @AWhitleyGA & @superbuggy. I just removed the   ` e.preventDefault();` and it redirected.
