### ISSUE TITLE
help me out of callback/promise hell

### ISSUE THREAD

**Issue by atflick** [ga-wdi-exercises/project4#475]
Alright, so this will probably be pretty lengthy:

To try to summarize, in one of my page controllers I have multiple DB queries to fetch data from my MedicalPlan model based on different categories (employer size, industry and region).  This brings back different sets of arrays of data.  I then instantiate a class object for each data set which calculates the averages of all the data I actually want.  My class objects are working and getting back what I want, but the problem is I am then trying to call another method after this that pushes my data to an array in the format I need for my bar graphs to display the data.  

The problem I am running into, is that this second method seems to be calling before my queries bring back the data so it is just pushing undefined to my barchart data:

here is my first method that queries the db and instantiates the class objects
```
  this.updateData = () => {
    CategoryFactory.query({
      type: this.activePlan.type,
      category: "employer.size",
      subcategory: this.employer.size
    }, (res) => {
      this.sizeData = new MedicalPlanData(res)
      // console.log(this.sizeData); these console logs come back with the correct data I want
    })
    CategoryFactory.query({
      type: this.activePlan.type,
      category: "employer.industry",
      subcategory: this.employer.industry
    }, (res) => {
      this.industryData = new MedicalPlanData(res)
      // console.log(this.industryData);
    })
    CategoryFactory.query({
      type: this.activePlan.type,
      category: "employer.region",
      subcategory: this.employer.region
    }, (res) => {
      this.regionData = new MedicalPlanData(res)
      // console.log(this.regionData);
    })
  }
```

then this should call after the above runs
```
  this.updateGraphData = (sizeData, industryData, regionData) => {

    let plansArr = [this.activePlan, sizeData, industryData, regionData]
    plansArr.forEach((plan) => {
      let singlePlanArr = []
      singlePlanArr.push(plan.office, plan.specialist, plan.uc, plan.er)
      this.barData.series.push(singlePlanArr)
      singlePlanArr = []
      singlePlanArr.push(plan.ded_ee, plan.ded_f, plan.oop_ee, plan.oop_f)
      this.barTwoData.series.push(singlePlanArr)
    })
    console.log(this.barData.series);
  }
```

to top it off this is all called within a callback (lol)
```
  this.medPlans = ErMedicalFactory.query({id: $stateParams.id}, (res) => {
    this.activePlan = res[0]
    this.updateData()
    this.updateGraphData(this.sizeData, this.industryData, this.regionData)
  })
```

I feel like I need a promise or callback AFTER `updateData()` runs.. but I can't get it to work.

plz help.
I'm out in the student area if you want to talk about it...

**Comment by amaseda** [comment]
Just chatted IRL. Closing for now but if you have any questions/issues with the approaches we discussed, re-open this!
