### ISSUE TITLE
Twitter API

### ISSUE THREAD

**Issue by HabRonan** [ga-wdi-exercises/project4#476]
I have tried using ajax using this-https://dev.twitter.com/rest/public/search  documentation. but I am getting this error-
```Response to preflight request doesn't pass access control check: No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'http://localhost:3001' is therefore not allowed access. The response had HTTP status code 400.```

Another method used other than .ajax request - 
I have tried this method I found online and I can see it logging the result but I can't access outside the function for some reason. check the last function - callTwitter() 
```js
var https = require('https');
var headers = {
  'User-Agent': 'Coding Defined',
  Authorization: 'bearer ' + require('./oauth.json').access_token
};

function jsonHandler(response, callback) {
  var json = '';
  response.setEncoding('utf8');
  if(response.statusCode === 200) {
    response.on('data', function(chunk) {
      json += chunk;
    }).on('end', function() {
     callback(JSON.parse(json));
    });
  } else {
    console.log('Error : ' + response.statusCode);
  }
}
var trendOptions = {
  host: 'api.twitter.com',
  path: '/1.1/trends/place.json?id=1', // id = 1 for global trends
  headers: headers
}

var tweetDetails = {
  maxresults: 10,
  resultType: 'recent', // options are mixed, popular and recent
  options: {
    host: 'api.twitter.com',
    headers: headers,
  }
}

function fullTweetPath(query) {
  var path = '/1.1/search/tweets.json?q=%23Adventure'
  + '&count=' + tweetDetails.maxResult
  + '&include_entities=true&result_type=' + tweetDetails.resultType;

  tweetDetails.options.path = path;
}


function callTwitter(options, callback){
  https.get(options, function(response) {
    jsonHandler(response, callback);
  }).on('error', function(e) {
    console.log('Error : ' + e.message);
  })
}

callTwitter(trendOptions, function(trendsArray) {
  fullTweetPath(trendsArray[0].trends.query)
  callTwitter(tweetDetails.options, function(tweetObj) {
    tweetObj.statuses.forEach(function(tweet) {
     console.log('\n' + tweet.user.screen_name + ' : ' + tweet.text);
    })
  })
});
```

**Comment by amaseda** [comment]
Is the `console.log` of the result in `callTwitter( )`?

If that data is local to `callTwitter( )`'s scope, you need to send it out of the function somehow. Some options...
- `return` it from the function
- Define a variable in a higher scope and store the result in there

**Comment by HabRonan** [comment]
I am gonna try that

**Comment by HabRonan** [comment]
I used return for tweetObj, tweet but it's not working

ReferenceError: tweetObj is not defined
ReferenceError: tweet is not defined

**Comment by amaseda** [comment]
How/where are you doing that?

**Comment by HabRonan** [comment]
```js
callTwitter(trendOptions, function(trendsArray) {
  fullTweetPath(trendsArray[0].trends.query)
  callTwitter(tweetDetails.options, function(tweetObj) {
    tweetObj.statuses.forEach(function(tweet) {
     console.log('\n' + tweet.user.screen_name + ' : ' + tweet.text);
     return tweet
    })
  })
});
```

console.log(tweet)

**Comment by amaseda** [comment]
You can't return from inside of the `.forEach` callback. Well, you can, but it won't do anything.

You need to return it from the root level of the function. You may need to define an empty variable at the start of `callTwitter` and then give it a value inside of `.forEach`.

**Comment by HabRonan** [comment]
```
callTwitter(trendOptions, function(trendsArray) {
  var array = []
  fullTweetPath(trendsArray[0].trends.query)
  callTwitter(tweetDetails.options, function(tweetObj) {
    tweetObj.statuses.forEach(function(tweet) {
     console.log('\n' + tweet.user.screen_name + ' : ' + tweet.text);
     array.push(tweet.user.screen_name)
    })
  })
});
console.log(array)
```
without the console.log it doesn't error out but with the console.log it says it doesn't array is undefined

**Comment by amaseda** [comment]
You would need to do something like one of the following two options...

```js
callTwitter(trendOptions, function(trendsArray) {
  var array = []    // define variable at start of function
  fullTweetPath(trendsArray[0].trends.query)
  callTwitter(tweetDetails.options, function(tweetObj) {
    tweetObj.statuses.forEach(function(tweet) {
     console.log('\n' + tweet.user.screen_name + ' : ' + tweet.text);
     array.push(tweet.user.screen_name)    // push to variable
    })
  })
  return array    // return variable from root level of function
});
console.log(callTwitter( ... ))  // logging the return value of the above function
```

...or...

```js
var array = []    // define variable in higher scope
callTwitter(trendOptions, function(trendsArray) {
  fullTweetPath(trendsArray[0].trends.query)
  callTwitter(tweetDetails.options, function(tweetObj) {
    tweetObj.statuses.forEach(function(tweet) {
     console.log('\n' + tweet.user.screen_name + ' : ' + tweet.text);
     array.push(tweet.user.screen_name)    // modify variable defined in higher scope
    })
  })
});
console.log(array)    // console.log the same variable
```

**Comment by HabRonan** [comment]
it is an empty array = []

**Comment by amaseda** [comment]
Oh, realizing now that this function is being called recursively. That might be re-initializing the array as empty each time you go through the function.

Does the second approach I outlined work? It's not ideal, but might get your code working for now.

Otherwise, you can modify `callTwitter` so it also accepts an argument that will contain the array that is being pushed to.

**Comment by HabRonan** [comment]
the first is not working, the second is the one which is giving the empty array

**Comment by amaseda** [comment]
Is this in the global scope? Or is it possible that `var array = [ ]` is being run multiple times?

**Comment by HabRonan** [comment]
yes, in the global scope.

**Comment by amaseda** [comment]
Closing this for now since we talked about it IRL, but feel free to re-open if you have any more questions/comments.
