### ISSUE TITLE
Conditionally load route on page load

### ISSUE THREAD

**Issue by fanelenan7** [ga-wdi-exercises/project4#478]
If I have refreshed the page in the state that requires user input from another state before it can render stuff on it, it craps out. How can I attach a conditional to it so it loads the state with the input field if the page loads on the wrong state?

**Comment by amaseda** [comment]
Hmm, not sure if I understand the question. Would it be possible to pseudo code this? Maybe wrap the code that you want to render conditionally in an if statement. I think that'll help paint a picture.

**Comment by fanelenan7** [comment]
If I reload the page where the paragraphs are generated, the number is null. And nothing at all shows up because React freaks out. I want in to load the root page if the page was reloaded.

**Comment by superbuggy** [comment]
I would instead pass this data via a container and functions passed down to child components.
