### ISSUE TITLE
jquery addClass is adding too many classes in iteration

### ISSUE THREAD

**Issue by adrianshep** [ga-wdi-exercises/project4#48]
Using .addClass to define font red, yellow and green status colors for li's. According to console, status color classes are initially added correctly, but then the iteration adds the other, inappropriate status color classes to most (but not all) of the li's. I cannot figure out why this is happening.

``` js
for (var i=0; i<$.csv.toObjects(response).length; i++) {
  $('.kwslist').append("<li>" + "" + ($.csv.toObjects(response)[i].Differential) + " " + ($.csv.toObjects(response)[i].Keyword) + "</li>");
  if (parseFloat(($.csv.toObjects(response)[i].Differential)) > 1.10) {
    $("li").addClass("red"); }
  else if (parseFloat(($.csv.toObjects(response)[i].Differential)) > 0.90){
    $("li").addClass("yellow");
  }else{
    $("li").addClass("green");
  }
}
```

**Comment by RobertAKARobin** [comment]
ARGH! What completely un-semantcally-named classes! Call them "low", "medium", and "high", or anything other than these. What if you decide you want them to be blue, green, and purple or something?!

Also: indent.

Also: running `toObjects` so many times is very inefficient: you're doing it four times on each iteration when you only need to do it once:

``` js
var csvObjects = $.csv.toObjects(response);
var objectsCount = csvObjects.length;
var csv, diff, val, keyword, i;
for (i = 0; i< objectsCount; i++) {
  csv = csvObjects[i];
  diff = csv.Differential;
  keyword = csv.Keyword;
  val = parseFloat(diff);
  $('.kwslist').append("<li>" + (diff) + " " + (keyword) + "</li>");
  if (val > 1.10) {
    $("li").addClass("low"); }
  else if (val > 0.90){
    $("li").addClass("medium");
  }else{
    $("li").addClass("high");
  }
}
```

Re-organize your code and then try running it again.

**Comment by adrianshep** [comment]
Thanks; trying reorg now.

**Comment by adrianshep** [comment]
So, I've reorganized using your code above and I'm still getting the same problem, which is the initially added class is correct, but in the case of the first 8 of the 10 keywords additional classes are being added.

**Comment by RobertAKARobin** [comment]
That's OK! Your code is easier to read now.

Please try console.logging everything inside each iteration to see what changes. For example:

``` js
var csvObjects = $.csv.toObjects(response);
var objectsCount = csvObjects.length;
var csv, diff, val, keyword, i;
for (i = 0; i< objectsCount; i++) {
  csv = csvObjects[i];
  diff = csv.Differential;
  keyword = csv.Keyword;
  val = parseFloat(diff);
  console.dir([i, objectsCount, csv, diff, keyword, val]);
  $('.kwslist').append("<li>" + (diff) + " " + (keyword) + "</li>");
  if (val > 1.10) {
    $("li").addClass("low"); }
  else if (val > 0.90){
    $("li").addClass("medium");
  }else{
    $("li").addClass("high");
  }
}
```

There may be something unexpected in there.

**Comment by adrianshep** [comment]
Thanks, will do.

**Comment by adrianshep** [comment]
I've run the iterations and examined the logs and am not seeing anything that's unexpected or could be read incorrectly.
