### ISSUE TITLE
MEAN App deployment error

### ISSUE THREAD

**Issue by dlin2102** [ga-wdi-exercises/project4#484]
I'm trying to deploy my app to heroku and I keep getting this error:

$ git push heroku master
Counting objects: 222, done.
Delta compression using up to 4 threads.
Compressing objects: 100% (204/204), done.
Writing objects: 100% (222/222), 238.54 KiB | 0 bytes/s, done.
Total 222 (delta 83), reused 0 (delta 0)
remote: Compressing source files... done.
remote: Building source:
remote: 
remote: -----> Failed to detect app matching https://codon-buildpacks.s3.amazonaws.com/buildpacks/heroku/nodejs.tgz buildpack
remote:        More info: https://devcenter.heroku.com/articles/buildpacks#detection-failure
remote: 
remote:  !     Push failed
remote: Verifying deploy...
remote: 
remote: !	Push rejected to partners-app.
remote: 
To https://git.heroku.com/partners-app.git
 ! [remote rejected] master -> master (pre-receive hook declined)
error: failed to push some refs to 'https://git.heroku.com/partners-app.git'

I've set my buildpack to nodejs but its not finding it?

**Comment by amaseda** [comment]
Have you gone through this? If not, it might help with the error you're getting. If you already have, let me know and we can keep troubleshooting.

https://devcenter.heroku.com/articles/getting-started-with-nodejs#introduction

**Comment by dlin2102** [comment]
I went through it but I can't get past pushing my heroku.

**Comment by superbuggy** [comment]
Think you solved this, reopen if necessary.
