### ISSUE TITLE
Loop trouble

### ISSUE THREAD

**Issue by ghost** [ga-wdi-exercises/project4#488]
Good morning Andy,

I am having an issue with a for loop.
The array at the bottom of this issue is a collection of arrays. Each array has a letter as its first element, an a collection of arrays with two elements in them: [x, y], where x represents depth, and y represents time.
If an array has the exact values for x and y, I can successfully log the the letter from the array that contains the array [x, y], like so:

```js
for (var i = 0; i < tableOne.length; i++) {
  for (var j = 1; j < tableOne[i].length; j++) {
    if (tableOne[i][j][0] == x && tableOne[i][j][1] == y) {
      console.log("Pressure Group " + tableOne[i][0]);
    } 
  }
}
```

For example:
let x = 60;
let y = 39;
logs: Pressure Group "P".

What I want to accomplish is the ability to give values that are not exact. For example if I give x the value of 55, which is non existent on the array, I should round to the next grater value, in this case 60, and do the same thing logic as previous. I am looking for the program to find only the one array with the values for x and y, but it logs all the arrays where there is an x with that value, and a y with that value, even though they are not one unique pair.

For example:
When I try to run this updated code to round x to the grater value:
let x = 55;
let y = 35;

```js
for (var i = 0; i < tableOne.length; i++) {
  for (var j = 1; j < tableOne[i].length; j++) {
    if (tableOne[i][j][0] == x && tableOne[i][j][1] == y) {
      console.log("Pressure Group " + tableOne[i][0]);
    } else if (tableOne[i][j][0] > x && tableOne[i][j][1] == y) {
      console.log("Pressure Group " +tableOne[i][0])
    }
  }
}
```

It logs Pressure Groups "N" and "Q", because those arrays contain those values, even though they are not a pair. I am trying to log only the one array that contains those values for x and y.

```js
let allThis = [
  ["M", [35, 67], [40, 55], [50, 41], [60, 33], [70, 27], [80, 23], [90, 21], [100, 18], [110, 16]],
  ["N", [35, 73], [40, 60], [50, 44], [60, 35], [70, 29], [80, 25], [90, 22], [100, 19]],
  ["O", [35, 79], [40, 64], [50, 47], [60, 37], [70, 31], [80, 26], [90, 23], [100, 20]],
  ["P", [35, 85], [40, 69], [50, 50], [60, 39], [70, 33], [80, 28], [90, 22]],
  ["Q", [35, 92], [40, 74], [50, 53], [60, 42], [70, 35], [80, 29], [90, 25]],
  ["R", [35, 100], [40, 79], [50, 57], [60, 44], [70, 36], [80, 30]],
  ["S", [35, 108], [40, 85], [50, 60], [60, 47], [70, 38]],
  ["T", [35, 117], [40, 91], [50, 63], [60, 49], [70, 40]],
  ["U", [35, 127], [40, 97], [50, 67], [60, 52]],
  ["V", [35, 139], [40, 104], [50, 71], [60, 54]],
  ["W", [35, 152], [40, 111], [50, 75], [60, 55]],
  ["X", [35, 168], [40, 120], [50, 80]],
  ["Y", [35, 188], [40, 129]],
  ["Z", [35, 205], [40, 140]]
]
```

I hope I explain myself well. Please let me know if you have any questions...

**Comment by ghost** [comment]
Sorry, one mistake...
Lets name the array tableOne instead of allThis

**Comment by andresmaria** [comment]
If I tried putting a break statement, but it logs the same results.

`for (var i = 0; i < tableOne.length; i++) {
  for (var j = 1; j < tableOne[i].length; j++) {
    if (tableOne[i][j][0] == x && tableOne[i][j][1] == y) {
      console.log("Pressure Group " + tableOne[i][0]);
    } else if (tableOne[i][j][0] > x && tableOne[i][j][1] == y) {
      console.log("Pressure Group " +tableOne[i][0])
      **break**
    }
  }
}`

**Comment by ghost** [comment]
I tried to break statement, but it logs the same results:

`for (var i = 0; i < tableOne.length; i++) {
  for (var j = 1; j < tableOne[i].length; j++) {
    if (tableOne[i][j][0] == x && tableOne[i][j][1] == y) {
      console.log("Pressure Group " + tableOne[i][0]);
    } else if (tableOne[i][j][0] > x && tableOne[i][j][1] == y) {
      console.log("Pressure Group " +tableOne[i][0])
      break
    }
  }
}`

**Comment by juancgarcia** [comment]
An aside, when submitting comments with multi-line code blocks use this style to keep formatting and indentation:
<pre>
```js
//code goes here 
```
</pre>
replace `js` on the first line with `rb` if your code is ruby instead
(* I've taken the liberty to update your original question)

**Comment by ghost** [comment]
Thank you Juan

**Comment by juancgarcia** [comment]
@andresmaria Can you give me some more information about what you want your app to do here. If I can understand the purpose from a user's perspective I think I might have a better chance at helping you get past this.

**Comment by ghost** [comment]
Bellow is array tableOne. This array itself contains 7 arrays. Each of those arrays contain arrays in the format [x, y].

```js
let tableOne = [
  ["A", [35, 10], [40, 9], [50, 7], [60, 6], [70, 5], [80, 4], [90, 4], [100, 3], [110, 3], [120, 3], [130, 3]],
  ["B", [35, 19], [40, 16], [50, 13], [60, 11], [70, 9], [80, 8], [90, 7], [100, 6], [110, 6], [120, 5], [130, 5], [140, 4]],
  ["C", [35, 25], [40, 22], [50, 17], [60, 14], [70, 12], [80, 10], [90, 9], [100, 8], [110, 7], [120, 6], [130, 6], [140, 5]],
  ["D", [35, 29], [40, 25], [50, 19], [60, 16], [70, 13], [80, 11], [90, 10], [100, 9], [110, 8], [120, 7], [130, 7], [140, 6]],
  ["E", [35, 32], [40, 27], [50, 21], [60, 17], [70, 15], [80, 13], [90, 11], [100, 10], [110, 9], [120, 8], [140, 7]],
  ["F", [35, 36], [40, 31], [50, 24], [60, 19], [70, 16], [80, 14], [90, 12], [100, 11], [110, 10], [120, 9], [130, 8], [140, 8]],
  ["G", [35, 40], [40, 34], [50, 26], [60, 21], [70, 18], [80, 15], [90, 13], [100, 12], [110, 11], [120, 10], [130, 9]],
```
with the following code I can loop through the array and log any array element that is included in tableOne.

```js
for (var i = 0; i < tableOne.length; i++) {
  for (var j = 1; j < tableOne[i].length; j++) {
    if (x == tableOne[i][j][0] && y == tableOne[i][j][1]) {
      console.log(tableOne[i][j]);
    }
  }
}
```
For example: 
If I want to get the second array '[40, 9] from the first array:
If I let x = 40, and y = 9, I get the array that contains both of those numbers: [40, 9].

The problem I am having is that I want to be able to find that same array when I enter a value for x that is not in the tableOne array. For example, If I let x = 36, and y = 9, I know there is no value x of 36, but I want to round to the nearest grater value, 40, and then find the array [40, 9].

**Comment by AndyWhitley** [comment]
Hi Andres, I see what you are trying to do by iterating through all of the arrays (and their set of possible coordinates) to match a given depth and time to a pressure level. My question is whether or not there is an existing mathematical formula that could be made into a function that would do this for you (i.e. one that would take in a depth and time and returns back something that could be compared to some scale to determine pressure level)?

**Comment by AndyWhitley** [comment]
For the logic you are using now, the base to find the level would look something like this:
```js
let tableOne = [
  ["M", [35, 67], [40, 55], [50, 41], [60, 33], [70, 27], [80, 23], [90, 21], [100, 18], [110, 16]],
  ["N", [35, 73], [40, 60], [50, 44], [60, 35], [70, 29], [80, 25], [90, 22], [100, 19]],
  ["O", [35, 79], [40, 64], [50, 47], [60, 37], [70, 31], [80, 26], [90, 23], [100, 20]],
  ["P", [35, 85], [40, 69], [50, 50], [60, 39], [70, 33], [80, 28], [90, 22]],
  ["Q", [35, 92], [40, 74], [50, 53], [60, 42], [70, 35], [80, 29], [90, 25]],
  ["R", [35, 100], [40, 79], [50, 57], [60, 44], [70, 36], [80, 30]],
  ["S", [35, 108], [40, 85], [50, 60], [60, 47], [70, 38]],
  ["T", [35, 117], [40, 91], [50, 63], [60, 49], [70, 40]],
  ["U", [35, 127], [40, 97], [50, 67], [60, 52]],
  ["V", [35, 139], [40, 104], [50, 71], [60, 54]],
  ["W", [35, 152], [40, 111], [50, 75], [60, 55]],
  ["X", [35, 168], [40, 120], [50, 80]],
  ["Y", [35, 188], [40, 129]],
  ["Z", [35, 205], [40, 140]]
]

function findPressureLevel(depth, time) {
  let pressureLevel = tableOne.find((level) => {
    for(let i = 1; i < level.length ; i++) {
      if(compareArrays(level[i], [depth, time])) {
        return true
      }
    }
    return false
  })
  return pressureLevel[0]
}

function compareArrays(searchArray, matchArray) {
  return searchArray[0] === matchArray[0] && matchArray[1] === searchArray[1]
}

```

**Comment by AndyWhitley** [comment]
However, if you need to allow for non-exact numbers, I would suggest doing two things:
1. Control user input to make sure depth entered is in an increment of 5
2. For the time, we can adjust the compareArrays function to find the first one where the searched depth exceeds the matched depth:

```js
function compareArrays(searchArray, matchArray) {
  return searchArray[0] === matchArray[0] && searchArray[1] >= matchArray[1]
}
```

**Comment by AndyWhitley** [comment]
Let me know if this answers your question

**Comment by jsm13** [comment]
I'd do a little massaging of the data structure so that you can do something like this
```javascript
// helper
function sortNumber(a,b) {
    return a - b;
}

// data elided for brevity 
const alphabet = ['A', 'B', 'C', ...]

const timeByDepth = {
  35: [10, 19, 25, ...],
  40: [9, 16, ...]
  ...
}

function getLevel(desiredDepth, desiredTime) {
  const depths = Object.keys(timeByDepth).sort(sortNumber) // see 1. bellow
  const depthLevel = depths.find(depth => depth >= desiredDepth)
  if (depthLevel === undefined) throw "DANGER, too deep!"
  const levelIndex = timeByDepth[depthLevel].findIndex(time => time >= desiredTime)
  if (levelIndex === -1) throw "DANGER, too long!"
  return alphabet[levelIndex] // see 2. bellow
}

```

1. javascript sorts alphabetically by default so need to explicitly say how to sort. https://stackoverflow.com/a/1063027. We need to sort in the first place because Object.keys is not guaranteed to give you keys in the correct order. The resulting array will be `[35, 40, 50, ...]`

2. instead of hardcoding the alphabet, you can take advantage of [ASCII codes](http://ee.hawaii.edu/~tep/EE160/Book/chap4/subsection2.1.1.1.html) and `return String.fromCharCode(65 + levelIndex)`

**Comment by ghost** [comment]
This table was the result of empirical experiments done by the US navy in The Puget Sound. They sent some guys to different depths and measured their nitrogen levels.
I tried looking for an algorithm online, but I found very difficult mathematical concepts, even Henry's laws!
I will study your suggestions,
Thank you very much.
