### ISSUE TITLE
accessing nested routes when skipping over one view

### ISSUE THREAD

**Issue by wjpurdum** [ga-wdi-exercises/project4#491]
Having trouble rendering json for a nested route view when I've skipped over the "index" page of the nested collection. 

In the route below, I don't have a corresponding view page for frameworks so it can't pick up a :title for the show page. How can I access it using Angular on the front end, and then pass it on to Node so it knows what JSON to render for the view?

Thank you!
```js
  app.get("/api/ends/:type/frameworks/:title", (req, res) => {
      	Framework.find({frameworks: req.params.end.frameworks}).then(function(end){
          res.json(end);
          })
      	});
```

**Comment by AndyWhitley** [comment]
Hi Whitney, could you please put a code snippet of the code that is sending the request from your front-end and a link to your Github repo?

**Comment by wjpurdum** [comment]
Ah, sorry Andy!

```js
function FrameworkShowControllerFunction($state, $stateParams, frameworkFactory){
  this.framework = frameworkFactory.get({title: $stateParams.title})
}
```

I know that I need to loop through the object to get the title I'm looking for so I can put it in the sref on the End Show Page: 
<a data-ui-sref="frameworkShow({type: vm.end.type, title: vm.end.framework.title})">{{framework.title}}</a>

but I'm not sure how to isolate that information for each element. 
Link to my repo: https://github.com/wjpurdum/UpAndRunning

**Comment by wjpurdum** [comment]
function FrameworkShowControllerFunction($state, $stateParams, frameworkFactory){ this.framework = frameworkFactory.get({end: $stateParams.end, title: $stateParams.title}) }

Backend:
app.get("/api/ends/:type/frameworks/:title", (req, res) => {
End.findOne({type: req.params.type}).then(function(end){
let framework = end.frameworks.find(function(framework){
framework.title === req.params.title
})
res.json(framework)
})
})

**Comment by AndyWhitley** [comment]
Yep, that should work. Are you still getting errors?

**Comment by wjpurdum** [comment]
Above is the updated code I'm using, and this is the specific error I'm getting: 
Error: Could not resolve 'frameworkShow' from state 'endShow'

**Comment by wjpurdum** [comment]
This is my sref: <a data-ui-sref="frameworkShow({type: vm.end.type, title: framework.title})">{{framework.title}}</a>

**Comment by AndyWhitley** [comment]
Not sure if you've updated the code compared to what I'm seeing on your GitHub repo, but that is a routing error that could be caused by a few things:
1. The code for the `.state("frameworkShow")` in the `RouterFunction` seems to be commented out
2. I don't see a `.controller("frameworkShow")` attached to `.module()`
