### ISSUE TITLE
project4

### ISSUE THREAD

**Issue by AmlakBarkon** [ga-wdi-exercises/project4#493]
What I did  was i create a table that has five by five cell and create 10 randomly selected cells and hide bomb or restricted area how ever when i press the game all hidden bomb displayed
What I expected when i clicked each cell from the table if there is a bomb hidden in that cell it will display or change the color of that cell or end of the game
What I got is all hidden area are display same time

**Comment by AndyWhitley** [comment]
Could you please make sure to push all your current code to GitHub and then link the repo below.
