### ISSUE TITLE
Having Issues on "draw" function under script.js

### ISSUE THREAD

**Issue by kwonih1020** [ga-wdi-exercises/project4#499]
I'm creating tic tac toe game using html, css, and Javascript.
i'm trying to add "draw" function to my "normal mode" which is under scripts/script.js.
Keep getting buggy every time i tried to add "draw" function.
please help me, where do i start?

one more issue on same part. Everytime after hard refresh, winner alert is not showing even game is over.

my repo : https://github.com/kwonih1020/Project-4

**Comment by jsm13** [comment]
If I'm understanding right, you want [this line](https://github.com/kwonih1020/Project-4/blob/master/scripts/script.js#L31) to draw a new board? Do you have the logic for that `draw` function I could see? What do you mean by "getting buggy" throwing a specific error or causing unexpected behavior?

**Comment by kwonih1020** [comment]
i dont have logic for draw function yet, not sure how to start with that logic. Also, "buggy" means after hard refresh the page, the "winner message" is not showing up (only after hard leash).

**Comment by jsm13** [comment]
Since all of the app state is in memory (not coming from a backend with a database), I would expect the hard refresh would start with a new game on refresh.

**Comment by kwonih1020** [comment]
i understand that part! However, when i first open "index.html" from command line,  winner message for player X or O is not showing for only first few game. (after reset game or refresh the page, then the winner messages pop up correctly).

**Comment by AndyWhitley** [comment]
Hi @kwonih1020 , are you still having problems with the draw function and notifications? If so, could you please push your most recent code to your GitHub so I can see where you're at.

**Comment by kwonih1020** [comment]
https://github.com/kwonih1020/Project-4


<img width="748" alt="screen shot 2017-06-07 at 9 09 29 am" src="https://user-images.githubusercontent.com/26310384/26880013-10535bf6-4b61-11e7-95b4-6f10859aa99c.png">

From screenshot, winner message is not showing up even player "X" won the game.

**Comment by kwonih1020** [comment]
and for player "0" too.
<img width="605" alt="screen shot 2017-06-07 at 9 13 52 am" src="https://user-images.githubusercontent.com/26310384/26880203-a966fdb6-4b61-11e7-9d1f-0a62d070e14c.png">

**Comment by AndyWhitley** [comment]
Hi Ick, I've been testing it for a bit now, and unfortunately, while I can't seem to pin down exactly where the bug is, I feel pretty confident that it is some bug in the logic of `checkForWinner()`. Notice that if you have `X` cover the top three squares, it works (along with some other combinations). Try testing out different combinations and checking the logic in `checkForWinner()`.

**Comment by kwonih1020** [comment]
got it!

**Comment by jsm13** [comment]
These comments were meant to go here, @kwonih1020:

https://github.com/ga-wdi-exercises/project4/issues/504#issuecomment-306805446
https://github.com/ga-wdi-exercises/project4/issues/504#issuecomment-306807734

**Comment by AndyWhitley** [comment]
^The comment referenced above:

Another, cleaner way to handle this logic is to keep the logic out of the DOM. This would mean having some sort of data structure that contains the state of the game and that your Javascript using to render the DOM from. Example:
```js
let board = [
  [
    "", "", ""
  ],
  [
    "", "", ""
  ],
  [
    "", "", ""
  ]
]
```
