### ISSUE TITLE
Performing CRUD when you are not at the element's own route

### ISSUE THREAD

**Issue by wjpurdum** [ga-wdi-exercises/project4#500]
Hello,
I'm creating a MEAN app with nested routes. In my model, a framework has many comments. I'd like to be able to have a user post a comment on the framework page. Right now I'm having trouble figuring out the differnece in routes between the POST request and the Comment Factory query URL.  I'm not sure if my comment factory should reference the comment json itself, or the framework page that the post request is actually occurring on. 

The error I'm getting is: http://localhost:4000/api/ends/frameworks/comments 404 (Not Found) - so I feel it's not connecting to the backend when trying to post? 

The Comment Factory Function: 
```
function CommentFactoryFunction($resource) {
  return $resource ("/api/ends/:type/frameworks/:title/comments", {}, {
    update: {method: "PUT"}
  })
}
```
Controller Code: 
```
function FrameworkShowControllerFunction($state, $stateParams, frameworkFactory, commentFactory){
  this.framework = frameworkFactory.get({type: $stateParams.type, title: $stateParams.title})
  this.newComment = new commentFactory()
  this.create = function () {
    this.newComment.$save().then(function(framework){
      console.log(this.newComment)
      $state.go("frameworkShow", {type: $stateParams.type})
    })
  }
}
```
This is my backend code (it is now routing to the page where the CRUD is occurring):
```
app.post("/api/ends/:type/frameworks/:title", function(req, res){
      Comment.create(req.body).then(function(comment){
      res.json(comment)
      })
    });
```

Link to my repo: 
https://github.com/wjpurdum/UpAndRunning 
Thanks for your help!

**Comment by jsm13** [comment]
The URL of the angular app does not need to have any relation to the api route that a resource is requesting from. The `404` means the request is hitting the server but there isn't a matching route defined by express. This is because the post request needs parameters for `type` and `title`. You'll want to pass these parameters in an object as an argument to `$save` so 

```
this.newComment.$save({type: $stateParams.type, title: $stateParams.title})
  .then(function(framework){
    ...
}
```

**Comment by wjpurdum** [comment]
Hi John, 
Thank you! I put in those params a while back and when I console log the submit, the object is there with the correct parameters, but I'm still getting:
 angular.js:11821 POST http://localhost:4000/api/ends/Back%20End/frameworks?framework=Rails 404 (Not Found)

I'm re-posting my code here in case you can spot something. I'm really at a loss on this! Caroline and I tried to troubleshoot this all day(we have similar model structures), but keep circling back to the same 404. Thanks for your help!

Angular: 
```js
function FrameworkShowControllerFunction($state, $stateParams, endFactory, frameworkFactory, commentFactory){
  this.end = endFactory.get({type: $stateParams.type})
  this.framework = frameworkFactory.get({type: $stateParams.type, title: $stateParams.title})
  this.create = function(){
    console.log("click submitting")
    let newComment = new commentFactory()
    // this.newComment.create = function(){
    newComment.link = this.newComment.link
    newComment.username = this.newComment.username
    console.log(newComment)
    newComment.$save({type: $stateParams.type, framework: $stateParams.title}).then(function(){
      $state.reload
      })
    // }
  }
}
```
Factory: 
```js
function CommentFactoryFunction($resource) {
  return $resource ("/api/ends/:type/frameworks/:title", {}, {
    update: {method: "PUT"}
  })
}
```
Express:
```js
  app.post("/api/ends/:type/frameworks/:title/comments", function(req, res){
        End.findOne({type: req.params.type}.then(function(err, end){
          let framework = end.frameworks.find((framework)=> {
            return framework.title = req.params.title
            Comment.create({link: req.body.link, username: req.body.username}).then(function(comment){
              framework.comments.push(comment)
              framework.comments.save(function(framework){
                res.json(comment)
                console.log(comment)
              })
            })
          })
        }))
      })
```

**Comment by AndyWhitley** [comment]
Hi @wjpurdum , the problem I see with the format of the request your Angular code submitted is that the title of the framework is being added to the URL as query parameters instead of as named parameters in the route. Did you resolve this problem already? If not, could you please push your most recent code to GitHub so I can take a look at where you are at?

**Comment by wjpurdum** [comment]
Yeah , I noticed that too. I can't figure out of that's an Angular factory or controller issue, or an issue with my corresponding Express route. I didn't resolve this problem yet, but my most recent code is on GitHub.

**Comment by AndyWhitley** [comment]
Hi @wjpurdum , when I cloned down your current code and tested it locally, it did work (i.e. I can see the `{{vm.framework.title}}" being rendered on the partial `show` view. Is that what you were having trouble with? Also, do you have cache disabled and the devtools open when you refresh?

**Comment by AndyWhitley** [comment]
Oh you're having trouble with the comments, nevermind. One moment...

**Comment by AndyWhitley** [comment]
One problem I see is that the framework property in the object passed to `$save` should be `title` to match up with the URL template defined in `commentFactory`. Example:
```js
    newComment.$save({type: $stateParams.type, title: $stateParams.title}).then(function(){
      $state.reload
      })
```
at : https://github.com/wjpurdum/UpAndRunning/blob/master/public/js/app.js#L103

**Comment by AndyWhitley** [comment]
A second problem is that the url in `commentFactory` should have `/comments` at the end of it:
```js
function CommentFactoryFunction($resource) {
  return $resource ("/api/ends/:type/frameworks/:title/comments", {}, {
    update: {method: "PUT"}
  })
}
```

at: https://github.com/wjpurdum/UpAndRunning/blob/master/public/js/app.js#L74

**Comment by AndyWhitley** [comment]
Lastly, the Express method you use for adding the comment should use a format like below:
```js
      app.post("/api/ends/:type/frameworks/:title/comments", function(req, res){
        End.findOne({type: req.params.type}).then(function(end){
          let framework = end.frameworks.find((framework)=> {
            return framework.title == req.params.title
          })
          framework.comments.push({link: req.body.link, username: req.body.username})
          end.save().then(function(end) {
            res.json(end)
          })
        })
      })
```

**Comment by wjpurdum** [comment]
THANK YOU!!! This is now saving to the database! Thank you so much!

**Comment by AndyWhitley** [comment]
@wjpurdum && @twelve13 
Once correction, you would still use the Comment model to make sure any model validations / helpers are enforced:

```js
      app.post("/api/ends/:type/frameworks/:title/comments", function(req, res){
        End.findOne({type: req.params.type}).then(function(end){
          let framework = end.frameworks.find((framework)=> {
            return framework.title == req.params.title
          })
          let newComment = new Comment({link: req.body.link, username: req.body.username})
          framework.comments.push(newComment)
          end.save().then(function(end) {
            res.json(end)
          })
        })
      })
```
