### ISSUE TITLE
two high-level questions

### ISSUE THREAD

**Issue by twelve13** [ga-wdi-exercises/project4#503]
1.  what exactly does the express route need to match?

2.  if there's a nested route and you want to create a child element on the server, can you just call models.Childname.create(req.body), or do you need traverse through the parent first?

**Comment by jsm13** [comment]
1. The express route needs to match the [incoming request path](https://expressjs.com/en/guide/routing.html#route-parameters)
2. This depends on the schema not on the route. It depends on how the schema is defined. If the relationship is by id and you have that id available then you can just create the new document using the appropriate id. If the document is nested, you need to get the parent document, add the document being created, and save the parent document
