### ISSUE TITLE
Creating a nested element

### ISSUE THREAD

**Issue by twelve13** [ga-wdi-exercises/project4#504]
https://github.com/twelve13/budgeting
user has many accounts which have many withdrawals

Ok Andy helped me with the form and app.js, and I understand that for the index.js I need to navigate down through users, then accounts to access the withdrawals, but I just can't get the exact syntax down.  Right now there are no errors being thrown in the console, but the new withdrawal doesn't save.

form:
https://github.com/twelve13/budgeting/blob/createuser/public/js/ng-views/dashboard.html#L28-L32

app.js
https://github.com/twelve13/budgeting/blob/createuser/public/js/app.js#L94-L104

index.js
https://github.com/twelve13/budgeting/blob/createuser/index.js#L60-L73

**Comment by twelve13** [comment]
updated links because i added some code and it threw the line indices off

form:
https://github.com/twelve13/budgeting/blob/createuser/public/js/ng-views/dashboard.html#L33-L37

app.js
https://github.com/twelve13/budgeting/blob/createuser/public/js/app.js#L104-L112

index.js
https://github.com/twelve13/budgeting/blob/createuser/index.js#L67-L80

**Comment by AWhitleyGA** [comment]
Hi Ick, I've been testing it for a bit now, and unfortunately, while I can't seem to pin down exactly where the bug is, I feel pretty confident that it is some bug in the logic of `checkForWinner()`. Notice that if you have `X` cover the top three squares, it works (along with some other combinations). Try testing out different combinations and checking the logic in `checkForWinner()`.

**Comment by AWhitleyGA** [comment]
Another, cleaner way to handle this logic is to keep the logic out of the DOM. This would mean having some sort of data structure that contains the state of the game and that your Javascript using to render the DOM from. Example:
```js
let board = [
  [
    "", "", ""
  ],
  [
    "", "", ""
  ],
  [
    "", "", ""
  ]
]
```

**Comment by twelve13** [comment]
i think these are for another issue?

**Comment by twelve13** [comment]
wheeee!! i looked at Whitney's issue (we have the same structure) and it works!!!!  thanks!
