### ISSUE TITLE
API 401 Unauthorized

### ISSUE THREAD

**Issue by utamilah** [ga-wdi-exercises/project4#505]
For my app I'm using Spotify's API. I want the user to log in and view some of their unique Spotify data. Using Angular, within my` UserShowController` I'm able to make a successful get request and I can console the data but I can't get it to show up in the view (I tried a bunch of expressions).

So now I'm trying to use a factory but the request comes back as unauthorized even though I've added the appropriate headers:

```
function User($location, $resource) {
  let url_tokens = $location.$$path
  let access_token = url_tokens.substr(url_tokens.indexOf('=') +1)

  return $resource('https://api.spotify.com/v1/me', {}, {
      get: {
          method: 'GET',
          headers:{'Authorization':'Bearer ' + access_token}
      }
    });
}
```

So now when I do `this.user = User.query()` I get a 401 unauthorized error. Not sure how to proceed with this. Also do I need the factories? If not how do I get the requested data displayed on the view without a factory?

**Comment by jsm13** [comment]
The 401 isn't a going to be a problem with factories but with the request being made. You are able to inject either `$resource` or `$http` directly into a controller circumventing the need for a factory but it is definitely better practice to use the factory. I would test the request in another tool like postman. This is a problem with the token (request is getting to spotify and the 401 is coming back because either something is missing, the token is expired, or the token is pulling  from the path wrong, or some other problem with the token)

**Comment by jsm13** [comment]
As far as getting the data to show up in the view, once the request is successful, that should be as straight forward as assigning the returned resource to a value on the  view-model.

**Comment by utamilah** [comment]
Yea it's really weird because the http.get request worked great in my controller functions. I think I will disregard the factory for now though and get the display working from the factory. Thanks!

**Comment by AndyWhitley** [comment]
Hi Hali, could you push your most recent code to GitHub and link your repo so I can clone it down and test it?

**Comment by utamilah** [comment]
Sorry for the delay! I actually ended up using my controller function for everything but the factory is still there. 

https://github.com/utamilah/music-id-test

**Comment by utamilah** [comment]
Right now I have a test view that's displaying content but I can't seem to show anything without including an index...

**Comment by AndyWhitley** [comment]
@utamilah Note that you need to access properties off of the response you get from Spotify:
```js
  let urlTracks = "https://api.spotify.com/v1/me/top/tracks"
  $http.get(urlTracks, {headers:{'Authorization':'Bearer ' + access_token}})
  .success( function(response){
    self.tracks = response.items
  })
```
> Here you need to assign `self.tracks` as `response.items` (a similar property will be needed for artists)

**Comment by AndyWhitley** [comment]
And then you can use `ng-repeat` like normal:
```html
<section class="wrapper">
  <div>
    <h2 ng-repeat="track in vm.tracks">
      <p>{{track.name}}</p>
    </h2>
  </div>
</section>
```

**Comment by AndyWhitley** [comment]
The problem with your `User` factory was that the parsing of the access token was slightly off:
```js
function User($location, $resource) {
  let url_tokens = $location.$$path
  let access_token = url_tokens.substr(url_tokens.indexOf('='))

  return $resource('https://api.spotify.com/v1/me', {}, {
      get: {
          method: 'GET',
          headers:{'Authorization':'Bearer ' + access_token}
      }
  });

  console.log()
}
```
should be:
```js
function User($location, $resource) {
  let url_tokens = $location.$$path
  let access_token = url_tokens.substr(url_tokens.indexOf('=') + 1)

  return $resource('https://api.spotify.com/v1/me', {}, {
      get: {
          method: 'GET',
          headers:{'Authorization':'Bearer ' + access_token}
      }
  });

  console.log()
}
```
> Note the `+ 1` on the `access_token` definition

**Comment by AndyWhitley** [comment]
@utamilah If this fixes this problem, could you please close this issue when you're done reviewing. If not, please let me know.

**Comment by utamilah** [comment]
Awesome, thanks! The ng-repeat works beautifully now!

For the factory function, I had that there initially but it still didn't work. I think I will stick with making the call in the controller functions since that's working for now and probably figure that out later.

But everything seems to be working fine right now!
