### ISSUE TITLE
rendering issue

### ISSUE THREAD

**Issue by jkoo87** [ga-wdi-exercises/project4#507]
I am working on a map component using google map API. I was able to get the data shown on the page, however, the map is being rendered even before lat & lng props are passed down to the map component. Is there a way to make the map component wait until props are passed down? 
https://github.com/jkoo87/SluggingDC

**Comment by jsm13** [comment]
Talking about [this map (`Map.js`)](https://github.com/jkoo87/SluggingDC/blob/master/slugging-dc-react/src/components/Map.js), not [this map (`GoogleMap.js`)](https://github.com/jkoo87/SluggingDC/blob/master/slugging-dc-react/src/components/GoogleMap.js), right?

**Comment by jkoo87** [comment]
Yes Map.js

**Comment by jsm13** [comment]
spinning things up to get an idea of what you're describing but off the bat, can render conditionally based on the presence of props so here: https://github.com/jkoo87/SluggingDC/blob/master/slugging-dc-react/src/components/Map.js#L17-L33 could do something along the lines of:

```
...
    render() {
        console.log(this.state.address.lat)
        const markers = this.props.markers || []

        return (
            markers.length ? // if there are markers render the map
            <GoogleMap
              defaultZoom={15}
              defaultCenter={{ lat: this.state.address.lat, lng: this.state.address.lat }}>
              {markers.map((marker, index) => (
                <Marker {...marker}/>
                )
              )}
            </GoogleMap> :
            <h2>Loading...</h2>

        )
    }
...

**Comment by jkoo87** [comment]
```
import React, {Component} from 'react'
import { withGoogleMap, GoogleMap } from "react-google-maps";

class Map extends Component {
    constructor(props){
      super(props)
      this.state={
        address: this.props.address
      }
    }
    componentWillReceiveProps(nextProps){
      this.setState({
        address: nextProps.address
      })
    }

    render() {
        console.log(this.state.address.lat)

        return (
            <GoogleMap
              defaultZoom={15}
              defaultCenter={{ lat: this.state.address.lat, lng: this.state.address.lng }}>
            </GoogleMap>

        )
    }
}

export default withGoogleMap(Map)
```
Before 'this.state.address.lat(number) & this.state.address.lng(number)' passed down from the upper component, google map is already done rendering ({{ lat: this.state.address.lat(undefined), lng: this.state.address.lng(undefined) }}), which returns back an error massage saying that 'InvalidValueError: setCenter: not a LatLng or LatLngLiteral: in property lat: not a number'

**Comment by jsm13** [comment]
Yeah, I'm seeing that just tried rendering conditionally on the presence of those lat and long values and got the same empty grey box. Still digging

**Comment by jkoo87** [comment]
Thanks a lot for your help!

**Comment by jsm13** [comment]
Issue is that in `Station` when you set [`state.station` to an empty array](https://github.com/jkoo87/SluggingDC/blob/master/slugging-dc-react/src/components/Station.js#L11) and [then pass `state.station.map`](https://github.com/jkoo87/SluggingDC/blob/master/slugging-dc-react/src/components/Station.js#L66) into the address prop, you are passing `[].map` the function.

You'll need to add logic to not display the map until the response comes back (can do this in the render function of Station) after that you don't need state in the `Map` component but can just use the props passed in directly

**Comment by jkoo87** [comment]
I really appreciate your help on this issue! I've been working on this problem literally all day long today, and your direction fixed my issue less than 10 minutes!!!! Awesome!!

**Comment by jsm13** [comment]
So happy to hear it. Sorry it took me a while to get there
