### ISSUE TITLE
Still having trouble with draw function

### ISSUE THREAD

**Issue by kwonih1020** [ga-wdi-exercises/project4#508]
repo:  https://github.com/kwonih1020/Project-4

still draw message is not showing, i just committed all the works that i've done so far.
It's under scripts/script.js

**Comment by AndyWhitley** [comment]
Hi Ick, where in your current code are you trying to draw the line when the game ends?

**Comment by AndyWhitley** [comment]
@kwonih1020 Check out this StackOverflow question on using an <svg> element to draw a line:
https://stackoverflow.com/questions/19382872/how-to-connect-html-divs-with-lines

**Comment by kwonih1020** [comment]
Actually what i mean by "draw function" is like "it's tie game" or "Game Draw", i want to makes draw messages pop up when there are no winners for my tic tac toe game.

**Comment by kwonih1020** [comment]
scripts/script.js 
line 43.

**Comment by AndyWhitley** [comment]
@kwonih1020 After testing it a bit further, I noticed why the draw functionality isn't working. Just like you have to query the DOM again for the new square values in `checkWinnerInternal()`, you will need to do so before checking for a draw. If you put a `console.log` in the place I indicate below and test the code, you will notice the discrepancy. The solution will be to set up a separate function, say `checkForDraw()` that checks all of the squares again and then runs through the same logic:
```js
      if (winner != -1 && winner != "") {
	     if (winner == "X") {
          $('#messages').html("Player X Wins!").fadeIn().delay(3000).fadeOut(function(){
            counter_X ++;
            counterX();
          })
       }
        else if (winner == "O") {
          $("#messages").html("Player O Wins!").fadeIn().delay(3000).fadeOut(function() {
            counter_O ++;
            counterO();
          })
        }
      }
      else if ( (!!space1) && (!!space2) &&
                (!!space3) && (!!space4) &&
                (!!space5) && (!!space6) &&
                (!!space7) && (!!space8) &&
                (!!space9) ) {
                  console.log('draw')
                  $("#messages").html("Draw!").fadeIn().delay(3000).fadeOut();
                }
      else {
        console.log(space1, space2, space3, space4, space5, space6, space7, space8, space9)
      }
```

**Comment by kwonih1020** [comment]
Thank you! I figured out!
