### ISSUE TITLE
deleting nested element

### ISSUE THREAD

**Issue by twelve13** [ga-wdi-exercises/project4#509]
not critical to my app, but just wondering how to delete a nested element

if users have many accounts, and I want to delete an account

I find the user, then find that account, then...splice it out of the array of user.accounts?

https://github.com/twelve13/budgeting/blob/deletefunctionality/index.js#L68-L85

**Comment by jsm13** [comment]
Exactly, then save `user`

**Comment by twelve13** [comment]
thanks - the code I have isn't working.  i get no error in the console, but it redirects to the welcome page without deleting the account:
```
app.delete("/users/:name/accounts/:id", (req, res) => {
	models.User.findOne({name: req.params.name}).then(function(user){
		let account = user.accounts.find((account) => {
			return account.id == req.params.id
		})
		for(let i=0; i < user.accounts.length; i++){
			if(user.accounts.id[i]== account.id){
				user.accounts.splice(user.accounts[i], 1)
			}
		}
		// let index = user.accounts.indexOf(account);
		// user.accounts.splice(index, 1);
		user.save().then(function(){
				res.json({success: true})
			})
	})
})
```
https://github.com/twelve13/budgeting/blob/deletefunctionality/index.js#L68-L85

**Comment by jsm13** [comment]
problem is `user.accounts.splice(user.accounts[i], 1)`. See [parameters for splice](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/splice?v=example#Syntax)

**Comment by twelve13** [comment]
got it - should have been user.accounts[i].id, not user.accounts.id[i] - thanks!
