### ISSUE TITLE
Passing callbacks to getAjaxData function causes it to fail

### ISSUE THREAD

**Issue by tomBeach** [ga-wdi-exercises/project4#51]
To avoid putting several sequential ajax calls into a loop (while avoiding making nearly duplicate ajax functions), I am passing a unique callback each time I call getAjaxData.  The first time through it works, but produces error after the next call to it: 

```
Uncaught TypeError: this.getAjaxData is not a function
```

getAjaxData is called from this switch statement: (I checked values of this.currentUser.id, url, etc. all ok)

``` js
        switch (whichList) {
            case "nursePatients":
                var url = "/welcome/getNursePatients/" + this.currentUser.id;
                var nursePatientJson = this.getAjaxData(url, this.processJsonData);
                break;
```

Here is the loop in which I am calling getAjaxData twice and passing a different url and callback each time:

``` js
        patientsJson.forEach(function(patientObject) {
            var url = "/welcome/getPatientInfo/" + patientObject.person_id;
            var patientInfo = self.getAjaxData(url, self.getPatientInfo);
            var url = "/welcome/getPatientMeds/" + patientObject.id;
            var medIconString = self.getAjaxData(url, self.getPatientMeds);
```

Here is the getAjaxData function:

``` js
    // ======= ======= ======= getAjaxData ======= ======= =======
    Display.prototype.getAjaxData = function(url, callback) {

        // == ajax LOCAL user login
        $.ajax({
            url: url,
            method: "GET",
            dataType: "json"
        }).done(function(jsonData){
            console.log("  ajax SUCCESS");
            console.dir(jsonData);
            callback(jsonData);
        }).fail(function(){
            console.log("  ajax FAIL");
        });
    }
```

Does it have anything to do with calling getAjaxData while it is still busy processing the previous call to it?

**Comment by RobertAKARobin** [comment]
No, I don't think that's the problem. Before the `var nursePatientJson` line, put `console.dir(this)`. Is `this` what you expect it to be?

(I'm guessing `this` has just changed somewhere along the line. That could probably be fixed with a `var self = this;` right inside the function that contains the `switch` block.)

**Comment by tomBeach** [comment]
I correctly get the Display object when I console.dir(this) before the var nursePatientJson line, but I get the window object when console.dir(self) before var patientInfo line inside loop.  (There's a var self = this; before the loop is called so I thought that would set the scope properly.)  How do I reference Display the second time then?

**Comment by RobertAKARobin** [comment]
Can you paste the code containing the `switch` block?

**Comment by tomBeach** [comment]
``` js
    // ======= ======= ======= makeListObjects ======= ======= =======
    Display.prototype.makeListObjects = function(whichList) {
        console.log("makeListObjects");

        var self = this;
        this.$el = $("<div class='listItem'>");
        this.clearContainerElements();

        switch (whichList) {
            case "nursePatients":
                var url = "/welcome/getNursePatients/" + this.currentUser.id;
                var data = this.currentUser.id;
                console.dir(this);
                var nursePatientJson = this.getAjaxData(url, this.processJsonData);
                break;
        }
    }
```

**Comment by tomBeach** [comment]
I am planning to add more items to switch (keeping it simple for now!)

**Comment by RobertAKARobin** [comment]
Instead of doing `this.getAjaxData`, try `self.getAjaxData`. Then it should refer to the proper object.

**Comment by RobertAKARobin** [comment]
Oh, I'm sorry, I misread the error. The trouble's inside the loop, right?

**Comment by tomBeach** [comment]
The call from the switch statement is working ok (object is Display).  It's the call from this function that fails:

``` js
    // ======= ======= ======= processJsonData ======= ======= =======
    Display.prototype.processJsonData = function(patientsJson) {
        console.log("processJsonData");

        var self = this;
        var htmlString = null;
        console.dir(this);

        patientsJson.forEach(function(patientObject) {
            var data = patientObject.person_id;
            var url = "/welcome/getPatientInfo/" + patientObject.person_id;
            console.dir(self);
            var patientInfo = self.getAjaxData(url, self.getPatientInfo);
            var url = "/welcome/getPatientMeds/" + patientObject.id;
            var medIconString = self.getAjaxData(url, self.getPatientMeds);
```

Both console.dirs refer to window (even the first one near top of function..

**Comment by RobertAKARobin** [comment]
Can you tell me where `processJsonData()` is being called?

**Comment by RobertAKARobin** [comment]
Fixed with `.bind`
