### ISSUE TITLE
getting module injector error 

### ISSUE THREAD

**Issue by lgmusic24** [ga-wdi-exercises/project4#511]
Error not showing up, but nothing changed. Background, dropdown menu, and other items are gone. Weird.

**Comment by lgmusic24** [comment]
Error not showing up, but nothing changed. Background, dropdown menu, and other items are gone. Weird.

**Comment by jsm13** [comment]
Going to need a little more info and a link to your repo. It does make sense that an injector error (likely trying to inject a module which has not been defined either because of a typo or not having loaded an external dependency) would cause an error preventing other loading from happening

**Comment by lgmusic24** [comment]
I thought I fixed the injector error, but it somehow came back. GRRRRRRR!!!  

Link--https://github.com/lgmusic24/SHOPDROP-NEW


angular.js:38  

Uncaught Error: [$injector:modulerr] http://errors.angularjs.org/1.5.6/$injector/modulerr?p0=shopDrop&p1=Error%3…ogleapis.com%2Fajax%2Flibs%2Fangularjs%2F1.5.6%2Fangular.min.js%3A21%3A332)

**Comment by lgmusic24** [comment]
I just got rid of it :)

**Comment by AndyWhitley** [comment]
Hi @lgmusic24 , you were able to solve your issue, right?

**Comment by lgmusic24** [comment]
yep, working on the crud and trying to get my API to work :)
