### ISSUE TITLE
everything is undefined

### ISSUE THREAD

**Issue by edawson1980** [ga-wdi-exercises/project4#513]
I've started a new branch, building from the ground up by following both the react-translator and reactTVMaze lesson plans.  when I make an axios call to the GoogleBooks API (in Books.js), I get an error when trying to map the API response...whichever property I try to access cannot be viewed because what it belongs to is undefined.

<img width="1132" alt="screen shot 2017-06-08 at 11 02 57 am" src="https://user-images.githubusercontent.com/16961196/26935725-b351cdfe-4c3a-11e7-8ae6-44139c9089c1.png">

I think I've lost track of my values across the different components, and now I'm having a hard time tracking this undefined issue back to the source.  A fresh set of eyes would be greatly appreciated.

https://github.com/edawson1980/library-finder/tree/fromscratch

**Comment by jsm13** [comment]
The response is an object not an array.

<img width="1178" alt="screen shot 2017-06-08 at 11 30 55 am" src="https://user-images.githubusercontent.com/7882341/26936910-f96aac18-4c3d-11e7-979e-f6e342bb7333.png">


To access the books' `volumeInfo`. You want
```
return response.data.items.map( item => {
  return item.volumeInfo
}
```
at the line where the error is being thrown

**Comment by edawson1980** [comment]
oh, man.  thank you!
