### ISSUE TITLE
css styling disappears on page refresh

### ISSUE THREAD

**Issue by twelve13** [ga-wdi-exercises/project4#515]
https://github.com/twelve13/budgeting/tree/styling

all styling disappears when I refresh the page
from my googling I think it has to do with reconfiguring to html5.  there's some talk of modifying a .htaccess file - is that really necessary?  thanks!

**Comment by AndyWhitley** [comment]
One solution is to replace the relative path with an absolute one. There likely is a more elegant configuration solution, but this will work:
```html
	<link rel="stylesheet" href="http://localhost:4000/assets/css/styles.css">
```

**Comment by AndyWhitley** [comment]
^ @twelve13

**Comment by twelve13** [comment]
yay!  elegant enough for me!  thanks
