### ISSUE TITLE
Heroku deployment

### ISSUE THREAD

**Issue by StormyRamsey** [ga-wdi-exercises/project4#516]
Hello, 
https://github.com/StormyRamsey/pattern_on_pattern_off
I am trying to deploy my rails app to Heroku but I am receiving this error: 

red)>'
remote:        Tasks: TOP => assets:precompile
remote:        (See full trace by running task with --trace)
remote:  !
remote:  !     Precompiling assets failed.
remote:  !
remote:  !     Push rejected, failed to compile Ruby app.
remote: 
remote:  !     Push failed
remote: Verifying deploy...
remote: 
remote: !	Push rejected to tranquil-dawn-78007.
remote: 
To https://git.heroku.com/tranquil-dawn-78007.git
 ! [remote rejected] master -> master (pre-receive hook declined)
error: failed to push some refs to 'https://git.heroku.com/tranquil-dawn-78007.git'

**Comment by AndyWhitley** [comment]
@StormyRamsey Try running `rails assets:precompile` and then try pushing again. IF that fails as well, then go to `config/environments/production.rb` and change the `config.assets.compile = false` to `config.assets.compile = true`

**Comment by StormyRamsey** [comment]
I was able to get it up and running on Heroku but my seed data didn't show, so I just recreated the model items via the website.

**Comment by AndyWhitley** [comment]
Oh ok. To run your seed data, you have to tell Heroku to do so. Try running `heroku run rails db:seed`
