### ISSUE TITLE
Issue with heroku deployment

### ISSUE THREAD

**Issue by twelve13** [ga-wdi-exercises/project4#518]
https://github.com/twelve13/budgeting/tree/deployment

I've added my procfile, created an mlab account, and installed the addon in my heroku.  I'm having issues seeding my heroku

  message: 'failed to connect to server [localhost:27017] on first connect [MongoError: connect ECONNREFUSED 127.0.0.1:27017]' }

and though my landing page shows when i run heroku open, there's no functionality.

p.s. does it matter that my whole mean stack is in one branch?  thanks!

**Comment by juancgarcia** [comment]
Heroku doesn't provide access to a Mongo database by default. You'll need to take one of two paths to get mongo hooked up via a service called [mLab](https://mlab.com/)

First option is to add a Heroku add-on for communicating with mLab as your database. This is pretty straight forward, but Heroku needs you to have a credit card on file before they allow you to include add-ons. They won't charge you if you select the free database tier, but you won't have the option without setting up your CC first:

https://devcenter.heroku.com/articles/mongolab

Option 2 is to go straight to mLab and make a free database there. Once you have the DB created, you just replace your mongodb connection url with the one provided on mLab.

**Comment by twelve13** [comment]
https://github.com/twelve13/budgeting/tree/deployment

thanks!  andy has been troubleshooting with me but there are still connection issues.  i created an mlab account and created a new user . i ran
$ heroku config:set MONGOLAB_URL=mongodb://test:testerson@ds015760.mlab.com:15760/yourappname

but changed out the test:testerson with my username and password

when i try to seed I get

 message: 'failed to connect to server [localhost:27017] on first connect [MongoError: connect ECONNREFUSED 127.0.0.1:27017]' }

in my chrome console i get

peaceful-sands-66523.herokuapp.com/:1 GET https://peaceful-sands-66523.herokuapp.com/ 503 (Service Unavailable)
favicon.ico:1 GET https://peaceful-sands-66523.herokuapp.com/favicon.ico 503 (Service Unavailable)

**Comment by twelve13** [comment]
when i run
$ heroku run printenv

i get this below.  i see that there is both a MONGOLAB_URL and a MONGODB_URI but I think I changed out all my mongodb-uri's to mongolab_url's

Running printenv on ⬢ peaceful-sands-66523... up, run.2691 (Free)
TERM=xterm-256color
WEB_MEMORY=512
MEMORY_AVAILABLE=512
COLUMNS=136
DYNO=run.2691
PATH=/app/.heroku/node/bin:/app/.heroku/yarn/bin:/usr/local/bin:/usr/bin:/bin:/app/bin:/app/node_modules/.bin
WEB_CONCURRENCY=1
PWD=/app
MONGOLAB_URL=mongodb://caroline:caroline123@ds119302.mlab.com:19302/heroku_lrr3qvqh
NODE_ENV=production
PS1=\[\033[01;34m\]\w\[\033[00m\] \[\033[01;32m\]$ \[\033[00m\]
LINES=28
SHLVL=1
HOME=/app
PORT=48791
MONGODB_URI=mongodb://caroline:caroline123@ds119302.mlab.com:19302/heroku_lrr3qvqh
NODE_HOME=/app/.heroku/node
_=/usr/bin/printenv

**Comment by juancgarcia** [comment]
A couple of things:

When pushing to `heroku master` from a local branch of a different name (eg `deployment` instead of local `master`), you need to specify that:

```bash
git push heroku deployment:master
```

This will solve your `localhost` issues since you were likely actually pushing from your master branch where the connection string was for localhost.

**Comment by juancgarcia** [comment]
Also

In your index.js, make sure you're using the port provided by Heroku `process.env.PORT`:

```js
// after declaring `app`
app.set("port", process.env.PORT || 8080)

// ...

// starting your server
app.listen(app.get("port"), () => {
// ...
```

**Comment by twelve13** [comment]
it's deployed!! thank you andy and juan!
