### ISSUE TITLE
React npm run start error

### ISSUE THREAD

**Issue by sonnykbp** [ga-wdi-exercises/project4#519]
Hey James! I got this error when i ran npm run start:

<img width="701" alt="screen shot 2017-07-17 at 12 11 40 pm" src="https://user-images.githubusercontent.com/25208667/28277943-616e6b5a-6ae9-11e7-8add-16b0312e5c72.png">

It was running fine earlier but i got this error after i deleted "registerServiceWorker.js" from my /src and "manifest.json" from /public from my app. I put that file back in the app but no luck! Can you help me go in the right direction please thank you!

**Comment by superbuggy** [comment]
does `yarn start` yield a better result?

**Comment by superbuggy** [comment]
if that fails, try running `yarn install` and then re-run `yarn start`. Let me know how that goes!

**Comment by sonnykbp** [comment]
works purrrrfectly!!! thank yoU!!
