### ISSUE TITLE
Seeding Issue

### ISSUE THREAD

**Issue by Antwana** [ga-wdi-exercises/project4#522]
I'm not really sure what I'm doing wrong. Every time I try to seed the database I get the following error

"$ node db/seeds.js
/Users/antwanawadlington/wdi/projects/birthday-app/db/connection.js:5
  name: String,
      ^
SyntaxError: Unexpected token :"

Connection.js
var mongoose = require("mongoose")
mongoose.connect("mongodb://localhost/birthday")

var CommentSchema = new mongoose.Schema([
  name: String,
  idea: String,
  comments: String
])
var PostSchema = new mongoose.Schema({
  name: String,
  idea: String,
  ages: String,
  gender: Array,
  image: String,
  description: String,
  comments: [CommentSchema]
}
)

mongoose.model("Post", PostSchema)
mongoose.model("Comment", CommentSchema)

module.exports = mongoose

**Comment by nayana487** [comment]
Should be curly brackets after `.Schema`. In your CommentSchema. See how you did it in the PostSchema?

**Comment by Antwana** [comment]
Thank you !!

**Comment by nayana487** [comment]
closing now, let us know if you have other issues!
