### ISSUE TITLE
Issue loading my assets 

### ISSUE THREAD

**Issue by RobLowe1992** [ga-wdi-exercises/project4#525]
I'm getting two 404 errors when attempting to connect my index.js and style.css in my index.html page. I have tried changing my public folder to use assets as a static folder but that doesn't seem to be working

**Comment by superbuggy** [comment]
can I see your code in `index.js`?

**Comment by RobLowe1992** [comment]
var express = require("express");
var parser = require("body-parser");
var mongoose = require("./db/connection");
const app = express();

const Article = mongoose.ArticleModel;
app.set('port', process.env.PORT || 8080)
app.use(parser.json({extended: true}));
app.set('views', __dirname + '/views');
app.engine('html', require('ejs').renderFile);
app.set('view engine', 'html');

app.get("/", function(req, res){
  res.render("index");
});

app.get('/api/articles', function(req,res){
    Article.find({}).then((articles)=>{
        res.json(articles);
    });
});
app.get('/api/articles/:title', function(req,res){
    Article.findOne({title: req.params.title}).then((article)=>{
        res.json(article);
    });
});
app.post('/api/articles', function(req,res){
    Article.create(req.body).then((article)=>{
        res.json(article);
    });
});
app.delete('/api/articless/:title', function(req,res){
    Article.findOneAndRemove({title: req.params.title}).then(()=>{
        res.json({success: true});
    });
});
app.put('/api/articless/:title', function(req,res){
    Article.findOneAndUpdate({title: req.params.title}, req.body, {new: true}).then((article)=>{
        res.json(article);
    });
});
app.listen(8080, ()=> {
    console.log(['Listening on port 8080'])
})

**Comment by superbuggy** [comment]
ah okay, you need to tell express what to serve as static assets, which would look something like this, assuming your assets are in a `public` folder

```js
const express = require('express')
const app     = express()

app.use("public", express.static("public"))
```

**Comment by RobLowe1992** [comment]
I tried this and it doesn’t seem to be working

**Comment by superbuggy** [comment]
You're still getting the 404? what folder are your assets in? Can you share the html code which is producing the 404?

**Comment by RobLowe1992** [comment]
<!DOCTYPE html>
<html ng-app="npr">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" type="text/css" href='/public/css/style.css'>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">
    <title>NPR</title>
</head>
<body>
    <main class="container-fluid" data-ui-view>
    </main>
</body>
<script src="https://cdnjs.cloudflare.com/ajax/libs/angular.js/1.6.5/angular.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/react/15.6.1/react.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/react/15.3.2/react-dom.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/ngreact/0.4.1/ngReact.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/angular-ui-router/0.2.15/angular-ui-router.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/angular.js/1.5.0-beta.2/angular-resource.min.js"></script>
<script src="/public/app.js" charset="utf-8"></script>
</html>

**Comment by superbuggy** [comment]
closing for now!
