### ISSUE TITLE
cannot figure out how to connect backend seed data to front end

### ISSUE THREAD

**Issue by Antwana** [ga-wdi-exercises/project4#526]
**Below is my server.js**
‘use strict’

var express = require(`express`);
// var mongoose = require(`mongoose`);
var bodyParser = require(`body-parser`);
var mongoose= require("../db/connection");

var app = express();
var router = express.Router();

var port = process.env.API_PORT || 3001;

app.use(bodyParser.urlencoded({ extended: true }));
app.use(bodyParser.json());

router.get(‘/’, function(req, res) {
 res.json({ message: ‘API Initialized!’});
});

app.use(‘/api’, router);

app.listen(port, function() {
 console.log(`api running on port ${port}`);
});

**Below is seeds.js**
var mongoose = require("./connection.js")
var seedData = require("./seeds.json")

var Post = mongoose.model("Post")
var Comment = mongoose.model("Comment")

Post.remove({}).then(() => {
  Post.collection.insert(seedData).then(() =>{
    process.exit()
  })
})

Comment.remove({}).then(() => {
  Comment.collection.insert(seedData).then(() =>{
    process.exit()
  })
})

**Comment by nayana487** [comment]
what are you using for your front end?

**Comment by Antwana** [comment]
React

**Comment by nayana487** [comment]
Just messaged you on Slack. Let's meet in person
