### ISSUE TITLE
Can`t aceess show page json

### ISSUE THREAD

**Issue by tedlayea** [ga-wdi-exercises/project4#527]
I can get index page JSON data but not show page.
Here is part of my code:
```js
// My catagoryController
show(req,res){
    Person.findOne({name: req.params.name},(err,contact)=>{
      console.log(contact);
      res.send(contact)
    })
  }
//index.js
app.get('/backend/:catagory', catagoryController.show)
```
![screenshot](https://user-images.githubusercontent.com/27984226/28370105-798370f8-6c67-11e7-8f59-f97e4a5645c9.png)

**Comment by superbuggy** [comment]
Does your program ever console.log the value of `contact`

**Comment by tedlayea** [comment]
Yes when I run my controller, it does. I can see the result in the terminal(not the browser).

**Comment by superbuggy** [comment]
since you have `{name: req.params.name}` as your 1st argument to `.findOne()`:
Change 

```js
app.get('/backend/:catagory', catagoryController.show)`
```
to

```js
app.get('/backend/:name', catagoryController.show)
```

**Comment by tedlayea** [comment]
I did it, but still no change.

**Comment by superbuggy** [comment]
What's the value of `contact` when it is logged?

**Comment by tedlayea** [comment]
If I run the controller and put this code: 
catagoriesController.show({catagoryName: "aaa"})
Then the log show me detail about aaa

**Comment by superbuggy** [comment]
You have data in your mongo db, right?

**Comment by tedlayea** [comment]
The previous image is screenshot when I use postman.
Here is screenshot of browser
![screenshot2](https://user-images.githubusercontent.com/27984226/28372641-48befbc0-6c6e-11e7-8395-a55434cbe418.png)

**Comment by tedlayea** [comment]
Yes I have data I can see index page clearly.

**Comment by superbuggy** [comment]
Ah that's what I thought, `badcfg` refers to when an object is received instead of an array (single thing instead of a list of things). Instead of  `.query()`, use `.get()`.

**Comment by tedlayea** [comment]
ops now even I can`t see index page

**Comment by superbuggy** [comment]
I don't have a sense of where you are with your issue, can you include relevant code and errors?

**Comment by tedlayea** [comment]
now solved, thanks.

**Comment by superbuggy** [comment]
yay!
