### ISSUE TITLE
Images won't render

### ISSUE THREAD

**Issue by daniellefricke** [ga-wdi-exercises/project4#529]
Hi James,

I'm trying to get a main image for each blog to load onto my blog index page but its not working. Here is the code I've used.
```<img src={blog.mainImage} alt="{blog.title}"/>```
Any ideas as to why this wouldn't work? Thanks!

**Comment by superbuggy** [comment]
I would remove the quotes around `{blog.title}`.  Maybe `blog` isn't defined, or `mainImage` is undefined. What errors are you getting?

**Comment by daniellefricke** [comment]
I have 'mainImage' as a key in my seeds/schema and can see it in each object when I console log the index. in the alt, it is requiring "" and I'm not getting any errors.

**Comment by superbuggy** [comment]
This seemed like it was due to flickr's outside image linking policy. Reopen if necessary!
