### ISSUE TITLE
PUT 500 (Internal Server Error)

### ISSUE THREAD

**Issue by ericacomfort** [ga-wdi-exercises/project4#53]
I'm having an error when a user tries to update an event.

A user can edit an event which displays the `editEvent.html` template: https://github.com/andersenek/gracious.guest/blob/master/gracious_guest/views/index.ejs#L331

Here is the `update` method on the template: https://github.com/andersenek/gracious.guest/blob/master/gracious_guest/views/index.ejs#L351

Which triggers the updateEvent method in the `EditEventCtrl`: https://github.com/andersenek/gracious.guest/blob/master/gracious_guest/public/javascripts/angularApp.js#L330

The `updateEvent` method is in the factory which is where I'm hitting the error: https://github.com/andersenek/gracious.guest/blob/master/gracious_guest/public/javascripts/angularApp.js#L150-L158
**In the console it's displaying `PUT http://localhost:3000/events/55fb7eb1cbcdbece3638a0b3 500 (Internal Server Error)` This is the event/id that I want to update so I'm not sure why I'm getting the error.

Here is the Angular route: https://github.com/andersenek/gracious.guest/blob/master/gracious_guest/public/javascripts/angularApp.js#L31-L40

Here is the server-side route: https://github.com/andersenek/gracious.guest/blob/master/gracious_guest/routes/events.js#L145-L160

To run my app you'll need to run:
`npm install`
`mongod`
`npm start`

Thanks in advance for any help!

**Comment by adambray** [comment]
Hey Erica!

Good job getting so far! HTTP 500 errors indicate that the server (node/express) encountered an error. Can you trigger the error again and then look at the logs in your terminal to see what it was? (And copy paste it here?)

-Adam

**Comment by ericacomfort** [comment]
Thanks! It's not showing much but here are the last two messages in my terminal:
`GET /events/55fb781ce9538a5b36ad2ea9 200 5.578 ms - 548`
`PUT /events/55fb781ce9538a5b36ad2ea9 500 9.374 ms - 2354`

**Comment by RobertAKARobin** [comment]
Here's the problematic line:

``` js
event = _.extend(event, req.body);
```

`_.extend` isn't available inside Node. It's an Underscore method, which isn't a dependency of your app.

Also:

``` js
router.put('/events/:event_id', function(req, res) {
    var event = Event.findById(req.params.id);
```

It should be `var event = Event.findById(req.params.event_id);` to match the URL.

**Comment by RobertAKARobin** [comment]
I found that by putting in `console.log("hello")` after every line until I found the one that wasn't getting logged, meaning the line before it was causing the problem.

**Comment by ericacomfort** [comment]
Thanks Robin! And thank you Adam for walking me through 'update' the Mongo way!
