### ISSUE TITLE
rspec has a valid factory (FAILED - 1) in a join model

### ISSUE THREAD

**Issue by scottpiercew** [ga-wdi-exercises/project4#531]
I'm using rspec to test that my join table ```categorization``` has a factory and I'm having trouble writing code to get a passing test. My other model specs are passing. The test passes the ```is invalid without a category_id``` but fails the ```has a valid factory (FAILED - 1)```. Is there a different process for testing join model? 

```
Categorization
  has a valid factory (FAILED - 1)
  is invalid without a category_id
```

```
spec/factories/categorizations.rd
```

```rb
FactoryGirl.define do
  factory :categorization do
    category_id 1
    organization_id 1
  end
end
```

```
spec/models/categorization_spec.rb
```

```rb
require 'rails_helper'

describe Categorization do
 it "has a valid factory" do
 build(:categorization).should be_valid
 end
 it "is invalid without a category_id" do
  build(:categorization, category_id: nil).should_not be_valid
 end
end
```

**Comment by superbuggy** [comment]
https://www.google.com/search?q=test+factory+girl+join+model&rlz=1C5CHFA_enUS727US727&oq=test+factory+girl+join+model&aqs=chrome..69i57.6526j0j1&sourceid=chrome&ie=UTF-8

😆

**Comment by superbuggy** [comment]
How did this work out?

**Comment by scottpiercew** [comment]
Passed! I was using ```build``` to create instances so both category and organization did not have an ```id```. I switched to ```create``` to figure this out. 

```spec/factories/categorizations.rd```
```FactoryGirl.define do
  factory :categorization do
    category_id {}
    organization_id {}
  end
end
```

```spec/models/categorization_spec.rb```
```
require 'rails_helper'

describe Categorization do
  let(:category) { create(:category) }
  let(:organization) { create(:organization) }
  it "has a valid factory" do
    build(:categorization, category_id: category.id, organization_id: organization.id).should be_valid
  end
  it "is invalid without a category_id" do
    build(:categorization, category_id: nil).should_not be_valid
  end
end
```

**Comment by superbuggy** [comment]
Yes!!
