### ISSUE TITLE
I am getting the following errors

### ISSUE THREAD

**Issue by Antwana** [ga-wdi-exercises/project4#537]
**TypeError: Cannot read property 'prototype' of undefined**
This is referencing this **node_modules/express/lib/request.js:31** in my front end repository.
I've separated the frontend from the backend. Should I delete the node_modules folder from my frontend repository? I also cannot figure out how to connect backend to frontend

**Comment by superbuggy** [comment]
definitely keep `node_modules` on your front end. Did you move or delete anything else? 

You could try running `yarn install` from the command-line, also, but I doubt that will fix this issue.

In terms of connecting your front-end with your backend, you can use axios in your React front-end to communicate with your Express back-end.

**Comment by superbuggy** [comment]
Did `yarn install` work?

**Comment by Antwana** [comment]
The only thing I moved was the db folder and the server.js file. I moved both to a different repository. Is this okay?

Yarn install doesn’t work. It says command not found.

I will try axios.

Thanks

**Comment by Antwana** [comment]
yarn install didn't work. it said command not found

**Comment by superbuggy** [comment]
what about `npm install`?

**Comment by superbuggy** [comment]
if you don't have `yarn` you can install it with `brew install yarn`

**Comment by Antwana** [comment]
no. it doesn't work.

**Comment by nayana487** [comment]
what's the output when you ran `brew install yarn`? can you screenshot the error?

**Comment by Antwana** [comment]
I'm sorry. I didn't see James message about installing yarn. I was replying to his message about npm install. I'll try installing yarn now. Thanks

**Comment by Antwana** [comment]
Do I install int globally?

**Comment by nayana487** [comment]
homebrew installs tools on your operating system so `brew install yarn` should be sufficient
