### ISSUE TITLE
can't get ajax response from 3-table merged json file

### ISSUE THREAD

**Issue by tomBeach** [ga-wdi-exercises/project4#54]
I am able to pull data from three models and merge them into a json file for return, but this only works when hard-coding the query.  Matt corrected this to use relationships technique but the request still fails. 
Here is the controller code:

``` rb
    # ======= getPatientInfo =======
    def getPatientInfo
        puts "*** getPatientInfo " + "*" * 50
        puts params
        @nurse = Person.where(id: params[:id])
        @patient = @nurse.patient
        @meds = @patient.prescriptions

        respond_to do |format|
            format.json {
               render :json => {
                  :nurse => @nurse,
                  :patient => @patient,
                  :meds => @meds
               }
            }
        end
    end
```

Here is the ajax.  I am passing in the getNursePatientData function (below) as the callback.  The error is: GET http://localhost:3000/welcome/getPatientInfo/7 500 (Internal Server Error)

``` js
    // ======= ======= ======= getAjaxData ======= ======= =======
    Display.prototype.getAjaxData = function(url, callback, index) {
        console.log("getAjaxData");
        console.log("  url: " + url);
        console.log("  index1: " + index);

        var self = this;

        // == ajax LOCAL user login
        $.ajax({
            url: url,
            method: "GET",
            dataType: "json"
        }).done(function(jsonData, index){
            console.log("  ajax SUCCESS");
            console.dir(jsonData);
            callback(jsonData, index);
        }).fail(function(){
            console.log("  ajax FAIL");
            // self.displayTextMsg("Login failed.  Please try again.")
        });
    }

    // ======= ======= ======= getNursePatientData ======= ======= =======
    Display.prototype.getNursePatientData = function(nursePatientJson) {
        console.log("getNursePatientData");

        var self = this;
        var index = -1;
        var htmlString = null;
        var nextListItem;
        console.dir(this);

        nursePatientJson.forEach(function(nextPatientObject) {
            index++;
            var url = "/welcome/getPatientInfo/" + nextPatientObject.person_id;
            self.getAjaxData(url, self.getPatientInfo, index, nextPatientObject);
            var medIconString = "meds";
        });
    }

```

**Comment by RobertAKARobin** [comment]
What error is showing up in your Terminal, where the Rails output is being logged?

**Comment by tomBeach** [comment]
Here's the server error:

```
*** getPatientInfo **************************************************
{"controller"=>"welcome", "action"=>"getPatientInfo", "id"=>"7"}
  Person Load (0.2ms)  SELECT "persons".* FROM "persons" WHERE "persons"."id" = $1  [["id", 7]]
Completed 500 Internal Server Error in 4ms (ActiveRecord: 0.0ms)

NoMethodError (undefined method `patient' for #<Person::ActiveRecord_Relation:0x007fdde708d208>):
  app/controllers/welcome_controller.rb:32:in `getPatientInfo'
```

**Comment by jshawl** [comment]
@tomBeach can i see your person model? does it have `has_many :patients`?

**Comment by jshawl** [comment]
or does a person have one patient?

**Comment by tomBeach** [comment]
Here's the person model:

```
class Person < ActiveRecord::Base
    has_many :patients
    has_many :doctors
    has_many :nurses
end
```

and patients:

```
class Patient < ActiveRecord::Base
    belongs_to :person
    belongs_to :doctor
    belongs_to :nurse
    has_many :prescriptions
end
```

and the nurse:

```
class Nurse < ActiveRecord::Base
    belongs_to :person
    has_many :patients
end
```

**Comment by RobertAKARobin** [comment]
The problem is that a person has many patient**s**. So you can't call `@person.patient`; you'd need to call `@person.patients`.

**Comment by tomBeach** [comment]
Here's what I changed: (now using nurse instead of person but otherwise same)nstill failing

```
    def getPatientInfo
        puts "*** getPatientInfo " + "*" * 50
        puts params
        @nurse = Person.where(id: params[:id])
        @patient = @nurse.patients
        @meds = @patient.prescriptions
```

**Comment by mattscilipoti** [comment]
From your relationships, we see that each person has_many patients.  How can you limit (or find) the one patient you want to use in this controller, from the collection of @nurse.patients?

**Comment by RobertAKARobin** [comment]
Right. A Person can potentially have many Patients, so when you do `person.patients` it returns an array of patients, even if that array contains only one patient. You'll need `person.patients.find_by` or `.first` or something to narrow it down to one.

**Comment by tomBeach** [comment]
I was originally using the person_id (for nurse) in the patients table to find patients belonging to the nurse (below).  That worked to find patients.  It's when I tried using this:

``` rb
@meds = Prescription.where(patient_id: @patient.id)
```

I could only get the meds for the patient when hardcoding the id.  @meds = @patient.prescriptions is not working.

``` rb
@nurse = Person.where(id: params[:id])
@patient = Patient.where(person_id: params[:id])
@meds = Prescription.where(patient_id: 1)
```

**Comment by RobertAKARobin** [comment]
You're going to get the same thing with `where`. There could potentially be many things that have a `person_id` of that particular ID, so `where` is always going to return an array -- even if that array contains just one thing. Using `@nurse.patients` -- what you had before -- has the same result, and is much more concise. You just need to add a `.something` onto the end of it to narrow down the collection of patients to a specific one.

What ActiveRecord methods have we seen to narrow down collections/arrays to specific objects?

**Comment by tomBeach** [comment]
I tried both find_by and find...  No luck.

```
        @meds = @patient.prescriptions.find(patient_id: @patient.id)

```

**Comment by RobertAKARobin** [comment]
`@patient.prescriptions` automatically finds the prescriptions with the patient's ID. That's sort-of the whole point of that method. So `@patient.prescriptions.find(patient_id: @patient.id)` is redundant: it's saying "Find all the prescriptions with this patient's ID, and then of those, find all the prescriptions with this patient's ID."

Instead of `.find`, try `.first`, which just returns the first item in a collection.

**Comment by RobertAKARobin** [comment]
Wait, hold on. If you want _all_ `@patient`'s prescriptions, than just leave it at `@patient.prescriptions`.

But this is a different scenario than you were talking about before, with `@person.patients`. Let's not get these confused, and get one working before going to the other.

**Comment by RobertAKARobin** [comment]
If all you're trying to do here is get all of a Person's Prescriptions, then the simplest solution is to define a `has_many through`:

``` rb
class Person < ActiveRecord::Base
    has_many :patients
    has_many :doctors
    has_many :nurses
    has_many :prescriptions, through: :patients
end
```

Then, you can simply do `@person.prescriptions`.

**Comment by tomBeach** [comment]
The presrciptions really belong to the patient, not really tothe person (I have the prescriptions foriegn key in the patient file but not person).  The only reason person is involved is to put their name on the page, otherwise all the action is with patient.  Can we do a code one-on-one about this?

**Comment by jshawl** [comment]
headin over
