### ISSUE TITLE
quick one on setting states and immutability helpers

### ISSUE THREAD

**Issue by perryf** [ga-wdi-exercises/project4#549]
Just wanted to double check that this is a correct 'react friendly' approach to changing states.  
```
import update from 'immutability-helper'
//
// Many lines down.....
//
  let synth = update(this.state.synth, {playing: {$set: true}})
      this.setState({
        synth: synth
      })
```

I believe this helper function creates a copy with a little less syntax than the Object.assign method.  Just want to make sure before carrying on.

**Comment by jsm13** [comment]
Oh rad, I haven't seen `immutability-helper` before. I think this is right if `synth` is an object with a top level property `playing`. Good find on this.

**Comment by perryf** [comment]
yeah, top level property is playing.  thanks John - got everything up to speed at this point
