### ISSUE TITLE
Deployment Issue

### ISSUE THREAD

**Issue by Ryan-321** [ga-wdi-exercises/project4#55]
Deployed to heroku and can't get any data to sync b/c browser is saying it can't find my template.  I keep getting this error, https://wdi-flash.herokuapp.com/assets/views/subjects/index.html Failed to load resource: the server responded with a status of 404 (Not Found).  

I switched the URL for the services, below, not sure what else I would need to switch.  Do I need to put the whole above line in the router???

``` js

 subjectServices.factory('Subject', ['$resource', function($resource) {
    return $resource('https://wdi-flash.herokuapp.com/subjects/:id.json', {}, {
      update: {method:'PUT'} // Medthod that needs to be added b/c $resouce doesn't support PUT, which we need for Editing
    });
  }]);
  subjectServices.factory('Card', ['$resource', function($resource) {
    return $resource('https://wdi-flash.herokuapp.com/subjects/:subjectId/cards/:id', {}, {
      update: {method:'PUT'}
    });
  }]);

```

**Comment by RobertAKARobin** [comment]
I'm pushing this to my own Heroku right now.

**Comment by jshawl** [comment]
have you done `heroku run rake assets:precompile`?

**Comment by Ryan-321** [comment]
no, just rake db:migrate

**Comment by RobertAKARobin** [comment]
Move your `app/assets/javascripts/views` folder to `public/views`. Then, change the templateUrls from `assets/views/subjects/edit.html` to `views/subjects/edit.html`.

**Comment by RobertAKARobin** [comment]
Then, in subjectServices, change `'http://localhost:3000/subjects/:id.json'` to `./subjects/:id.json`. Heroku doesn't use `localhost`.

**Comment by RobertAKARobin** [comment]
https://vast-mesa-8632.herokuapp.com/#/subjects

Don't forget `heroku run rake db:migrate`!
