### ISSUE TITLE
Deployment issue

### ISSUE THREAD

**Issue by mattcfilbert** [ga-wdi-exercises/project4#557]
I failed at deploying my app on heroku (it is pure front end, AngularJS and Websockets) and even though I could probably do a tutorial or something to refresh my memory, I would love a final consult. Am happy to spend my group's final token from project 3.

Thaaaannnnkkkssss

**Comment by juancgarcia** [comment]
By "failed at deploying" do you mean that the heroku deployment aborted with an error, or that after completing deployment there is some breaking error that prevents it from running on heroku?

Also could you supply some links to your repo(s) and the deployed app?

**Comment by mattcfilbert** [comment]
Sure thing, one moment. I'll redeploy

**Comment by mattcfilbert** [comment]
Repo: https://github.com/mattcfilbert/websocketChat
Deployed: https://connect-2-by-4.herokuapp.com/

After deploying, there is a generic application error. I'm sure there was a human error on my end somewhere.

EDIT: updated URL

**Comment by juancgarcia** [comment]
[We might need to inspect the server logs to see what might be wrong](https://devcenter.heroku.com/articles/logging#view-logs), but I suspect the issue is that you're hard-coding port 3001 in your server. Heroku insists that your app use the port number they provide via `process.env.PORT`

Try adding this line near the top of your script...
```js
const port = process.env.PORT || 3001
```

...then when you fire up the server, use that variable instead of `3001`:
```js
http.listen(port, () => {
  console.log(`listening on ${port}`)
})
```

**Comment by mattcfilbert** [comment]
Hmm, that sounded like the issue, but unfortunately making that change did not resolve the error.

**Comment by mattcfilbert** [comment]
Do I need to make npm start an alias for node index.js or something?

**Comment by juancgarcia** [comment]
Ah, yes. You need a "start" entry in your package.json "scripts" section. This is how heroku kickstarts your app. Just add one with `node index.js` and that will get you up and running:

```js
  "scripts": {
    "start": "node index.js",
    "test": "echo \"Error: no test specified\" && exit 1"
  },
```

**Comment by mattcfilbert** [comment]
That works! Thanks, Juan!
