### ISSUE TITLE
Meteor/MongoDB issue; adding data to existing Collection

### ISSUE THREAD

**Issue by omarimayerswalker** [ga-wdi-exercises/project4#56]
I know this is out of the scope of what was taught in the class but...

I'm having trouble updating an existing mongodb collection using the methods provided by the meteor/mongodb documentation. If any of you have meteor/mongodb experience it would be greatly appreciated.

**Comment by RobertAKARobin** [comment]
Try us! Can you show the errors you were having?

**Comment by omarimayerswalker** [comment]
I don't have any errors to show...

``` js
Template.body.events({
        "submit .new-task": function(event){
            //prevent default browser submit
            event.preventDefault();

            //get valute from form element
            var text = event.target.text.value;
            var points = parseInt(event.target.number.value);

            // insert task
            Tasks.insert({
                text: text,
                points: points,
                createdAt: new Date(),
                owner: Meteor.userId(),
                username: Meteor.user().username
            }),

            // update total points
            Totals.insert({
                owner: Meteor.userId(),
                username: Meteor.user().username,
                totalPoints: points
            });

            // clear form
            event.target.text.value = "";
            event.target.number.value = "";
        },
        "change .hide-completed input": function(event){
            Session.set("hideCompleted", event.target.checked);
        }
    });
```

Im trying to replace the Totals.insert method and trying to update the collection Totals by using this:

```
Totals.update(
   { owner: Meteor.userId() },
   {
     $inc: { totalPoints: points}
   }
)
```

I'm also unable to define the Totals collection before the click event. Ideally I don't want to use Tasks.insert on the click event  because that creates a new instance on Totals for each Task entry. I want the Totals to update on each entry.

**Comment by RobertAKARobin** [comment]
Hm. So what exactly isn't working?

**Comment by omarimayerswalker** [comment]
I'm not able to 1) make it so there is only one Totals collection entry per user and 2) increment the Totals totalPoints value on each submit event.

**Comment by RobertAKARobin** [comment]
Sorry, I meant if you could clarify what "not able" means. Are you getting an error? Do you have the code set up and it's not throwing an error but it doesn't seem to be doing anything?

**Comment by omarimayerswalker** [comment]
With my two issues:

1) this is a concept so there is no code or errors
2) there are no errors for the Totals.update method. The app still runs. The code after the non functioning code is still executed.

**Comment by RobertAKARobin** [comment]
1) What have you tried so far?
2) Can you push your code to Github so I can try it?

**Comment by omarimayerswalker** [comment]
1) As a work around I created a method that uses a for loop to go through each Tasks entry and adds them all up. That works but I haven't figured out a way to have it work for each user, so as it stands it adds up all the entries.
2) I just pushed it up:

https://github.com/omarimayerswalker/do

**Comment by RobertAKARobin** [comment]
You need to iterate through all the tasks. To figure out how to do this, first I looked up "mongo find all", then "metero mongo iterate". Give this a shot:

``` js
var totalPoints = 0;
Tasks.find({}).forEach(function(task){
  totalPoints += task.points;
});
console.dir(totalPoints)
```

It seems to work fine on my computer!

**Comment by omarimayerswalker** [comment]
I can get the totalPoints with this:

``` js
totalsAll: function(){
             var distinctEntries = _.uniq(Totals.find({}, {
                 sort: {totalPoints: 1}, fields: {totalPoints: true}
             }).fetch().map(function(x) {
                 return x.totalPoints;
             }), true);

             var userTotal = 0;

             for(var i = 0; i < distinctEntries.length; i++){

             if (Number.isInteger(distinctEntries[i])){
                 userTotal = userTotal + distinctEntries[i];
             }
         }
        // console.log(userTotal);
        return userTotal;
 }
```

**Comment by omarimayerswalker** [comment]
I am unable to do it for individual users

**Comment by RobertAKARobin** [comment]
How about:

``` js
            var totalPoints = 0;
            Tasks.find({}).forEach(function(task){
              if(task.owner != Meteor.userId()) return;
              totalPoints += task.points;
            });
            console.dir(totalPoints)
```

**Comment by RobertAKARobin** [comment]
Or something like this:

``` js
    Template.total.helpers({
      totalPoints: function(){
        var totalPoints = 0;
        Tasks.find({}).forEach(function(task){
          if(task.owner != Meteor.userId()) return;
          totalPoints += task.points;
        });
        return totalPoints
      }
    })
```

**Comment by omarimayerswalker** [comment]
Still not working for me. I'm getting no errors or results.
