### ISSUE TITLE
Deploying to Heroku: $resource error that wasn't in local version

### ISSUE THREAD

**Issue by msteffan** [ga-wdi-exercises/project4#57]
I am trying to deploy to Heroku and my app allows me to log in but not to create and display new content once I'm inside. I am trying to create a new source via a form, but submitting the form returns this error:

```
Error: [$resource:badcfg] query
http://errors.angularjs.org/1.4.5/$resource/badcfg?p0=array&p1=object&p2=GET&p3=https%3A%2F%2Fsourcefourth.herokuapp.com%2F
    at angular.js:68
    at k.then.n.$resolved (angular-resource.min.js:9)
    at processQueue (angular.js:14634)
    at angular.js:14650
    at Scope.$eval (angular.js:15878)
    at Scope.$digest (angular.js:15689)
    at Scope.$apply (angular.js:15986)
    at done (angular.js:10511)
    at completeRequest (angular.js:10683)
    at XMLHttpRequest.requestLoaded (angular.js:10624)
```

The error page explains: 
"This error occurs when the $resource service expects a response that can be deserialized as an array but receives an object, or vice versa. By default, all resource actions expect objects, except query which expects arrays."

However it's working my local version, so I'm unsure what I would need to change in order to make this work on Heroku.

**Comment by msteffan** [comment]
Just kidding. Now I'm getting the error in my local version as well.

So I think the code it's referring to is in my router:

```
//GET a user's sources
router.get("/sources", function(req, res){
  User.findOne({ where: {id: req.query.userId}})
  .then(function(user){
    Source.findAll({where: {userId: user.id}})
    .then(function(sources, err){
        var sourceArray = [];
        for (var i=0;i<sources.length; i++){
            var oneSource = sources[i].dataValues;
            sourceArray.push(oneSource)
        }
        res.json(sourceArray);
        //console.log(err);
    })

  });
});
```

And my angular controller, here's the code that makes the request:

```
sourceControllers.controller('sourcesController', ['Source', '$http', '$location', function(Source, $http, $location) {
        var self = this;
        self.sources = {};
        $http.get("/currentUser").then(function(response){
             Source.query({userId: response.data}, function(sources){
                 self.sources = sources;

             });
        });
```

**Comment by adambray** [comment]
What code is in your service / factory for 'Source'... is that using `$resource`? If so, is it loaded correctly there?

**Comment by adambray** [comment]
So the error seems to be implying that one of your calls (either .findOne, .findAll, or .query) is getting an array when it's expecting  a single object, or vice versa. Can you double check your backend and confirm that they are returning the appropriate values?

**Comment by msteffan** [comment]
The code in the facotory Is:

```
  sourceServices.factory('Source', ['$resource', function($resource) {
    return $resource('http://localhost:3000/:id', { name: '@name', profession:'@profession', location: '@location', email: '@email', phone: '@phone', other: "@other", userId: '@userId'}, {
    //   query: {method: 'GET', isArray: false },
      update: {method:'PUT'}
    });
  }]);
})();
```

I tried updating it with that commented-out line to specify what comes back from the GET request, but this made the entire page run reaaaaalllly slowly and didn't load the correct items. So I'm not sure what I changed between last night and updating `app.js` this morning for deployment but it's not happy! I just rolled back to a previous commit and will use that for the presentation.

**Comment by adambray** [comment]
So that commented line seems like it may be the issue. Without it, your `Source.query` in your controller likely won't work. Not sure why keeping it in lead to issues, maybe you need to adjust the parameters to that method call.

**Comment by RobertAKARobin** [comment]
I'm going to close this since it's been a while. Feel free to make a new one if need-be!
