### ISSUE TITLE
random GET request causing 404 error on refresh

### ISSUE THREAD

**Issue by jaredarkin** [ga-wdi-exercises/project4#58]
In both my local and deployed versions, I am getting the following error when I refresh the page:
GET http://green-thumb-design.herokuapp.com/%7B%7Bplant.photo_url%7D%7D 404 (Not Found)
GET http://localhost:4000/%7B%7Bplant.photo_url%7D%7D 404 (Not Found)

So, it's looking for an image file with the source/name {{plant.photo_url}} which obviously doesn't exist. I can't tell where the GET request comes from or when it's being sent.

Here's where {{plant.photo_url}} exists in my code:

An ng-repeat creates a list of all plants using a custom plant directive
`<li class="list-group-item" ng-repeat="plant in plantCtrl.plants">
        <plant></plant>
      </li>`

The custom directive shows a bootstrap thumbnail of the image
`<div class="col-md-4 thumbnail">
    <img src="{{plant.photo_url}}" alt="{{plant.name}}" >
  </div>`

There's also a directive to add an image of the plant to the garden. But that only happens when a button is clicked so it shouldn't cause an error on refresh. Also, it's not in {{}}
`directives.directive('addtogarden', function($compile){
    return function(scope, element, attrs){
      element.bind("click", function(){
        angular.element(document.getElementById('garden-layout')).append($compile('<img draggable  class="layout-image" src=' + scope.plant.photo_url + ' />')(scope));
      });
    };
  });`

**Comment by adambray** [comment]
You should use `ng-src` instead of `src` on img tags!

**Comment by adambray** [comment]
(For this very reason)

**Comment by jaredarkin** [comment]
Thanks!
