### ISSUE TITLE
Deployment help - app only accessible on port

### ISSUE THREAD

**Issue by alexbannon** [ga-wdi-exercises/project4#59]
So this may be tricky, because I deployed on aws ec2 through Bitnami MEAN stack.

Problem is, it's only accessible right now at emptydesks.com:8080

emptydesks.com is only showing the congratulations page. I followed part of the lesson on digital ocean to remove the port, but I'm pretty lost.

Other info: 

aws site: ec2-54-174-239-65.compute-1.amazonaws.com
aws ip: 54.174.239.65
my domain: emptydesks.com

**Comment by adambray** [comment]
Is your node / express app's port set to 80? What HTTP server are you using? (nginx vs apache?)

what are the configs for your HTTP server looking like?

**Comment by adambray** [comment]
Also, what guide(s) did you follow?

**Comment by alexbannon** [comment]
This guide: https://scotch.io/tutorials/deploying-a-mean-app-to-amazon-ec2-part-1. Skipped over only a couple steps. I think the AMI I'm using on AWS does too much so I have no idea what I'm actually trying to fix. Levels of abstraction and whatnot. It comes preinstalled with mongo and node and a whole bunch of crap.

I might just totally start over and follow a tutorial on how to start from scratch.

**Comment by alexbannon** [comment]
Help me Obi-Wan, you're my only hope.

**Comment by jshawl** [comment]
im pretty unfamiliar with EC2 myself, but this article mentions changing port configurations - http://www.lauradhamilton.com/how-to-set-up-a-nodejs-web-server-on-amazon-ec2

**Comment by alexbannon** [comment]
I think this'll lead me down a helpful path. Thanks!
