### ISSUE TITLE
Meteor: getting data from an ajax response into the html template

### ISSUE THREAD

**Issue by puzzleboks** [ga-wdi-exercises/project4#6]
I am using Meteor for my application and am having difficulty getting data to display in my html, as follows: 
I am successfully making an ajax call to the Marvel api (through a form submission), and receiving a response. However, I don't know how to get that data into my Spacebars template, so that I can display it in my html. I've tried using a global variable, but it doesn't seem to work. I asked Nic about it last night, but he wasn't all that familiar with Meteor.

**Comment by RobertAKARobin** [comment]
Can you clarify what you mean by "doesn't seem to work"? Are you getting an error?

**Comment by puzzleboks** [comment]
I'll try to explain. When I try set the global variable in my ajax.done function (which is within a submit function, which is within Template.heroImg.events({})), it returns undefined in my avatarPath: function () {} (which is within Template.heroImg.helper({})). If I set my global variable at the top of my javascript file, outside of any other functions (like, myImgPath = ""), it only ever returns an empty string, even though I am setting the value of myImgPath in the ajax.done function.

**Comment by RobertAKARobin** [comment]
I'll come take a look in a second.

**Comment by puzzleboks** [comment]
Thank you
