### ISSUE TITLE
Question on ActionMailer 

### ISSUE THREAD

**Issue by jacohen10** [ga-wdi-exercises/project4#67]
I'm curious if I used a conditional and then deliver_later, would the conditional be checked right away or when the delay was executed. 

So for example: 

``` rb
class UsersController < ApplicationController
  def create
    @user = User.new(params[:user])
    if @user.email == true 
     UserMailer.welcome_user(@user).deliver_later(wait: 5.minute)
    end
  end
end
```

Now that I'm writing this out I'm pretty sure it'll check it right away and send if the conditional is true even if it changes before those 5 minutes have expired.

Is using the sleep method a way around this? Such as:

``` rb
class UsersController < ApplicationController
  def create
    @user = User.new(params[:user])
    sleep(5.minutes)
    if @user.email == true 
     UserMailer.welcome_user(@user).deliver_later(wait: 5.minute)
    end
  end
end
```

I now realize I should just test this out on my own... sorry

**Comment by RobertAKARobin** [comment]
Just to make sure: It looks like you want the e-mail to go out 5 minutes after the user has been created?

**Comment by jacohen10** [comment]
Yes, but only if the if statement is true

**Comment by RobertAKARobin** [comment]
Ruby executes everything in the order in which it appears, so if you have `sleep` before the conditional, then it'll sleep before evaluating the conditional.

**Comment by jacohen10** [comment]
Sweet, so I guess theoretically that'll solve that issue. I'll test it out. Code below would be more correct since the sleep handles the 5 minutes delay and .deliver wouldn't need too

``` rb
class UsersController < ApplicationController
  def create
    @user = User.new(params[:user])
    sleep(5.minutes)
    if @user.email == true 
     UserMailer.welcome_user(@user).deliver_now
    end
  end
end
```

**Comment by RobertAKARobin** [comment]
You prooooobably don't want to use `sleep` since it'll cause the entire app to hang for the user until those 5 minutes are up.

**Comment by RobertAKARobin** [comment]
Instead, I'd look into "Cron" jobs. Usually these are used to run something on an interval, but may be used to run something later without causing your whole app to hang. For example:

https://github.com/javan/whenever

**Comment by RobertAKARobin** [comment]
This may be a better resource: http://edgeguides.rubyonrails.org/active_job_basics.html

**Comment by jacohen10** [comment]
That last source looks really helpful, thank!
