### ISSUE TITLE
Two Way Data Binding in a Rails Backbone App

### ISSUE THREAD

**Issue by neka-io** [ga-wdi-exercises/project4#68]
Alexis and I are working on a side project that makes an API call from the back end using form data submitted by the user. The object is created in the data base upon the completion of the API call but is not rendered on the page until a refresh even though there are model event listeners for collections. 

We have tried updating the collection in Backbone in the promise of the $.post but that automatically makes a PUT request on the model that was just created. 

The only solution we have had is to call on the index function of our router which fetches the models from our API but we aren't sure if that is the right way to do it. 

Is there a way to trigger the fetch function when there are changes/additions made to the database from the backend? Can we talk to someone about two way data binding in a situation like this?

Thanks,
Negar & Alexis

**Comment by RobertAKARobin** [comment]
Just to make sure: You're submitting the form using `$.post`, and _not_ by clicking an `<input type="submit" />` or `<button type="submit">`?

**Comment by neka-io** [comment]
Correct. We are preventing default on the submission user event and making a post AJAX call to our API.

**Comment by RobertAKARobin** [comment]
Could you link to the part of your code containing the `.post`?

**Comment by RobertAKARobin** [comment]
Also, shouldn't you be using `.save`?

https://github.com/ga-dc/curriculum/tree/master/11-multi-track/bb_models_collections#models

**Comment by neka-io** [comment]
https://github.com/noonkay/giphify/blob/master/app/assets/javascripts/backbone/views/search.js#L24

**Comment by RobertAKARobin** [comment]
Why are you using `post` instead of `save`? `post` is a jQuery method and doesn't have any of that data-binding built-in, but `save` does.

See the section of the lesson plan I linked above.

**Comment by neka-io** [comment]
We are using AJAX post method to make an HTTP request with a POST method to /photos route because that's what triggers the API call in the backend. I'm not sure what we would use .save on in Backbone when the photo object is being created in the back end when the API call to giphy api is completed

**Comment by solowt** [comment]
Seems like you're overthinking it.

.save has AJAX built into it (so does .fetch and probably more backbone methods).  As long as your API endpoints are restful and you give your backbone models the proper URL, you shouldn't have to explicitly make AJAX calls.

Looking at the documentation, .save triggers a change event, and I'd guess that's how the data is bound.  If you just use AJAX without .save, then there's no change event and your model on the front end won't be updated until you sync with the backend (probably .fetch when you refresh the page).

**Comment by neka-io** [comment]
Thank you Thomas! :+1:  That's what we found too and through the process learned a little more about what's happening under the hood for Backbone's model events. But yes, definitely overthinking it :)
