### ISSUE TITLE
fixed nav bar overlapping with contents

### ISSUE THREAD

**Issue by onesick** [ga-wdi-exercises/project4#69]
I tried to use float. But since it's CSS... Its giving me too hard time to fix it.
I tried to use float, but it's not working
I have made a fixed item on top, and it's overlapping with the contents

**Comment by RobertAKARobin** [comment]
Is something like this what you're looking for?
http://robertakarobin.github.io/css-lightbox
https://github.com/RobertAKARobin/css-lightbox

**Comment by RobertAKARobin** [comment]
The trick to keep it from overlapping is to give the next object a margin, border, or padding on the top. So if my nav bar is 50px tall, as in the example I linked, then I would want the element that comes after the nav to have `margin-top: 50px;` or `padding-top: 50px;`.
