### ISSUE TITLE
Angular + Express -- getting data to the controller from the view

### ISSUE THREAD

**Issue by msteffan** [ga-wdi-exercises/project4#7]
I am trying to figure out how to pass session variable data about a user from the server to the view, and then from the view to the Angular controller. I've tried reading StackOverflow posts, which suggest using ng-init and setting a variable equal to my session variable. However, by the time my controller tries to access it, the value is still undefined.

My controller code is:

```
  sourceControllers.controller('sourcesController', ['Source', function(Source, $scope) {
      this.sources = Source.query({userId: $scope.userId});
  }]);
```

My view code is:

```
 {{#if currentUser}}
          <div ng-app="sourceFourth" ng-init="userId = {{userId}}">
             <div ng-view></div>
          </div>
    {{ else }}
```

`currentUser` exists as a session variable, and if I view this in the browser, it does print out the user's id as an attribute of the DOM element. I just can't pass it back to the controller to actually get the things that belong to this particular user.

What am I missing?

**Comment by msteffan** [comment]
Follow up to this:

I also want to pass data from my Angular controller to my Express router to create new items, but I also can't figure out how to get the User ID to the router because it's not being passed through the request.

Express router code to get user's sources is:

```
router.get("/sources", function(req, res){
    console.log(req);
  User.findOne({ where: {id: req.user.id}})
  .then(function(user){
    Source.findAll({where: {userId: user.id}})
    .then(function(sources, err){
        //console.log("I worked", sources);
        res.json(sources);
        //console.log(err);
    })

  });
});
```

A source depends on the user ID, so I currently can't do anything with sources (create, read, update—anything).

**Comment by RobertAKARobin** [comment]
Investigating now

**Comment by RobertAKARobin** [comment]
So this is a little tricky. You're trying to store data in the DOM, and in general that's kinda discouraged. What if instead you made a new API endpoint that returned all the information about the current user? Something like:

``` js
app.get("/currentUser", function(req, res){
  res.json(session.currentUser); // or however that works
});
```

**Comment by msteffan** [comment]
So I saw this solution in StackOverflow but I don't know how to implement
it.

1) Where would this go in the app.js code? the entire user auth situation
was a matter of having things in places where they were accessible.

2) if `this.sources = Source.query({etc etc})` where would I make the call
to that endpoint in my controller?
^ not sure why that's not formatting correctly

**Comment by RobertAKARobin** [comment]
1) It could go anywhere, really. If you're feeling fancy you could create a `currentUser.js` file and require it in `app.js`, but I'd probably just leave it right in `app.js`.

2) Something like:

``` js
$http.get("/currentUser").then(function(response){
  this.sources = response;
});
```

If you want, you could make a factory for that, so that the current user is "got" when the app first loads, and then you don't need to query it again.

``` js
app.module("yourApp").factory("currentUser", function(){
  var user = this;
  $http.get("/currentUser").then(function(response){
    user.data = response;
  });
});
```

**Comment by jshawl** [comment]
closing for now - please reopen if you have another issue and feel free to reference this one!
