### ISSUE TITLE
Models and Migrations

### ISSUE THREAD

**Issue by dan-ator** [ga-wdi-exercises/project4#70]
I am setting up the back-end of my app in rails.  I set up the migrations using `rake db:migrate' after i set up all my migrations.  I guess I forgot about models though so now when I go and try to create the models after I have already migrated I get:

```
Running via Spring preloader in process 72940
      invoke  active_record
    conflict    db/migrate/20160111145806_create_items.rb
Another migration is already named create_items: /Users/danielalexander/wdi/projects/project_four/closet/db/migrate/20160111140713_create_items.rb. Use --force to replace this migration or --skip to ignore conflicted file.
```

My question is it seems like I can run it with --skip to ignore the conflict, but then will the model be properly associated with the migration?  Or is it best to start the migrations from scratch?

**Comment by RobertAKARobin** [comment]
Just rename the migrations file to something else. You can't have `123456_create_items.rb` and `987654_create_items.rb`.

**Comment by dan-ator** [comment]
But isn't the model called 'items' as opposed to 'create_items'?  This is the command I used (I ended up going with --skip and figured I would just see what happens): `rails g model Item --skip`

**Comment by RobertAKARobin** [comment]
The name of the file matters only as a visual reminder to you, the developer. There shouldn't really be a situation in which you create a model called "Items" twice anyway: you create it once and then maybe change the model later on, but you don't create it twice.

**Comment by dan-ator** [comment]
Just ran the command for the 'outfit' model and took your advice to just change the name of the migration file (I guess since I already ran `rake:db:migrate` it doesn't matter what the migration file is called?  Anyways it seems to have worked that way too.

**Comment by dan-ator** [comment]
I just created 'Items' once, I just did the migration before I did the model (the lesson plan and official rails tutorial seemed to gloss over the models part).

**Comment by dan-ator** [comment]
Ok...just realized that doing the `rails g model outfit` creates the model and also the migration.  So now I have extra migrations.  I just did this all backwards and I guess did not need to run `rails g migration` since `rails g model` does that implicitly.

**Comment by RobertAKARobin** [comment]
Yes, the name of the migration file is important only visually to you.

Ah, I see. You shouldn't run both `rails g migration` and `rails g model`: do one or the other. Both generate a migration file, which is why you had duplicate files. If you do `g migration`, you'll need to create the model file yourself.

**Comment by RobertAKARobin** [comment]
Pay close attention to what's output in your terminal when you run `rails g` anything: it gives you a list of the files created.
