### ISSUE TITLE
issue with starting an angular app

### ISSUE THREAD

**Issue by Ly900** [ga-wdi-exercises/project4#73]
I tried to start an angular app using the lesson plan notes and just want the template to show up or now. I expected html to show where I put data-ui-view. I got an error instead.

Index:
![image](https://cloud.githubusercontent.com/assets/12722650/12240912/0f6b98b2-b85e-11e5-9b8e-e9207fb6e26d.png)

app.js
![image](https://cloud.githubusercontent.com/assets/12722650/12240920/1ca86122-b85e-11e5-927c-bb936ff5a9eb.png)

error:
![image](https://cloud.githubusercontent.com/assets/12722650/12240928/249864e0-b85e-11e5-8850-dc93e074c207.png)

**Comment by RobertAKARobin** [comment]
What was it?

**Comment by Ly900** [comment]
the dependency's ui.router not ui-router! keke...
