### ISSUE TITLE
trouble with date input in angular

### ISSUE THREAD

**Issue by cpgruber** [ga-wdi-exercises/project4#74]
For the life of me, I can't seem to get angular to play nicely with date form input. I can create objects using a date picker, but editing an object with a date is throwing this error: https://docs.angularjs.org/error/ngModel/datefmt?p0=2016-01-14T05:00:00.000Z

I've tried converting the date in scope to a new Date() object and tried creating a custom filter, but to no avail.

Anything that can point me in the right direction would be appreciated.

**Comment by amaseda** [comment]
How exactly are you trying to edit the Date object? Haven't dealt with this issue myself but perhaps there is a limitation as to what exactly you can do to a Date object.

**Comment by nolds9** [comment]
Looks like you've already tried some of the work-arounds mentioned [here](http://stackoverflow.com/questions/26782917/model-is-not-a-date-object-on-input-in-angularjs), but another alternative could be to make your own directive as a helper for formatting. Haven't run into this issue before but will do some more digging

**Comment by cpgruber** [comment]
I'm trying to populate an object's edit form with a date value associated with the object from the database. Initially, the date input in the form is blank and the value associated with "last_water" is not wrapped in quotes (see first pic). When I use the date picker, two way binding suggests that the value for "last_water" should be wrapped in quotes (see second pic). I haven't tried formatting it as a string... maybe that's the ticket?
![screen shot 2016-01-11 at 4 11 08 pm](https://cloud.githubusercontent.com/assets/11283135/12246741/2dfc4d9c-b87e-11e5-9a40-e449ab32c951.png)
![screen shot 2016-01-11 at 4 11 20 pm](https://cloud.githubusercontent.com/assets/11283135/12246742/3217c2bc-b87e-11e5-82ba-1d9238f6b56d.png)

**Comment by cpgruber** [comment]
I should also add that the date gets updated in the database-- I just don't understand why the error is being thrown

**Comment by RobertAKARobin** [comment]
Can you push your code?

**Comment by cpgruber** [comment]
https://github.com/cpgruber/plant-whisperer

angular branch

FYI Twitter OAuth is implemented

**Comment by RobertAKARobin** [comment]
Just to be clear, you tried exactly this:

``` js
$scope.plant.last_water = new Date($scope.plant.last_water);
```

**Comment by cpgruber** [comment]
In the form directive? yes

**Comment by RobertAKARobin** [comment]
This really stumped me. Seems like the long and short of it is that Angular's support for `type="date"` is inconsistent with Chrome's, and the solution is to just use strings instead. That seems really stupid, but `date` is fairly new. There are some Angular modules you can download that emulate `date`.
