### ISSUE TITLE
Connecting Angular to Rails back end - error loading module

### ISSUE THREAD

**Issue by ghost** [ga-wdi-exercises/project4#75]
I'm trying to build the angular index that shows data in my rails api.

I've tried walking through the screencasts in the angular factories and services lesson plan to build the index.html, index.controller.js files and adding index router in my runners.js file.

I expected my index file to return a list of postTitles, but instead get 
`{{post.questionTitle}}`
and error:  injector module error "runner" module not loaded.

My repo is https://github.com/thomhouseholder/runners-app/tree/angular.

**Comment by nolds9** [comment]
Interesting, I think the problem you are running into is that Angular is not loading the correct dependencies, I would check that you have linked to the correct files, and are injecting the necessary dependencies into your modules.  i.e. check that there is a `runners` module injected into your `app.js`

However, I think you also might be running into a bigger problem which is how Rails deals with asset management (i.e. JS).  It doesn't look like you are using any kind of gem such as [angularjs-rails](https://github.com/hiravgandhi/angularjs-rails) to help with integrating Angular in Rails, which may mean you have to explicitly include your `js` files in `application.js` for Rails to serve those files.

I would recommend using a gem such as the one I linked that helps Angular play nicely with Rails. Another solution would be to seperate your Angular app entirely from your Rails app, and just format your Rails app to serve as a json-rendering back-end, and then use a seperate Angular app to consume those endpoints, i.e. how we did it in [grumblr_rails_api](https://github.com/ga-dc/grumblr_rails_api) and [grumblr_angular](https://github.com/ga-dc/grumblr_angular)

Sorry for the long-winded response, but have run into a similar problem in the past...

**Comment by ghost** [comment]
Thanks, this is all very helpful. 
After I submitted I decided to split the apps instead of combining them. I got snarled quickly!

On Mon, Jan 11, 2016 at 12:52 PM -0800, "Nicholas Olds" notifications@github.com wrote:

Interesting, I think the problem you are running into is that Angular is not loading the correct dependencies, I would check that you have linked to the correct files, and are injecting the necessary dependencies into your modules.  i.e. check that there is a runners module injected into your app.js

However, I think you also might be running into a bigger problem which is how Rails deals with asset management (i.e. JS).  It doesn't look like you are using any kind of gem such as 'angularjs-railsto help with integrating Angular in Rails, which may mean you have to explicitly include yourjsfiles inapplication.js` for Rails to serve those files.

I would recommend using a gem such as the one I linked that helps Angular play nicely with Rails. Another solution would be to seperate your Angular app entirely from your Rails app, and just format your Rails app to serve as a json-rendering back-end, and then use a seperate Angular app to consume those endpoints, i.e. how we did it in [grumblr_rails_api](https://github.com/ga-dc/grumblr_rails_api) and [grumblr_angular](https://github.com/ga-dc/grumblr_angular)

Sorry for the long-winded response, but have run into a similar problem in the past...
