### ISSUE TITLE
Postman Help

### ISSUE THREAD

**Issue by dan-ator** [ga-wdi-exercises/project4#76]
I think I have finished building out the back-end of my app - with rails.  I am trying now to test the api with postman. Using the lesson on api's I tried entering my url (localhost:3000/items), methodL post, content-type set to application/json, and added some item data in the body using x-www-form-urlencoded a key and value pair.  I also tried putting in raw json data. This doesn't seem to post but instead of an error it just send me a bunch of html markup.  I am not really sure what this means or how to send the post request correctly. Help?

**Comment by RobertAKARobin** [comment]
The HTML markup it's sending you may be a Rails error page. Check the server log in your Terminal for error messages.

**Comment by dan-ator** [comment]
It's a real long one, starts with:

```
Started POST "/items" for ::1 at 2016-01-11 16:38:44 -0500
Processing by ItemsController#create as */*
  Parameters: {"item"=>{"name"=>"pants"}}
Can't verify CSRF token authenticity
Completed 422 Unprocessable Entity in 1ms (ActiveRecord: 0.0ms)
```

**Comment by RobertAKARobin** [comment]
Google `Can't verify CSRF token authenticity`.

**Comment by dan-ator** [comment]
Ok looks like the solution was adding `skip_before_filter  :verify_authenticity_token` to the controller (not enough to just remove the `before_action :authenticate_user!, only: [:create, :update, :destroy]`.  Closing but inputting this in case anyone else has this issue.

**Comment by RobertAKARobin** [comment]
Thanks, Dan!
