### ISSUE TITLE
trouble wiring angular to rails

### ISSUE THREAD

**Issue by ghost** [ga-wdi-exercises/project4#78]
I'm trying to display data in my rails api in my angular front end.

I've closely followed the resources and factories lesson plan, and should see my data (post titles) listed in my app.  Instead, nothing.

My back end serves data like a charm, repo for back end is https://github.com/thomhouseholder/runners-app.

My angular app is called runners, I'm looking for post.postTitle to display in index and show.  

Code in my app/posts/index.html is 
`<div data-ng-repeat="post in PostIndexViewModel.posts">
  <p><a data-ui-sref="postShow({id: post.id})">{{post.postTitle}}</a></p>
</div>`

My front end repo is https://github.com/thomhouseholder/runners-angular.

**Comment by RobertAKARobin** [comment]
Do you get any errors?

I would try `console.log(posts)` inside your controller to see what the data inside your posts actually looks like.

**Comment by ghost** [comment]
I have the cross-domain error that Adam mentioned briefly in last week's build-a-server mini lesson.  I don't remember seeing that in class or building the radio project.  Shouldn't I be able to ping http://localhost:3000/posts?

XMLHttpRequest cannot load http://localhost:3000/posts. No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'http://localhost:8080' is therefore not allowed access.

**Comment by RobertAKARobin** [comment]
Check this out:

https://github.com/ga-dc/curriculum/blob/master/10-angular/ui-router/readme.md#http-server

**Comment by ghost** [comment]
Yes, running the server.

console.log(posts) returns posts undefined error - that's because i'm not reading from the back end, correct?  solving the cross-domain problem will fix or at least impact that error?

**Comment by RobertAKARobin** [comment]
Yep!

**Comment by RobertAKARobin** [comment]
Just to be clear: are you currently accessing your front-end via `file:///something` in your browser, or `localhost:8080/something`?

**Comment by ghost** [comment]
yes, the latter:  localhost:8080/#/posts

**Comment by RobertAKARobin** [comment]
~~Huh. Where you at? I can come take a look.~~

**Comment by ghost** [comment]
in the back, across the room from the instructor lair.

**Comment by RobertAKARobin** [comment]
Actually, before I do that, can you verify that your Rails app is returning data? Use Postman, or at least `puts` the information so you can see it in your terminal.

**Comment by ghost** [comment]
yes - getting the post titles and post bodies returned from localhost:3030/posts

**Comment by ghost** [comment]
This issue is rearing its head again with additional methods.

error mssg:
cannot load http://localhost:3000/posts/new. No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'http://localhost:8080' is therefore not allowed access.  404 error.

Added 

``` rb
before_filter :enable_cors


  def enable_cors
    headers['Access-Control-Allow-Origin'] = '*'
    headers['Access-Control-Allow-Methods'] = 'POST, PUT, DELETE, GET, PATCH, OPTIONS'
    headers['Access-Control-Request-Method'] = '*'
    headers['Access-Control-Allow-Headers'] = 'Origin, X-Requested-With, Content-Type, Accept, Authorization'
  end
```

to the api application_controller.rb, and that solved the initial problem with index and show routes.  now running into this issue with new, edit, delete.

**Comment by RobertAKARobin** [comment]
Are you trying to `GET` `posts/new`, or `POST`?

**Comment by RobertAKARobin** [comment]
Either way, the only action I see in your posts controller is `index`.

**Comment by ghost** [comment]
Trying to POST new. And I did not push in my haste to submit before this outcomes panel. 

On Tue, Jan 12, 2016 at 10:06 AM -0800, "Robert Thomas" notifications@github.com wrote:

Either way, the only action I see in your posts controller is index.

**Comment by RobertAKARobin** [comment]
No sweat! Please push afterward and I'll have a gander.

**Comment by ghost** [comment]
just pushed both repos:
api:  https://github.com/thomhouseholder/runners-app
front end:  https://github.com/thomhouseholder/runners-angular

**Comment by RobertAKARobin** [comment]
Is the problem that the `create` action lives at `POST /posts`, rather than `POST /posts/new`?

Remember to `rake routes`!

**Comment by ghost** [comment]
can you expand on that a little?

**Comment by RobertAKARobin** [comment]
```
POST localhost:3000/artists
# Create a new artist

GET localhost:3000/artists
# Render a list of all artists

GET localhost:3000/artists/new
# Render the form you use to create a new artst

POST localhost:3000/artists/new
# Does not exist
```

**Comment by ghost** [comment]
great, think i'm back on the move.  thanks!
