### ISSUE TITLE
Rails + Angular Connection

### ISSUE THREAD

**Issue by malissaromero** [ga-wdi-exercises/project4#8]
I am having trouble putting establishing the connection between rails and angular partly because I'm not grasping it well. I decided to use the CDN in my layout file in Rails to make the connection. Is that enough or do I need more?

**Comment by RobertAKARobin** [comment]
That brings in the Angular library, but it won't make your app run. To bring in all of your Angular files, you'll need to link to them explicitly.

**Comment by malissaromero** [comment]
I believe that I have all the script tags in my application.html.erb. Here is my source code: https://github.com/malissaromero/match_me

**Comment by RobertAKARobin** [comment]
You can get rid of all the `<script>` tags. You see how `application.js` has that `//= require_tree .` line? That means it's automatically going to pull in any files inside that `assets/javascripts` folder. So all of those `.js` files are being included automatically.

You can see this by viewing the source code of a page in your web browser. You'll see something like:

``` html
<script src="/assets/users/directives/user.self-75e6b43e63678ea78d032d8a1137a56fa21b23ab4aad280a92843f938e7a7127.js?body=1" data-turbolinks-track="true"></script>
```

Click on that link, and you'll see that it contains the Javascript of your `directives/user.js` file.

So once you've removed those lines, you should be good to go.

**Comment by malissaromero** [comment]
I am now getting a error message that I have not loaded my app, but I believe that I have. The error message: 
![screen shot 2015-09-15 at 11 31 52 am](https://cloud.githubusercontent.com/assets/11203264/9881317/6b154b0e-5b9d-11e5-815a-19fca7e5493d.png)

My code: 

```
'use strict';

(function() {
  var app = angular.module('matchme', [
    'ngRoute',
    'ngResource',
    'userControllers',
    'userRouter',
    'userServices',
    'userDirectives'
  ]);
})();
```

**Comment by RobertAKARobin** [comment]
Can you keep clicking the links in those errors you get until you don't get any more links? It should be only 2 or 3. Let me know what the last one says!

**Comment by malissaromero** [comment]
![screen shot 2015-09-15 at 11 35 09 am](https://cloud.githubusercontent.com/assets/11203264/9881438/dd08815e-5b9d-11e5-8302-63fa1acf6b1c.png)

**Comment by malissaromero** [comment]
Do I need to require angular in my js/app.js ?

**Comment by RobertAKARobin** [comment]
Awesome. The trouble here is `ngRoute` and `ngResource` both have their own files. Load these right after `angular.min.js` and you should be good to go. 

``` html
<script src="https://cdnjs.cloudflare.com/ajax/libs/angular.js/1.4.5/angular-resource.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/angular.js/1.4.5/angular-route.min.js"></script>
```

**Comment by malissaromero** [comment]
Unfortunately, I am getting the same error. I put the tags in my application.html.erb after my angular cdn script tag like so: 

```
<script src="https://ajax.googleapis.com/ajax/libs/angularjs/1.3.15/angular.min.js"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/angular.js/1.4.5/angular-resource.min.js"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/angular.js/1.4.5/angular-route.min.js"></script>
```

**Comment by RobertAKARobin** [comment]
Can you push to GH again so I can take a look?

**Comment by malissaromero** [comment]
Ok, just did: https://github.com/malissaromero/match_me

**Comment by RobertAKARobin** [comment]
Sorry, I'm trying to figure this out

**Comment by malissaromero** [comment]
No, Please. I really appreciate it. I wish that I knew more about Angular to figure it out. There are a lot of tutorials online but they are all so different.

**Comment by RobertAKARobin** [comment]
Got it! The issue was you were missing parentheses on the ends of some of your files.

This:

``` js
(function(){
  var directives = angular.module('userDirectives', []);
  ...
  }]);
})
```

...has to be this:

``` js
(function(){
  var directives = angular.module('userDirectives', []);
  ...
  }]);
})()
```

Make sure all of your Angular files have that on the end.

**Comment by RobertAKARobin** [comment]
The next problem you'll run into is that Angular can't find your view files because Rails stores so-called "static" files (anything that's not an image, JS, or CSS) in a weird way. Your Angular views need to be inside the `public` folder in the root directory of your app. So, if my `public` folder looks like this:

```
public/
  404.html
  422.html
  500.html
  favicon.ico
  hithere/
    malissa.html
  robots.txt
```

...my `routes.js` would look like this:

``` js
(function(){
  var router = angular.module('userRouter', ['ngRoute']);
  router.config([
    '$routeProvider',
    function($routeProvider){
      $routeProvider.
      when("/users", {
        templateUrl: 'hithere/malissa.html',
        controller: 'usersController',
        controllerAs: 'usersCtrl'
      });
    }
  ])
})()
```

**Comment by malissaromero** [comment]
I have no more errors! However, it is still not showing anything. I thought I was querying my rails api through my controller. I just pushed: https://github.com/malissaromero/match_me

**Comment by jshawl** [comment]
Interesting - I see a lot of html in the source (cmd + option + u).

what is working?

**Comment by jshawl** [comment]
Remove the word `public` from line 8 - https://github.com/malissaromero/match_me/blob/master/app/assets/javascripts/routes.js#L8

**Comment by malissaromero** [comment]
The application.html.erb is working but not my Angular views or my Rails views.

**Comment by malissaromero** [comment]
I removed the word public but still cannot get my users to show up. I know my json is working so I don't see how it is not connecting together.

**Comment by jshawl** [comment]
notices http://localhost:3000/users.json is not working. with error "template missing"

**Comment by malissaromero** [comment]
My /users.json is working now with the respond_to method but still cannot get the application to recognize index.html.erb and public/views/index.html

**Comment by jshawl** [comment]
are there any errors in the console

**Comment by malissaromero** [comment]
Clean so far.

**Comment by jshawl** [comment]
how do you know "but still cannot get the application to recognize index.html.erb and public/views/index.html" ?

**Comment by malissaromero** [comment]
I put code in both and see that it is not showing up. I put an h2 tag in index.html.erb and ng-repeat of all users in the index.html.

**Comment by jshawl** [comment]
are you visiting `http://localhost:3000/#/users` in your browser? and if so are there any errors in the console?

**Comment by malissaromero** [comment]
Shoot, I have not! I got 3 errors. Let me work on these and can I get back to you if I cannot work through them?

**Comment by malissaromero** [comment]
However, Is there a reason I have to go to that url and not my main localhost:3000? Which one should I be working off of?

**Comment by jshawl** [comment]
because you're using the angular router - https://github.com/malissaromero/match_me/blob/b93575185c11cb1a294a68d50ac758013a4df895/app/assets/javascripts/routes.js#L7

closing for now but feel free to reference this issue in another one!
