### ISSUE TITLE
issue with devise

### ISSUE THREAD

**Issue by tkentor** [ga-wdi-exercises/project4#80]
I tried to implement devise so that only an admin can create/update/destroy posts. When I sign in and create a new post, I get the following error message:

undefined method `set_story' for #StoriesController:0x007ff1fc50c9b8
"          lambda { |target, _, &blk| target.send filter, &blk }"

My code at the top of the stories_controller looks like this:

```
class StoriesController < ApplicationController
  before_action :set_story, only: [:show]
  before_action :authenticate_user!, only: [:new, :create, :edit, :update, :destroy]
def index 
  [...]
```

My project can be found here: https://github.com/tkentor/end-of-days

**Comment by RobertAKARobin** [comment]
You're getting `undefined method` because you're trying to call a method called `set_story` that doesn't exist. Take a look here:

https://github.com/ga-dc/devise_blog/blob/solution/app/controllers/posts_controller.rb#L40

**Comment by tkentor** [comment]
Ah got it, thank you!
