### ISSUE TITLE
Leaflet generates tiles even when the view is not rendered in backbone

### ISSUE THREAD

**Issue by neka-io** [ga-wdi-exercises/project4#81]
My view is set up to show a map when 'render' is invoked from 'initialize'. There is a div element with id="map" in the html. I've found that the map shows no matter what and breaks everything else (including console.logs) even when I don't invoke render. I thought it was a browser cache issue but my caching is disabled and I've tried the same in the incognito mode and a different browser. The map keeps showing until I manually take out the div from the html template. When I do that and comment out this.render(), I still get an error that the map container is not found. 

This is what my view looks like 

``` js
App.Views.GameBoard = App.View.extend({
  initialize: function(){
    console.log('view initialized')
    console.log('collection:' + this.collection)
    this.render()
  },

  render: function(){
    var map = L.map('map').setView([38, -77], 15);
    L.tileLayer(
      'https://api.tiles.mapbox.com/v4/{id}/{z}/{x}/{y}.png?access_token={accessToken}',
      {
        attribution: 'Map data &copy; <a href="http://openstreetmap.org">OpenStreetMap</a> contributors, <a href="http://creativecommons.org/licenses/by-sa/2.0/">CC-BY-SA</a>, Imagery © <a href="http://mapbox.com">Mapbox</a>',
        maxZoom: 18,
        id:[Mapbox ID],
        accessToken: [Access Token]
      }
    ).addTo(map);
  }
})
```

**Comment by RobertAKARobin** [comment]
Hm. Could you push your code up to Github so I can look?

**Comment by neka-io** [comment]
Thanks. I modified a little but still have the same issue. In fact it seems like none of my code is updating as long as I have the div with the map id in index.hbs. On my machine it even console logs from lines I remove. 
https://github.com/noonkay/WhereintheWorld

**Comment by RobertAKARobin** [comment]
While I'm looking, can you tell me what the difference is between `public/backbone` and `public/js/backbone`?

**Comment by RobertAKARobin** [comment]
Also, are you running Nodemon? I'm wondering whether your server is actually restarting when you make changes.

**Comment by neka-io** [comment]
I am running nodemon and it says it's restarting. But even manually restarting it doesn't change anything.

Where do you see `public/backbone` ? That's where I initially had my backbone files but then put them in a js folder.

**Comment by RobertAKARobin** [comment]
Right here: https://github.com/noonkay/WhereintheWorld/tree/master/public/backbone
