### ISSUE TITLE
issue with express routing

### ISSUE THREAD

**Issue by Ly900** [ga-wdi-exercises/project4#82]
I have an Express back-end connected to a local MongoDB and Angular front-end. 

I'm able to render data as json when a get request is made to the server at app.get("/contactlist", ...) and on the front-end,  $http.get("/contactlist", ...). I can change the names and if they match, I get the json data. 

However, when I tried to make both just the root, ("/"), that did not work. I expected that if they matched, I'd be able to retrieve the data still. I do not have a root path anywhere in my server routes.

Why does this not work? How does the browser know to automatically render the index.html page when a user goes to the root page ("/") even though I did not express-ly (ha-ha) state it as one of the paths on my server?

```
// server.js
```

![image](https://cloud.githubusercontent.com/assets/12722650/12270977/e556cadc-b926-11e5-9a4f-b2db5d7d5ccc.png)

```
// controller.js
```

![image](https://cloud.githubusercontent.com/assets/12722650/12271026/21c95994-b927-11e5-9087-2c222057643e.png)

**Comment by RobertAKARobin** [comment]
What response do you get when you try root? What do you mean by "did not work"?

**Comment by Ly900** [comment]
When I try root in both the server and the controller, I get no response from the server or the controller other than this error message in the controller: 

![image](https://cloud.githubusercontent.com/assets/12722650/12271771/dac2d2d8-b92a-11e5-87a0-9401467cc887.png)

**Comment by RobertAKARobin** [comment]
Could you push your code to Github?

If you click the link in that error then you can see the trouble is with whatever you're `ng-repeat`ing. What I'd do is go into the controller for that view and `console.log` what you're `ng-repeat`ing.

**Comment by Ly900** [comment]
https://github.com/Ly900/contactlisttestapp

**Comment by RobertAKARobin** [comment]
When you go to `localhost:3000`, you're looking at the `/` route. So when you try to `$http.get("/")`, you're trying to GET `localhost:3000` -- that is, the page you're looking at right now.

**Comment by RobertAKARobin** [comment]
Node shows you `public/index.html` if you don't tell it to show you something else.

**Comment by RobertAKARobin** [comment]
Why not put the contactList-find-y bit in a separate route?

``` js
app.get("/", function(req, res) {
  console.log("I received a get request");
  // sorts by name (provided by mongojs)
}); //ends app.get

app.get("/contactlist", function(req, res){
  db.contactlist.find().sort({name: 1},(function(err, docs) {
    console.log(docs);
    res.json(docs);
  }));
});
```

**Comment by Ly900** [comment]
Ok that part makes sense. Then I guess my follow up question is how is the data in the DB retrieved to be shown on index.html when a user goes to the root path if all my code for retrieving the data is under app.get "/contactlist"?

**Comment by RobertAKARobin** [comment]
``` js
      $http.get("/contactlist").success(function(response){
        console.log("I got the data I requested");
        $scope.contactlist = response;
        console.log($scope.contactlist);
        $scope.contact = "";
      });
```

**Comment by Ly900** [comment]
Robin, I'm not sure if the code above is in response to my last question or follow up code to your suggestion about a separate route.

**Comment by RobertAKARobin** [comment]
It's in response to your last question: Instead of doing `$http.get("/"`, just do `$http.get("/contactlist"`

**Comment by Ly900** [comment]
Yes that's how I have it working. I am not understanding how the page is loading the data from the database when I go to the root path if I currently do not have a root path specified.

**Comment by Ly900** [comment]
Is it because when I go to the root path, my ng-repeat directs it to the AppCtrl, which then automatically makes a $http.get request to /contactlist form the server? I may have just answered my own question... not sure.

**Comment by RobertAKARobin** [comment]
Yep! This line is run every time your App Controller is instantiated:

https://github.com/Ly900/contactlisttestapp/blob/master/public/controllers/controller.js#L24

**Comment by Ly900** [comment]
Yup makes sense. I thought it was magic until now. Thanks!
