### ISSUE TITLE
Big(er) Picture Q

### ISSUE THREAD

**Issue by mcgrodsky** [ga-wdi-exercises/project4#85]
My app can create guitar chords on a fretboard when a user clicks a certain fret. When the “chord” is being created, the values of the input are being stored in an array called ‘sel’. My goal is to turn this array into a JSON object, push, and save it into my Ruby database associated with my chords model.

The second part is that I want users to be able to name the chord they are creating. Should i have an input box on the client side where users can type in the name, and like ‘sel’ this value can be parsed, stored in JSON, and saved to the database in conjunction with the created chord? Or, should the naming of the chord occur through an input box tied to my “chord” model? My end goal is to have created chords belong to the user that created them, so my final conundrum is whether or not to set up the relationships between users and chords before or after figuring out how to save chords to my db. <maybe inconsequential, but i'm trying to figure out the best approach that would save time in the long run.

**Comment by RobertAKARobin** [comment]
So the question is whether your table should look like this:

```
| id | name | sel          |
| 0  | foo  | [1, 2, 3, 4] |
```

...or like this:

```
| id | sel                                |
| 0  | {name: "foo", notes: [1, 2, 3, 4]} |
```

**Comment by jsm13** [comment]
That's a ton clearer than what I was about to ask^

**Comment by mcgrodsky** [comment]
Issue solved. Thanks for your helpful diagram @RobertAKARobin !
