### ISSUE TITLE
Creating a New Q

### ISSUE THREAD

**Issue by ghost** [ga-wdi-exercises/project4#86]
I'm trying to create a new question in my app and am getting a page not found error when I submit the form data.  

I think I might not have the form set up correctly:

```
<form>
  <input placeholder="Question Title" data-ng-model="PostNewViewModel.post.questionTitle" />
  <textarea placeholder="What's your question?" data-ng-model="PostNewViewModel.post.questionBody" ></textarea>
  <button type="button" data-ng-click="PostNewViewModel.create()">Create</button>
</form>
```

or the new.controller function:

```
function PostNewControllerFunction( PostFactory ){
      this.post = new PostFactory();
      this.create = function(){
        this.post.$save()
      };
      console.log(this.post);
```

Can I get an amen and a genius bar visit?

My back end is https://github.com/thomhouseholder/runners-app.

Front end is https://github.com/thomhouseholder/runners-angular.

**Comment by RobertAKARobin** [comment]
~~If you want your form to POST to a URL, then you need to specify a `method` and an `action`:~~

```
<form method="post" action="/my/url">
```

**Comment by RobertAKARobin** [comment]
We solved this by adding the `rack-cors` gem, removing all of the CORS stuff from the application controller, and then matching the `config/application.rb` to this:

https://github.com/ga-dc/grumblr_rails_api/blob/5e733e8d90ff0a0eb06604d435c0da23c3e6e442/config/application.rb
