### ISSUE TITLE
issue with Rails____

### ISSUE THREAD

**Issue by MohamedGood** [ga-wdi-exercises/project4#87]
I tried _add my books to categories for some reason it is not happening____. I expected **my books to be listed under the categories I selected_** to happen.**Instead I am getting some weird error_** happened instead.
My repo link is ___ and my question is about lines _my show.html.erb file__.

**Comment by RobertAKARobin** [comment]
I tried add my books to categories for some reason it is not happening. I expected my books to be listed under the categories I selected to happen. Instead I am getting some weird error happened instead.
My repo link is ___ and my question is about lines my show.html.erb file.

**Comment by RobertAKARobin** [comment]
What error are you getting? What does your code look like?

**Comment by MohamedGood** [comment]
Thank you Robin, You can close this issue, Erica helped me out
