### ISSUE TITLE
issue with angular file set-up

### ISSUE THREAD

**Issue by schersh** [ga-wdi-exercises/project4#90]
I tried setting up a basic file structure for an angular app (changed projects this morning). I expected my seeded data to appear on my index.html view, but I'm just seeing this in the page view. 

```
{{ingredientsViewModel.veg[0]}}
```

My repo link is https://github.com/schersh/Bibimbap_app and I'm hoping to visit the Genius Bar for a few minutes to talk about my basic file set-up and naming conventions so that I can make sure I'm formatting this correctly. Thanks.

**Comment by andrewsunglaekim** [comment]
where is `{{ingredientsViewModel.veg[0]}}` written in your code? I don't currently see it in the repo

**Comment by andrewsunglaekim** [comment]
Nvm, i see it.. this looks correct. Are you gettin an error at all?
