### ISSUE TITLE
Question about Angular structure

### ISSUE THREAD

**Issue by lewis2ba** [ga-wdi-exercises/project4#91]
I am trying to pass data around in my app that I receive from an $http request to wunderground. Right now I am doing my http call in a custom form directive. I need to use this data(wind speed) in a calculation along with other parameters the user inputs in a different custom directive. Because I dont know how to pass this data around I am appending the wind speed to the DOM and using jquery to select it and get its text(). I know this is a bad way but its the only way I can think of at the moment. Should I create a service to make my http call and use that service in my custom directives? And maybe another to do my calculations? Just need help with structure. Thanks!

**Comment by RobertAKARobin** [comment]
A service would be the "better" way. But you have something that works, so I'd say keep it and move onto other things. You can always refactor later!

**Comment by lewis2ba** [comment]
I guess ill keep working on it this way. Thanks!
