### ISSUE TITLE
Destroying Devise

### ISSUE THREAD

**Issue by dan-ator** [ga-wdi-exercises/project4#92]
I am trying to get rid of my user model that I created on the backend with devise so I can do this on the front-end with angular.  So I went and ran `rails destroy model User` and then line by line deleted all references to User or Devise in the app.  Then I deleted the migrations that I had previously created to create the User table.  Now I need to run a migration to drop the table from the database because User table is still in my schema.  I finally think I have a migration that will work, but now I get `PG::UndefinedTable: ERROR:  table "users" does not exist` because I foolishly went and manually deleted the table in the rails console.  

I also just tried dropping the database, creating the database, and then running the migrations again but to no avail.  So not sure how to proceed here...

**Comment by RobertAKARobin** [comment]
Just ran DCMS
