### ISSUE TITLE
Big Picture Issue

### ISSUE THREAD

**Issue by dan-ator** [ga-wdi-exercises/project4#93]
For my app I need the user to be able to upload and then later move around images.  I thought I was going to use AWS, Carrierwave, fog, and figaro (which I have set up already on my rails backend).  Then I thought I would just need some way for users to upload the photos on the front-end(angular).  It has been brought to my attention that AWS may not be a great option because of cost.  So looking through imgur documentation they require OAuth 2.0.  I assume that means I cannot use the easy-to-follow lesson plan on token-based authentication with devise.  First question: Is that so?

**Comment by RobertAKARobin** [comment]
It may be a bit different. Why not take a stab at it? https://api.imgur.com/#authentication

**Comment by dan-ator** [comment]
So then I don't need(and should remove) the carrierwave and fog and figaro on backend?  And then the image and api key for image storing is all on the client-side? Is that secure?

**Comment by RobertAKARobin** [comment]
Unless you've paid for your API access, or the API otherwise interacts with sensitive information, securing the API keys doesn't need to be a priority.
