### ISSUE TITLE
Getting Started with Angular

### ISSUE THREAD

**Issue by codedre** [ga-wdi-exercises/project4#94]
I am having trouble displaying my feature views via my routes. I went through tutorials the lesson plan and set up everything exactly how it is in past apps and I cannot get anything to view nor can I pull from data from my api

**Comment by RobertAKARobin** [comment]
Are you getting an error?

**Comment by codedre** [comment]
No errors

**Comment by codedre** [comment]
on page load the root route is not hitting the controller at all. none of my logs are displaying

**Comment by RobertAKARobin** [comment]
The issue was having `data-ui-sref="/some_url"`, instead of `data-ui-sref="name-of-the-state"`

**Comment by RobertAKARobin** [comment]
@codedre If you inject `$locationProvider` and use `$locationProvider.html5Mode(true);` and add `<base href="/" />` to the `head` of your main `index.html`, and create a route with `url: "/"`, then going to the root URL should activate the route.

**Comment by RobertAKARobin** [comment]
I just pushed a commit to Grumblr showing what I mean:

https://github.com/ga-dc/grumblr_angular/commit/82a9e8f0526d0073a25bc96dda7df05782d8833c

**Comment by RobertAKARobin** [comment]
...but keep in mind:

http://stackoverflow.com/a/16570533/2053389

**Comment by codedre** [comment]
thanks
