### ISSUE TITLE
AJAX request in Angular

### ISSUE THREAD

**Issue by murgia** [ga-wdi-exercises/project4#95]
I am currently trying to make a "GET" request to a 3rd party API.  I added this code and it seems to be making the request but the request is not successful.

```
 function($scope, $http){
    var state = $(".state-input").val();
    $http.get("/http://api.eia.gov/series/?api_key=48A9046E879936B4E85D0D8E88AD81BE&series_id=ELEC.PRICE." + state + "-RES.A").then(function(res){
      console.log(res);
      $scope.price = res;
    });
```

The website that I am trying to access works but it is adding my local host ahead of it like this:

 http://127.0.0.1:8080/http://api.eia.gov/series/?api_key=48A9046E879936B4E85D0D8E88AD81BE&series_id=ELEC.PRICE.VA-RES.A 

in my console.

**Comment by RobertAKARobin** [comment]
Why do you have `/http` at the beginning of your URL? Why not `http`?

**Comment by murgia** [comment]
My code I am looking at is
 in js/appliances/appliances.js

https://github.com/murgia/kilowatt-calc

**Comment by murgia** [comment]
andddddd that was it

**Comment by RobertAKARobin** [comment]
:tada:
