### ISSUE TITLE
issue with timestamps

### ISSUE THREAD

**Issue by tkentor** [ga-wdi-exercises/project4#97]
I'm trying to add timestamps to my model. I added timestamps through a migration. The migration looks like this:

``` rb
class CreateArticles < ActiveRecord::Migration
  def change
    create_table :articles do |t|
      t.string :title
      t.string :body
      t.string :takeaway
      t.string :action
      t.string :sources
      t.string :pictures
      t.timestamps
    end
  end
end
```

I have this at the bottom of my controller:

``` rb
private
  def set_article
    @article = Article.find(params[:id])
  end

  def article_params
    params.require(:article).permit(:title, :body, :takeaway, :action, :sources, :pictures, :timestamps)
  end
```

And this is how I display it in the view:

`<%= article.timestamps %>`

**Comment by RobertAKARobin** [comment]
What's the issue?

**Comment by tkentor** [comment]
Page won't load due to an undefined method

**Comment by RobertAKARobin** [comment]
What's the undefined method? Can you show a screenshot? Also, what code is the error referring to?

**Comment by tkentor** [comment]
Timestamps is the undefined method...error refers to the html where I call
it.

[image: Inline image 1]

**Comment by RobertAKARobin** [comment]
Could you re-upload the screenshot of the error? Looks like it didn't make it in here.

**Comment by tkentor** [comment]
Sure, get it now?

And forgot to include a link to my repo:
https://github.com/tkentor/end-of-days

**Comment by RobertAKARobin** [comment]
Solution was `<%= article.created_at %>`
