### ISSUE TITLE
issue with angular controller

### ISSUE THREAD

**Issue by schersh** [ga-wdi-exercises/project4#98]
I am working on an angular app, and having trouble with my ingredientsController file - the angular error is 
`Argument 'ingredientsController' is not a function, got undefined`
I was having an issue with this yesterday, but was able to fix the issue by refactoring the index.controller.js file with Robin, so I'm not sure why the error is reappearing today. I think it may be a syntax error? My repo link is https://github.com/schersh/Bibimbap_app and my question is about my js/ingredients/index.controller.js file and why it is not linking correctly on line 40 on my main index.html file.

**Comment by RobertAKARobin** [comment]
You don't have anything called `ingredientsController` in your app. The name of your controller is `IngredientIndexController`.

**Comment by schersh** [comment]
Yes, I was trying to change the naming to match the grumblr example, but must have mismatched. I renamed the controller in my index.html but now the error is 
`Argument 'IngredientIndexController' is not a function, got string`

**Comment by RobertAKARobin** [comment]
``` js
  angular
  .module("ingredients")
  .controller("IngredientIndexController", [
    "ControllerFunction"
  ]);
```

It should be this:

``` js
  angular
  .module("ingredients")
  .controller("IngredientsIndexController", [
    ControllerFunction
  ]);
```
- Ingredient should be plural
- Controller function shouldn't be in quotes

**Comment by schersh** [comment]
_sigh_ So that's why it was saying it was a string, instead of a function. Sorry I missed that. Thanks.
