### ISSUE TITLE
issue with angular's data-ng-class

### ISSUE THREAD

**Issue by Ly900** [ga-wdi-exercises/project4#99]
I tried to change a div's class when it is clicked. I expected to be able to use an if statement to change the class name on click. The class stayed as the original instead.

```
// index.html
```

Tried
![image](https://cloud.githubusercontent.com/assets/12722650/12302218/17871e1e-b9f2-11e5-9d81-53c3b20c3a47.png)
and
![image](https://cloud.githubusercontent.com/assets/12722650/12302302/87691f34-b9f2-11e5-8e86-1531f230bb77.png)

```
// main.css
```

![image](https://cloud.githubusercontent.com/assets/12722650/12302226/2b929fb4-b9f2-11e5-8fbd-75217aedc5c6.png)

```
// app.js
```

![image](https://cloud.githubusercontent.com/assets/12722650/12302256/569389d0-b9f2-11e5-9b61-2015172d5864.png)

**Comment by RobertAKARobin** [comment]
How about just `class="{{cardClass}}"`?

**Comment by Ly900** [comment]
Did not work =/

**Comment by Ly900** [comment]
So we figured it out and you're going to be so mad. Take a look at my if statement. _sigh_
